// Static string->LucideIcon registry for the amenity/accessibility vocabulary
// (public.amenities.icon_name). Explicit imports keep the bundle tree-shakeable
// rather than pulling all of lucide-react. Add a row here when a new icon_name
// is introduced in the vocabulary seed.
//
// An unlisted name does not fail — it silently renders the generic Tag glyph,
// which on a clinic's service list turns "PrEP" and "Abortion care" into
// indistinguishable grey chips. `Hand` sat missing that way from
// 20260916160000 until 20261023110000, so the one term whose job is telling a
// Deaf visitor they can be understood (`sign-language-interpreted`) rendered as
// the generic chip. That migration now asserts every health-scoped icon_name
// appears in this list.
import {
  AirVent,
  Accessibility,
  Baby,
  Banknote,
  Bath,
  Beer,
  BookOpen,
  BriefcaseMedical,
  BusFront,
  CalendarCheck,
  ChefHat,
  CigaretteOff,
  CircleAlert,
  CloudFog,
  Coffee,
  ConciergeBell,
  Crown,
  Dice5,
  Disc3,
  Dog,
  DoorClosed,
  DoorOpen,
  Dumbbell,
  Ear,
  Flame,
  Flower2,
  Footprints,
  Hand,
  HandHeart,
  Heart,
  HeartPulse,
  Lock,
  Martini,
  Mic2,
  Microscope,
  Moon,
  Music,
  Palmtree,
  PartyPopper,
  PawPrint,
  Pill,
  PlugZap,
  Rainbow,
  ShieldCheck,
  ShowerHead,
  Shirt,
  SquareParking,
  Stethoscope,
  Sun,
  Syringe,
  TestTube,
  TestTubes,
  Thermometer,
  Toilet,
  Trees,
  Tv,
  Users,
  Utensils,
  WashingMachine,
  Waves,
  Tag,
  type LucideIcon,
} from 'lucide-react';

const ICONS: Record<string, LucideIcon> = {
  AirVent,
  Accessibility,
  Baby,
  Banknote,
  Bath,
  Beer,
  BookOpen,
  BriefcaseMedical,
  BusFront,
  CalendarCheck,
  ChefHat,
  CigaretteOff,
  CircleAlert,
  CloudFog,
  Coffee,
  ConciergeBell,
  Crown,
  Dice5,
  Disc3,
  Dog,
  DoorClosed,
  DoorOpen,
  Dumbbell,
  Ear,
  Flame,
  Flower2,
  Footprints,
  Hand,
  HandHeart,
  Heart,
  HeartPulse,
  Lock,
  Martini,
  Mic2,
  Microscope,
  Moon,
  Music,
  Palmtree,
  PartyPopper,
  PawPrint,
  Pill,
  PlugZap,
  Rainbow,
  ShieldCheck,
  ShowerHead,
  Shirt,
  SquareParking,
  Stethoscope,
  Sun,
  Syringe,
  TestTube,
  TestTubes,
  Thermometer,
  Toilet,
  Trees,
  Tv,
  Users,
  Utensils,
  WashingMachine,
  Waves,
};

/** Resolve a vocabulary icon_name to a lucide component (Tag fallback). */
export function amenityIcon(iconName?: string | null): LucideIcon {
  return (iconName && ICONS[iconName]) || Tag;
}
