/**
 * Place-name tags that redirect to the real place entity.
 *
 * These `unified_tags` rows name a city, country or district that already exists as its own
 * entity, so `/tags/<slug>` was a second page about the same place — publishing encyclopaedic
 * geography under a glossary category. `20270501180000` deindexed the first 135 of them and
 * `81000101100000` finished the job (the Berlin district cohort plus the same-name bucket the
 * audit had blocked). Deindexing stops crawlers; it does NOT stop a reader landing on the page,
 * which is what these redirects are for.
 *
 * WHY THIS FILE EXISTS AT ALL
 * `tag_slug_redirects` cannot express it: the edge resolver hardcodes `routePrefix: '/tags'`
 * (functions/_lib/detail.ts), so a tag can only ever redirect to another tag. This is the same
 * shape as `src/lib/mergedVillageRedirects.ts` and exists for the same reason.
 *
 * `public/_redirects` holds the identical pairs and serves the first 100 edge rules directly.
 * Cloudflare silently ignores later entries for this project, so `functions/_middleware.ts`
 * consumes this same map as the cold-request fallback. The map also covers `/:lang/` paths and
 * client-side navigation inside the SPA. Tests keep all three surfaces in step.
 *
 * The tags themselves are NOT deleted, merged or deprecated: `unified_tag_assignments`,
 * `usage_count` and the denormalized `events.tags`/`venues.tags` arrays all keep working, so
 * `?tags=<slug>` and every browse filter are unaffected.
 */
export const PLACE_TAG_REDIRECTS: Readonly<Record<string, string>> = {
  algeria: '/country/algeria',
  argentina: '/country/argentina',
  auckland: '/city/auckland',
  australia: '/country/australia',
  austria: '/country/austria',
  badung: '/city/badung',
  bangkok: '/city/bangkok',
  barcelona: '/city/barcelona',
  beijing: '/city/beijing',
  berkeley: '/city/berkeley-us-0wh5n',
  berlin: '/city/berlin',
  bielefeld: '/city/bielefeld-de-jqije',
  birmingham: '/city/birmingham',
  braunschweig: '/city/braunschweig-de-lzwc9',
  brazil: '/country/brazil',
  bremen: '/city/bremen-de-srecc',
  brighton: '/city/brighton',
  brisbane: '/city/brisbane',
  'buenos-aires': '/city/buenos-aires',
  canada: '/country/canada',
  'cape-town': '/city/cape-town',
  casablanca: '/city/casablanca',
  'castro-district': '/villages/castro-district',
  'chiang-mai': '/city/chiang-mai-th-i65oi',
  chicago: '/city/chicago',
  chihuahua: '/city/chihuahua-mx-t01r7',
  colombia: '/country/colombia',
  copenhagen: '/city/copenhagen',
  'costa-rica': '/country/costa-rica',
  croatia: '/country/croatia',
  cuernavaca: '/city/cuernavaca-mx-i5l4z',
  dallas: '/city/dallas',
  denver: '/city/denver',
  dortmund: '/city/dortmund-de-zfu3i',
  durban: '/city/durban',
  eastbourne: '/city/eastbourne-gb-1nfsz',
  espana: '/country/spain',
  estonia: '/country/estonia',
  exeter: '/city/exeter-gb-h5y0o',
  'fort-lauderdale': '/city/fort-lauderdale',
  'fortitude-valley': '/villages/fortitude-valley',
  france: '/country/france',
  friedrichshain: '/villages/friedrichshain',
  georgia: '/country/georgia',
  germany: '/country/germany',
  gothenburg: '/city/gothenburg',
  'gran-canaria': '/city/gran-canaria',
  greece: '/country/greece',
  'guatemala-city': '/city/guatemala-city',
  harrisburg: '/city/harrisburg-us-l5til',
  iceland: '/country/iceland',
  india: '/country/india',
  indianapolis: '/city/indianapolis',
  indonesia: '/country/indonesia',
  israel: '/country/israel',
  istanbul: '/city/istanbul',
  italy: '/country/italy',
  japan: '/country/japan',
  johannesburg: '/city/johannesburg',
  kazan: '/city/kazan',
  'key-west': '/city/key-west',
  kolkata: '/city/kolkata',
  kreuzberg: '/villages/kreuzberg',
  'la-spezia': '/city/la-spezia-it-jd5n6',
  'lake-tahoe': '/city/lake-tahoe',
  'las-vegas': '/city/las-vegas-united-states',
  launceston: '/city/launceston',
  lima: '/city/lima',
  'los-angeles': '/city/los-angeles',
  luxembourg: '/country/luxembourg',
  madrid: '/city/madrid',
  malta: '/country/malta',
  merignac: '/city/m-rignac-france',
  mexico: '/country/mexico',
  'mexico-city': '/city/mexico-city',
  milan: '/city/milan',
  'mill-valley': '/city/mill-valley-us-57nze',
  mitte: '/villages/mitte',
  monterey: '/city/monterey',
  montreal: '/city/montreal',
  morelia: '/city/morelia-mx-kxzkr',
  morocco: '/country/morocco',
  munich: '/city/munich',
  murphys: '/city/murphys',
  netherlands: '/country/netherlands',
  neukolln: '/villages/neukoelln',
  'new-orleans': '/city/new-orleans',
  'new-zealand': '/country/new-zealand',
  'newcastle-upon-tyne': '/city/newcastle-upon-tyne-gb-l7wnj',
  nigeria: '/country/nigeria',
  norway: '/country/norway',
  oakland: '/city/oakland',
  oldenburg: '/city/oldenburg-de-cvzak',
  olympia: '/city/olympia',
  osaka: '/city/osaka',
  paignton: '/city/paignton-gb-zvny2',
  'palo-alto': '/city/palo-alto-us-4k5vb',
  paris: '/city/paris',
  pembroke: '/city/pembroke-gb-ccw0o',
  peru: '/country/peru',
  philadelphia: '/city/philadelphia',
  pittsburgh: '/city/pittsburgh',
  poland: '/country/poland',
  'port-louis': '/city/port-louis',
  prague: '/city/prague',
  prenzlauer: '/villages/prenzlauer-berg',
  'puerto-rico': '/country/puerto-rico',
  pune: '/city/pune-in-u6fuy',
  raleigh: '/city/raleigh-us-nygbl',
  reykjavik: '/city/reykjavik',
  rijeka: '/city/rijeka-hr-w60rh',
  'rio-de-janeiro': '/city/rio-de-janeiro',
  rosario: '/city/rosario',
  rotterdam: '/city/rotterdam',
  russia: '/country/russia',
  sacramento: '/city/sacramento',
  'salt-lake-city': '/city/salt-lake-city-united-states',
  salvador: '/city/salvador',
  'san-antonio': '/city/san-antonio',
  'san-diego': '/city/san-diego',
  'san-francisco': '/city/san-francisco',
  'san-juan': '/city/san-juan-1',
  'santa-clarita': '/city/santa-clarita',
  santiago: '/city/santiago',
  'sao-paulo': '/city/s-o-paulo',
  schoneberg: '/villages/schoeneberg',
  seattle: '/city/seattle',
  seminyak: '/city/seminyak',
  'sint-maarten': '/country/sint-maarten',
  skopje: '/city/skopje',
  'south-africa': '/country/south-africa',
  'south-bend': '/city/south-bend',
  split: '/city/split-hr-z2ivf',
  stuttgart: '/city/stuttgart-germany',
  sweden: '/country/sweden',
  switzerland: '/country/switzerland',
  taipei: '/city/taipei',
  tbilisi: '/city/tbilisi',
  'tel-aviv': '/city/tel-aviv',
  thailand: '/country/thailand',
  toronto: '/city/toronto',
  torremolinos: '/city/torremolinos',
  turkey: '/country/turkey',
  turkiye: '/country/turkey',
  uk: '/country/united-kingdom',
  'united-kingdom': '/country/united-kingdom',
  'united-states': '/country/united-states',
  'usti-nad-labem': '/city/usti-nad-labem-cz-6zkxh',
  venezia: '/city/venice-italy',
  vienna: '/city/vienna',
  'washington-d-c': '/city/washington-d-c',
  'washington-dc': '/city/washington-d-c',
  wellington: '/city/wellington',
  'west-hollywood': '/city/west-hollywood',
  wustrow: '/city/wustrow-lower-saxony',
  zurich: '/city/zuerich',
};

/** Path a place-name tag slug redirects to, or null if it is not one. */
export function placeTagRedirect(tagSlug: string | undefined | null): string | null {
  if (!tagSlug) return null;
  return PLACE_TAG_REDIRECTS[tagSlug.toLowerCase()] ?? null;
}
