// Mock fix runner. Synchronous: pretends to run Claude and immediately
// returns a fabricated fix so the UI can be exercised end-to-end without any
// external runner wired up. Used by the playwright e2e suite and by
// developers running the stack locally.

import type { FixRunner } from './types.ts';

export const mockFixRunner: FixRunner = {
  name: 'mock',
  async dispatch({ runId, storyId }) {
    const externalRef = `mock-${runId.slice(0, 8)}`;
    return {
      externalRef,
      syncResult: {
        prUrl: `https://github.com/tmaeder/queer-guide-hub/pull/${1000 + (parseInt(runId.replace(/-/g, '').slice(0, 4), 16) % 1000)}`,
        commitSha: runId.replace(/-/g, '').slice(0, 7),
        filesChanged: [
          'src/components/admin/feedback/StoryDetailDrawer.tsx',
          'supabase/functions/feedback-embed/index.ts',
        ],
        summary: `Mock fix for story ${storyId.slice(0, 8)}: addressed reported issue with safe defaults and added regression coverage. Generated by mock runner — replace by enabling github_actions or api runner.`,
        confidence: 'medium',
        risks: 'No real code change applied. This is the mock runner.',
      },
    };
  },
};
