// This is a placeholder for the styled-system jsx exports
// In a real Park UI setup, this would be generated by Panda CSS
export const styled = (component: any, recipe?: any) => {
  return component
}