// This is a placeholder for the styled-system recipe exports
// In a real Park UI setup, this would be generated by Panda CSS

export interface ButtonVariantProps {
  variant?: 'solid' | 'outline' | 'ghost' | 'subtle'
  size?: 'xs' | 'sm' | 'md' | 'lg' | 'xl'
}

export const button = {
  // Recipe configuration would be here
}