/**
 * Type declarations for Wasm modules built from workers/wasm/.
 * These are generated by wasm-bindgen during `npm run build:wasm`.
 */

declare module '../../wasm/pkg/csv_parser/csv_parser' {
  export function parse_csv(csv: string): string[][];
}

declare module '../../wasm/pkg/geo_wasm/geo_wasm' {
  export function haversine_km(lat1: number, lon1: number, lat2: number, lon2: number): number;
  export function batch_nearest(
    origin_lat: number,
    origin_lon: number,
    points_json: string,
    limit: number,
  ): string;
  export function point_in_polygon(lat: number, lon: number, polygon_json: string): boolean;
}

declare module '../../wasm/pkg/text_utils_wasm/text_utils_wasm' {
  export function clean_html_entities(raw: string): string;
  export function normalize_record_fields(json: string): string;
}
