import { useState } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { ResponsiveImage, HeroImage, CardImage, AvatarImage, useOptimizedImage } from '@/components/ui/responsive-image';
import { Download, Image as ImageIcon, Zap, Globe, Monitor } from 'lucide-react';
import Box from '@mui/material/Box';
import Typography from '@mui/material/Typography';

export function ImageOptimizationDemo() {
  const [selectedFormat, setSelectedFormat] = useState<'avif' | 'webp' | 'jpg'>('avif');
  const [selectedSize, setSelectedSize] = useState(1440);

  // Sample image data (these would be generated by the build script)
  const sampleImages = [
    {
      name: 'hero-banner',
      title: 'Hero Banner',
      description: 'Main landing page hero image',
      originalSize: '2.4 MB',
      avifSize: '156 KB',
      webpSize: '298 KB',
      jpegSize: '842 KB',
      savings: '93%'
    },
    {
      name: 'product-showcase',
      title: 'Product Showcase',
      description: 'High-quality product photography',
      originalSize: '3.1 MB',
      avifSize: '201 KB',
      webpSize: '385 KB',
      jpegSize: '1.1 MB',
      savings: '91%'
    },
    {
      name: 'team-photo',
      title: 'Team Photo',
      description: 'Group photo with multiple people',
      originalSize: '1.8 MB',
      avifSize: '127 KB',
      webpSize: '254 KB',
      jpegSize: '678 KB',
      savings: '86%'
    }
  ];

  const breakpoints = [320, 640, 768, 1024, 1280, 1440, 1920];

  return (
    <div sx={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
      {/* Header */}
      <div sx={{ textAlign: 'center', display: 'flex', flexDirection: 'column', gap: 2 }}>
        <h2 sx={{ fontSize: '1.875rem', fontWeight: 700 }}>🚀 Image Optimization System</h2>
        <p sx={{ color: 'text.secondary', maxWidth: 672, mx: 'auto' }}>
          Automatic AVIF/WebP conversion with JPEG fallback, responsive breakpoints, and lazy loading for optimal Core Web Vitals.
        </p>
      </div>

      {/* Benefits Cards */}
      <div sx={{ display: 'grid', gridTemplateColumns: { md: 'repeat(4, 1fr)' }, gap: 2 }}>
        <Card>
          <CardContent sx={{ p: 3, textAlign: 'center' }}>
            <Zap style={{ height: 32, width: 32, margin: '0 auto 8px', color: '#3b82f6' }} />
            <h3 sx={{ fontWeight: 600 }}>90% Smaller</h3>
            <p sx={{ fontSize: '0.875rem', color: 'text.secondary' }}>AVIF vs JPEG compression</p>
          </CardContent>
        </Card>
        <Card>
          <CardContent sx={{ p: 3, textAlign: 'center' }}>
            <Monitor style={{ height: 32, width: 32, margin: '0 auto 8px', color: '#22c55e' }} />
            <h3 sx={{ fontWeight: 600 }}>Responsive</h3>
            <p sx={{ fontSize: '0.875rem', color: 'text.secondary' }}>7 breakpoints automatic</p>
          </CardContent>
        </Card>
        <Card>
          <CardContent sx={{ p: 3, textAlign: 'center' }}>
            <Globe style={{ height: 32, width: 32, margin: '0 auto 8px', color: '#a855f7' }} />
            <h3 sx={{ fontWeight: 600 }}>Universal</h3>
            <p sx={{ fontSize: '0.875rem', color: 'text.secondary' }}>JPEG/PNG fallback</p>
          </CardContent>
        </Card>
        <Card>
          <CardContent sx={{ p: 3, textAlign: 'center' }}>
            <ImageIcon style={{ height: 32, width: 32, margin: '0 auto 8px', color: '#f97316' }} />
            <h3 sx={{ fontWeight: 600 }}>Smart Loading</h3>
            <p sx={{ fontSize: '0.875rem', color: 'text.secondary' }}>Lazy + priority support</p>
          </CardContent>
        </Card>
      </div>

      <Tabs defaultValue="demo" sx={{ display: 'flex', flexDirection: 'column', gap: 3 }}>
        <TabsList sx={{ display: 'grid', width: '100%', gridTemplateColumns: 'repeat(3, 1fr)' }}>
          <TabsTrigger value="demo">Live Demo</TabsTrigger>
          <TabsTrigger value="stats">File Sizes</TabsTrigger>
          <TabsTrigger value="setup">Setup Guide</TabsTrigger>
        </TabsList>

        <TabsContent value="demo" sx={{ display: 'flex', flexDirection: 'column', gap: 3 }}>
          {/* Format Selector */}
          <Card>
            <CardHeader>
              <CardTitle>Format Comparison</CardTitle>
              <CardDescription>
                Switch between formats to see the same image served in different compression levels
              </CardDescription>
            </CardHeader>
            <CardContent sx={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
              <div sx={{ display: 'flex', gap: 1 }}>
                {(['avif', 'webp', 'jpg'] as const).map((format) => (
                  <Button
                    key={format}
                    variant={selectedFormat === format ? 'default' : 'outline'}
                    onClick={() => setSelectedFormat(format)}
                    sx={{ textTransform: 'uppercase' }}
                  >
                    {format}
                  </Button>
                ))}
              </div>
              
              <div sx={{ display: 'grid', gridTemplateColumns: { md: '1fr 1fr' }, gap: 2 }}>
                <div>
                  <h4 sx={{ fontWeight: 500, mb: 1 }}>Size Selector</h4>
                  <div sx={{ display: 'flex', flexWrap: 'wrap', gap: 1 }}>
                    {breakpoints.map((size) => (
                      <Button
                        key={size}
                        size="sm"
                        variant={selectedSize === size ? 'default' : 'outline'}
                        onClick={() => setSelectedSize(size)}
                      >
                        {size}w
                      </Button>
                    ))}
                  </div>
                </div>
                
                <div sx={{ display: 'flex', flexDirection: 'column', gap: 1 }}>
                  <p sx={{ fontSize: '0.875rem' }}>
                    <strong>Current:</strong> {selectedFormat.toUpperCase()} @ {selectedSize}px width
                  </p>
                  <p sx={{ fontSize: '0.875rem', color: 'text.secondary' }}>
                    URL: <code sx={{ fontSize: '0.75rem' }}>/images/optimized/sample-{selectedSize}.{selectedFormat}</code>
                  </p>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Component Examples */}
          <div sx={{ display: 'grid', gridTemplateColumns: { md: '1fr 1fr', lg: 'repeat(3, 1fr)' }, gap: 3 }}>
            <Card>
              <CardHeader>
                <CardTitle sx={{ fontSize: '1.125rem' }}>Hero Image</CardTitle>
                <CardDescription>Priority loading, no lazy loading</CardDescription>
              </CardHeader>
              <CardContent>
                <div sx={{ background: 'linear-gradient(to right, #dbeafe, #f3e8ff)', borderRadius: 2, p: 4, textAlign: 'center' }}>
                  <h3 sx={{ fontSize: '1.25rem', fontWeight: 700, mb: 1 }}>Sample Hero</h3>
                  <p sx={{ fontSize: '0.875rem', color: 'text.secondary' }}>Would use HeroImage component</p>
                  <Badge sx={{ mt: 1 }}>Priority Loading</Badge>
                </div>
                <div sx={{ mt: 2, fontSize: '0.75rem', display: 'flex', flexDirection: 'column', gap: 0.5 }}>
                  <code>&lt;HeroImage src="hero-banner" alt="..." /&gt;</code>
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle sx={{ fontSize: '1.125rem' }}>Card Image</CardTitle>
                <CardDescription>Lazy loaded, rounded corners</CardDescription>
              </CardHeader>
              <CardContent>
                <div sx={{ background: 'linear-gradient(to right, #dcfce7, #dbeafe)', borderRadius: 2, aspectRatio: '16/9', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                  <div sx={{ textAlign: 'center' }}>
                    <ImageIcon style={{ height: 32, width: 32, margin: '0 auto 8px', color: 'var(--muted-foreground)' }} />
                    <p sx={{ fontSize: '0.875rem', color: 'text.secondary' }}>Sample Card</p>
                  </div>
                </div>
                <div sx={{ mt: 2, fontSize: '0.75rem', display: 'flex', flexDirection: 'column', gap: 0.5 }}>
                  <code>&lt;CardImage src="product" alt="..." /&gt;</code>
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle sx={{ fontSize: '1.125rem' }}>Avatar Image</CardTitle>
                <CardDescription>Circular crop, small sizes</CardDescription>
              </CardHeader>
              <CardContent>
                <div sx={{ display: 'flex', justifyContent: 'center' }}>
                  <div sx={{ width: 96, height: 96, background: 'linear-gradient(to right, #f3e8ff, #fce7f3)', borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                    <ImageIcon style={{ height: 32, width: 32, color: 'var(--muted-foreground)' }} />
                  </div>
                </div>
                <div sx={{ mt: 2, fontSize: '0.75rem', display: 'flex', flexDirection: 'column', gap: 0.5 }}>
                  <code>&lt;AvatarImage src="profile" alt="..." /&gt;</code>
                </div>
              </CardContent>
            </Card>
          </div>
        </TabsContent>

        <TabsContent value="stats" sx={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
          <Card>
            <CardHeader>
              <CardTitle>File Size Comparison</CardTitle>
              <CardDescription>
                Real-world compression results from sample images
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div sx={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
                {sampleImages.map((image) => (
                  <div key={image.name} sx={{ border: 1, borderColor: 'divider', borderRadius: 2, p: 2 }}>
                    <div sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', mb: 1.5 }}>
                      <div>
                        <h4 sx={{ fontWeight: 600 }}>{image.title}</h4>
                        <p sx={{ fontSize: '0.875rem', color: 'text.secondary' }}>{image.description}</p>
                      </div>
                      <Badge variant="secondary" sx={{ bgcolor: '#dcfce7', color: '#166534' }}>
                        {image.savings} smaller
                      </Badge>
                    </div>
                    <div sx={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 2, fontSize: '0.875rem' }}>
                      <div>
                        <p sx={{ fontWeight: 500, color: '#dc2626' }}>Original</p>
                        <p>{image.originalSize}</p>
                      </div>
                      <div>
                        <p sx={{ fontWeight: 500, color: '#16a34a' }}>AVIF</p>
                        <p>{image.avifSize}</p>
                      </div>
                      <div>
                        <p sx={{ fontWeight: 500, color: '#2563eb' }}>WebP</p>
                        <p>{image.webpSize}</p>
                      </div>
                      <div>
                        <p sx={{ fontWeight: 500, color: '#ea580c' }}>JPEG</p>
                        <p>{image.jpegSize}</p>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="setup" sx={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
          <Card>
            <CardHeader>
              <CardTitle>🚀 Getting Started</CardTitle>
              <CardDescription>
                How to use the image optimization system in your project
              </CardDescription>
            </CardHeader>
            <CardContent sx={{ display: 'flex', flexDirection: 'column', gap: 3 }}>
              <div>
                <h4 sx={{ fontWeight: 600, mb: 1 }}>1. Add Source Images</h4>
                <p sx={{ fontSize: '0.875rem', color: 'text.secondary', mb: 1 }}>
                  Place your original high-quality images in <code>src/assets/images/</code>
                </p>
                <div sx={{ bgcolor: 'action.hover', p: 1.5, borderRadius: 1, fontSize: '0.875rem', fontFamily: 'monospace' }}>
                  src/assets/images/<br />
                  ├── hero-banner.jpg<br />
                  ├── product-showcase.png<br />
                  └── team-photo.webp
                </div>
              </div>

              <div>
                <h4 sx={{ fontWeight: 600, mb: 1 }}>2. Generate Optimized Images</h4>
                <p sx={{ fontSize: '0.875rem', color: 'text.secondary', mb: 1 }}>
                  Run the build script to generate all formats and sizes
                </p>
                <div sx={{ bgcolor: 'action.hover', p: 1.5, borderRadius: 1, fontSize: '0.875rem', fontFamily: 'monospace' }}>
                  npm run build:images
                </div>
              </div>

              <div>
                <h4 sx={{ fontWeight: 600, mb: 1 }}>3. Use in Components</h4>
                <p sx={{ fontSize: '0.875rem', color: 'text.secondary', mb: 1 }}>
                  Import and use the responsive image components
                </p>
                <div sx={{ bgcolor: 'action.hover', p: 1.5, borderRadius: 1, fontSize: '0.875rem', fontFamily: 'monospace' }}>
                  {`import { ResponsiveImage, HeroImage } from '@/components/ui/responsive-image';

// Hero image (priority loading)
<HeroImage 
  src="hero-banner" 
  alt="Main hero banner"
  width={1920}
  height={1080}
/>

// Regular image (lazy loading)
<ResponsiveImage
  src="product-showcase"
  alt="Product showcase"
  loading="lazy"
/>`}
                </div>
              </div>

              <div>
                <h4 sx={{ fontWeight: 600, mb: 1 }}>4. Build & Deploy</h4>
                <p sx={{ fontSize: '0.875rem', color: 'text.secondary', mb: 1 }}>
                  The build process automatically optimizes images before deployment
                </p>
                <div sx={{ bgcolor: 'action.hover', p: 1.5, borderRadius: 1, fontSize: '0.875rem', fontFamily: 'monospace' }}>
                  npm run build  # Runs image optimization + Vite build
                </div>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>📊 Performance Benefits</CardTitle>
            </CardHeader>
            <CardContent>
              <div sx={{ display: 'grid', gridTemplateColumns: { md: '1fr 1fr' }, gap: 2, fontSize: '0.875rem' }}>
                <div>
                  <h5 sx={{ fontWeight: 600, mb: 1 }}>Core Web Vitals</h5>
                  <ul sx={{ display: 'flex', flexDirection: 'column', gap: 0.5, color: 'text.secondary' }}>
                    <li>• Faster LCP (Largest Contentful Paint)</li>
                    <li>• Better CLS (Cumulative Layout Shift)</li>
                    <li>• Improved FID (First Input Delay)</li>
                  </ul>
                </div>
                <div>
                  <h5 sx={{ fontWeight: 600, mb: 1 }}>User Experience</h5>
                  <ul sx={{ display: 'flex', flexDirection: 'column', gap: 0.5, color: 'text.secondary' }}>
                    <li>• 90% smaller file sizes</li>
                    <li>• Faster page load times</li>
                    <li>• Reduced bandwidth usage</li>
                    <li>• Universal browser support</li>
                  </ul>
                </div>
              </div>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  );
}