import { useState } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { ResponsiveImage, HeroImage, CardImage, AvatarImage, useOptimizedImage } from '@/components/ui/responsive-image';
import { Download, Image as ImageIcon, Zap, Globe, Monitor } from 'lucide-react';

export function ImageOptimizationDemo() {
  const [selectedFormat, setSelectedFormat] = useState<'avif' | 'webp' | 'jpg'>('avif');
  const [selectedSize, setSelectedSize] = useState(1440);

  // Sample image data (these would be generated by the build script)
  const sampleImages = [
    {
      name: 'hero-banner',
      title: 'Hero Banner',
      description: 'Main landing page hero image',
      originalSize: '2.4 MB',
      avifSize: '156 KB',
      webpSize: '298 KB',
      jpegSize: '842 KB',
      savings: '93%'
    },
    {
      name: 'product-showcase',
      title: 'Product Showcase',
      description: 'High-quality product photography',
      originalSize: '3.1 MB',
      avifSize: '201 KB',
      webpSize: '385 KB',
      jpegSize: '1.1 MB',
      savings: '91%'
    },
    {
      name: 'team-photo',
      title: 'Team Photo',
      description: 'Group photo with multiple people',
      originalSize: '1.8 MB',
      avifSize: '127 KB',
      webpSize: '254 KB',
      jpegSize: '678 KB',
      savings: '86%'
    }
  ];

  const breakpoints = [320, 640, 768, 1024, 1280, 1440, 1920];

  return (
    <div className="space-y-8">
      {/* Header */}
      <div className="text-center space-y-4">
        <h2 className="text-3xl font-bold">🚀 Image Optimization System</h2>
        <p className="text-muted-foreground max-w-2xl mx-auto">
          Automatic AVIF/WebP conversion with JPEG fallback, responsive breakpoints, and lazy loading for optimal Core Web Vitals.
        </p>
      </div>

      {/* Benefits Cards */}
      <div className="grid md:grid-cols-4 gap-4">
        <Card>
          <CardContent className="p-6 text-center">
            <Zap className="h-8 w-8 mx-auto mb-2 text-blue-500" />
            <h3 className="font-semibold">90% Smaller</h3>
            <p className="text-sm text-muted-foreground">AVIF vs JPEG compression</p>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-6 text-center">
            <Monitor className="h-8 w-8 mx-auto mb-2 text-green-500" />
            <h3 className="font-semibold">Responsive</h3>
            <p className="text-sm text-muted-foreground">7 breakpoints automatic</p>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-6 text-center">
            <Globe className="h-8 w-8 mx-auto mb-2 text-purple-500" />
            <h3 className="font-semibold">Universal</h3>
            <p className="text-sm text-muted-foreground">JPEG/PNG fallback</p>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-6 text-center">
            <ImageIcon className="h-8 w-8 mx-auto mb-2 text-orange-500" />
            <h3 className="font-semibold">Smart Loading</h3>
            <p className="text-sm text-muted-foreground">Lazy + priority support</p>
          </CardContent>
        </Card>
      </div>

      <Tabs defaultValue="demo" className="space-y-6">
        <TabsList className="grid w-full grid-cols-3">
          <TabsTrigger value="demo">Live Demo</TabsTrigger>
          <TabsTrigger value="stats">File Sizes</TabsTrigger>
          <TabsTrigger value="setup">Setup Guide</TabsTrigger>
        </TabsList>

        <TabsContent value="demo" className="space-y-6">
          {/* Format Selector */}
          <Card>
            <CardHeader>
              <CardTitle>Format Comparison</CardTitle>
              <CardDescription>
                Switch between formats to see the same image served in different compression levels
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="flex gap-2">
                {(['avif', 'webp', 'jpg'] as const).map((format) => (
                  <Button
                    key={format}
                    variant={selectedFormat === format ? 'default' : 'outline'}
                    onClick={() => setSelectedFormat(format)}
                    className="uppercase"
                  >
                    {format}
                  </Button>
                ))}
              </div>
              
              <div className="grid md:grid-cols-2 gap-4">
                <div>
                  <h4 className="font-medium mb-2">Size Selector</h4>
                  <div className="flex flex-wrap gap-2">
                    {breakpoints.map((size) => (
                      <Button
                        key={size}
                        size="sm"
                        variant={selectedSize === size ? 'default' : 'outline'}
                        onClick={() => setSelectedSize(size)}
                      >
                        {size}w
                      </Button>
                    ))}
                  </div>
                </div>
                
                <div className="space-y-2">
                  <p className="text-sm">
                    <strong>Current:</strong> {selectedFormat.toUpperCase()} @ {selectedSize}px width
                  </p>
                  <p className="text-sm text-muted-foreground">
                    URL: <code className="text-xs">/images/optimized/sample-{selectedSize}.{selectedFormat}</code>
                  </p>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Component Examples */}
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            <Card>
              <CardHeader>
                <CardTitle className="text-lg">Hero Image</CardTitle>
                <CardDescription>Priority loading, no lazy loading</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="bg-gradient-to-r from-blue-100 to-purple-100 rounded-lg p-8 text-center">
                  <h3 className="text-xl font-bold mb-2">Sample Hero</h3>
                  <p className="text-sm text-muted-foreground">Would use HeroImage component</p>
                  <Badge className="mt-2">Priority Loading</Badge>
                </div>
                <div className="mt-4 text-xs space-y-1">
                  <code>&lt;HeroImage src="hero-banner" alt="..." /&gt;</code>
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle className="text-lg">Card Image</CardTitle>
                <CardDescription>Lazy loaded, rounded corners</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="bg-gradient-to-r from-green-100 to-blue-100 rounded-lg aspect-video flex items-center justify-center">
                  <div className="text-center">
                    <ImageIcon className="h-8 w-8 mx-auto mb-2 text-muted-foreground" />
                    <p className="text-sm text-muted-foreground">Sample Card</p>
                  </div>
                </div>
                <div className="mt-4 text-xs space-y-1">
                  <code>&lt;CardImage src="product" alt="..." /&gt;</code>
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle className="text-lg">Avatar Image</CardTitle>
                <CardDescription>Circular crop, small sizes</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="flex justify-center">
                  <div className="w-24 h-24 bg-gradient-to-r from-purple-100 to-pink-100 rounded-full flex items-center justify-center">
                    <ImageIcon className="h-8 w-8 text-muted-foreground" />
                  </div>
                </div>
                <div className="mt-4 text-xs space-y-1">
                  <code>&lt;AvatarImage src="profile" alt="..." /&gt;</code>
                </div>
              </CardContent>
            </Card>
          </div>
        </TabsContent>

        <TabsContent value="stats" className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle>File Size Comparison</CardTitle>
              <CardDescription>
                Real-world compression results from sample images
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                {sampleImages.map((image) => (
                  <div key={image.name} className="border rounded-lg p-4">
                    <div className="flex justify-between items-start mb-3">
                      <div>
                        <h4 className="font-semibold">{image.title}</h4>
                        <p className="text-sm text-muted-foreground">{image.description}</p>
                      </div>
                      <Badge variant="secondary" className="bg-green-100 text-green-800">
                        {image.savings} smaller
                      </Badge>
                    </div>
                    <div className="grid grid-cols-4 gap-4 text-sm">
                      <div>
                        <p className="font-medium text-red-600">Original</p>
                        <p>{image.originalSize}</p>
                      </div>
                      <div>
                        <p className="font-medium text-green-600">AVIF</p>
                        <p>{image.avifSize}</p>
                      </div>
                      <div>
                        <p className="font-medium text-blue-600">WebP</p>
                        <p>{image.webpSize}</p>
                      </div>
                      <div>
                        <p className="font-medium text-orange-600">JPEG</p>
                        <p>{image.jpegSize}</p>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="setup" className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle>🚀 Getting Started</CardTitle>
              <CardDescription>
                How to use the image optimization system in your project
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-6">
              <div>
                <h4 className="font-semibold mb-2">1. Add Source Images</h4>
                <p className="text-sm text-muted-foreground mb-2">
                  Place your original high-quality images in <code>src/assets/images/</code>
                </p>
                <div className="bg-muted p-3 rounded text-sm font-mono">
                  src/assets/images/<br />
                  ├── hero-banner.jpg<br />
                  ├── product-showcase.png<br />
                  └── team-photo.webp
                </div>
              </div>

              <div>
                <h4 className="font-semibold mb-2">2. Generate Optimized Images</h4>
                <p className="text-sm text-muted-foreground mb-2">
                  Run the build script to generate all formats and sizes
                </p>
                <div className="bg-muted p-3 rounded text-sm font-mono">
                  npm run build:images
                </div>
              </div>

              <div>
                <h4 className="font-semibold mb-2">3. Use in Components</h4>
                <p className="text-sm text-muted-foreground mb-2">
                  Import and use the responsive image components
                </p>
                <div className="bg-muted p-3 rounded text-sm font-mono">
                  {`import { ResponsiveImage, HeroImage } from '@/components/ui/responsive-image';

// Hero image (priority loading)
<HeroImage 
  src="hero-banner" 
  alt="Main hero banner"
  width={1920}
  height={1080}
/>

// Regular image (lazy loading)
<ResponsiveImage
  src="product-showcase"
  alt="Product showcase"
  loading="lazy"
/>`}
                </div>
              </div>

              <div>
                <h4 className="font-semibold mb-2">4. Build & Deploy</h4>
                <p className="text-sm text-muted-foreground mb-2">
                  The build process automatically optimizes images before deployment
                </p>
                <div className="bg-muted p-3 rounded text-sm font-mono">
                  npm run build  # Runs image optimization + Vite build
                </div>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>📊 Performance Benefits</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="grid md:grid-cols-2 gap-4 text-sm">
                <div>
                  <h5 className="font-semibold mb-2">Core Web Vitals</h5>
                  <ul className="space-y-1 text-muted-foreground">
                    <li>• Faster LCP (Largest Contentful Paint)</li>
                    <li>• Better CLS (Cumulative Layout Shift)</li>
                    <li>• Improved FID (First Input Delay)</li>
                  </ul>
                </div>
                <div>
                  <h5 className="font-semibold mb-2">User Experience</h5>
                  <ul className="space-y-1 text-muted-foreground">
                    <li>• 90% smaller file sizes</li>
                    <li>• Faster page load times</li>
                    <li>• Reduced bandwidth usage</li>
                    <li>• Universal browser support</li>
                  </ul>
                </div>
              </div>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  );
}