// AUTO-GENERATED by scripts/sync-cms-page-routes.mjs — do not edit.
//
// Slugs rendered by CMSRoutePage at a bare path, plus the /p/:slug route
// handled by Page.tsx. The middleware uses this to decide whether a request
// could be a CMS page without asking the database, which would otherwise mean
// a round-trip on every non-asset request including "/".
//
// Re-run the script when a CMS route is added or removed.

export const CMS_PAGE_SLUGS: readonly string[] = [
  'about-hub',
  'accessibility',
  'blog',
  'cookies',
  'dmca',
  'legal',
  'press',
  'privacy',
  'sustainability',
  'terms',
  'values',
  'vision'
] as const;

const SLUG_SET = new Set(CMS_PAGE_SLUGS);

/**
 * Resolves a locale-stripped path to the cms_pages slug it renders, or null.
 * Accepts both the bare form ("/terms") and the generic form ("/p/:slug").
 */
export function cmsPageSlugFor(basePath: string): string | null {
  const path = basePath.replace(/\/+$/, '') || '/';
  const segments = path.split('/').filter(Boolean);

  if (segments.length === 1 && SLUG_SET.has(segments[0])) return segments[0];
  if (segments.length === 2 && segments[0] === 'p' && /^[a-z0-9-]+$/.test(segments[1])) {
    return segments[1];
  }
  return null;
}
