// AUTO-GENERATED by scripts/seo-localised-locales.mjs. Do not edit by hand.
// Lists locales whose translation files differ from en.json by at least 5 %
// of strings. Used by functions/_middleware.ts to gate hreflang emission and
// to emit noindex for locale-prefixed URLs whose content is still effectively
// English (P3.1 of the SEO remediation). Re-run the script after a locale
// gets translated.

export const LOCALISED_LOCALES: readonly string[] = ["en","es","fr","de","pt","it","ru","zh","ja","ko","ar"] as const;

export function isLocaleLocalised(locale: string): boolean {
  return LOCALISED_LOCALES.includes(locale);
}
