import type { DayPart, ItineraryDayInput, ItineraryResult } from './generateItinerary';

/**
 * The two pieces of real logic that sat inside `ItineraryGenerator`'s render:
 * deciding which city each day belongs to, and turning a generated plan into
 * `trip_places` rows.
 *
 * Extracted for the same reason `generateItinerary` is pure — both decide
 * something a reader would notice being wrong (which city you are in on
 * Thursday; whether a stop lands on the right day), and neither is worth
 * testing through a render when it can be tested directly.
 */

/** A city stop on the trip, in route order. */
export interface RouteStop {
  cityId: string;
  name: string;
}

/** Minimal shape of a `trip_days` row. */
export interface DayRow {
  id: string;
  date: string;
}

/**
 * Spread the trip's days across its city stops, in order.
 *
 * `trip_days` is generated by a DB trigger from the trip's date range, so the
 * dates are complete and correct and there is nothing to invent — this only
 * decides WHERE each of them happens.
 *
 * The stops come from the trip's own `trip_places` rows with `category='city'`,
 * which is how a multi-city trip actually arrives: `/trips/discover` writes one
 * per station, and on a fresh trip that is the only thing there.
 * `trip_destinations` exists in the schema with per-destination date ranges and
 * would be the better source — but nothing in the client has ever written to it
 * (7 rows live, from a backfill), so reading it would resolve to nothing on
 * every real trip. When it gets a writer, this function is the one place that
 * changes.
 *
 * Days are split as evenly as possible and never re-ordered: the route order is
 * the order the line generator already put the cities in geographically, so
 * shuffling it would send the traveller back and forth across a continent.
 */
export function assignDaysToStops(
  days: DayRow[],
  stops: RouteStop[],
  fallback: RouteStop | null,
): ItineraryDayInput[] {
  const ordered = [...days].sort((a, b) => a.date.localeCompare(b.date));
  if (ordered.length === 0) return [];

  const route = stops.length > 0 ? stops : fallback ? [fallback] : [];
  if (route.length === 0) return [];

  // Ceil, so the remainder lands on the LAST stop rather than overflowing past
  // the end of the route. With 5 days over 2 stops that is 3 + 2, not 3 + 3.
  const perStop = Math.ceil(ordered.length / route.length);
  return ordered.map((day, i) => {
    // The clamp is UNREACHABLE while `perStop` is a ceiling — mutation testing
    // confirmed no test can distinguish its presence, because ceil already
    // bounds the index at `route.length - 1`. It stays as the failure mode for
    // a future change to `perStop`: a floor there would index past the route
    // and hand back `undefined`, and a day in no city is worse than a day
    // doubled up on the last one. Kept deliberately, not by accident.
    const stop = route[Math.min(Math.floor(i / perStop), route.length - 1)];
    return { date: day.date, cityId: stop.cityId, cityName: stop.name };
  });
}

/**
 * Nominal start times, used only to order the places within a day.
 *
 * NOT a claim about opening hours — the corpus has none. That is also why the
 * rows below carry a null `duration_minutes`: an invented visit length would
 * propagate into the leg estimates as though it had been measured.
 */
export const SLOT_TIME: Record<DayPart, string> = {
  morning: '10:00:00',
  afternoon: '14:00:00',
  evening: '19:00:00',
  night: '22:30:00',
};

/** A `trip_places` insert row, as `addPlacesBulk` expects it. */
export interface PlaceRow {
  day_id: string | null;
  venue_id: string | null;
  event_id: string | null;
  hotel_id: null;
  custom_name: null;
  custom_address: null;
  latitude: number;
  longitude: number;
  city_id: string;
  country_id: string | null;
  start_time: string;
  end_time: null;
  duration_minutes: null;
  notes: null;
  category: string;
  sort_order: number;
  icon: null;
  arrive_mode: null;
}

/**
 * Turn a generated plan into insert rows.
 *
 * Empty slots contribute nothing — the gap is a thing the reader is told about,
 * not a row. `sort_order` runs across the WHOLE plan rather than restarting per
 * day, because the itinerary renders places in that order within their day and
 * a per-day reset makes every day's first stop tie with every other day's.
 */
export function itineraryToPlaceRows(
  result: ItineraryResult,
  dayIdByDate: Map<string, string>,
): PlaceRow[] {
  const rows: PlaceRow[] = [];
  for (const day of result.days) {
    for (const slot of day.slots) {
      const c = slot.candidate;
      if (!c) continue;
      rows.push({
        day_id: dayIdByDate.get(day.date) ?? null,
        venue_id: c.kind === 'venue' ? c.id : null,
        event_id: c.kind === 'event' ? c.id : null,
        hotel_id: null,
        custom_name: null,
        custom_address: null,
        latitude: c.latitude,
        longitude: c.longitude,
        city_id: c.cityId,
        country_id: c.countryId,
        start_time: SLOT_TIME[slot.dayPart],
        end_time: null,
        duration_minutes: null,
        notes: null,
        category: c.kind,
        sort_order: rows.length,
        icon: null,
        arrive_mode: null,
      });
    }
  }
  return rows;
}
