import { test, expect, type APIRequestContext } from '@playwright/test';
import { SUPPORTED_LOCALES } from '../functions/_lib/routeMeta';

/**
 * A doubled locale prefix must hard-404 and advertise NOTHING.
 *
 * `/fr/fr/places` answered HTTP 200 as an indexable SPA shell and emitted an
 * hreflang alternate for all 11 locales, each carrying the stray segment
 * (`/es/fr/places`, `/it/fr/places`, …). One junk URL minted ten more and
 * crawlers recycled them indefinitely.
 *
 * WHY THIS IS ITS OWN SPEC, not part of e2e/locale-prefix.spec.ts: that spec
 * is on the critical-path list, which runs against `vite preview`
 * (E2E_BASE_URL=http://localhost:4173). That is a static server — it does NOT
 * execute Pages Functions, so `functions/_middleware.ts` never runs and the
 * 404 can never happen there. Asserting it on that target fails for the
 * environment rather than for the code, which is a broken gate, not a strict
 * one. (It did exactly that once: Expected 404, Received 200.)
 *
 * The compile-time half of this guard — that the middleware carries an
 * unconditional `startsWithLocale(basePath)` branch, that it returns 404, and
 * that it runs before resolveLandingRoute — lives in
 * src/__tests__/doubledLocaleGuard.test.ts and DOES run on every PR. This file
 * is the behavioural half and runs wherever a real deployment is the target
 * (the nightly suite points at https://queer.guide).
 */

/**
 * Does this origin execute Pages Functions?
 *
 * Probed rather than inferred from the hostname: a preview deployment is not
 * localhost but a localhost tunnel is, and either guess would be wrong
 * silently. `/brand/tokens.css` is generated by functions/brand/ and has no
 * static file behind it, so a CSS 200 proves Functions ran.
 */
async function functionsAreLive(request: APIRequestContext): Promise<boolean> {
  try {
    const res = await request.get('/brand/tokens.css', { maxRedirects: 0 });
    if (res.status() !== 200) return false;
    return (res.headers()['content-type'] ?? '').includes('css');
  } catch {
    return false;
  }
}

test.describe('doubled locale prefix', () => {
  test.setTimeout(60_000);

  // Same-locale, cross-locale, and a locale the old hand-written guard list
  // omitted entirely (`ko` — and the error board contains `/ko/ko`).
  const PAIRS = [
    ['fr', 'fr'],
    ['it', 'fr'],
    ['ko', 'ko'],
  ] as const;

  for (const [outer, inner] of PAIRS) {
    test(`/${outer}/${inner}/places hard-404s and advertises no alternates`, async ({
      request,
    }) => {
      test.skip(
        !(await functionsAreLive(request)),
        'target does not execute Pages Functions (vite preview) — middleware cannot run',
      );

      const res = await request.get(`/${outer}/${inner}/places`, { maxRedirects: 0 });
      expect(res.status(), `/${outer}/${inner}/places must hard-404, not soft-404 at 200`).toBe(
        404,
      );

      const html = await res.text();
      const alternates = [...html.matchAll(/<link[^>]+rel="alternate"[^>]*>/g)].map((m) => m[0]);
      expect(
        alternates,
        `a 404 must not advertise hreflang alternates: ${alternates.join(' ')}`,
      ).toEqual([]);
      // Nothing may point back at the doubled shape, in ANY locale.
      expect(html).not.toMatch(new RegExp(`/(${SUPPORTED_LOCALES.join('|')})/${inner}/places`));
    });
  }

  /**
   * Positive control. Without it the assertions above would also pass if
   * /places broke entirely, or if every locale route started 404-ing — i.e.
   * the guard would be strongest exactly when the site is most broken.
   */
  test('positive control: the single-prefix URL still resolves', async ({ request }) => {
    test.skip(
      !(await functionsAreLive(request)),
      'target does not execute Pages Functions (vite preview)',
    );
    const res = await request.get('/fr/places', { maxRedirects: 0 });
    expect(res.status(), '/fr/places must still be served').toBe(200);
  });
});
