import { Globe } from 'lucide-react';
import type { ContentTypeConfig, FieldConfig } from '@/types/cms';

export const countryFields: FieldConfig[] = [
  {
    name: 'name',
    label: 'Country Name',
    type: 'text',
    required: true,
    group: 'basic',
    searchable: true,
    sortable: true,
  },
  {
    name: 'code',
    label: 'Country Code',
    type: 'text',
    required: true,
    group: 'basic',
    maxLength: 3,
  },
  { name: 'slug', label: 'Slug', type: 'text', group: 'basic' },
  { name: 'flag_emoji', label: 'Flag Emoji', type: 'text', group: 'basic' },
  { name: 'description', label: 'Description', type: 'richtext', group: 'basic', colSpan: 2 },
  { name: 'capital', label: 'Capital', type: 'text', group: 'details' },
  { name: 'population', label: 'Population', type: 'number', group: 'details', sortable: true },
  { name: 'area_km2', label: 'Area (km²)', type: 'number', group: 'details' },
  { name: 'currency', label: 'Currency', type: 'text', group: 'details' },
  { name: 'calling_code', label: 'Calling Code', type: 'text', group: 'details' },
  { name: 'internet_tld', label: 'Internet TLD', type: 'text', group: 'details' },
  {
    name: 'driving_side',
    label: 'Driving Side',
    type: 'select',
    group: 'details',
    options: [
      { value: 'right', label: 'Right' },
      { value: 'left', label: 'Left' },
    ],
  },
  { name: 'government_type', label: 'Government Type', type: 'text', group: 'details' },
  { name: 'continent', label: 'Continent', type: 'text', group: 'details' },
  { name: 'languages', label: 'Languages', type: 'tags', group: 'details' },
  { name: 'national_day', label: 'National Day', type: 'text', group: 'details' },
  { name: 'major_religions', label: 'Major Religions', type: 'tags', group: 'details' },
  { name: 'visa_requirements', label: 'Visa Requirements', type: 'json', group: 'details', helpText: 'Visa requirement data by nationality' },
  { name: 'lgbti_data_last_updated', label: 'LGBTI Data Last Updated', type: 'date', group: 'details' },
  { name: 'gdp_usd', label: 'GDP (USD)', type: 'number', group: 'details', readOnly: true },
  { name: 'gdp_per_capita_usd', label: 'GDP per Capita (USD)', type: 'number', group: 'details', readOnly: true },
  { name: 'human_development_index', label: 'HDI', type: 'number', group: 'details', readOnly: true, min: 0, max: 1 },
  { name: 'life_expectancy', label: 'Life Expectancy', type: 'number', group: 'details', readOnly: true },
  { name: 'literacy_rate', label: 'Literacy Rate (%)', type: 'number', group: 'details', readOnly: true, min: 0, max: 100 },
  { name: 'climate_zones', label: 'Climate Zones', type: 'tags', group: 'details', readOnly: true },
  { name: 'natural_resources', label: 'Natural Resources', type: 'tags', group: 'details', readOnly: true },
  { name: 'unesco_sites', label: 'UNESCO Sites', type: 'tags', group: 'details', readOnly: true },
  { name: 'major_industries', label: 'Major Industries', type: 'tags', group: 'details', readOnly: true },
  { name: 'exports', label: 'Exports', type: 'tags', group: 'details', readOnly: true },
  { name: 'imports', label: 'Imports', type: 'tags', group: 'details', readOnly: true },
  { name: 'airport_codes', label: 'Airport Codes', type: 'tags', group: 'details', readOnly: true },
  { name: 'major_airports', label: 'Major Airports', type: 'tags', group: 'details', readOnly: true },
  { name: 'national_symbols', label: 'National Symbols', type: 'json', group: 'details', readOnly: true },
  { name: 'latitude', label: 'Latitude', type: 'number', group: 'location', min: -90, max: 90 },
  { name: 'longitude', label: 'Longitude', type: 'number', group: 'location', min: -180, max: 180 },
  // LGBTQ
  {
    name: 'equality_score',
    label: 'Equality Score',
    type: 'number',
    group: 'lgbtq',
    min: 0,
    max: 100,
  },
  { name: 'lgbt_rights_status', label: 'LGBTQ+ Rights Status', type: 'text', group: 'lgbtq' },
  { name: 'lgbt_legal_status', label: 'Legal Status', type: 'text', group: 'lgbtq' },
  { name: 'lgbti_same_sex_unions', label: 'Same-Sex Unions', type: 'text', group: 'lgbtq' },
  { name: 'lgbti_adoption_rights', label: 'Adoption Rights', type: 'text', group: 'lgbtq' },
  {
    name: 'lgbti_conversion_therapy_regulation',
    label: 'Conversion Therapy',
    type: 'text',
    group: 'lgbtq',
  },
  { name: 'lgbti_intersex_protection', label: 'Intersex Protection', type: 'text', group: 'lgbtq' },
  {
    name: 'lgbti_criminalization',
    label: 'Criminalization Data',
    type: 'json',
    group: 'lgbtq',
    readOnly: true,
  },
  {
    name: 'lgbti_employment_protection',
    label: 'Employment Protection',
    type: 'json',
    group: 'lgbtq',
    readOnly: true,
  },
  {
    name: 'lgbti_constitutional_protection',
    label: 'Constitutional Protection',
    type: 'json',
    group: 'lgbtq',
    readOnly: true,
  },
  {
    name: 'lgbti_gender_recognition',
    label: 'Gender Recognition',
    type: 'json',
    group: 'lgbtq',
    readOnly: true,
  },
  { name: 'lgbti_expression_restrictions', label: 'Expression Restrictions', type: 'json', group: 'lgbtq', readOnly: true },
  { name: 'lgbti_association_restrictions', label: 'Association Restrictions', type: 'json', group: 'lgbtq', readOnly: true },
  { name: 'lgbti_goods_services_protection', label: 'Goods & Services Protection', type: 'json', group: 'lgbtq', readOnly: true },
  { name: 'lgbti_health_protection', label: 'Health Protection', type: 'json', group: 'lgbtq', readOnly: true },
  { name: 'lgbti_education_protection', label: 'Education Protection', type: 'json', group: 'lgbtq', readOnly: true },
  { name: 'lgbti_bullying_protection', label: 'Bullying Protection', type: 'json', group: 'lgbtq', readOnly: true },
  { name: 'lgbti_housing_protection', label: 'Housing Protection', type: 'json', group: 'lgbtq', readOnly: true },
  { name: 'lgbti_hate_crime_law', label: 'Hate Crime Law', type: 'json', group: 'lgbtq', readOnly: true },
  { name: 'lgbti_incitement_prohibition', label: 'Incitement Prohibition', type: 'json', group: 'lgbtq', readOnly: true },
  // Media
  { name: 'image_url', label: 'Country Image', type: 'image', group: 'media' },
  { name: 'curated_image_url', label: 'Curated Image', type: 'image', group: 'media' },
];

export const countryContentType: ContentTypeConfig = {
  id: 'countries',
  tableName: 'countries',
  primaryKey: 'id',
  titleField: 'name',
  descriptionField: 'description',
  imageField: 'image_url',
  icon: Globe,
  label: { singular: 'Country', plural: 'Countries' },
  color: '#6366f1',
  fields: countryFields,
  fieldGroupOrder: ['basic', 'details', 'location', 'lgbtq', 'media'],
  translatableFields: ['name', 'description', 'lgbt_rights_status'],
  commentable: true,
};
