import { Globe } from 'lucide-react';
import type { ContentTypeConfig, FieldConfig } from '@/types/cms';

export const countryFields: FieldConfig[] = [
  {
    name: 'name',
    label: 'Country Name',
    type: 'text',
    required: true,
    group: 'basic',
    searchable: true,
    sortable: true,
  },
  {
    name: 'code',
    label: 'Country Code',
    type: 'text',
    required: true,
    group: 'basic',
    maxLength: 3,
  },
  { name: 'flag_emoji', label: 'Flag Emoji', type: 'text', group: 'basic' },
  { name: 'description', label: 'Description', type: 'richtext', group: 'basic', colSpan: 2 },
  { name: 'capital', label: 'Capital', type: 'text', group: 'details' },
  { name: 'population', label: 'Population', type: 'number', group: 'details', sortable: true },
  { name: 'area_km2', label: 'Area (km²)', type: 'number', group: 'details' },
  { name: 'currency', label: 'Currency', type: 'text', group: 'details' },
  { name: 'calling_code', label: 'Calling Code', type: 'text', group: 'details' },
  { name: 'internet_tld', label: 'Internet TLD', type: 'text', group: 'details' },
  {
    name: 'driving_side',
    label: 'Driving Side',
    type: 'select',
    group: 'details',
    options: [
      { value: 'right', label: 'Right' },
      { value: 'left', label: 'Left' },
    ],
  },
  { name: 'government_type', label: 'Government Type', type: 'text', group: 'details' },
  { name: 'continent', label: 'Continent', type: 'text', group: 'details' },
  { name: 'latitude', label: 'Latitude', type: 'number', group: 'location', min: -90, max: 90 },
  { name: 'longitude', label: 'Longitude', type: 'number', group: 'location', min: -180, max: 180 },
  // LGBTQ
  {
    name: 'equality_score',
    label: 'Equality Score',
    type: 'number',
    group: 'lgbtq',
    min: 0,
    max: 100,
  },
  { name: 'lgbt_rights_status', label: 'LGBTQ+ Rights Status', type: 'text', group: 'lgbtq' },
  { name: 'lgbt_legal_status', label: 'Legal Status', type: 'text', group: 'lgbtq' },
  { name: 'lgbti_same_sex_unions', label: 'Same-Sex Unions', type: 'text', group: 'lgbtq' },
  { name: 'lgbti_adoption_rights', label: 'Adoption Rights', type: 'text', group: 'lgbtq' },
  {
    name: 'lgbti_conversion_therapy_regulation',
    label: 'Conversion Therapy',
    type: 'text',
    group: 'lgbtq',
  },
  { name: 'lgbti_intersex_protection', label: 'Intersex Protection', type: 'text', group: 'lgbtq' },
  {
    name: 'lgbti_criminalization',
    label: 'Criminalization Data',
    type: 'json',
    group: 'lgbtq',
    readOnly: true,
  },
  {
    name: 'lgbti_employment_protection',
    label: 'Employment Protection',
    type: 'json',
    group: 'lgbtq',
    readOnly: true,
  },
  {
    name: 'lgbti_constitutional_protection',
    label: 'Constitutional Protection',
    type: 'json',
    group: 'lgbtq',
    readOnly: true,
  },
  {
    name: 'lgbti_gender_recognition',
    label: 'Gender Recognition',
    type: 'json',
    group: 'lgbtq',
    readOnly: true,
  },
];

export const countryContentType: ContentTypeConfig = {
  id: 'countries',
  tableName: 'countries',
  primaryKey: 'id',
  titleField: 'name',
  descriptionField: 'description',
  icon: Globe,
  label: { singular: 'Country', plural: 'Countries' },
  color: '#6366f1',
  fields: countryFields,
  fieldGroupOrder: ['basic', 'details', 'location', 'lgbtq'],
  translatableFields: ['name', 'description', 'lgbt_rights_status'],
  commentable: true,
};
