import { Calendar } from 'lucide-react';
import type { ContentTypeConfig, FieldConfig } from '@/types/cms';
import { validateEvent } from '@/utils/contentValidation';

export const eventFields: FieldConfig[] = [
  {
    name: 'title',
    label: 'Title',
    type: 'text',
    required: true,
    group: 'basic',
    searchable: true,
    sortable: true,
    maxLength: 255,
  },
  { name: 'description', label: 'Description', type: 'richtext', group: 'basic', colSpan: 2 },
  {
    name: 'edition',
    label: 'Edition',
    type: 'text',
    group: 'basic',
    placeholder: 'e.g. 5th, 2026, Vol. 3',
    maxLength: 100,
  },
  {
    name: 'event_type',
    label: 'Event Type',
    type: 'select',
    required: true,
    group: 'basic',
    filterable: true,
    listColumn: true,
    options: [
      { value: 'party', label: 'Party' },
      { value: 'festival', label: 'Festival' },
      { value: 'pride', label: 'Pride' },
      { value: 'meetup', label: 'Meetup' },
      { value: 'workshop', label: 'Workshop' },
      { value: 'concert', label: 'Concert' },
      { value: 'exhibition', label: 'Exhibition' },
      { value: 'fundraiser', label: 'Fundraiser' },
      { value: 'sports', label: 'Sports' },
      { value: 'community', label: 'Community' },
      { value: 'cruise', label: 'Cruise' },
      { value: 'other', label: 'Other' },
    ],
  },
  {
    name: 'start_date',
    label: 'Start Date',
    type: 'datetime',
    required: true,
    group: 'basic',
    sortable: true,
  },
  { name: 'end_date', label: 'End Date', type: 'datetime', group: 'basic' },
  { name: 'timezone', label: 'Timezone', type: 'text', group: 'basic' },
  {
    name: 'status',
    label: 'Status',
    type: 'select',
    group: 'basic',
    filterable: true,
    options: [
      { value: 'active', label: 'Active' },
      { value: 'cancelled', label: 'Cancelled' },
      { value: 'postponed', label: 'Postponed' },
      { value: 'completed', label: 'Completed' },
    ],
  },
  // Location
  { name: 'venue_name', label: 'Venue Name', type: 'text', group: 'location' },
  { name: 'venue_address', label: 'Venue Address', type: 'text', group: 'location' },
  {
    name: 'address',
    label: 'Address',
    type: 'location',
    group: 'location',
    resolverType: 'address',
    relatedFields: {
      city: 'city',
      state: 'state',
      country: 'country',
      latitude: 'latitude',
      longitude: 'longitude',
      city_id: 'city_id',
      country_id: 'country_id',
      queer_village_id: 'queer_village_id',
    },
  },
  {
    name: 'city',
    label: 'City',
    type: 'city_autocomplete',
    required: true,
    group: 'location',
    filterable: true,
    relatedFields: {
      city_id: 'city_id',
      country_id: 'country_id',
      country: 'country',
    },
  },
  { name: 'state', label: 'State', type: 'text', group: 'location' },
  {
    name: 'country',
    label: 'Country',
    type: 'country_autocomplete',
    required: true,
    group: 'location',
    filterable: true,
    relatedFields: {
      country_id: 'country_id',
      city: 'city',
      city_id: 'city_id',
    },
  },
  {
    name: 'latitude',
    label: 'Latitude',
    type: 'number',
    group: 'location',
    hidden: true,
    min: -90,
    max: 90,
  },
  {
    name: 'longitude',
    label: 'Longitude',
    type: 'number',
    group: 'location',
    hidden: true,
    min: -180,
    max: 180,
  },
  // Details
  { name: 'website', label: 'Website', type: 'url', group: 'details' },
  { name: 'ticket_url', label: 'Ticket URL', type: 'url', group: 'details' },
  { name: 'price_min', label: 'Min Price', type: 'number', group: 'details', min: 0 },
  { name: 'price_max', label: 'Max Price', type: 'number', group: 'details', min: 0 },
  { name: 'currency', label: 'Currency', type: 'text', group: 'details', readOnly: true, helpText: 'Auto-set from country' },
  { name: 'is_free', label: 'Free Event', type: 'boolean', group: 'details' },
  { name: 'age_restriction', label: 'Age Restriction', type: 'text', group: 'details' },
  { name: 'max_attendees', label: 'Max Attendees', type: 'number', group: 'details', min: 0 },
  { name: 'organizer_name', label: 'Organizer', type: 'text', group: 'details' },
  { name: 'organizer_contact', label: 'Organizer Contact', type: 'text', group: 'details' },
  { name: 'is_recurring', label: 'Recurring', type: 'boolean', group: 'details' },
  { name: 'recurrence_pattern', label: 'Recurrence Pattern', type: 'text', group: 'details' },
  { name: 'accessibility_attributes', label: 'Accessibility', type: 'tags', group: 'details' },
  { name: 'target_groups', label: 'Target Groups', type: 'tags', group: 'details' },
  // Media
  { name: 'images', label: 'Images', type: 'images', group: 'media' },
  // Settings
  { name: 'is_featured', label: 'Featured', type: 'boolean', group: 'settings' },
  { name: 'is_public', label: 'Public', type: 'boolean', group: 'settings' },
  // External (hidden FKs)
  { name: 'venue_id', label: 'Venue Reference', type: 'text', group: 'external', hidden: true },
  { name: 'city_id', label: 'City Reference', type: 'text', group: 'external', hidden: true },
  { name: 'country_id', label: 'Country Reference', type: 'text', group: 'external', hidden: true },
  {
    name: 'queer_village_id',
    label: 'Queer Village',
    type: 'text',
    group: 'external',
    readOnly: true,
  },
];

export const eventContentType: ContentTypeConfig = {
  id: 'events',
  tableName: 'events',
  primaryKey: 'id',
  titleField: 'title',
  descriptionField: 'description',
  imageField: 'images',
  icon: Calendar,
  label: { singular: 'Event', plural: 'Events' },
  color: '#ec4899',
  fields: eventFields,
  defaults: { is_featured: false, is_free: false, is_public: true, status: 'active' },
  validate: validateEvent,
  fieldGroupOrder: ['basic', 'location', 'details', 'media', 'settings'],
  translatableFields: ['title', 'description'],
  commentable: true,
  aiAssist: {
    ops: ['summarize', 'seo_draft', 'auto_tag'],
    writableFields: ['description', 'meta_title', 'meta_description', 'tags'],
  },
};
