import { Newspaper } from 'lucide-react';
import type { ContentTypeConfig, FieldConfig } from '@/types/cms';
import { validateNewsArticle } from '@/utils/contentValidation';

export const newsArticleFields: FieldConfig[] = [
  {
    name: 'title',
    label: 'Title',
    type: 'text',
    required: true,
    group: 'basic',
    searchable: true,
    sortable: true,
    maxLength: 255,
  },
  { name: 'excerpt', label: 'Excerpt', type: 'textarea', group: 'basic' },
  { name: 'content', label: 'Content', type: 'richtext', group: 'basic', colSpan: 2 },
  { name: 'url', label: 'Source URL', type: 'url', required: true, group: 'basic' },
  {
    name: 'publisher_name',
    label: 'Medium',
    type: 'text',
    group: 'basic',
    filterable: true,
    sortable: true,
    listColumn: true,
  },
  {
    name: 'author',
    label: 'Author',
    type: 'text',
    group: 'basic',
    filterable: true,
    listColumn: true,
  },
  {
    // Authoritative category. Options are the `news_categories` slugs — the same
    // vocabulary the public tabs and the classifier use. This field previously
    // pointed at the legacy `category` column with its own private 8-value list
    // (travel/entertainment exist nowhere else in the product), which is why the
    // admin list rendered "General" on 93% of rows.
    name: 'category_canonical',
    label: 'Category',
    type: 'select',
    required: true,
    group: 'basic',
    filterable: true,
    listColumn: true,
    options: [
      { value: 'rights-legal', label: 'Rights & Legal' },
      { value: 'politics', label: 'Politics' },
      { value: 'community', label: 'Community' },
      { value: 'health-wellness', label: 'Health & Wellness' },
      { value: 'culture-arts', label: 'Culture & Arts' },
      { value: 'sports', label: 'Sports' },
      { value: 'education', label: 'Education' },
      { value: 'technology', label: 'Technology' },
      { value: 'business-economy', label: 'Business & Economy' },
      { value: 'international', label: 'International' },
      { value: 'general', label: 'General (unclassified)' },
    ],
  },
  {
    name: 'published_at',
    label: 'Published',
    type: 'datetime',
    group: 'basic',
    sortable: true,
    filterable: true,
    listColumn: true,
  },
  {
    name: 'first_seen_at',
    label: 'First seen',
    type: 'datetime',
    group: 'details',
    sortable: true,
    filterable: true,
  },
  {
    name: 'sentiment',
    label: 'Sentiment',
    type: 'select',
    group: 'details',
    filterable: true,
    listColumn: true,
    options: [
      { value: 'positive', label: 'Positive' },
      { value: 'neutral', label: 'Neutral' },
      { value: 'negative', label: 'Negative' },
    ],
  },
  {
    name: 'lgbti_relevance_score',
    label: 'Relevance',
    type: 'number',
    group: 'details',
    sortable: true,
    filterable: true,
    listColumn: true,
    min: 0,
    max: 1,
  },
  {
    name: 'quality_score',
    label: 'Quality',
    type: 'number',
    group: 'details',
    sortable: true,
    filterable: true,
    min: 0,
    max: 1,
  },
  { name: 'tags', label: 'Tags', type: 'unified_tag', group: 'details' },
  {
    name: 'source_id',
    label: 'News Source',
    type: 'select',
    group: 'details',
    filterable: true,
    dynamicOptions: { table: 'news_sources', valueColumn: 'id', labelColumn: 'name' },
  },
  { name: 'image_attribution', label: 'Image Attribution', type: 'text', group: 'details' },
  {
    name: 'country_ids',
    label: 'Countries',
    type: 'tags',
    group: 'details',
    helpText: 'Country geo-tags',
  },
  { name: 'city_ids', label: 'Cities', type: 'tags', group: 'details', helpText: 'City geo-tags' },
  { name: 'image_url', label: 'Image', type: 'image', group: 'media' },
  {
    name: 'is_featured',
    label: 'Featured',
    type: 'boolean',
    group: 'settings',
    filterable: true,
    listColumn: true,
  },
  {
    name: 'is_editors_pick',
    label: "Editor's pick",
    type: 'boolean',
    group: 'settings',
    filterable: true,
    listColumn: true,
    helpText: 'Surfaces as the right-hand column of the Above-the-fold band on /news.',
  },
  {
    name: 'needs_attention',
    label: 'Needs attention',
    type: 'boolean',
    group: 'settings',
    filterable: true,
    listColumn: true,
  },
  // External
  { name: 'views_count', label: 'Views', type: 'number', group: 'external', readOnly: true },
  {
    name: 'relevance_score',
    label: 'Relevance Score',
    type: 'number',
    group: 'external',
    readOnly: true,
    min: 0,
    max: 1,
  },
];

export const newsArticleContentType: ContentTypeConfig = {
  id: 'news_articles',
  tableName: 'news_articles',
  primaryKey: 'id',
  titleField: 'title',
  descriptionField: 'excerpt',
  imageField: 'image_url',
  icon: Newspaper,
  label: { singular: 'News Article', plural: 'News Articles' },
  color: 'hsl(var(--foreground))',
  fields: newsArticleFields,
  defaults: { category_canonical: 'general', is_featured: false },
  validate: validateNewsArticle,
  defaultSort: { field: 'published_at', dir: 'desc' },
  fieldGroupOrder: ['basic', 'details', 'media', 'settings', 'external'],
  translatableFields: ['title', 'excerpt', 'content'],
  commentable: true,
  aiAssist: {
    ops: ['quality_review', 'summarize', 'seo_draft', 'auto_tag'],
    // No meta_title/meta_description — news_articles has no such columns. SEO
    // overrides for entity types live in the cms_content_metadata sidecar.
    writableFields: ['excerpt', 'tags'],
  },
  admin: {
    duplicatesRoute: '/admin/duplicates',
    dedup: {
      searchType: 'news',
      metaTable: 'news_articles',
      metaCols: 'id, quality_score, created_at, is_featured',
      mergePath: 'entities',
    },
  },
  // `archived_at` added in 20261028100000 — see hotel.ts.
  lifecycle: {
    type: 'news',
    archive: { column: 'archived_at', predicate: 'present', label: 'Archived' },
  },
  publicPath: (row) => (row.slug ? `/news/${row.slug}` : null),
};
