import { Newspaper } from 'lucide-react';
import type { ContentTypeConfig, FieldConfig } from '@/types/cms';
import { validateNewsArticle } from '@/utils/contentValidation';

export const newsArticleFields: FieldConfig[] = [
  {
    name: 'title',
    label: 'Title',
    type: 'text',
    required: true,
    group: 'basic',
    searchable: true,
    sortable: true,
    maxLength: 255,
  },
  { name: 'excerpt', label: 'Excerpt', type: 'textarea', group: 'basic' },
  { name: 'content', label: 'Content', type: 'richtext', group: 'basic', colSpan: 2 },
  { name: 'url', label: 'Source URL', type: 'url', required: true, group: 'basic' },
  {
    name: 'publisher_name',
    label: 'Medium',
    type: 'text',
    group: 'basic',
    filterable: true,
    sortable: true,
    listColumn: true,
  },
  {
    name: 'author',
    label: 'Author',
    type: 'text',
    group: 'basic',
    filterable: true,
    listColumn: true,
  },
  {
    name: 'category',
    label: 'Category',
    type: 'select',
    required: true,
    group: 'basic',
    filterable: true,
    listColumn: true,
    options: [
      { value: 'general', label: 'General' },
      { value: 'politics', label: 'Politics' },
      { value: 'culture', label: 'Culture' },
      { value: 'health', label: 'Health' },
      { value: 'travel', label: 'Travel' },
      { value: 'community', label: 'Community' },
      { value: 'rights', label: 'Rights' },
      { value: 'entertainment', label: 'Entertainment' },
    ],
  },
  {
    name: 'published_at',
    label: 'Published',
    type: 'datetime',
    group: 'basic',
    sortable: true,
    filterable: true,
    listColumn: true,
  },
  {
    name: 'first_seen_at',
    label: 'First seen',
    type: 'datetime',
    group: 'details',
    sortable: true,
    filterable: true,
  },
  {
    name: 'sentiment',
    label: 'Sentiment',
    type: 'select',
    group: 'details',
    filterable: true,
    listColumn: true,
    options: [
      { value: 'positive', label: 'Positive' },
      { value: 'neutral', label: 'Neutral' },
      { value: 'negative', label: 'Negative' },
    ],
  },
  {
    name: 'lgbti_relevance_score',
    label: 'Relevance',
    type: 'number',
    group: 'details',
    sortable: true,
    filterable: true,
    listColumn: true,
    min: 0,
    max: 1,
  },
  {
    name: 'quality_score',
    label: 'Quality',
    type: 'number',
    group: 'details',
    sortable: true,
    filterable: true,
    min: 0,
    max: 1,
  },
  { name: 'tags', label: 'Tags', type: 'tags', group: 'details' },
  {
    name: 'source_id',
    label: 'News Source',
    type: 'select',
    group: 'details',
    filterable: true,
    dynamicOptions: { table: 'news_sources', valueColumn: 'id', labelColumn: 'name' },
  },
  { name: 'image_attribution', label: 'Image Attribution', type: 'text', group: 'details' },
  { name: 'country_ids', label: 'Countries', type: 'tags', group: 'details', helpText: 'Country geo-tags' },
  { name: 'city_ids', label: 'Cities', type: 'tags', group: 'details', helpText: 'City geo-tags' },
  { name: 'image_url', label: 'Image', type: 'image', group: 'media' },
  {
    name: 'is_featured',
    label: 'Featured',
    type: 'boolean',
    group: 'settings',
    filterable: true,
    listColumn: true,
  },
  {
    name: 'needs_attention',
    label: 'Needs attention',
    type: 'boolean',
    group: 'settings',
    filterable: true,
    listColumn: true,
  },
  // External
  { name: 'views_count', label: 'Views', type: 'number', group: 'external', readOnly: true },
  { name: 'relevance_score', label: 'Relevance Score', type: 'number', group: 'external', readOnly: true, min: 0, max: 1 },
];

export const newsArticleContentType: ContentTypeConfig = {
  id: 'news_articles',
  tableName: 'news_articles',
  primaryKey: 'id',
  titleField: 'title',
  descriptionField: 'excerpt',
  imageField: 'image_url',
  icon: Newspaper,
  label: { singular: 'News Article', plural: 'News Articles' },
  color: '#3b82f6',
  fields: newsArticleFields,
  defaults: { category: 'general', is_featured: false },
  validate: validateNewsArticle,
  defaultSort: { field: 'published_at', dir: 'desc' },
  fieldGroupOrder: ['basic', 'details', 'media', 'settings', 'external'],
  translatableFields: ['title', 'excerpt', 'content'],
  commentable: true,
  aiAssist: {
    ops: ['summarize', 'seo_draft', 'auto_tag'],
    writableFields: ['excerpt', 'meta_title', 'meta_description', 'tags'],
  },
};
