import { Building } from 'lucide-react';
import type { ContentTypeConfig, FieldConfig } from '@/types/cms';
import { validateVenue } from '@/utils/contentValidation';

export const venueFields: FieldConfig[] = [
  // Basic
  {
    name: 'name',
    label: 'Name',
    type: 'text',
    required: true,
    group: 'basic',
    searchable: true,
    sortable: true,
    maxLength: 255,
  },
  { name: 'description', label: 'Description', type: 'richtext', group: 'basic', colSpan: 2 },
  {
    name: 'category',
    label: 'Category',
    type: 'select',
    required: true,
    group: 'basic',
    filterable: true,
    options: [
      { value: 'bar', label: 'Bar' },
      { value: 'club', label: 'Club' },
      { value: 'restaurant', label: 'Restaurant' },
      { value: 'cafe', label: 'Café' },
      { value: 'sauna', label: 'Sauna' },
      { value: 'hotel', label: 'Hotel' },
      { value: 'shop', label: 'Shop' },
      { value: 'community_center', label: 'Community Center' },
      { value: 'beach', label: 'Beach' },
      { value: 'cruise_club', label: 'Cruise Club' },
      { value: 'theater', label: 'Theater' },
      { value: 'gallery', label: 'Gallery' },
      { value: 'bookstore', label: 'Bookstore' },
      { value: 'gym', label: 'Gym' },
      { value: 'other', label: 'Other' },
    ],
  },
  // Location
  {
    name: 'address',
    label: 'Address',
    type: 'location',
    group: 'location',
    resolverType: 'address',
    relatedFields: {
      city: 'city',
      state: 'state',
      country: 'country',
      postal_code: 'postal_code',
      latitude: 'latitude',
      longitude: 'longitude',
      city_id: 'city_id',
      country_id: 'country_id',
      queer_village_id: 'queer_village_id',
    },
  },
  {
    name: 'city',
    label: 'City',
    type: 'city_autocomplete',
    required: true,
    group: 'location',
    filterable: true,
    relatedFields: {
      city_id: 'city_id',
      country_id: 'country_id',
      country: 'country',
    },
  },
  { name: 'state', label: 'State/Province', type: 'text', group: 'location' },
  {
    name: 'country',
    label: 'Country',
    type: 'country_autocomplete',
    required: true,
    group: 'location',
    filterable: true,
    relatedFields: {
      country_id: 'country_id',
      city: 'city',
      city_id: 'city_id',
    },
  },
  { name: 'postal_code', label: 'Postal Code', type: 'text', group: 'location' },
  {
    name: 'latitude',
    label: 'Latitude',
    type: 'number',
    group: 'location',
    hidden: true,
    min: -90,
    max: 90,
  },
  {
    name: 'longitude',
    label: 'Longitude',
    type: 'number',
    group: 'location',
    hidden: true,
    min: -180,
    max: 180,
  },
  // Details
  { name: 'phone', label: 'Phone', type: 'phone', group: 'details' },
  { name: 'email', label: 'Email', type: 'email', group: 'details' },
  { name: 'website', label: 'Website', type: 'url', group: 'details' },
  { name: 'instagram', label: 'Instagram', type: 'text', group: 'details', placeholder: '@handle' },
  {
    name: 'price_range',
    label: 'Price Range',
    type: 'select',
    group: 'details',
    options: [
      { value: '1', label: '$ (Budget)' },
      { value: '2', label: '$$ (Mid-range)' },
      { value: '3', label: '$$$ (Upscale)' },
      { value: '4', label: '$$$$ (Fine Dining)' },
    ],
  },
  {
    name: 'hours',
    label: 'Opening Hours',
    type: 'json',
    group: 'details',
    helpText: 'JSON with day names as keys',
  },
  { name: 'amenities', label: 'Amenities', type: 'tags', group: 'details' },
  { name: 'services', label: 'Services', type: 'tags', group: 'details' },
  { name: 'tags', label: 'Tags', type: 'tags', group: 'details' },
  { name: 'accessibility_attributes', label: 'Accessibility', type: 'tags', group: 'details' },
  { name: 'target_groups', label: 'Target Groups', type: 'tags', group: 'details' },
  { name: 'accessibility_notes', label: 'Accessibility Notes', type: 'textarea', group: 'details' },
  // Media
  { name: 'images', label: 'Images', type: 'images', group: 'media' },
  // Settings
  { name: 'featured', label: 'Featured', type: 'boolean', group: 'settings' },
  { name: 'verified', label: 'Verified', type: 'boolean', group: 'settings' },
  {
    name: 'closed_at',
    label: 'Closed At',
    type: 'datetime',
    group: 'settings',
    helpText: 'Set when this venue permanently closed. Leave empty if still open.',
  },
  // External (read-only)
  {
    name: 'foursquare_id',
    label: 'Foursquare ID',
    type: 'text',
    group: 'external',
    readOnly: true,
  },
  {
    name: 'foursquare_rating',
    label: 'Foursquare Rating',
    type: 'number',
    group: 'external',
    readOnly: true,
  },
  { name: 'data_source', label: 'Data Source', type: 'text', group: 'external', readOnly: true },
  { name: 'city_id', label: 'City Reference', type: 'text', group: 'external', hidden: true },
  { name: 'country_id', label: 'Country Reference', type: 'text', group: 'external', hidden: true },
  {
    name: 'queer_village_id',
    label: 'Queer Village',
    type: 'text',
    group: 'external',
    readOnly: true,
  },
];

export const venueContentType: ContentTypeConfig = {
  id: 'venues',
  tableName: 'venues',
  primaryKey: 'id',
  titleField: 'name',
  descriptionField: 'description',
  imageField: 'images',
  icon: Building,
  label: { singular: 'Venue', plural: 'Venues' },
  color: '#DB2777',
  fields: venueFields,
  defaults: { featured: false, verified: false },
  validate: validateVenue,
  fieldGroupOrder: ['basic', 'location', 'details', 'media', 'settings', 'external'],
  translatableFields: ['name', 'description', 'accessibility_notes'],
  commentable: true,
  aiAssist: {
    ops: ['summarize', 'seo_draft', 'auto_tag', 'fact_check'],
    writableFields: ['description', 'meta_title', 'meta_description', 'tags'],
  },
};
