-- Insert role tags
INSERT INTO public.tags (name, category, description) 
SELECT name, category, description FROM (VALUES
  ('acolyte', 'roles', 'Religious or spiritual follower role'),
  ('adult baby', 'roles', 'Age regression role playing as an infant'),
  ('Adventurer', 'roles', 'Explorer or seeker of new experiences'),
  ('Aesthetic Exhibitionist', 'roles', 'Person who displays themselves for artistic beauty'),
  ('Affection Slut', 'roles', 'Person who craves affection and attention'),
  ('Ageplayer', 'roles', 'Person who engages in age regression play'),
  ('Alien', 'roles', 'Otherworldly or extraterrestrial role'),
  ('Anal Slut', 'roles', 'Person focused on anal activities'),
  ('Angel', 'roles', 'Divine or heavenly being role'),
  ('Alpha', 'roles', 'Dominant leadership role'),
  ('Alpha Pet', 'roles', 'Dominant pet in hierarchy'),
  ('alpha submissive', 'roles', 'Dominant submissive role'),
  ('Archangel', 'roles', 'High-ranking divine being'),
  ('Artist', 'roles', 'Creative or artistic role'),
  ('ashtray', 'roles', 'Object used for smoking fetish'),
  ('Ass Centric', 'roles', 'Focused on buttocks worship'),
  ('Attention Slut', 'roles', 'Person who seeks attention'),
  ('Attention Whore', 'roles', 'Person who demands attention'),
  ('Aunt', 'roles', 'Family role in age play'),
  ('baby', 'roles', 'Infant role in age play'),
  ('babyboy', 'roles', 'Male baby role'),
  ('babydoll', 'roles', 'Cute baby role'),
  ('babyfur', 'roles', 'Furry baby role'),
  ('babygirl', 'roles', 'Female baby role'),
  ('babyghoul', 'roles', 'Gothic baby role'),
  ('bad boy', 'roles', 'Rebellious male role'),
  ('bad girl', 'roles', 'Rebellious female role'),
  ('Badge Bunny', 'roles', 'Person attracted to authority figures'),
  ('Bakushi', 'roles', 'Japanese rope bondage artist'),
  ('Ballbustee', 'roles', 'Receiver of ballbusting'),
  ('Ballbuster', 'roles', 'Person who performs ballbusting'),
  ('Balloon', 'roles', 'Balloon fetish role'),
  ('Battle Sub', 'roles', 'Resistant submissive'),
  ('Beast', 'roles', 'Animal or creature role'),
  ('Bedroom Dom', 'roles', 'Dominant only in sexual contexts'),
  ('Bedroom Submissive', 'roles', 'Submissive only in sexual contexts'),
  ('Beta', 'roles', 'Secondary or follower role'),
  ('Big', 'roles', 'Caregiver role in age play'),
  ('Big Brother', 'roles', 'Older brother role'),
  ('Big Sister', 'roles', 'Older sister role'),
  ('Big Spoon', 'roles', 'Cuddling position role'),
  ('Bimbo', 'roles', 'Stereotypically feminine role'),
  ('bitch', 'roles', 'Submissive or degraded role'),
  ('Blood Player', 'roles', 'Person involved in blood play'),
  ('Blue Booty Buddy', 'roles', 'Law enforcement attraction role'),
  ('Board Member', 'roles', 'Authority figure role'),
  ('Bobcat', 'roles', 'Wild cat animal role'),
  ('bodyguard', 'roles', 'Protective role'),
  ('boi', 'roles', 'Young male or masculine role'),
  ('Bondage Bottom', 'roles', 'Receiver of bondage'),
  ('bondage slut', 'roles', 'Person who loves bondage'),
  ('Bondage Switch', 'roles', 'Both giver and receiver of bondage'),
  ('Bondage Top', 'roles', 'Person who performs bondage'),
  ('bondmaid', 'roles', 'Bonded servant role'),
  ('Boner Donor', 'roles', 'Person who provides arousal'),
  ('boot bitch', 'roles', 'Boot worship submissive'),
  ('Bootblack', 'roles', 'Boot care specialist'),
  ('boot slut', 'roles', 'Boot fetish enthusiast'),
  ('Boss', 'roles', 'Authority figure role'),
  ('bossy bottom', 'roles', 'Demanding bottom role'),
  ('bottom', 'roles', 'Receiving partner in activities'),
  ('Bottom-Leaning Switch', 'roles', 'Switch who prefers bottoming'),
  ('Boy Toy', 'roles', 'Young male plaything'),
  ('Brat', 'roles', 'Mischievous or defiant role'),
  ('Brat Breaker', 'roles', 'Person who disciplines brats'),
  ('Brat Enabler', 'roles', 'Person who encourages bratty behavior'),
  ('Brat Tamer', 'roles', 'Person who controls brats'),
  ('Brat Handler', 'roles', 'Person who manages brats'),
  ('Brat Wrangler', 'roles', 'Person who corrals brats'),
  ('bratochist', 'roles', 'Masochistic brat'),
  ('Bratty Dom / Bratty Domme', 'roles', 'Dominant with bratty tendencies'),
  ('Brother', 'roles', 'Sibling role'),
  ('Buck', 'roles', 'Male deer or dominant male'),
  ('Bull', 'roles', 'Dominant male in cuckold scenarios'),
  ('Bully', 'roles', 'Aggressive dominant role'),
  ('bunny', 'roles', 'Cute animal role'),
  ('butler', 'roles', 'Service role'),
  ('Captive', 'roles', 'Prisoner or captured role'),
  ('captor', 'roles', 'Person who captures others'),
  ('Caregiver', 'roles', 'Nurturing role'),
  ('Castrator', 'roles', 'Person who performs castration play'),
  ('Castratrix', 'roles', 'Female castrator'),
  ('Cat', 'roles', 'Feline animal role'),
  ('catboy', 'roles', 'Male cat role'),
  ('catgirl', 'roles', 'Female cat role'),
  ('Centaur', 'roles', 'Mythological creature role'),
  ('chain mouse', 'roles', 'Small chained pet'),
  ('chaos gremlin', 'roles', 'Mischievous troublemaker'),
  ('Chaos Gremlin Tamer', 'roles', 'Person who controls chaos gremlins'),
  ('Chaos Kitten', 'roles', 'Mischievous kitten role'),
  ('Chastity Queen', 'roles', 'Person who controls chastity'),
  ('chauffeur', 'roles', 'Driver service role'),
  ('Cheerleader', 'roles', 'Supportive enthusiastic role'),
  ('chew toy', 'roles', 'Object for biting or chewing'),
  ('Circus Master', 'roles', 'Leader of circus performers'),
  ('Circus Mistress', 'roles', 'Female circus leader'),
  ('Clown', 'roles', 'Entertaining performer role'),
  ('cock sleeve', 'roles', 'Penis covering object role'),
  ('cock whore', 'roles', 'Person obsessed with penises'),
  ('Cock Worshipper', 'roles', 'Person who worships penises'),
  ('Commander', 'roles', 'Military leadership role'),
  ('concubine', 'roles', 'Sexual servant role'),
  ('Concubus', 'roles', 'Gender-neutral succubus'),
  ('conditional slave', 'roles', 'Slave with conditions'),
  ('Conductor', 'roles', 'Orchestra leader role'),
  ('Consort', 'roles', 'Royal companion'),
  ('Corruptor', 'roles', 'Person who corrupts others'),
  ('Cougar', 'roles', 'Older woman seeking younger partners'),
  ('Cousin', 'roles', 'Extended family role'),
  ('Cow', 'roles', 'Farm animal role'),
  ('Crafter', 'roles', 'Creative maker role'),
  ('Creature', 'roles', 'Non-human being'),
  ('Cryptid', 'roles', 'Mysterious creature role'),
  ('Cub', 'roles', 'Young animal role'),
  ('cuckold', 'roles', 'Husband whose wife has other partners'),
  ('Cuckcake', 'roles', 'Third party in cuckolding'),
  ('Cuckoldress', 'roles', 'Wife who cuckolds her husband'),
  ('cuckquean', 'roles', 'Wife whose husband has other partners'),
  ('Cuddle Slut', 'roles', 'Person who loves cuddling'),
  ('Cuddly Mogwai', 'roles', 'Cute creature role'),
  ('cumdump', 'roles', 'Receptacle for semen'),
  ('Cum Slut', 'roles', 'Person who loves receiving semen'),
  ('Cunt', 'roles', 'Vulgar term for submissive'),
  ('cupcake', 'roles', 'Sweet cute role'),
  ('Daddi', 'roles', 'Alternative spelling of daddy'),
  ('Daddy', 'roles', 'Paternal dominant role'),
  ('Daddy Dom', 'roles', 'Dominant father figure'),
  ('Daddy Domme', 'roles', 'Female daddy figure'),
  ('damsel', 'roles', 'Maiden in need of rescue'),
  ('Damsel in distress', 'roles', 'Person needing rescue'),
  ('Dancer', 'roles', 'Performing artist role'),
  ('Dark Dom', 'roles', 'Sinister dominant'),
  ('Degrader', 'roles', 'Person who degrades others'),
  ('degradee', 'roles', 'Person who enjoys being degraded'),
  ('Deity', 'roles', 'Divine being role'),
  ('Delta', 'roles', 'Third level in hierarchy'),
  ('Denial Player', 'roles', 'Person involved in orgasm denial'),
  ('Denial Top', 'roles', 'Person who denies orgasms'),
  ('Denial Switch', 'roles', 'Switch in denial play'),
  ('denial bottom', 'roles', 'Person who receives denial'),
  ('Demon', 'roles', 'Evil supernatural being'),
  ('Demon Daddy', 'roles', 'Demonic father figure'),
  ('Demoness', 'roles', 'Female demon'),
  ('Demonette', 'roles', 'Young female demon'),
  ('Deviant', 'roles', 'Person with unconventional desires'),
  ('devotee', 'roles', 'Dedicated follower'),
  ('Diaper Lover', 'roles', 'Person with diaper fetish'),
  ('Disciplinarian', 'roles', 'Person who enforces discipline'),
  ('Disciplinee', 'roles', 'Person who receives discipline'),
  ('Diva', 'roles', 'Prima donna role'),
  ('Doe', 'roles', 'Female deer role'),
  ('doll', 'roles', 'Toy-like role'),
  ('Dollmaker', 'roles', 'Person who creates dolls'),
  ('Domina', 'roles', 'Female dominant'),
  ('Dominant', 'roles', 'Person in control'),
  ('Dominant Bottom', 'roles', 'Bottom who controls the scene'),
  ('Dominant Masochist', 'roles', 'Dominant who enjoys pain'),
  ('Dom-Leaning Switch', 'roles', 'Switch who prefers dominating'),
  ('Domme', 'roles', 'Female dominant'),
  ('Dom(me) Tamer', 'roles', 'Person who tames dominants'),
  ('Drag King', 'roles', 'Person performing masculine drag'),
  ('Drag Queen', 'roles', 'Person performing feminine drag'),
  ('Dragon', 'roles', 'Mythical creature role'),
  ('drone', 'roles', 'Mindless worker role'),
  ('Duchess', 'roles', 'Noble title role'),
  ('duck', 'roles', 'Waterfowl role'),
  ('ducky', 'roles', 'Cute duck role'),
  ('Edge bottom', 'roles', 'Person who receives edging'),
  ('Edge Player', 'roles', 'Person who practices edge play'),
  ('Edge Switch', 'roles', 'Switch in edge play'),
  ('Edge Top', 'roles', 'Person who performs edging'),
  ('Educator', 'roles', 'Teaching role'),
  ('Electro Bottom', 'roles', 'Receiver of electrical play'),
  ('Electro Switch', 'roles', 'Switch in electrical play'),
  ('Electro Top', 'roles', 'Person who performs electrical play'),
  ('Emotional Masochist', 'roles', 'Person who enjoys emotional pain'),
  ('Emotional Sadist', 'roles', 'Person who inflicts emotional pain'),
  ('Emotional Sadomasochist', 'roles', 'Person who enjoys giving and receiving emotional pain'),
  ('Empress', 'roles', 'Female ruler role'),
  ('Enchantress', 'roles', 'Magical seductress'),
  ('Energy Bottom', 'roles', 'Receiver of energy play'),
  ('Energy Player', 'roles', 'Person involved in energy exchange'),
  ('Energy Switch', 'roles', 'Switch in energy play'),
  ('Energy Top', 'roles', 'Person who directs energy'),
  ('Evil Scientist', 'roles', 'Mad scientist role'),
  ('Evolving', 'roles', 'Person discovering their role'),
  ('Exhibitionist', 'roles', 'Person who enjoys being watched'),
  ('Experimentalist', 'roles', 'Person who tries new things'),
  ('Exploring', 'roles', 'Person discovering kink'),
  ('Facilitator', 'roles', 'Person who helps others'),
  ('Fae', 'roles', 'Fairy creature role'),
  ('Fairy Kink Daddy', 'roles', 'Magical father figure'),
  ('Fairy Kink Mother', 'roles', 'Magical mother figure'),
  ('Familiar', 'roles', 'Magical companion'),
  ('Feedee', 'roles', 'Person who is fed'),
  ('Feeder', 'roles', 'Person who feeds others'),
  ('FemBull', 'roles', 'Female bull role'),
  ('FemDaddy', 'roles', 'Female daddy role'),
  ('Femme Daddy', 'roles', 'Feminine daddy role'),
  ('FemDom slave', 'roles', 'Slave to female dominant'),
  ('Femdom submissive', 'roles', 'Submissive to female dominant'),
  ('Feminizer', 'roles', 'Person who feminizes others'),
  ('feminizee', 'roles', 'Person being feminized'),
  ('Femme Fatale', 'roles', 'Dangerous seductress'),
  ('Feral', 'roles', 'Wild animal role'),
  ('Fetishist', 'roles', 'Person with specific fetishes'),
  ('Final Girl', 'roles', 'Horror movie survivor trope'),
  ('FinDom(me)', 'roles', 'Financial dominant'),
  ('fire bottom', 'roles', 'Receiver of fire play'),
  ('fire bunny', 'roles', 'Fire play enthusiast'),
  ('Fire Fairy', 'roles', 'Magical fire being'),
  ('Fire Switch', 'roles', 'Switch in fire play'),
  ('Fire Top', 'roles', 'Person who performs fire play'),
  ('Fistee', 'roles', 'Person receiving fisting'),
  ('Fister', 'roles', 'Person who fists'),
  ('Fisting Bottom', 'roles', 'Bottom in fisting'),
  ('Fisting Top', 'roles', 'Top in fisting'),
  ('Fitdom', 'roles', 'Fitness-focused dominant'),
  ('Flirt', 'roles', 'Playfully seductive person'),
  ('Floozy', 'roles', 'Promiscuous person'),
  ('Food Daddy', 'roles', 'Food-focused caregiver'),
  ('Food Player', 'roles', 'Person involved in food play'),
  ('Foodslut', 'roles', 'Person obsessed with food play'),
  ('Foot Bottom', 'roles', 'Receiver in foot play'),
  ('Foot Fetishist', 'roles', 'Person with foot fetish'),
  ('Footlady', 'roles', 'Female foot dominant'),
  ('Foot Lover', 'roles', 'Person who loves feet'),
  ('Foot Slut', 'roles', 'Person obsessed with feet'),
  ('Foot Switch', 'roles', 'Switch in foot play'),
  ('Foot Top', 'roles', 'Dominant in foot play'),
  ('Foster Daddy', 'roles', 'Temporary father figure'),
  ('Foster Mommy', 'roles', 'Temporary mother figure'),
  ('fox', 'roles', 'Cunning animal role'),
  ('Freak', 'roles', 'Unusual or kinky person'),
  ('Frog', 'roles', 'Amphibian role'),
  ('Fuckboy', 'roles', 'Casual sexual partner'),
  ('Fuckdoll', 'roles', 'Sexual toy role'),
  ('fuck puppet', 'roles', 'Controlled sexual object'),
  ('Fucktoy', 'roles', 'Sexual plaything'),
  ('Furry', 'roles', 'Animal character role'),
  ('Gamma', 'roles', 'Third tier in hierarchy'),
  ('genie', 'roles', 'Wish-granting magical being'),
  ('Gentleman', 'roles', 'Refined male role'),
  ('Giantess Foot Slave', 'roles', 'Slave to giant woman''s feet'),
  ('gimp', 'roles', 'Bound or masked person'),
  ('goat', 'roles', 'Farm animal role'),
  ('Goblin', 'roles', 'Mischievous creature'),
  ('Goblin King', 'roles', 'Ruler of goblins'),
  ('God', 'roles', 'Divine male being'),
  ('Goddess', 'roles', 'Divine female being'),
  ('Goddex', 'roles', 'Gender-neutral divine being'),
  ('good boy', 'roles', 'Well-behaved male'),
  ('good girl', 'roles', 'Well-behaved female'),
  ('Gooner', 'roles', 'Person obsessed with arousal'),
  ('Goonette', 'roles', 'Female gooner'),
  ('Gorean', 'roles', 'Follower of Gor philosophy'),
  ('Guitarist', 'roles', 'Musical performer'),
  ('Halfling', 'roles', 'Small fantasy creature'),
  ('Handler', 'roles', 'Person who manages others'),
  ('hand puppet', 'roles', 'Controlled toy role'),
  ('Head of Household', 'roles', 'Family leader'),
  ('Hedgehog', 'roles', 'Spiky animal role'),
  ('Hedonist', 'roles', 'Pleasure seeker'),
  ('Hellhound', 'roles', 'Demonic dog'),
  ('hellpuppy', 'roles', 'Demonic puppy'),
  ('Henchman', 'roles', 'Villainous assistant'),
  ('Himbo', 'roles', 'Attractive but simple male'),
  ('hole', 'roles', 'Sexual opening role'),
  ('Host', 'roles', 'Person who entertains'),
  ('Hothusband', 'roles', 'Attractive married man'),
  ('Hotwife', 'roles', 'Married woman with other partners'),
  ('hucow', 'roles', 'Human cow role'),
  ('Human Canvas', 'roles', 'Person for body art'),
  ('human furniture', 'roles', 'Person used as furniture'),
  ('hypno bottom', 'roles', 'Subject of hypnosis'),
  ('Hypno Top', 'roles', 'Person who hypnotizes'),
  ('Imp', 'roles', 'Small mischievous demon'),
  ('Impact Bottom', 'roles', 'Receiver of impact play'),
  ('Impact Model', 'roles', 'Model for impact demonstrations'),
  ('Impact Switch', 'roles', 'Switch in impact play'),
  ('Impact Top', 'roles', 'Person who performs impact play'),
  ('Incubus', 'roles', 'Male sexual demon'),
  ('Intellectual Sadist', 'roles', 'Sadist who enjoys mental games'),
  ('Intellectual Sadomasochist', 'roles', 'Person who enjoys intellectual pain exchange'),
  ('Jarl', 'roles', 'Norse noble title'),
  ('kajira', 'roles', 'Female Gorean slave'),
  ('kajirus', 'roles', 'Male Gorean slave'),
  ('Key Holder', 'roles', 'Person who controls chastity device'),
  ('Keeper', 'roles', 'Guardian or caretaker'),
  ('King', 'roles', 'Male ruler'),
  ('kinderfur', 'roles', 'Young furry character'),
  ('Kinkster', 'roles', 'Person involved in kink'),
  ('kitten', 'roles', 'Young cat role'),
  ('Intellectual Masochist', 'roles', 'Person who enjoys intellectual pain'),
  ('Knight', 'roles', 'Chivalrous warrior'),
  ('Lab Rat', 'roles', 'Test subject'),
  ('Lady', 'roles', 'Noble female title'),
  ('Lady of the Manor', 'roles', 'Female estate owner'),
  ('lamb', 'roles', 'Innocent sheep role'),
  ('Latex Kitten', 'roles', 'Kitten in latex'),
  ('Latex Top', 'roles', 'Dominant in latex play'),
  ('Latex Switch', 'roles', 'Switch in latex play'),
  ('Latex Bottom', 'roles', 'Bottom in latex play'),
  ('Latex Slut', 'roles', 'Person obsessed with latex'),
  ('Latex Pony', 'roles', 'Pony in latex'),
  ('Latex Pup', 'roles', 'Puppy in latex'),
  ('Lash Bearer', 'roles', 'Person who receives whipping'),
  ('Leader', 'roles', 'Person in charge'),
  ('Leather', 'roles', 'Leather community member'),
  ('Leather bottom', 'roles', 'Bottom in leather community'),
  ('Leatherboi', 'roles', 'Young male in leather'),
  ('Leatherboy', 'roles', 'Male in leather'),
  ('Leather Cat', 'roles', 'Cat in leather community'),
  ('Leather Daddy', 'roles', 'Father figure in leather'),
  ('Leather Dog', 'roles', 'Dog in leather community'),
  ('Leather Dyke', 'roles', 'Lesbian in leather'),
  ('Leathergirl', 'roles', 'Female in leather'),
  ('Leatherman', 'roles', 'Male leather community member'),
  ('Leather Mommy', 'roles', 'Mother figure in leather'),
  ('Leather Person', 'roles', 'Gender-neutral leather member'),
  ('Leatherperson', 'roles', 'Leather community member'),
  ('Leather Pony', 'roles', 'Pony in leather community'),
  ('Leather Pup', 'roles', 'Puppy in leather community'),
  ('Leather Slut', 'roles', 'Promiscuous leather member'),
  ('Leather Top', 'roles', 'Dominant in leather'),
  ('Leatherwoman', 'roles', 'Female leather community member'),
  ('Lion', 'roles', 'King of beasts role'),
  ('Lioness', 'roles', 'Female lion role'),
  ('little', 'roles', 'Age regression role'),
  ('little bitch', 'roles', 'Diminutive submissive'),
  ('little boy', 'roles', 'Male child role'),
  ('little brother', 'roles', 'Younger brother role'),
  ('little girl', 'roles', 'Female child role'),
  ('Little Goddess', 'roles', 'Divine child role'),
  ('little lamb', 'roles', 'Innocent child role'),
  ('little monster', 'roles', 'Mischievous child'),
  ('little one', 'roles', 'Small or young role'),
  ('little princess', 'roles', 'Royal child role'),
  ('Little Sister', 'roles', 'Younger sister role'),
  ('Little Spoon', 'roles', 'Smaller cuddling partner'),
  ('Little Thing', 'roles', 'Small endearing role'),
  ('Lord', 'roles', 'Noble male title'),
  ('Ma''am', 'roles', 'Respectful address for woman'),
  ('Madame', 'roles', 'Formal address for woman'),
  ('Maestro', 'roles', 'Master of arts'),
  ('maid', 'roles', 'Domestic service role'),
  ('Maiden', 'roles', 'Young unmarried woman'),
  ('majordomo', 'roles', 'Head of household staff'),
  ('marionette', 'roles', 'String puppet role'),
  ('masochist', 'roles', 'Person who enjoys pain'),
  ('masoslut', 'roles', 'Promiscuous masochist'),
  ('Master', 'roles', 'Male dominant owner'),
  ('Meerkat', 'roles', 'Small mammal role'),
  ('Mentor', 'roles', 'Teacher or guide'),
  ('Mermaid', 'roles', 'Mythical sea creature'),
  ('Middle', 'roles', 'Between little and big'),
  ('milkmaid', 'roles', 'Dairy worker role'),
  ('minion', 'roles', 'Loyal servant'),
  ('Minotaur', 'roles', 'Bull-headed creature'),
  ('Miss', 'roles', 'Title for young woman'),
  ('Mister', 'roles', 'Title for man'),
  ('Mistress', 'roles', 'Female dominant owner'),
  ('Mistrix', 'roles', 'Alternative spelling of mistress'),
  ('Model', 'roles', 'Person who poses'),
  ('Mommy', 'roles', 'Mother figure'),
  ('Monarch', 'roles', 'Royal ruler'),
  ('Monster', 'roles', 'Frightening creature'),
  ('Mommy Domme', 'roles', 'Dominant mother figure'),
  ('mummification bottom', 'roles', 'Person being wrapped'),
  ('mummification bunny', 'roles', 'Cute mummification subject'),
  ('Mummification Switch', 'roles', 'Switch in mummification'),
  ('Mummification Top', 'roles', 'Person who wraps others'),
  ('Mummifier', 'roles', 'Person who mummifies'),
  ('Munch Organizer', 'roles', 'Person who organizes kink events'),
  ('muppet', 'roles', 'Puppet-like character'),
  ('Muse', 'roles', 'Inspiring figure'),
  ('Mutha', 'roles', 'Alternative spelling of mother'),
  ('Mx.', 'roles', 'Gender-neutral title'),
  ('Needle Bottom', 'roles', 'Receiver of needle play'),
  ('Needle Switch', 'roles', 'Switch in needle play'),
  ('Needle Top', 'roles', 'Person who performs needle play'),
  ('nephew', 'roles', 'Male relative role'),
  ('Nerd', 'roles', 'Intellectual enthusiast'),
  ('Nibling', 'roles', 'Gender-neutral niece/nephew'),
  ('Niece', 'roles', 'Female relative role'),
  ('Not Applicable', 'roles', 'No specific role'),
  ('Novice Dom', 'roles', 'Beginning dominant'),
  ('Nudist', 'roles', 'Person who prefers nudity'),
  ('Nun', 'roles', 'Religious sister'),
  ('Nymph', 'roles', 'Nature spirit'),
  ('Nymphic Domme', 'roles', 'Nymph-like dominant'),
  ('Nympho', 'roles', 'Highly sexual person'),
  ('object', 'roles', 'Thing rather than person'),
  ('offering', 'roles', 'Gift or sacrifice'),
  ('omega', 'roles', 'Lowest in hierarchy'),
  ('Organizer', 'roles', 'Event coordinator'),
  ('Otherkin', 'roles', 'Non-human identity'),
  ('Owner', 'roles', 'Person who owns another'),
  ('Padded Caregiver', 'roles', 'Diaper-wearing caregiver'),
  ('Papabear', 'roles', 'Protective father figure'),
  ('Parent', 'roles', 'Caregiver role'),
  ('painslut', 'roles', 'Person who loves pain'),
  ('panda', 'roles', 'Bear species role'),
  ('Papi', 'roles', 'Latino daddy figure'),
  ('pay pig', 'roles', 'Financial submissive'),
  ('Performance Artist', 'roles', 'Artistic performer'),
  ('Perpetrator', 'roles', 'Person who commits acts'),
  ('personal assistant', 'roles', 'Private helper'),
  ('personal secretary', 'roles', 'Private administrative assistant'),
  ('Pervert', 'roles', 'Sexually deviant person'),
  ('pet', 'roles', 'Animal companion role'),
  ('Photographer', 'roles', 'Picture taker'),
  ('Pibling', 'roles', 'Gender-neutral aunt/uncle'),
  ('pig', 'roles', 'Farm animal role'),
  ('piggy', 'roles', 'Cute pig role'),
  ('Pillow Princess', 'roles', 'Passive sexual partner'),
  ('Pillow Queen', 'roles', 'Alternative to pillow princess'),
  ('pincushion', 'roles', 'Person for needle play'),
  ('Pirate', 'roles', 'Sea-faring outlaw'),
  ('Piss Drinker', 'roles', 'Person who drinks urine'),
  ('Piss Slut', 'roles', 'Person who loves watersports'),
  ('Pixie', 'roles', 'Small fairy creature'),
  ('plaything', 'roles', 'Object for play'),
  ('Pleaser', 'roles', 'Person who aims to please'),
  ('Pleasure Dom', 'roles', 'Dominant focused on pleasure'),
  ('Pleasure Sadist', 'roles', 'Sadist who enjoys giving pleasure'),
  ('Pleasure Sub', 'roles', 'Submissive focused on pleasure'),
  ('Poet', 'roles', 'Writer of verse'),
  ('pony', 'roles', 'Horse role'),
  ('Poppet', 'roles', 'Small doll or pet'),
  ('possession', 'roles', 'Owned object'),
  ('Possum', 'roles', 'Marsupial role'),
  ('Potty Princess', 'roles', 'Royal bathroom play role'),
  ('Power Bottom', 'roles', 'Controlling bottom'),
  ('Praise Slut', 'roles', 'Person who craves praise'),
  ('prey', 'roles', 'Hunted animal role'),
  ('Priest', 'roles', 'Religious leader'),
  ('Primal', 'roles', 'Instinctual role'),
  ('primal bottom', 'roles', 'Instinctual bottom'),
  ('Primal Daddy', 'roles', 'Instinctual father figure'),
  ('Primal Hunter', 'roles', 'Instinctual predator'),
  ('Primal Huntress', 'roles', 'Female primal hunter'),
  ('Primal Masochist', 'roles', 'Instinctual pain receiver'),
  ('Primal Mommy', 'roles', 'Instinctual mother figure'),
  ('Primal Predator', 'roles', 'Instinctual hunter'),
  ('Primal Sadist', 'roles', 'Instinctual pain giver'),
  ('Primal Sadomasochist', 'roles', 'Instinctual pain exchanger'),
  ('Primal Sensualist', 'roles', 'Instinctual pleasure seeker'),
  ('Primal Switch', 'roles', 'Instinctual switcher'),
  ('Primal Top', 'roles', 'Instinctual dominant'),
  ('Prince', 'roles', 'Male royal'),
  ('Princess', 'roles', 'Female royal'),
  ('Princess by Day, Slut by Night', 'roles', 'Dual personality role'),
  ('Priestess', 'roles', 'Female religious leader'),
  ('property', 'roles', 'Owned possession'),
  ('Protector', 'roles', 'Guardian role'),
  ('Puppet', 'roles', 'Controlled figure'),
  ('puppy', 'roles', 'Young dog role'),
  ('puppyboy', 'roles', 'Male puppy role'),
  ('puppygirl', 'roles', 'Female puppy role'),
  ('Queanbull', 'roles', 'Female bull in cuckqueaning'),
  ('Queen', 'roles', 'Female ruler'),
  ('Raccoon', 'roles', 'Masked animal role'),
  ('Ragdoll', 'roles', 'Limp doll role'),
  ('Rigger', 'roles', 'Person who ties rope'),
  ('Reynard', 'roles', 'Clever fox character'),
  ('Roleplayer', 'roles', 'Person who plays characters'),
  ('Rope Bat', 'roles', 'Rope enthusiast'),
  ('Rope Brat', 'roles', 'Mischievous rope bottom'),
  ('Rope Bottom', 'roles', 'Person being tied'),
  ('Rope Bunny', 'roles', 'Rope bottom'),
  ('Rope Dummy', 'roles', 'Practice partner for rope'),
  ('Rope Gremlin', 'roles', 'Mischievous rope enthusiast'),
  ('Rope Kitten', 'roles', 'Cat-like rope bottom'),
  ('Rope Menace', 'roles', 'Troublesome rope bottom'),
  ('Rope Model', 'roles', 'Professional rope subject'),
  ('Rope Monkey', 'roles', 'Playful rope bottom'),
  ('Rope Princess', 'roles', 'Royal rope bottom'),
  ('rope pup', 'roles', 'Dog-like rope bottom'),
  ('Rope Slut', 'roles', 'Person who loves rope'),
  ('Rope Switch', 'roles', 'Both tier and bottom'),
  ('Rope Top', 'roles', 'Person who ties rope'),
  ('Rubberist', 'roles', 'Rubber fetishist'),
  ('Sacred Feminine', 'roles', 'Divine feminine energy'),
  ('Sacred Masculine', 'roles', 'Divine masculine energy'),
  ('sacrificial lamb', 'roles', 'Innocent sacrifice'),
  ('Sadist', 'roles', 'Person who enjoys inflicting pain'),
  ('Sadomasochist', 'roles', 'Person who enjoys both pain roles'),
  ('Sailor', 'roles', 'Sea-faring person'),
  ('Satyress', 'roles', 'Female satyr'),
  ('Satyric Dominant', 'roles', 'Lustful dominant'),
  ('Savage', 'roles', 'Wild or brutal role'),
  ('Scratching Post', 'roles', 'Object for scratching'),
  ('Secondhand Sadist', 'roles', 'Sadist who enjoys others'' sadism'),
  ('Selective slut', 'roles', 'Choosy promiscuous person'),
  ('Self-Suspender', 'roles', 'Person who suspends themselves'),
  ('Self-Tyer', 'roles', 'Person who ties themselves'),
  ('Sensation Bottom', 'roles', 'Receiver of sensation play'),
  ('Sensation Switch', 'roles', 'Switch in sensation play'),
  ('Sensation Top', 'roles', 'Giver of sensation play'),
  ('Sensualist', 'roles', 'Pleasure-focused person'),
  ('Sensual Hedonist', 'roles', 'Pleasure-seeking person'),
  ('sensual prey', 'roles', 'Hunted for pleasure'),
  ('Seraphim', 'roles', 'Highest angel'),
  ('servant', 'roles', 'Service provider'),
  ('Service Bottom', 'roles', 'Bottom who serves'),
  ('Service Brat', 'roles', 'Brat who serves'),
  ('service cat', 'roles', 'Cat who serves'),
  ('Service Masochist', 'roles', 'Masochist who serves'),
  ('Service Pet', 'roles', 'Pet who serves'),
  ('service pup', 'roles', 'Puppy who serves'),
  ('service sadist', 'roles', 'Sadist who serves'),
  ('Service Sadomasochist', 'roles', 'Sadomasochist who serves'),
  ('service slave', 'roles', 'Slave who serves'),
  ('service submissive', 'roles', 'Submissive who serves'),
  ('Service Switch', 'roles', 'Switch who serves'),
  ('Service Top', 'roles', 'Top who serves'),
  ('Sex Kitten', 'roles', 'Sexually playful person'),
  ('Sex Slave', 'roles', 'Sexual servant'),
  ('Sexual Masochist', 'roles', 'Person who enjoys sexual pain'),
  ('Sexual Sadist', 'roles', 'Person who inflicts sexual pain'),
  ('Shackler', 'roles', 'Person who restrains others'),
  ('Shadow Daddy', 'roles', 'Dark father figure'),
  ('Shapeshifter', 'roles', 'Form-changing being'),
  ('Shared Wife', 'roles', 'Wife shared with others'),
  ('Sharps Bottom', 'roles', 'Receiver of sharp objects'),
  ('Sharps Switch', 'roles', 'Switch in sharps play'),
  ('Sharps Top', 'roles', 'User of sharp objects'),
  ('Sibling', 'roles', 'Brother or sister'),
  ('Sigma', 'roles', 'Independent role'),
  ('Sir', 'roles', 'Title of respect'),
  ('Siren', 'roles', 'Seductive sea creature'),
  ('Sissy', 'roles', 'Feminized male'),
  ('Sister', 'roles', 'Female sibling'),
  ('Sitter', 'roles', 'Caregiver role'),
  ('Size Queen', 'roles', 'Person who prefers large partners'),
  ('Skunkseeker', 'roles', 'Person attracted to skunks'),
  ('Slasher', 'roles', 'Horror villain role'),
  ('slave', 'roles', 'Owned person'),
  ('Slut', 'roles', 'Promiscuous person'),
  ('Soft Dom/Soft Domme', 'roles', 'Gentle dominant'),
  ('Smart Ass Masochist', 'roles', 'Clever pain receiver'),
  ('Smart Ass Sadist', 'roles', 'Clever pain giver'),
  ('Smart Ass Sadomasochist', 'roles', 'Clever pain exchanger'),
  ('Snow Bunny', 'roles', 'Winter animal role'),
  ('Solo Player', 'roles', 'Person who plays alone'),
  ('Spankee', 'roles', 'Person being spanked'),
  ('Spanker', 'roles', 'Person who spanks'),
  ('Spanko', 'roles', 'Spanking enthusiast'),
  ('Spider', 'roles', 'Web-spinning creature'),
  ('Squire', 'roles', 'Knight''s assistant'),
  ('Squirrel', 'roles', 'Nut-gathering animal'),
  ('Squishy toy', 'roles', 'Soft plaything'),
  ('Staff', 'roles', 'Support personnel'),
  ('Stag', 'roles', 'Male deer'),
  ('Stay-at-Home Dominant', 'roles', 'Domestic dominant'),
  ('Stay-at-Home Sub', 'roles', 'Domestic submissive'),
  ('steer', 'roles', 'Castrated bull'),
  ('Step- Brother', 'roles', 'Non-biological brother'),
  ('Step-Daddy', 'roles', 'Non-biological father'),
  ('stone bottom', 'roles', 'Bottom who doesn''t reciprocate'),
  ('Stone Top', 'roles', 'Top who doesn''t receive'),
  ('Strawberry', 'roles', 'Sweet fruit role'),
  ('Stud', 'roles', 'Virile male'),
  ('student', 'roles', 'Learner'),
  ('submissive', 'roles', 'Person who submits'),
  ('Submissive Daddy', 'roles', 'Submissive father figure'),
  ('submissive masochist', 'roles', 'Submissive pain receiver'),
  ('Submissive Sister', 'roles', 'Submissive sibling'),
  ('Sub-Leaning Switch', 'roles', 'Switch who prefers submitting'),
  ('Succubus', 'roles', 'Female sexual demon'),
  ('Sufferer', 'roles', 'Person who endures'),
  ('Swinger', 'roles', 'Partner swapper'),
  ('Swiss Army Slut', 'roles', 'Versatile sexual person'),
  ('Switch', 'roles', 'Person who both dominates and submits'),
  ('Tamer', 'roles', 'Person who controls others'),
  ('Teacher', 'roles', 'Educator'),
  ('Tease', 'roles', 'Person who teases'),
  ('TeddyBear', 'roles', 'Cuddly toy role'),
  ('Tempter/Temptress', 'roles', 'Person who tempts'),
  ('Test Subject', 'roles', 'Experimental participant'),
  ('Thembo', 'roles', 'Gender-neutral himbo/bimbo'),
  ('Therian', 'roles', 'Person who identifies as animal'),
  ('thing', 'roles', 'Object rather than person'),
  ('thrall', 'roles', 'Bound servant'),
  ('Ticklee', 'roles', 'Person being tickled'),
  ('Tickler', 'roles', 'Person who tickles'),
  ('Tiger', 'roles', 'Striped cat role'),
  ('toilet', 'roles', 'Bathroom fixture role'),
  ('Toilet Slave', 'roles', 'Bathroom service role'),
  ('Tomcat', 'roles', 'Male cat'),
  ('Top', 'roles', 'Giving partner in activities'),
  ('Top-Leaning Switch', 'roles', 'Switch who prefers topping'),
  ('Torturer', 'roles', 'Person who inflicts suffering'),
  ('toy', 'roles', 'Plaything'),
  ('Toymaker', 'roles', 'Creator of toys'),
  ('Tradhusband', 'roles', 'Traditional husband'),
  ('Tradwife', 'roles', 'Traditional wife'),
  ('Trainer', 'roles', 'Person who teaches skills'),
  ('trash', 'roles', 'Worthless object'),
  ('Tyrant', 'roles', 'Cruel ruler'),
  ('Ukete', 'roles', 'Japanese rope bottom'),
  ('Uncle', 'roles', 'Male relative'),
  ('Undecided', 'roles', 'Person exploring roles'),
  ('Unicorn', 'roles', 'Mythical creature or third person'),
  ('urinal', 'roles', 'Bathroom fixture for watersports'),
  ('Vamp', 'roles', 'Seductive person'),
  ('Vampire', 'roles', 'Blood-drinking creature'),
  ('Vampire Bait', 'roles', 'Attractive to vampires'),
  ('vampire concubine', 'roles', 'Vampire''s companion'),
  ('Vampiress', 'roles', 'Female vampire'),
  ('Vanilla', 'roles', 'Non-kinky person'),
  ('Vers', 'roles', 'Versatile person'),
  ('Videographer', 'roles', 'Video creator'),
  ('victim', 'roles', 'Person who suffers'),
  ('Villain', 'roles', 'Evil character'),
  ('Vixen', 'roles', 'Cunning female'),
  ('Voyeur', 'roles', 'Person who watches'),
  ('waif', 'roles', 'Homeless or abandoned person'),
  ('Warlord', 'roles', 'Military leader'),
  ('Wax Bottom', 'roles', 'Receiver of wax play'),
  ('Wax Slut', 'roles', 'Person who loves wax play'),
  ('Wax Switch', 'roles', 'Switch in wax play'),
  ('Wax Top', 'roles', 'Person who performs wax play'),
  ('wench', 'roles', 'Serving woman'),
  ('Werewolf', 'roles', 'Wolf shapeshifter'),
  ('Whip Wielder', 'roles', 'Person who uses whips'),
  ('Whipmaster', 'roles', 'Master of whips'),
  ('Whipper', 'roles', 'Person who whips'),
  ('whipping post', 'roles', 'Object for whipping'),
  ('Whore', 'roles', 'Promiscuous person'),
  ('Witch', 'roles', 'Magical practitioner'),
  ('Wizard', 'roles', 'Male magical practitioner'),
  ('Fairy', 'roles', 'Magical creature'),
  ('Wolf', 'roles', 'Pack animal'),
  ('worshipper', 'roles', 'Person who worships'),
  ('Wrathsponge', 'roles', 'Person who absorbs anger'),
  ('Writer', 'roles', 'Author or scribe'),
  ('Zombie', 'roles', 'Undead creature'),
  ('footgirl', 'roles', 'Female foot enthusiast'),
  ('footboy', 'roles', 'Male foot enthusiast'),
  ('simp', 'roles', 'Person who shows excessive sympathy'),
  ('Ethical slut', 'roles', 'Ethically non-monogamous person')
) AS new_tags(name, category, description)
WHERE NOT EXISTS (
  SELECT 1 FROM public.tags WHERE tags.name = new_tags.name
);