-- Insert relationship style tags
INSERT INTO public.tags (name, category, description) VALUES
('Adult Nursing Relationship', 'relationship-style', 'Intimate relationship involving adult nursing'),
('Ambiamorous', 'relationship-style', 'Comfortable with both monogamous and non-monogamous relationships'),
('Anal-Only D/s', 'relationship-style', 'Dominance/submission dynamic focused on anal play'),
('Anchor Partner', 'relationship-style', 'Primary stable partner in polyamorous relationship'),
('Boyfriend', 'relationship-style', 'Male romantic partner'),
('Bromance', 'relationship-style', 'Close non-sexual relationship between men'),
('Bonded', 'relationship-style', 'Deep emotional or spiritual connection'),
('Collared', 'relationship-style', 'BDSM relationship with formal collar commitment'),
('Comet Partner', 'relationship-style', 'Partner who appears periodically like a comet'),
('Companion', 'relationship-style', 'Close supportive relationship'),
('Constellation', 'relationship-style', 'Network of interconnected relationships'),
('Coven', 'relationship-style', 'Group of people in spiritual/intimate bonds'),
('Crew', 'relationship-style', 'Close-knit group of friends or partners'),
('Crushing On', 'relationship-style', 'Having romantic feelings for someone'),
('Cuddle Buddy', 'relationship-style', 'Friend for physical affection without romance'),
('Dating', 'relationship-style', 'Exploring romantic connection'),
('Distance Control', 'relationship-style', 'BDSM dynamic maintained over distance'),
('Divorced', 'relationship-style', 'Legally ended marriage'),
('Don''t Ask Don''t Tell', 'relationship-style', 'Non-monogamy without discussing other partners'),
('Dynamic', 'relationship-style', 'Structured relationship pattern or power exchange'),
('Engaged', 'relationship-style', 'Committed to marriage'),
('Ethical Non-Monogamy', 'relationship-style', 'Consensual non-monogamous relationships'),
('Exclusive', 'relationship-style', 'Committed to one person only'),
('Female-Led Relationship', 'relationship-style', 'Relationship where woman takes leadership role'),
('Flock', 'relationship-style', 'Group of connected individuals'),
('Food Buddy', 'relationship-style', 'Friend to share meals and food experiences'),
('Friends With Benefits', 'relationship-style', 'Friendship with sexual component'),
('Friends With Mutual Feelings', 'relationship-style', 'Friendship with romantic feelings'),
('Girlfriend', 'relationship-style', 'Female romantic partner'),
('Handfasted', 'relationship-style', 'Pagan/spiritual marriage ceremony'),
('Harem Holder', 'relationship-style', 'Person with multiple submissive partners'),
('House', 'relationship-style', 'BDSM household or family structure'),
('Intimate', 'relationship-style', 'Close personal relationship'),
('It''s Complicated', 'relationship-style', 'Undefined or complex relationship status'),
('Joyfriend', 'relationship-style', 'Gender-neutral term for romantic partner'),
('Kindred Spirit', 'relationship-style', 'Person with deep spiritual connection'),
('Leather Family', 'relationship-style', 'BDSM/leather community family structure'),
('Life Partner', 'relationship-style', 'Long-term committed partner'),
('Long-Distance Dynamic', 'relationship-style', 'BDSM relationship maintained over distance'),
('Long-Distance Relationship', 'relationship-style', 'Romantic relationship over distance'),
('Lover', 'relationship-style', 'Romantic and sexual partner'),
('Married', 'relationship-style', 'Legally or spiritually wed'),
('Member of a House', 'relationship-style', 'Part of BDSM household structure'),
('Metamour', 'relationship-style', 'Partner''s other partner'),
('Monogamish', 'relationship-style', 'Mostly monogamous with some flexibility'),
('Monogamous', 'relationship-style', 'Exclusive to one partner'),
('Nesting Partner', 'relationship-style', 'Partner who shares living space'),
('Non-Monogamous', 'relationship-style', 'Having multiple partners'),
('Open Marriage', 'relationship-style', 'Married couple allowing other relationships'),
('Open Relationship', 'relationship-style', 'Committed relationship allowing other partners'),
('Pack', 'relationship-style', 'Close group with pack dynamics'),
('Partner', 'relationship-style', 'General term for romantic companion'),
('Partners in Mischief', 'relationship-style', 'Playful partnership in adventures'),
('Platonic Partner', 'relationship-style', 'Non-romantic life partner'),
('Play Partner', 'relationship-style', 'Partner for BDSM or sexual activities'),
('Plecostomus', 'relationship-style', 'Partner who provides support and maintenance'),
('Polyamory', 'relationship-style', 'Multiple loving relationships'),
('Poly Family', 'relationship-style', 'Family structure with multiple partners'),
('Poly Group', 'relationship-style', 'Group of polyamorous individuals'),
('Primal Partner', 'relationship-style', 'Partner in primal/animalistic dynamics'),
('Primary Partner', 'relationship-style', 'Main partner in hierarchy'),
('Protecting', 'relationship-style', 'Protective relationship dynamic'),
('Polyandrous', 'relationship-style', 'Woman with multiple male partners'),
('Polycurious', 'relationship-style', 'Curious about polyamory'),
('Polyfidelity', 'relationship-style', 'Closed group polyamory'),
('Polygyny', 'relationship-style', 'Man with multiple female partners'),
('Queer Platonic Partner', 'relationship-style', 'Non-romantic but committed partnership'),
('Relationship', 'relationship-style', 'General romantic connection'),
('Relationship Anarchist', 'relationship-style', 'Rejecting traditional relationship structures'),
('Romantic', 'relationship-style', 'Focused on romantic connection'),
('Rope Family', 'relationship-style', 'Bondage community family structure'),
('Rope Partner', 'relationship-style', 'Partner for rope bondage'),
('Satellite Partner', 'relationship-style', 'Secondary partner who orbits primary relationship'),
('Scene Partner', 'relationship-style', 'Partner for BDSM scenes'),
('Self Collared', 'relationship-style', 'BDSM submissive without current owner'),
('Separated', 'relationship-style', 'Living apart but still legally married'),
('Shade of My Heart', 'relationship-style', 'Deep spiritual romantic connection'),
('Single', 'relationship-style', 'Not in a romantic relationship'),
('Situationship', 'relationship-style', 'Undefined romantic situation'),
('Solo Poly', 'relationship-style', 'Polyamorous while maintaining independence'),
('Soulmate', 'relationship-style', 'Deeply connected spiritual partner'),
('Surviving Partner', 'relationship-style', 'Partner who has lost their significant other'),
('Spare-Tire Partner', 'relationship-style', 'Backup or secondary relationship'),
('Taken in Hand', 'relationship-style', 'Traditional male-led relationship dynamic'),
('Throuple', 'relationship-style', 'Three-person relationship'),
('Triad', 'relationship-style', 'Three-way relationship'),
('Tribe', 'relationship-style', 'Close community or family group'),
('Twin', 'relationship-style', 'Deep mirrored connection'),
('Twin Flame', 'relationship-style', 'Spiritual concept of soul''s other half'),
('T4T', 'relationship-style', 'Trans for trans relationships'),
('Uncollared', 'relationship-style', 'BDSM submissive without collar'),
('Under Protection', 'relationship-style', 'Being protected by dominant partner'),
('Widow(er)', 'relationship-style', 'Person whose spouse has died'),
('puddle', 'relationship-style', 'Emotional state after intense scene or experience')
ON CONFLICT (name) DO NOTHING;