-- Update major cities with their airport codes
UPDATE public.cities 
SET major_airport_code = CASE 
  WHEN name = 'New York' THEN 'JFK'
  WHEN name = 'Los Angeles' THEN 'LAX'
  WHEN name = 'Chicago' THEN 'ORD'
  WHEN name = 'Atlanta' THEN 'ATL'
  WHEN name = 'Dallas' THEN 'DFW'
  WHEN name = 'Denver' THEN 'DEN'
  WHEN name = 'San Francisco' THEN 'SFO'
  WHEN name = 'Seattle' THEN 'SEA'
  WHEN name = 'Las Vegas' THEN 'LAS'
  WHEN name = 'Orlando' THEN 'MCO'
  WHEN name = 'Miami' THEN 'MIA'
  WHEN name = 'Boston' THEN 'BOS'
  WHEN name = 'Washington' THEN 'DCA'
  WHEN name = 'Phoenix' THEN 'PHX'
  WHEN name = 'Philadelphia' THEN 'PHL'
  WHEN name = 'Houston' THEN 'IAH'
  WHEN name = 'London' THEN 'LHR'
  WHEN name = 'Paris' THEN 'CDG'
  WHEN name = 'Berlin' THEN 'TXL'
  WHEN name = 'Rome' THEN 'FCO'
  WHEN name = 'Madrid' THEN 'MAD'
  WHEN name = 'Barcelona' THEN 'BCN'
  WHEN name = 'Amsterdam' THEN 'AMS'
  WHEN name = 'Frankfurt' THEN 'FRA'
  WHEN name = 'Munich' THEN 'MUC'
  WHEN name = 'Vienna' THEN 'VIE'
  WHEN name = 'Zurich' THEN 'ZUR'
  WHEN name = 'Geneva' THEN 'GVA'
  WHEN name = 'Brussels' THEN 'BRU'
  WHEN name = 'Copenhagen' THEN 'CPH'
  WHEN name = 'Stockholm' THEN 'ARN'
  WHEN name = 'Oslo' THEN 'OSL'
  WHEN name = 'Helsinki' THEN 'HEL'
  WHEN name = 'Warsaw' THEN 'WAW'
  WHEN name = 'Prague' THEN 'PRG'
  WHEN name = 'Budapest' THEN 'BUD'
  WHEN name = 'Athens' THEN 'ATH'
  WHEN name = 'Istanbul' THEN 'IST'
  WHEN name = 'Moscow' THEN 'SVO'
  WHEN name = 'Tokyo' THEN 'NRT'
  WHEN name = 'Osaka' THEN 'KIX'
  WHEN name = 'Seoul' THEN 'ICN'
  WHEN name = 'Beijing' THEN 'PEK'
  WHEN name = 'Shanghai' THEN 'PVG'
  WHEN name = 'Hong Kong' THEN 'HKG'
  WHEN name = 'Singapore' THEN 'SIN'
  WHEN name = 'Bangkok' THEN 'BKK'
  WHEN name = 'Kuala Lumpur' THEN 'KUL'
  WHEN name = 'Jakarta' THEN 'CGK'
  WHEN name = 'Manila' THEN 'MNL'
  WHEN name = 'Ho Chi Minh City' THEN 'SGN'
  WHEN name = 'Hanoi' THEN 'HAN'
  WHEN name = 'Mumbai' THEN 'BOM'
  WHEN name = 'Delhi' THEN 'DEL'
  WHEN name = 'Bangalore' THEN 'BLR'
  WHEN name = 'Chennai' THEN 'MAA'
  WHEN name = 'Kolkata' THEN 'CCU'
  WHEN name = 'Hyderabad' THEN 'HYD'
  WHEN name = 'Dubai' THEN 'DXB'
  WHEN name = 'Abu Dhabi' THEN 'AUH'
  WHEN name = 'Doha' THEN 'DOH'
  WHEN name = 'Kuwait City' THEN 'KWI'
  WHEN name = 'Riyadh' THEN 'RUH'
  WHEN name = 'Jeddah' THEN 'JED'
  WHEN name = 'Cairo' THEN 'CAI'
  WHEN name = 'Casablanca' THEN 'CMN'
  WHEN name = 'Cape Town' THEN 'CPT'
  WHEN name = 'Johannesburg' THEN 'JNB'
  WHEN name = 'Nairobi' THEN 'NBO'
  WHEN name = 'Lagos' THEN 'LOS'
  WHEN name = 'Addis Ababa' THEN 'ADD'
  WHEN name = 'Sydney' THEN 'SYD'
  WHEN name = 'Melbourne' THEN 'MEL'
  WHEN name = 'Brisbane' THEN 'BNE'
  WHEN name = 'Perth' THEN 'PER'
  WHEN name = 'Auckland' THEN 'AKL'
  WHEN name = 'Wellington' THEN 'WLG'
  WHEN name = 'Christchurch' THEN 'CHC'
  WHEN name = 'Toronto' THEN 'YYZ'
  WHEN name = 'Vancouver' THEN 'YVR'
  WHEN name = 'Montreal' THEN 'YUL'
  WHEN name = 'Calgary' THEN 'YYC'
  WHEN name = 'São Paulo' THEN 'GRU'
  WHEN name = 'Rio de Janeiro' THEN 'GIG'
  WHEN name = 'Brasília' THEN 'BSB'
  WHEN name = 'Buenos Aires' THEN 'EZE'
  WHEN name = 'Santiago' THEN 'SCL'
  WHEN name = 'Lima' THEN 'LIM'
  WHEN name = 'Bogotá' THEN 'BOG'
  WHEN name = 'Quito' THEN 'UIO'
  WHEN name = 'Caracas' THEN 'CCS'
  WHEN name = 'Mexico City' THEN 'MEX'
  WHEN name = 'Cancún' THEN 'CUN'
  WHEN name = 'Guadalajara' THEN 'GDL'
  WHEN name = 'Monterrey' THEN 'MTY'
  WHEN name = 'Havana' THEN 'HAV'
  WHEN name = 'Nassau' THEN 'NAS'
  WHEN name = 'Kingston' THEN 'KIN'
  WHEN name = 'Port of Spain' THEN 'POS'
  WHEN name = 'Bridgetown' THEN 'BGI'
  WHEN name = 'Reykjavik' THEN 'KEF'
  WHEN name = 'Dublin' THEN 'DUB'
  WHEN name = 'Edinburgh' THEN 'EDI'
  WHEN name = 'Manchester' THEN 'MAN'
  WHEN name = 'Glasgow' THEN 'GLA'
  WHEN name = 'Birmingham' THEN 'BHX'
  WHEN name = 'Milan' THEN 'MXP'
  WHEN name = 'Naples' THEN 'NAP'
  WHEN name = 'Venice' THEN 'VCE'
  WHEN name = 'Florence' THEN 'FLR'
  WHEN name = 'Nice' THEN 'NCE'
  WHEN name = 'Lyon' THEN 'LYS'
  WHEN name = 'Marseille' THEN 'MRS'
  WHEN name = 'Toulouse' THEN 'TLS'
  WHEN name = 'Bordeaux' THEN 'BOD'
  WHEN name = 'Lisbon' THEN 'LIS'
  WHEN name = 'Porto' THEN 'OPO'
  WHEN name = 'Seville' THEN 'SVQ'
  WHEN name = 'Valencia' THEN 'VLC'
  WHEN name = 'Bilbao' THEN 'BIO'
  WHEN name = 'Málaga' THEN 'AGP'
  WHEN name = 'Palma' THEN 'PMI'
  WHEN name = 'Las Palmas' THEN 'LPA'
  WHEN name = 'Tel Aviv' THEN 'TLV'
  WHEN name = 'Jerusalem' THEN 'JRS'
  WHEN name = 'Haifa' THEN 'HFA'
  WHEN name = 'Thessaloniki' THEN 'SKG'
  WHEN name = 'Heraklion' THEN 'HER'
  WHEN name = 'Rhodes' THEN 'RHO'
  WHEN name = 'Corfu' THEN 'CFU'
  WHEN name = 'Mykonos' THEN 'JMK'
  WHEN name = 'Santorini' THEN 'JTR'
  WHEN name = 'Valletta' THEN 'MLA'
  WHEN name = 'Nicosia' THEN 'LCA'
  WHEN name = 'Paphos' THEN 'PFO'
  WHEN name = 'Larnaca' THEN 'LCA'
  WHEN name = 'Luxembourg' THEN 'LUX'
  WHEN name = 'Monaco' THEN 'MCM'
  WHEN name = 'Andorra la Vella' THEN 'ALV'
  WHEN name = 'San Marino' THEN 'RMI'
  WHEN name = 'Vatican City' THEN 'CIA'
  WHEN name = 'Vaduz' THEN 'ACH'
  ELSE major_airport_code
END,
airport_codes = CASE
  WHEN name = 'New York' THEN ARRAY['JFK', 'LGA', 'EWR']
  WHEN name = 'Los Angeles' THEN ARRAY['LAX', 'BUR', 'LGB']
  WHEN name = 'Chicago' THEN ARRAY['ORD', 'MDW']
  WHEN name = 'London' THEN ARRAY['LHR', 'LGW', 'STN', 'LTN']
  WHEN name = 'Paris' THEN ARRAY['CDG', 'ORY', 'BVA']
  WHEN name = 'Tokyo' THEN ARRAY['NRT', 'HND']
  WHEN name = 'Berlin' THEN ARRAY['TXL', 'SXF', 'BER']
  WHEN name = 'Rome' THEN ARRAY['FCO', 'CIA']
  WHEN name = 'Madrid' THEN ARRAY['MAD', 'TOJ']
  WHEN name = 'Barcelona' THEN ARRAY['BCN', 'GRO']
  WHEN name = 'Milan' THEN ARRAY['MXP', 'LIN', 'BGY']
  WHEN name = 'Bangkok' THEN ARRAY['BKK', 'DMK']
  WHEN name = 'Seoul' THEN ARRAY['ICN', 'GMP']
  WHEN name = 'Moscow' THEN ARRAY['SVO', 'DME', 'VKO']
  WHEN name = 'Istanbul' THEN ARRAY['IST', 'SAW']
  WHEN name = 'Dubai' THEN ARRAY['DXB', 'DWC']
  WHEN name = 'São Paulo' THEN ARRAY['GRU', 'VCP', 'CGH']
  WHEN name = 'Rio de Janeiro' THEN ARRAY['GIG', 'SDU']
  WHEN name = 'Buenos Aires' THEN ARRAY['EZE', 'AEP']
  WHEN name = 'Mumbai' THEN ARRAY['BOM']
  WHEN name = 'Delhi' THEN ARRAY['DEL']
  WHEN name = 'Shanghai' THEN ARRAY['PVG', 'SHA']
  WHEN name = 'Beijing' THEN ARRAY['PEK', 'PKX']
  WHEN name = 'Toronto' THEN ARRAY['YYZ', 'YTZ']
  WHEN name = 'Vancouver' THEN ARRAY['YVR', 'YKA']
  WHEN name = 'Sydney' THEN ARRAY['SYD', 'RSE']
  WHEN name = 'Melbourne' THEN ARRAY['MEL', 'AVV']
  WHEN name = 'Cairo' THEN ARRAY['CAI']
  WHEN name = 'Johannesburg' THEN ARRAY['JNB', 'HLA']
  WHEN name = 'Lagos' THEN ARRAY['LOS']
  WHEN name = 'Nairobi' THEN ARRAY['NBO']
  WHEN name = 'Casablanca' THEN ARRAY['CMN']
  WHEN name = 'Cape Town' THEN ARRAY['CPT']
  WHEN name = 'Nassau' THEN ARRAY['NAS']
  WHEN name = 'Kingston' THEN ARRAY['KIN']
  WHEN name = 'Port of Spain' THEN ARRAY['POS']
  WHEN name = 'Bridgetown' THEN ARRAY['BGI']
  ELSE airport_codes
END
WHERE major_airport_code IS NULL OR airport_codes IS NULL;