-- Update major cities with their airport codes
UPDATE public.cities 
SET major_airport_code = CASE 
  WHEN name = 'New York' THEN 'JFK'
  WHEN name = 'Los Angeles' THEN 'LAX'
  WHEN name = 'Chicago' THEN 'ORD'
  WHEN name = 'Atlanta' THEN 'ATL'
  WHEN name = 'Dallas' THEN 'DFW'
  WHEN name = 'Denver' THEN 'DEN'
  WHEN name = 'San Francisco' THEN 'SFO'
  WHEN name = 'Seattle' THEN 'SEA'
  WHEN name = 'Las Vegas' THEN 'LAS'
  WHEN name = 'Orlando' THEN 'MCO'
  WHEN name = 'Miami' THEN 'MIA'
  WHEN name = 'Boston' THEN 'BOS'
  WHEN name = 'Philadelphia' THEN 'PHL'
  WHEN name = 'Phoenix' THEN 'PHX'
  WHEN name = 'Houston' THEN 'IAH'
  WHEN name = 'Washington' THEN 'DCA'
  WHEN name = 'Detroit' THEN 'DTW'
  WHEN name = 'Minneapolis' THEN 'MSP'
  WHEN name = 'London' THEN 'LHR'
  WHEN name = 'Manchester' THEN 'MAN'
  WHEN name = 'Edinburgh' THEN 'EDI'
  WHEN name = 'Glasgow' THEN 'GLA'
  WHEN name = 'Birmingham' THEN 'BHX'
  WHEN name = 'Paris' THEN 'CDG'
  WHEN name = 'Lyon' THEN 'LYS'
  WHEN name = 'Nice' THEN 'NCE'
  WHEN name = 'Marseille' THEN 'MRS'
  WHEN name = 'Toulouse' THEN 'TLS'
  WHEN name = 'Bordeaux' THEN 'BOD'
  WHEN name = 'Frankfurt' THEN 'FRA'
  WHEN name = 'Munich' THEN 'MUC'
  WHEN name = 'Berlin' THEN 'BER'
  WHEN name = 'Hamburg' THEN 'HAM'
  WHEN name = 'Düsseldorf' THEN 'DUS'
  WHEN name = 'Stuttgart' THEN 'STR'
  WHEN name = 'Cologne' THEN 'CGN'
  WHEN name = 'Madrid' THEN 'MAD'
  WHEN name = 'Barcelona' THEN 'BCN'
  WHEN name = 'Palma' THEN 'PMI'
  WHEN name = 'Las Palmas' THEN 'LPA'
  WHEN name = 'Málaga' THEN 'AGP'
  WHEN name = 'Seville' THEN 'SVQ'
  WHEN name = 'Valencia' THEN 'VLC'
  WHEN name = 'Rome' THEN 'FCO'
  WHEN name = 'Milan' THEN 'MXP'
  WHEN name = 'Naples' THEN 'NAP'
  WHEN name = 'Venice' THEN 'VCE'
  WHEN name = 'Bologna' THEN 'BLQ'
  WHEN name = 'Florence' THEN 'FLR'
  WHEN name = 'Tokyo' THEN 'NRT'
  WHEN name = 'Osaka' THEN 'KIX'
  WHEN name = 'Nagoya' THEN 'NGO'
  WHEN name = 'Fukuoka' THEN 'FUK'
  WHEN name = 'Sapporo' THEN 'CTS'
  WHEN name = 'Beijing' THEN 'PEK'
  WHEN name = 'Shanghai' THEN 'PVG'
  WHEN name = 'Guangzhou' THEN 'CAN'
  WHEN name = 'Shenzhen' THEN 'SZX'
  WHEN name = 'Chengdu' THEN 'CTU'
  WHEN name = 'Kunming' THEN 'KMG'
  WHEN name = 'Xiamen' THEN 'XMN'
  WHEN name = 'Sydney' THEN 'SYD'
  WHEN name = 'Melbourne' THEN 'MEL'
  WHEN name = 'Brisbane' THEN 'BNE'
  WHEN name = 'Perth' THEN 'PER'
  WHEN name = 'Adelaide' THEN 'ADL'
  WHEN name = 'Darwin' THEN 'DRW'
  WHEN name = 'Hobart' THEN 'HBA'
  WHEN name = 'Toronto' THEN 'YYZ'
  WHEN name = 'Vancouver' THEN 'YVR'
  WHEN name = 'Montreal' THEN 'YUL'
  WHEN name = 'Calgary' THEN 'YYC'
  WHEN name = 'Edmonton' THEN 'YEG'
  WHEN name = 'Halifax' THEN 'YHZ'
  WHEN name = 'Ottawa' THEN 'YOW'
  WHEN name = 'São Paulo' THEN 'GRU'
  WHEN name = 'Rio de Janeiro' THEN 'GIG'
  WHEN name = 'Brasília' THEN 'BSB'
  WHEN name = 'Salvador' THEN 'SSA'
  WHEN name = 'Fortaleza' THEN 'FOR'
  WHEN name = 'Recife' THEN 'REC'
  WHEN name = 'Mexico City' THEN 'MEX'
  WHEN name = 'Cancún' THEN 'CUN'
  WHEN name = 'Guadalajara' THEN 'GDL'
  WHEN name = 'Monterrey' THEN 'MTY'
  WHEN name = 'Tijuana' THEN 'TIJ'
  WHEN name = 'Puerto Vallarta' THEN 'PVR'
  WHEN name = 'Los Cabos' THEN 'SJD'
  WHEN name = 'Delhi' THEN 'DEL'
  WHEN name = 'Mumbai' THEN 'BOM'
  WHEN name = 'Chennai' THEN 'MAA'
  WHEN name = 'Kolkata' THEN 'CCU'
  WHEN name = 'Bangalore' THEN 'BLR'
  WHEN name = 'Hyderabad' THEN 'HYD'
  WHEN name = 'Ahmedabad' THEN 'AMD'
  WHEN name = 'Moscow' THEN 'SVO'
  WHEN name = 'St. Petersburg' THEN 'LED'
  WHEN name = 'Yekaterinburg' THEN 'SVX'
  WHEN name = 'Kazan' THEN 'KZN'
  WHEN name = 'Rostov-on-Don' THEN 'ROV'
  WHEN name = 'Johannesburg' THEN 'JNB'
  WHEN name = 'Cape Town' THEN 'CPT'
  WHEN name = 'Durban' THEN 'DUR'
  WHEN name = 'Port Elizabeth' THEN 'PLZ'
  WHEN name = 'Bloemfontein' THEN 'BFN'
  WHEN name = 'East London' THEN 'ELS'
  WHEN name = 'Buenos Aires' THEN 'EZE'
  WHEN name = 'Córdoba' THEN 'COR'
  WHEN name = 'Mendoza' THEN 'MDZ'
  WHEN name = 'Iguazú' THEN 'IGR'
  WHEN name = 'Bariloche' THEN 'BRC'
  WHEN name = 'Istanbul' THEN 'IST'
  WHEN name = 'Ankara' THEN 'ESB'
  WHEN name = 'Antalya' THEN 'AYT'
  WHEN name = 'Izmir' THEN 'ADB'
  WHEN name = 'Trabzon' THEN 'TZX'
  WHEN name = 'Bangkok' THEN 'BKK'
  WHEN name = 'Phuket' THEN 'HKT'
  WHEN name = 'Chiang Mai' THEN 'CNX'
  WHEN name = 'Hat Yai' THEN 'HDY'
  WHEN name = 'Koh Samui' THEN 'USM'
  WHEN name = 'Singapore' THEN 'SIN'
  WHEN name = 'Dubai' THEN 'DXB'
  WHEN name = 'Abu Dhabi' THEN 'AUH'
  WHEN name = 'Sharjah' THEN 'SHJ'
  WHEN name = 'Ras Al Khaimah' THEN 'RKT'
  WHEN name = 'Seoul' THEN 'ICN'
  WHEN name = 'Busan' THEN 'PUS'
  WHEN name = 'Jeju' THEN 'CJU'
  WHEN name = 'Daegu' THEN 'TAE'
  WHEN name = 'Gwangju' THEN 'KWJ'
  WHEN name = 'Amsterdam' THEN 'AMS'
  WHEN name = 'Rotterdam' THEN 'RTM'
  WHEN name = 'Eindhoven' THEN 'EIN'
  WHEN name = 'Groningen' THEN 'GRQ'
  WHEN name = 'Zurich' THEN 'ZUR'
  WHEN name = 'Geneva' THEN 'GVA'
  WHEN name = 'Basel' THEN 'BSL'
  WHEN name = 'Bern' THEN 'BRN'
  WHEN name = 'Vienna' THEN 'VIE'
  WHEN name = 'Salzburg' THEN 'SZG'
  WHEN name = 'Innsbruck' THEN 'INN'
  WHEN name = 'Graz' THEN 'GRZ'
  WHEN name = 'Brussels' THEN 'BRU'
  WHEN name = 'Charleroi' THEN 'CRL'
  WHEN name = 'Antwerp' THEN 'ANR'
  WHEN name = 'Liège' THEN 'LGG'
  WHEN name = 'Stockholm' THEN 'ARN'
  WHEN name = 'Gothenburg' THEN 'GOT'
  WHEN name = 'Malmö' THEN 'MMX'
  WHEN name = 'Umeå' THEN 'UME'
  WHEN name = 'Oslo' THEN 'OSL'
  WHEN name = 'Bergen' THEN 'BGO'
  WHEN name = 'Trondheim' THEN 'TRD'
  WHEN name = 'Stavanger' THEN 'SVG'
  WHEN name = 'Copenhagen' THEN 'CPH'
  WHEN name = 'Billund' THEN 'BLL'
  WHEN name = 'Aalborg' THEN 'AAL'
  WHEN name = 'Esbjerg' THEN 'EBJ'
  WHEN name = 'Helsinki' THEN 'HEL'
  WHEN name = 'Tampere' THEN 'TMP'
  WHEN name = 'Turku' THEN 'TKU'
  WHEN name = 'Oulu' THEN 'OUL'
  WHEN name = 'Warsaw' THEN 'WAW'
  WHEN name = 'Kraków' THEN 'KRK'
  WHEN name = 'Gdańsk' THEN 'GDN'
  WHEN name = 'Wrocław' THEN 'WRO'
  WHEN name = 'Poznań' THEN 'POZ'
  WHEN name = 'Prague' THEN 'PRG'
  WHEN name = 'Brno' THEN 'BRQ'
  WHEN name = 'Ostrava' THEN 'OSR'
  WHEN name = 'Budapest' THEN 'BUD'
  WHEN name = 'Debrecen' THEN 'DEB'
  WHEN name = 'Lisbon' THEN 'LIS'
  WHEN name = 'Porto' THEN 'OPO'
  WHEN name = 'Faro' THEN 'FAO'
  WHEN name = 'Funchal' THEN 'FNC'
  WHEN name = 'Athens' THEN 'ATH'
  WHEN name = 'Thessaloniki' THEN 'SKG'
  WHEN name = 'Heraklion' THEN 'HER'
  WHEN name = 'Rhodes' THEN 'RHO'
  WHEN name = 'Corfu' THEN 'CFU'
  WHEN name = 'Tel Aviv' THEN 'TLV'
  WHEN name = 'Eilat' THEN 'ETH'
  WHEN name = 'Haifa' THEN 'HFA'
  WHEN name = 'Cairo' THEN 'CAI'
  WHEN name = 'Hurghada' THEN 'HRG'
  WHEN name = 'Sharm El Sheikh' THEN 'SSH'
  WHEN name = 'Marsa Alam' THEN 'RMF'
  WHEN name = 'Casablanca' THEN 'CMN'
  WHEN name = 'Marrakech' THEN 'RAK'
  WHEN name = 'Agadir' THEN 'AGA'
  WHEN name = 'Fez' THEN 'FEZ'
  WHEN name = 'Lagos' THEN 'LOS'
  WHEN name = 'Abuja' THEN 'ABV'
  WHEN name = 'Kano' THEN 'KAN'
  WHEN name = 'Port Harcourt' THEN 'PHC'
  WHEN name = 'Nairobi' THEN 'NBO'
  WHEN name = 'Mombasa' THEN 'MBA'
  WHEN name = 'Kisumu' THEN 'KIS'
  WHEN name = 'Eldoret' THEN 'ELD'
  WHEN name = 'Jakarta' THEN 'CGK'
  WHEN name = 'Denpasar' THEN 'DPS'
  WHEN name = 'Surabaya' THEN 'SUB'
  WHEN name = 'Malang' THEN 'MLG'
  WHEN name = 'Yogyakarta' THEN 'YOG'
  WHEN name = 'Kuala Lumpur' THEN 'KUL'
  WHEN name = 'Penang' THEN 'PEN'
  WHEN name = 'Kuching' THEN 'KCH'
  WHEN name = 'Kota Kinabalu' THEN 'BKI'
  WHEN name = 'Langkawi' THEN 'LGK'
  WHEN name = 'Manila' THEN 'MNL'
  WHEN name = 'Cebu' THEN 'CEB'
  WHEN name = 'Clark' THEN 'CRK'
  WHEN name = 'Iloilo' THEN 'ILO'
  WHEN name = 'Davao' THEN 'DVO'
  WHEN name = 'Ho Chi Minh City' THEN 'SGN'
  WHEN name = 'Hanoi' THEN 'HAN'
  WHEN name = 'Da Nang' THEN 'DAD'
  WHEN name = 'Nha Trang' THEN 'CXR'
  WHEN name = 'Phu Quoc' THEN 'PQC'
  WHEN name = 'Auckland' THEN 'AKL'
  WHEN name = 'Wellington' THEN 'WLG'
  WHEN name = 'Christchurch' THEN 'CHC'
  WHEN name = 'Queenstown' THEN 'ZQN'
  WHEN name = 'Dunedin' THEN 'DUD'
  WHEN name = 'Santiago' THEN 'SCL'
  WHEN name = 'Antofagasta' THEN 'ANF'
  WHEN name = 'Concepción' THEN 'CCP'
  WHEN name = 'Iquique' THEN 'IQQ'
  WHEN name = 'La Serena' THEN 'LSC'
  WHEN name = 'Bogotá' THEN 'BOG'
  WHEN name = 'Medellín' THEN 'MDE'
  WHEN name = 'Cali' THEN 'CLO'
  WHEN name = 'Cartagena' THEN 'CTG'
  WHEN name = 'Barranquilla' THEN 'BAQ'
  WHEN name = 'Lima' THEN 'LIM'
  WHEN name = 'Cusco' THEN 'CUZ'
  WHEN name = 'Arequipa' THEN 'AQP'
  WHEN name = 'Trujillo' THEN 'TRU'
  WHEN name = 'Piura' THEN 'PIU'
  WHEN name = 'Quito' THEN 'UIO'
  WHEN name = 'Guayaquil' THEN 'GYE'
  WHEN name = 'Cuenca' THEN 'CUE'
  WHEN name = 'Caracas' THEN 'CCS'
  WHEN name = 'Maracaibo' THEN 'MAR'
  WHEN name = 'Valencia' THEN 'VLN'
  WHEN name = 'Barcelona' THEN 'BLA'
  WHEN name = 'Tehran' THEN 'IKA'
  WHEN name = 'Isfahan' THEN 'ISF'
  WHEN name = 'Shiraz' THEN 'SYZ'
  WHEN name = 'Mashhad' THEN 'MHD'
  WHEN name = 'Baghdad' THEN 'BGW'
  WHEN name = 'Basra' THEN 'BSR'
  WHEN name = 'Erbil' THEN 'EBL'
  WHEN name = 'Sulaymaniyah' THEN 'ISU'
  WHEN name = 'Riyadh' THEN 'RUH'
  WHEN name = 'Jeddah' THEN 'JED'
  WHEN name = 'Dammam' THEN 'DMM'
  WHEN name = 'Abha' THEN 'AHB'
  WHEN name = 'Tabuk' THEN 'TUU'
  WHEN name = 'Karachi' THEN 'KHI'
  WHEN name = 'Lahore' THEN 'LHE'
  WHEN name = 'Islamabad' THEN 'ISB'
  WHEN name = 'Peshawar' THEN 'PEW'
  WHEN name = 'Dhaka' THEN 'DAC'
  WHEN name = 'Chittagong' THEN 'CGP'
  WHEN name = 'Cox''s Bazar' THEN 'CXB'
  WHEN name = 'Sylhet' THEN 'ZYL'
  WHEN name = 'Colombo' THEN 'CMB'
  WHEN name = 'Hambantota' THEN 'HRI'
  WHEN name = 'Jaffna' THEN 'JAF'
  WHEN name = 'Yangon' THEN 'RGN'
  WHEN name = 'Mandalay' THEN 'MDL'
  WHEN name = 'Naypyidaw' THEN 'NYT'
  WHEN name = 'Phnom Penh' THEN 'PNH'
  WHEN name = 'Siem Reap' THEN 'REP'
  WHEN name = 'Sihanoukville' THEN 'KOS'
  WHEN name = 'Vientiane' THEN 'VTE'
  WHEN name = 'Luang Prabang' THEN 'LPQ'
  WHEN name = 'Pakse' THEN 'PKZ'
  WHEN name = 'Ulaanbaatar' THEN 'ULN'
  WHEN name = 'Almaty' THEN 'ALA'
  WHEN name = 'Nur-Sultan' THEN 'NQZ'
  WHEN name = 'Shymkent' THEN 'CIT'
  WHEN name = 'Tashkent' THEN 'TAS'
  WHEN name = 'Samarkand' THEN 'SKD'
  WHEN name = 'Bukhara' THEN 'BHK'
  WHEN name = 'Bishkek' THEN 'FRU'
  WHEN name = 'Osh' THEN 'OSS'
  WHEN name = 'Dushanbe' THEN 'DYU'
  WHEN name = 'Khujand' THEN 'LBD'
  WHEN name = 'Ashgabat' THEN 'ASB'
  WHEN name = 'Turkmenbashi' THEN 'KRW'
  WHEN name = 'Kabul' THEN 'KBL'
  WHEN name = 'Herat' THEN 'HEA'
  WHEN name = 'Kandahar' THEN 'KDH'
  WHEN name = 'Mazar-i-Sharif' THEN 'MZR'
  WHEN name = 'Kathmandu' THEN 'KTM'
  WHEN name = 'Pokhara' THEN 'PKR'
  WHEN name = 'Biratnagar' THEN 'BIR'
  WHEN name = 'Thimphu' THEN 'PBH'
  WHEN name = 'Paro' THEN 'PBH'
  WHEN name = 'Malé' THEN 'MLE'
  WHEN name = 'Gan' THEN 'GAN'
  WHEN name = 'Victoria' THEN 'SEZ'
  WHEN name = 'Praslin' THEN 'PRI'
  WHEN name = 'Port Louis' THEN 'MRU'
  WHEN name = 'Rodrigues' THEN 'RRG'
  WHEN name = 'Antananarivo' THEN 'TNR'
  WHEN name = 'Nosy Be' THEN 'NOS'
  WHEN name = 'Toamasina' THEN 'TMM'
  WHEN name = 'Nassau' THEN 'NAS'
  WHEN name = 'Freeport' THEN 'FPO'
  WHEN name = 'Eleuthera' THEN 'ELH'
  WHEN name = 'Georgetown' THEN 'GHB'
  WHEN name = 'Kingston' THEN 'KIN'
  WHEN name = 'Montego Bay' THEN 'MBJ'
  WHEN name = 'Ocho Rios' THEN 'OCJ'
  WHEN name = 'Port of Spain' THEN 'POS'
  WHEN name = 'Tobago' THEN 'TAB'
  WHEN name = 'Scarborough' THEN 'SCA'
  WHEN name = 'Bridgetown' THEN 'BGI'
  WHEN name = 'Castries' THEN 'SLU'
  WHEN name = 'Vieux Fort' THEN 'UVF'
  WHEN name = 'St. George''s' THEN 'GND'
  WHEN name = 'Kingstown' THEN 'SVD'
  WHEN name = 'Canouan' THEN 'CIW'
  WHEN name = 'St. John''s' THEN 'ANU'
  WHEN name = 'Roseau' THEN 'DOM'
  WHEN name = 'Basseterre' THEN 'SKB'
  WHEN name = 'Nevis' THEN 'NEV'
  WHEN name = 'Havana' THEN 'HAV'
  WHEN name = 'Varadero' THEN 'VRA'
  WHEN name = 'Holguín' THEN 'HOG'
  WHEN name = 'Santiago de Cuba' THEN 'SCU'
  WHEN name = 'Santo Domingo' THEN 'SDQ'
  WHEN name = 'Punta Cana' THEN 'PUJ'
  WHEN name = 'Santiago' THEN 'STI'
  WHEN name = 'Azua' THEN 'AZS'
  WHEN name = 'Port-au-Prince' THEN 'PAP'
  WHEN name = 'Cap-Haïtien' THEN 'CAP'
  WHEN name = 'San Juan' THEN 'SJU'
  WHEN name = 'Aguadilla' THEN 'BQN'
  WHEN name = 'Ponce' THEN 'PSE'
  WHEN name = 'Reykjavik' THEN 'KEF'
  WHEN name = 'Akureyri' THEN 'AEY'
  WHEN name = 'Dublin' THEN 'DUB'
  WHEN name = 'Cork' THEN 'ORK'
  WHEN name = 'Shannon' THEN 'SNN'
  WHEN name = 'Knock' THEN 'NOC'
  WHEN name = 'Valletta' THEN 'MLA'
  WHEN name = 'Larnaca' THEN 'LCA'
  WHEN name = 'Paphos' THEN 'PFO'
  WHEN name = 'Ercan' THEN 'ECN'
  WHEN name = 'Luxembourg' THEN 'LUX'
  WHEN name = 'Monaco' THEN 'MCM'
  WHEN name = 'Andorra la Vella' THEN 'ALV'
  WHEN name = 'San Marino' THEN 'RMI'
  WHEN name = 'Vatican City' THEN 'CIA'
  WHEN name = 'Vaduz' THEN 'ACH'
  ELSE major_airport_code
END,
airport_codes = CASE 
  WHEN name = 'New York' THEN ARRAY['JFK', 'LGA', 'EWR']
  WHEN name = 'Los Angeles' THEN ARRAY['LAX', 'BUR', 'LGB', 'ONT']
  WHEN name = 'Chicago' THEN ARRAY['ORD', 'MDW']
  WHEN name = 'London' THEN ARRAY['LHR', 'LGW', 'STN', 'LTN']
  WHEN name = 'Paris' THEN ARRAY['CDG', 'ORY', 'BVA']
  WHEN name = 'Tokyo' THEN ARRAY['NRT', 'HND']
  WHEN name = 'Bangkok' THEN ARRAY['BKK', 'DMK']
  WHEN name = 'Istanbul' THEN ARRAY['IST', 'SAW']
  WHEN name = 'Dubai' THEN ARRAY['DXB', 'DWC']
  WHEN name = 'Seoul' THEN ARRAY['ICN', 'GMP']
  WHEN name = 'Moscow' THEN ARRAY['SVO', 'DME', 'VKO']
  WHEN name = 'São Paulo' THEN ARRAY['GRU', 'CGH', 'VCP']
  WHEN name = 'Rio de Janeiro' THEN ARRAY['GIG', 'SDU']
  WHEN name = 'Buenos Aires' THEN ARRAY['EZE', 'AEP']
  WHEN name = 'Shanghai' THEN ARRAY['PVG', 'SHA']
  WHEN name = 'Beijing' THEN ARRAY['PEK', 'PKX']
  WHEN name = 'Milan' THEN ARRAY['MXP', 'LIN', 'BGY']
  WHEN name = 'Barcelona' THEN ARRAY['BCN', 'GRO', 'REU']
  WHEN name = 'Berlin' THEN ARRAY['BER', 'SXF']
  WHEN name = 'Rome' THEN ARRAY['FCO', 'CIA']
  WHEN name = 'Mumbai' THEN ARRAY['BOM']
  WHEN name = 'Delhi' THEN ARRAY['DEL']
  WHEN name = 'Tel Aviv' THEN ARRAY['TLV', 'SDV']
  WHEN name = 'Cairo' THEN ARRAY['CAI']
  WHEN name = 'Casablanca' THEN ARRAY['CMN', 'RBA']
  WHEN name = 'Lagos' THEN ARRAY['LOS']
  WHEN name = 'Nairobi' THEN ARRAY['NBO', 'WIL']
  WHEN name = 'Jakarta' THEN ARRAY['CGK', 'HLP']
  WHEN name = 'Kuala Lumpur' THEN ARRAY['KUL', 'SZB']
  WHEN name = 'Manila' THEN ARRAY['MNL', 'CRK']
  WHEN name = 'Singapore' THEN ARRAY['SIN']
  WHEN name = 'Sydney' THEN ARRAY['SYD', 'KSY']
  WHEN name = 'Melbourne' THEN ARRAY['MEL', 'AVV']
  WHEN name = 'Auckland' THEN ARRAY['AKL']
  WHEN name = 'Toronto' THEN ARRAY['YYZ', 'YTZ']
  WHEN name = 'Vancouver' THEN ARRAY['YVR', 'YHC']
  WHEN name = 'Montreal' THEN ARRAY['YUL', 'YMX']
  WHEN name = 'Mexico City' THEN ARRAY['MEX', 'NLU']
  WHEN name = 'Lima' THEN ARRAY['LIM', 'PIU']
  WHEN name = 'Bogotá' THEN ARRAY['BOG', 'EYP']
  WHEN name = 'Santiago' THEN ARRAY['SCL', 'ULC']
  WHEN name = 'Caracas' THEN ARRAY['CCS', 'CCS']
  WHEN name = 'Quito' THEN ARRAY['UIO', 'GPS']
  WHEN name = 'Tehran' THEN ARRAY['IKA', 'THR']
  WHEN name = 'Baghdad' THEN ARRAY['BGW', 'XQC']
  WHEN name = 'Riyadh' THEN ARRAY['RUH', 'RUH']
  WHEN name = 'Karachi' THEN ARRAY['KHI', 'KHI']
  WHEN name = 'Dhaka' THEN ARRAY['DAC', 'DAC']
  WHEN name = 'Colombo' THEN ARRAY['CMB', 'RML']
  WHEN name = 'Yangon' THEN ARRAY['RGN', 'RGN']
  WHEN name = 'Phnom Penh' THEN ARRAY['PNH', 'PNH']
  WHEN name = 'Vientiane' THEN ARRAY['VTE', 'VTE']
  WHEN name = 'Ulaanbaatar' THEN ARRAY['ULN', 'ULN']
  WHEN name = 'Almaty' THEN ARRAY['ALA', 'ALA']
  WHEN name = 'Tashkent' THEN ARRAY['TAS', 'TAS']
  WHEN name = 'Bishkek' THEN ARRAY['FRU', 'FRU']
  WHEN name = 'Dushanbe' THEN ARRAY['DYU', 'DYU']
  WHEN name = 'Ashgabat' THEN ARRAY['ASB', 'ASB']
  WHEN name = 'Kabul' THEN ARRAY['KBL', 'KBL']
  WHEN name = 'Kathmandu' THEN ARRAY['KTM', 'KTM']
  WHEN name = 'Thimphu' THEN ARRAY['PBH', 'PBH']
  WHEN name = 'Malé' THEN ARRAY['MLE', 'MLE']
  WHEN name = 'Victoria' THEN ARRAY['SEZ', 'SEZ']
  WHEN name = 'Port Louis' THEN ARRAY['MRU', 'MRU']
  WHEN name = 'Antananarivo' THEN ARRAY['TNR', 'TNR']
  WHEN name = 'Nassau' THEN ARRAY['NAS', 'NAS']
  WHEN name = 'Kingston' THEN ARRAY['KIN', 'KIN']
  WHEN name = 'Port of Spain' THEN ARRAY['POS', 'POS']
  WHEN name = 'Bridgetown' THEN ARRAY['BGI', 'BGI']
  WHEN name = 'Castries' THEN ARRAY['SLU', 'UVF']
  WHEN name = 'St. George''s' THEN ARRAY['GND', 'GND']
  WHEN name = 'Kingstown' THEN ARRAY['SVD', 'CIW']
  WHEN name = 'St. John''s' THEN ARRAY['ANU', 'ANU']
  WHEN name = 'Roseau' THEN ARRAY['DOM', 'DOM']
  WHEN name = 'Basseterre' THEN ARRAY['SKB', 'NEV']
  WHEN name = 'Havana' THEN ARRAY['HAV', 'HAV']
  WHEN name = 'Santo Domingo' THEN ARRAY['SDQ', 'JBQ']
  WHEN name = 'Port-au-Prince' THEN ARRAY['PAP', 'PAP']
  WHEN name = 'San Juan' THEN ARRAY['SJU', 'SJU']
  WHEN name = 'Reykjavik' THEN ARRAY['KEF', 'RKV']
  WHEN name = 'Dublin' THEN ARRAY['DUB', 'DUB']
  WHEN name = 'Valletta' THEN ARRAY['MLA', 'MLA']
  WHEN name = 'Larnaca' THEN ARRAY['LCA', 'PFO']
  WHEN name = 'Luxembourg' THEN ARRAY['LUX', 'LUX']
  WHEN name = 'Monaco' THEN ARRAY['MCM', 'MCM']
  WHEN name = 'Andorra la Vella' THEN ARRAY['ALV', 'ALV']
  WHEN name = 'San Marino' THEN ARRAY['RMI', 'RMI']
  WHEN name = 'Vatican City' THEN ARRAY['CIA', 'CIA']
  WHEN name = 'Vaduz' THEN ARRAY['ACH', 'ACH']
  ELSE ARRAY[major_airport_code]
END
WHERE major_airport_code IS NULL OR airport_codes IS NULL OR array_length(airport_codes, 1) IS NULL;