-- Insert sexual orientation tags (only those that don't already exist)
INSERT INTO public.tags (name, category, description) 
SELECT name, category, description FROM (VALUES
  ('Abrosexual', 'sexual-orientation', 'Sexual orientation that changes over time'),
  ('Accipiosexual', 'sexual-orientation', 'Sexual attraction that varies in intensity'),
  ('Aceflux', 'sexual-orientation', 'Asexual identity that fluctuates in intensity'),
  ('Achillean', 'sexual-orientation', 'Men loving men (MLM)'),
  ('Aegosexual', 'sexual-orientation', 'Asexual who enjoys sexual content but not personal participation'),
  ('Allosexual', 'sexual-orientation', 'Experiencing sexual attraction (opposite of asexual)'),
  ('Androgynosexual', 'sexual-orientation', 'Attraction to androgynous people'),
  ('Androsexual', 'sexual-orientation', 'Attraction to men or masculinity'),
  ('Asexual', 'sexual-orientation', 'Little to no sexual attraction'),
  ('Aurasexual', 'sexual-orientation', 'Sexual attraction based on aura or energy'),
  ('Autosexual', 'sexual-orientation', 'Primary sexual attraction to oneself'),
  ('BDSM Orientated', 'sexual-orientation', 'Sexual orientation centered around BDSM practices'),
  ('Benignosexual', 'sexual-orientation', 'Sexual attraction without desire for sexual activity'),
  ('Bicurious', 'sexual-orientation', 'Curious about same-gender sexual experiences'),
  ('Bisexual', 'sexual-orientation', 'Attraction to two or more genders'),
  ('Cupiosexual', 'sexual-orientation', 'Asexual who desires a sexual relationship'),
  ('Demisexual', 'sexual-orientation', 'Sexual attraction only after strong emotional bond'),
  ('Dyke', 'sexual-orientation', 'Reclaimed term for masculine lesbian'),
  ('Finsexual', 'sexual-orientation', 'Attraction to feminine-in-nature people'),
  ('Fluctuating/Evolving', 'sexual-orientation', 'Sexual orientation that changes over time'),
  ('Fraysexual', 'sexual-orientation', 'Sexual attraction that fades as emotional connection grows'),
  ('Gay', 'sexual-orientation', 'Attraction to same gender'),
  ('Graysexual', 'sexual-orientation', 'Experiencing sexual attraction rarely or weakly'),
  ('Gynesexual', 'sexual-orientation', 'Attraction to women or femininity'),
  ('Heteroflexible', 'sexual-orientation', 'Primarily heterosexual with occasional same-gender attraction'),
  ('Heterosexual', 'sexual-orientation', 'Attraction to opposite gender'),
  ('Heterotypical', 'sexual-orientation', 'Typical heterosexual orientation'),
  ('Homoflexible', 'sexual-orientation', 'Primarily homosexual with occasional opposite-gender attraction'),
  ('Homosexual', 'sexual-orientation', 'Attraction to same gender'),
  ('Iamvanosexual', 'sexual-orientation', 'Sexual orientation that cannot be categorized'),
  ('Lesbian', 'sexual-orientation', 'Women attracted to women'),
  ('Megasexual', 'sexual-orientation', 'Strong sexual attraction'),
  ('Minsexual', 'sexual-orientation', 'Minimal sexual attraction'),
  ('Monosexual', 'sexual-orientation', 'Attraction to one gender'),
  ('Neosexual', 'sexual-orientation', 'New or emerging sexual identity'),
  ('Neptunic', 'sexual-orientation', 'Attraction to women and non-binary people'),
  ('Nebulasexual', 'sexual-orientation', 'Sexual orientation that is unclear or hard to define'),
  ('Noetisexual', 'sexual-orientation', 'Sexual attraction based on intelligence'),
  ('Novosexual', 'sexual-orientation', 'Sexual orientation that is constantly changing'),
  ('Objectum Sexuality', 'sexual-orientation', 'Sexual attraction to inanimate objects'),
  ('Omnisexual', 'sexual-orientation', 'Attraction to all genders with preference differences'),
  ('Pansexual', 'sexual-orientation', 'Attraction regardless of gender'),
  ('Phallosexual', 'sexual-orientation', 'Attraction to people with penises'),
  ('Placiosexual', 'sexual-orientation', 'Wanting to perform sexual acts but not receive'),
  ('Polysexual', 'sexual-orientation', 'Attraction to multiple but not all genders'),
  ('Pornosexual', 'sexual-orientation', 'Sexual orientation focused on pornography'),
  ('Queer', 'sexual-orientation', 'Non-heterosexual or non-cisgender identity'),
  ('Reciprosexual', 'sexual-orientation', 'Sexual attraction only when attraction is mutual'),
  ('Requissexual', 'sexual-orientation', 'Sexual attraction requiring emotional connection'),
  ('Sapiosexual', 'sexual-orientation', 'Attraction based on intelligence'),
  ('Sapphic', 'sexual-orientation', 'Women loving women (WLW)'),
  ('Sexually Fluid', 'sexual-orientation', 'Sexual orientation that changes over time'),
  ('Skoliosexual', 'sexual-orientation', 'Attraction to non-binary and transgender people'),
  ('Straight', 'sexual-orientation', 'Heterosexual orientation'),
  ('Soulsexual', 'sexual-orientation', 'Sexual attraction based on spiritual connection'),
  ('Symbiosexual', 'sexual-orientation', 'Sexual attraction requiring mutual dependence'),
  ('Trysexual', 'sexual-orientation', 'Willing to try various sexual experiences'),
  ('Unlabeled', 'sexual-orientation', 'Choosing not to use specific labels'),
  ('Vulvosexual', 'sexual-orientation', 'Attraction to people with vulvas')
) AS new_tags(name, category, description)
WHERE NOT EXISTS (
  SELECT 1 FROM public.tags WHERE tags.name = new_tags.name
);