import type { Track } from '@/components/transit/routeBulletMap';

/**
 * Octilinear abstractions of real rapid-transit networks, one per featured city.
 *
 * GENERATED by `node scripts/generate-city-transit-lines.mjs` from OpenStreetMap
 * route relations. Do not hand-edit — rerun the script. Committed rather than
 * fetched so the homepage costs no network request and every diagram is
 * reviewed once by eye before it ships.
 *
 * Pure data, no JSX, for the reason `intentMapGeometry.ts` is: the invariants
 * below become unit tests instead of visual checks
 * (see `__tests__/cityNetworkGeometry.test.ts`).
 *
 * THE INVARIANT THAT MAKES THIS WORK: coordinates are INTEGERS on a lattice and
 * every segment is axis-aligned or exactly diagonal, so a diagonal step of k is
 * (±k, ±k). "Every bearing is a multiple of 45°" is therefore exact arithmetic,
 * not a tolerance — and it survives being serialised as text.
 *
 * Track assignment is by LENGTH RANK measured inside the city core (flagship =
 * pink) — ranking on total length puts a suburban orbital first. This is the
 * documented exception to "one accent per context": the four track colors are
 * this artifact's own wayfinding vocabulary, not decoration. See
 * `docs/design-system/README.md`.
 *
 * Lines are nudged apart by a few units so trunk-sharing routes read as
 * parallel tracks. The nudges are integers and none of their differences is
 * axis-aligned or diagonal, so neither the 45° invariant nor the separation
 * can be lost.
 *
 * Cities with no usable rail network are absent — `CityNetwork` falls back to
 * the bending template line for those.
 *
 * Geometry derived from © OpenStreetMap contributors, ODbL.
 */

export const NETWORK_VIEWBOX = { w: 200, h: 110 } as const;

export type NetworkMode = 'subway' | 'light_rail' | 'tram';

export interface NetworkLine {
  /** Track color, assigned by core-length rank. */
  track: Track;
  /** The line's own OSM `ref` (e.g. "U1") — debugging aid, never rendered. */
  ref: string;
  /** Path data. `M`/`L` only, integer coordinates. */
  d: string;
}

export interface CityNetwork {
  mode: NetworkMode;
  lines: NetworkLine[];
  /** Busiest shared vertex — always a vertex of one of the lines. */
  interchange: { x: number; y: number };
}

/** Keyed by `cities.slug`. */
export const CITY_NETWORKS: Record<string, CityNetwork> = {
  berlin: {
    mode: 'subway',
    lines: [
      {
        track: 'pink',
        ref: 'U7',
        d: 'M 118 100 L 108 90 L 108 69 L 92 53 L 73 53 L 69 49 L 69 29 L 39 29',
      },
      {
        track: 'blue',
        ref: 'U2',
        d: 'M 48 38 L 57 47 L 72 47 L 78 53 L 87 53 L 87 46 L 97 46 L 97 19',
      },
      {
        track: 'green',
        ref: 'U8',
        d: 'M 102 68 L 102 54 L 99 51 L 99 44 L 76 21 L 68 21 L 68 14 L 71 11',
      },
      {
        track: 'yellow',
        ref: 'U5',
        d: 'M 86 39 L 89 42 L 126 42 L 135 51 L 150 36 L 150 28 L 162 28',
      },
    ],
    interchange: { x: 92, y: 53 },
  },
  madrid: {
    mode: 'subway',
    lines: [
      { track: 'pink', ref: 'L1', d: 'M 81 57 L 112 88 L 80 56 L 80 36 L 86 30 L 93 30' },
      {
        track: 'blue',
        ref: 'L6',
        d: 'M 74 50 L 66 58 L 76 48 L 69 41 L 83 41 L 90 48 L 90 63 L 76 63 L 68 55',
      },
      {
        track: 'green',
        ref: 'L9',
        d: 'M 68 26 L 71 23 L 71 35 L 80 35 L 80 58 L 108 58 L 143 93 L 159 93 L 166 100',
      },
      { track: 'yellow', ref: 'L10', d: 'M 83 11 L 83 23 L 79 27 L 79 42 L 70 51 L 62 51 L 34 79' },
    ],
    interchange: { x: 80, y: 36 },
  },
  barcelona: {
    mode: 'subway',
    lines: [
      {
        track: 'pink',
        ref: 'L1',
        d: 'M 144 17 L 125 17 L 125 27 L 121 31 L 121 63 L 100 84 L 67 84 L 79 96 L 75 100',
      },
      {
        track: 'blue',
        ref: 'L5',
        d: 'M 53 95 L 70 78 L 93 78 L 131 40 L 123 32 L 111 32 L 111 39 L 106 34',
      },
      {
        track: 'green',
        ref: 'L3',
        d: 'M 114 18 L 86 46 L 118 78 L 101 78 L 94 71 L 89 71 L 84 66 L 73 66',
      },
      {
        track: 'yellow',
        ref: 'L4',
        d: 'M 125 11 L 125 38 L 115 48 L 115 62 L 124 71 L 129 66 L 129 58 L 147 40 L 138 31',
      },
    ],
    interchange: { x: 125, y: 17 },
  },
  amsterdam: {
    mode: 'subway',
    lines: [
      {
        track: 'pink',
        ref: '50',
        d: 'M 134 87 L 122 87 L 99 64 L 90 64 L 81 55 L 59 55 L 59 15 L 63 11',
      },
      { track: 'blue', ref: '51', d: 'M 70 12 L 66 16 L 66 56 L 87 56 L 96 65 L 104 65 L 104 32' },
      { track: 'green', ref: '54', d: 'M 94 43 L 96 45 L 96 49 L 99 52 L 99 72 L 126 99 L 137 99' },
      {
        track: 'yellow',
        ref: '53',
        d: 'M 142 69 L 129 56 L 121 64 L 118 64 L 94 40 L 94 35 L 92 33',
      },
    ],
    interchange: { x: 99, y: 64 },
  },
  'mexico-city': {
    mode: 'subway',
    lines: [
      {
        track: 'pink',
        ref: '1',
        d: 'M 103 47 L 113 47 L 116 44 L 132 60 L 132 56 L 80 56 L 73 63 L 66 63',
      },
      {
        track: 'blue',
        ref: '8',
        d: 'M 116 68 L 110 62 L 103 62 L 103 45 L 121 63 L 121 86 L 131 86 L 141 96',
      },
      { track: 'green', ref: '2', d: 'M 102 96 L 100 96 L 100 49 L 84 49 L 76 41 L 61 41 L 60 42' },
      {
        track: 'yellow',
        ref: '3',
        d: 'M 112 12 L 99 25 L 99 52 L 97 54 L 97 71 L 83 85 L 83 91 L 86 94 L 86 99',
      },
    ],
    interchange: { x: 100, y: 49 },
  },
  bangkok: {
    mode: 'subway',
    lines: [
      {
        track: 'pink',
        ref: 'MRT-BL',
        d: 'M 74 55 L 74 48 L 86 36 L 102 36 L 102 58 L 90 46 L 81 55 L 70 55',
      },
      {
        track: 'blue',
        ref: 'สุขุมวิท',
        d: 'M 113 82 L 113 100 L 113 69 L 94 50 L 129 15 L 134 15',
      },
      { track: 'green', ref: 'สีลม', d: 'M 93 55 L 96 55 L 92 59 L 82 59 L 78 63 L 75 63 L 75 61' },
      {
        track: 'yellow',
        ref: 'MRT Purple',
        d: 'M 66 10 L 66 15 L 93 15 L 93 16 L 91 18 L 96 23 L 96 28',
      },
    ],
    interchange: { x: 94, y: 50 },
  },
  'tel-aviv': {
    mode: 'light_rail',
    lines: [
      {
        track: 'pink',
        ref: 'R1',
        d: 'M 35 95 L 45 85 L 34 74 L 45 63 L 45 40 L 66 40 L 81 25 L 167 25',
      },
      {
        track: 'blue',
        ref: 'R2',
        d: 'M 34 100 L 44 90 L 33 79 L 44 68 L 44 45 L 65 45 L 80 30 L 125 30 L 141 14',
      },
      {
        track: 'green',
        ref: 'R3',
        d: 'M 41 44 L 59 44 L 74 29 L 87 29 L 95 21 L 117 21 L 117 11 L 131 11',
      },
    ],
    interchange: { x: 45, y: 40 },
  },
  lisbon: {
    mode: 'subway',
    lines: [
      {
        track: 'pink',
        ref: 'Azul',
        d: 'M 150 86 L 138 98 L 112 72 L 101 72 L 91 62 L 72 62 L 72 53 L 46 53 L 41 58',
      },
      {
        track: 'blue',
        ref: 'Amarela',
        d: 'M 102 10 L 102 21 L 114 21 L 114 45 L 107 52 L 114 59 L 123 59 L 123 76 L 110 89',
      },
      {
        track: 'green',
        ref: 'Vermelha',
        d: 'M 119 76 L 145 76 L 150 71 L 150 46 L 160 46 L 160 34 L 158 32 L 147 32 L 135 44',
      },
      {
        track: 'yellow',
        ref: 'Verde',
        d: 'M 98 36 L 114 36 L 133 55 L 133 90 L 130 93 L 130 100 L 124 100',
      },
    ],
    interchange: { x: 123, y: 76 },
  },
  'buenos-aires': {
    mode: 'subway',
    lines: [
      {
        track: 'pink',
        ref: 'E',
        d: 'M 132 60 L 137 65 L 137 73 L 127 83 L 127 87 L 80 87 L 74 93 L 68 93 L 62 99',
      },
      { track: 'blue', ref: 'B', d: 'M 148 62 L 91 62 L 81 52 L 62 52 L 61 51 L 58 51 L 52 45' },
      { track: 'green', ref: 'D', d: 'M 56 12 L 99 55 L 99 60 L 110 60 L 120 70' },
      { track: 'yellow', ref: 'A', d: 'M 68 90 L 77 90 L 102 65 L 110 65 L 111 64 L 141 64' },
    ],
    interchange: { x: 137, y: 65 },
  },
  toronto: {
    mode: 'subway',
    lines: [
      {
        track: 'pink',
        ref: '1',
        d: 'M 105 64 L 105 17 L 105 100 L 105 86 L 88 69 L 88 35 L 78 35 L 78 24 L 64 10',
      },
      { track: 'blue', ref: '2', d: 'M 158 63 L 153 68 L 153 83 L 147 89 L 47 89 L 42 94' },
      { track: 'green', ref: '4', d: 'M 123 29 L 130 29 L 101 29' },
    ],
    interchange: { x: 88, y: 69 },
  },
  montreal: {
    mode: 'subway',
    lines: [
      {
        track: 'pink',
        ref: '2',
        d: 'M 78 42 L 73 37 L 58 37 L 104 37 L 124 57 L 108 73 L 99 73 L 70 44',
      },
      {
        track: 'blue',
        ref: '1',
        d: 'M 110 99 L 119 90 L 125 90 L 125 80 L 117 72 L 138 51 L 133 46 L 133 11',
      },
      {
        track: 'green',
        ref: '5',
        d: 'M 91 76 L 91 72 L 100 63 L 100 59 L 96 55 L 96 53 L 109 40 L 109 37',
      },
      {
        track: 'yellow',
        ref: '4',
        d: 'M 130 56 L 131 57 L 136 57 L 143 50 L 143 47 L 132 58 L 130 56',
      },
    ],
    interchange: { x: 104, y: 37 },
  },
  'san-francisco': {
    mode: 'subway',
    lines: [
      {
        track: 'pink',
        ref: 'Orange',
        d: 'M 129 100 L 129 75 L 93 39 L 93 29 L 91 29 L 85 23 L 81 23',
      },
      {
        track: 'blue',
        ref: 'Yellow',
        d: 'M 124 10 L 115 10 L 115 25 L 104 25 L 95 34 L 95 40 L 79 40 L 70 49 L 79 58',
      },
      {
        track: 'green',
        ref: 'Red',
        d: 'M 77 24 L 80 24 L 87 31 L 87 40 L 73 40 L 70 43 L 70 48 L 65 53 L 77 65',
      },
      {
        track: 'yellow',
        ref: 'Blue',
        d: 'M 135 47 L 111 47 L 97 33 L 80 33 L 77 36 L 77 41 L 72 46',
      },
    ],
    interchange: { x: 93, y: 29 },
  },
  'new-york': {
    mode: 'subway',
    lines: [
      {
        track: 'pink',
        ref: 'R',
        d: 'M 63 76 L 63 67 L 80 50 L 70 40 L 79 31 L 79 17 L 89 27 L 95 21 L 114 40',
      },
      {
        track: 'blue',
        ref: 'N',
        d: 'M 102 19 L 93 28 L 83 18 L 83 32 L 74 41 L 84 51 L 67 68 L 78 79 L 78 95',
      },
      {
        track: 'green',
        ref: 'F',
        d: 'M 77 98 L 77 63 L 72 58 L 72 39 L 68 35 L 80 23 L 102 23 L 126 47 L 137 47',
      },
      {
        track: 'yellow',
        ref: 'M',
        d: 'M 118 36 L 99 17 L 95 21 L 86 12 L 74 24 L 92 42 L 99 42 L 105 36',
      },
    ],
    interchange: { x: 70, y: 40 },
  },
  'los-angeles': {
    mode: 'subway',
    lines: [
      {
        track: 'pink',
        ref: 'B',
        d: 'M 50 12 L 66 28 L 66 35 L 83 52 L 119 52 L 119 81 L 137 99 L 145 91 L 151 91',
      },
      { track: 'blue', ref: 'D', d: 'M 55 86 L 116 86 L 129 99 L 137 91 L 141 91 L 143 93' },
    ],
    interchange: { x: 119, y: 81 },
  },
  london: {
    mode: 'subway',
    lines: [
      {
        track: 'pink',
        ref: 'Northern',
        d: 'M 83 100 L 118 65 L 118 57 L 106 57 L 106 41 L 92 27 L 92 16 L 86 10',
      },
      {
        track: 'blue',
        ref: 'Piccadilly',
        d: 'M 37 54 L 56 35 L 73 52 L 73 70 L 98 70 L 109 59 L 109 36 L 86 13',
      },
      {
        track: 'green',
        ref: 'Jubilee',
        d: 'M 54 33 L 63 42 L 63 51 L 90 51 L 106 67 L 139 67 L 142 64 L 142 50',
      },
      {
        track: 'yellow',
        ref: 'Central',
        d: 'M 68 51 L 74 45 L 84 55 L 133 55 L 140 48 L 137 45 L 163 19',
      },
    ],
    interchange: { x: 68, y: 51 },
  },
  paris: {
    mode: 'subway',
    lines: [
      {
        track: 'pink',
        ref: '14',
        d: 'M 109 10 L 96 23 L 96 36 L 114 54 L 101 67 L 101 78 L 113 90 L 113 100',
      },
      {
        track: 'blue',
        ref: '7',
        d: 'M 112 34 L 128 18 L 110 36 L 102 36 L 112 46 L 109 49 L 109 76',
      },
      {
        track: 'green',
        ref: '8',
        d: 'M 81 56 L 96 41 L 108 41 L 108 48 L 113 48 L 120 55 L 118 57 L 133 72 L 133 87',
      },
      {
        track: 'yellow',
        ref: '9',
        d: 'M 123 38 L 129 32 L 119 42 L 109 32 L 96 32 L 91 37 L 83 37 L 68 52',
      },
    ],
    interchange: { x: 96, y: 36 },
  },
  sydney: {
    mode: 'light_rail',
    lines: [
      {
        track: 'pink',
        ref: 'L1',
        d: 'M 108 79 L 108 74 L 118 64 L 135 64 L 137 62 L 135 60 L 136 59 L 143 66',
      },
      { track: 'blue', ref: 'L4', d: 'M 42 25 L 45 22 L 51 22 L 51 30 L 61 30 L 70 21 L 70 11' },
      {
        track: 'green',
        ref: 'L3',
        d: 'M 144 61 L 143 62 L 143 72 L 144 73 L 144 75 L 149 80 L 149 100',
      },
      {
        track: 'yellow',
        ref: 'L2',
        d: 'M 159 82 L 156 82 L 156 77 L 152 73 L 152 67 L 147 62 L 147 49 L 148 48',
      },
    ],
    interchange: { x: 143, y: 66 },
  },
  melbourne: {
    mode: 'tram',
    lines: [
      {
        track: 'pink',
        ref: '16',
        d: 'M 93 51 L 93 93 L 92 93 L 92 98 L 65 98 L 62 95 L 67 90 L 67 49',
      },
      { track: 'blue', ref: '6', d: 'M 61 23 L 68 23 L 68 52 L 66 52 L 66 90 L 110 90' },
      {
        track: 'green',
        ref: '58',
        d: 'M 45 13 L 45 33 L 49 33 L 49 49 L 54 54 L 54 72 L 63 81 L 93 81',
      },
      {
        track: 'yellow',
        ref: '109',
        d: 'M 48 77 L 60 65 L 60 60 L 71 60 L 71 56 L 98 56 L 103 51 L 155 51',
      },
    ],
    interchange: { x: 68, y: 52 },
  },
  copenhagen: {
    mode: 'subway',
    lines: [
      {
        track: 'pink',
        ref: 'M3',
        d: 'M 94 42 L 94 59 L 111 42 L 111 34 L 104 27 L 104 18 L 84 18 L 91 25 L 84 32',
      },
      {
        track: 'blue',
        ref: 'M2',
        d: 'M 137 81 L 137 53 L 125 53 L 111 39 L 102 39 L 98 43 L 66 43',
      },
      {
        track: 'green',
        ref: 'M1',
        d: 'M 102 99 L 102 61 L 107 56 L 107 46 L 100 39 L 96 43 L 64 43',
      },
      {
        track: 'yellow',
        ref: 'M4',
        d: 'M 117 12 L 106 23 L 113 30 L 113 38 L 98 53 L 98 69 L 93 69 L 83 59',
      },
    ],
    interchange: { x: 111, y: 42 },
  },
  stockholm: {
    mode: 'subway',
    lines: [
      {
        track: 'pink',
        ref: '18',
        d: 'M 155 100 L 141 86 L 141 18 L 131 28 L 72 28 L 59 15 L 46 15',
      },
      {
        track: 'blue',
        ref: '19',
        d: 'M 52 16 L 62 16 L 74 28 L 133 28 L 144 17 L 144 53 L 120 77 L 109 77',
      },
      {
        track: 'green',
        ref: 'Gul linje till Älvsjö',
        d: 'M 119 34 L 119 57 L 129 67 L 113 83 L 129 67 L 119 57 L 119 34 L 119 62 L 106 75',
      },
      {
        track: 'yellow',
        ref: '17',
        d: 'M 154 71 L 154 49 L 140 49 L 140 13 L 130 23 L 71 23 L 58 10 L 45 10',
      },
    ],
    interchange: { x: 141, y: 18 },
  },
  brussels: {
    mode: 'subway',
    lines: [
      {
        track: 'pink',
        ref: '5',
        d: 'M 25 91 L 43 91 L 80 54 L 87 54 L 104 71 L 134 71 L 134 99 L 153 99',
      },
      {
        track: 'blue',
        ref: '6',
        d: 'M 95 12 L 103 12 L 103 33 L 74 62 L 92 80 L 104 68 L 104 52 L 84 32',
      },
      {
        track: 'green',
        ref: '1',
        d: 'M 176 65 L 168 57 L 164 61 L 149 61 L 135 75 L 100 75 L 83 58 L 76 58 L 76 68',
      },
      {
        track: 'yellow',
        ref: '2',
        d: 'M 90 30 L 110 50 L 110 65 L 100 75 L 95 75 L 78 58 L 78 50 L 86 42',
      },
    ],
    interchange: { x: 104, y: 71 },
  },
  vienna: {
    mode: 'subway',
    lines: [
      { track: 'pink', ref: 'U1', d: 'M 126 11 L 124 13 L 124 22 L 93 53 L 93 91 L 98 96' },
      {
        track: 'blue',
        ref: 'U6',
        d: 'M 105 24 L 105 30 L 98 37 L 89 37 L 82 44 L 82 64 L 79 67 L 79 99',
      },
      {
        track: 'green',
        ref: 'U2',
        d: 'M 145 44 L 145 39 L 135 39 L 116 58 L 108 50 L 91 50 L 86 55 L 91 60',
      },
      {
        track: 'yellow',
        ref: 'U4',
        d: 'M 90 23 L 90 32 L 104 46 L 100 50 L 96 50 L 84 62 L 55 62',
      },
    ],
    interchange: { x: 93, y: 53 },
  },
};
