-- Insert Sexual Activities tags
INSERT INTO public.tags (name, category, description) VALUES
('Air Tight', 'sexual_activities', 'Sexual activity tag'),
('Anal Sex', 'sexual_activities', 'Sexual activity tag'),
('Bareback', 'sexual_activities', 'Sexual activity tag'),
('Blowbang', 'sexual_activities', 'Sexual activity tag'),
('Blowjob', 'sexual_activities', 'Sexual activity tag'),
('Breeding', 'sexual_activities', 'Sexual activity tag'),
('Bukkake', 'sexual_activities', 'Sexual activity tag'),
('Car Play', 'sexual_activities', 'Sexual activity tag'),
('Creampie', 'sexual_activities', 'Sexual activity tag'),
('Cunnilingus', 'sexual_activities', 'Sexual activity tag'),
('Cuntification', 'sexual_activities', 'Sexual activity tag'),
('Deepthroat', 'sexual_activities', 'Sexual activity tag'),
('Dining at the Y (DATY)', 'sexual_activities', 'Sexual activity tag'),
('Docking', 'sexual_activities', 'Sexual activity tag'),
('Dogging', 'sexual_activities', 'Sexual activity tag'),
('Double Penetration', 'sexual_activities', 'Sexual activity tag'),
('Edging', 'sexual_activities', 'Sexual activity tag'),
('Exposure Play', 'sexual_activities', 'Sexual activity tag'),
('Face Fucking', 'sexual_activities', 'Sexual activity tag'),
('Facial', 'sexual_activities', 'Sexual activity tag'),
('Figging', 'sexual_activities', 'Sexual activity tag'),
('Fisting', 'sexual_activities', 'Sexual activity tag'),
('Footjob', 'sexual_activities', 'Sexual activity tag'),
('Foursome', 'sexual_activities', 'Sexual activity tag'),
('Free Use', 'sexual_activities', 'Sexual activity tag'),
('Fucklicking', 'sexual_activities', 'Sexual activity tag'),
('Gangbang', 'sexual_activities', 'Sexual activity tag'),
('Gloryhole', 'sexual_activities', 'Sexual activity tag'),
('Intercrural Sex', 'sexual_activities', 'Sexual activity tag'),
('Jerk Off Instructions', 'sexual_activities', 'Sexual activity tag'),
('Masturbating', 'sexual_activities', 'Sexual activity tag'),
('Mixed Wrestling', 'sexual_activities', 'Sexual activity tag'),
('Moresome', 'sexual_activities', 'Sexual activity tag'),
('Morning Sex', 'sexual_activities', 'Sexual activity tag'),
('Mutual Masturbation', 'sexual_activities', 'Sexual activity tag'),
('Nipple play', 'sexual_activities', 'Sexual activity tag'),
('Oral', 'sexual_activities', 'Sexual activity tag'),
('Orgasm Play', 'sexual_activities', 'Sexual activity tag'),
('Orgy', 'sexual_activities', 'Sexual activity tag'),
('Party & Play', 'sexual_activities', 'Sexual activity tag'),
('Pegging', 'sexual_activities', 'Sexual activity tag'),
('Pompoir', 'sexual_activities', 'Sexual activity tag'),
('Quacking', 'sexual_activities', 'Sexual activity tag'),
('Queening', 'sexual_activities', 'Sexual activity tag'),
('Rimming', 'sexual_activities', 'Sexual activity tag'),
('Run a Train', 'sexual_activities', 'Sexual activity tag'),
('Scat Play', 'sexual_activities', 'Sexual activity tag'),
('Sexting', 'sexual_activities', 'Sexual activity tag'),
('Sexual Positions', 'sexual_activities', 'Sexual activity tag'),
('Snowballing', 'sexual_activities', 'Sexual activity tag'),
('Squirting', 'sexual_activities', 'Sexual activity tag'),
('Stretching', 'sexual_activities', 'Sexual activity tag'),
('Swinging', 'sexual_activities', 'Sexual activity tag'),
('Teabagging', 'sexual_activities', 'Sexual activity tag'),
('Testicular Sex', 'sexual_activities', 'Sexual activity tag'),
('Threesome', 'sexual_activities', 'Sexual activity tag'),
('Throat Fucking', 'sexual_activities', 'Sexual activity tag'),
('Triple Penetration', 'sexual_activities', 'Sexual activity tag'),
('Urethral Sounding', 'sexual_activities', 'Sexual activity tag'),
('Wand Teasing', 'sexual_activities', 'Sexual activity tag'),
('Yoni Massage', 'sexual_activities', 'Sexual activity tag'),
('Frotting', 'sexual_activities', 'Sexual activity tag'),
('Tit Fucking', 'sexual_activities', 'Sexual activity tag');