-- Insert Philia tags
INSERT INTO public.tags (name, category, description) VALUES
('Algophilia', 'philia', 'Philia tag'),
('Ass Fetish', 'philia', 'Philia tag'),
('Auralism', 'philia', 'Philia tag'),
('Breast Fetish', 'philia', 'Philia tag'),
('Dacryphilia', 'philia', 'Philia tag'),
('Diaper Fetish', 'philia', 'Philia tag'),
('Eproctophilia', 'philia', 'Philia tag'),
('Feedism', 'philia', 'Philia tag'),
('Giantess Fetish', 'philia', 'Philia tag'),
('heirophilia', 'philia', 'Philia tag'),
('Klismaphilia', 'philia', 'Philia tag'),
('Looner', 'philia', 'Philia tag'),
('Macrophilia', 'philia', 'Philia tag'),
('Microphilia', 'philia', 'Philia tag'),
('Nasophilia', 'philia', 'Philia tag'),
('Plushophilia', 'philia', 'Philia tag'),
('Pregnancy Fetish', 'philia', 'Philia tag'),
('Rubberism', 'philia', 'Philia tag'),
('Shoe Fetish', 'philia', 'Philia tag'),
('Somnophilia', 'philia', 'Philia tag'),
('Teratophilia', 'philia', 'Philia tag'),
('Xenophilia', 'philia', 'Philia tag'),
('Zoophilia', 'philia', 'Philia tag'),
('Uniform Fetish', 'philia', 'Philia tag');