-- Insert sample venues
INSERT INTO public.venues (
  name,
  description,
  address,
  city,
  state,
  country,
  category,
  phone,
  website,
  email,
  tags,
  amenities,
  price_range,
  verified,
  featured
) VALUES 
(
  'Rainbow Coffee House',
  'A cozy LGBTQ+ friendly coffee shop in the heart of downtown. Known for our inclusive atmosphere and amazing drag queen coffee art.',
  '123 Pride Street',
  'San Francisco',
  'CA',
  'US',
  'Cafe',
  '+1-415-555-0123',
  'https://rainbowcoffeehouse.com',
  'hello@rainbowcoffeehouse.com',
  ARRAY['LGBTQ+ Friendly', 'Coffee', 'Drag Shows', 'Community Space'],
  ARRAY['WiFi', 'Outdoor Seating', 'Wheelchair Accessible', 'Live Entertainment'],
  2,
  true,
  true
),
(
  'The Glitter Bar',
  'Premier cocktail lounge featuring craft cocktails and weekly drag performances. A safe space for everyone to shine.',
  '456 Castro Avenue',
  'San Francisco',
  'CA',
  'US',
  'Bar',
  '+1-415-555-0456',
  'https://theglitterbar.com',
  'info@theglitterbar.com',
  ARRAY['LGBTQ+ Friendly', 'Cocktails', 'Drag Shows', 'Nightlife'],
  ARRAY['Full Bar', 'Dance Floor', 'Live Entertainment', 'Private Events'],
  3,
  true,
  true
),
(
  'Diversity Bookstore & Gallery',
  'Independent bookstore specializing in LGBTQ+ literature, local art, and community events. A cultural hub for queer voices.',
  '789 Literary Lane',
  'New York',
  'NY',
  'US',
  'Bookstore',
  '+1-212-555-0789',
  'https://diversitybooks.com',
  'contact@diversitybooks.com',
  ARRAY['LGBTQ+ Friendly', 'Books', 'Art Gallery', 'Community Events'],
  ARRAY['Reading Corner', 'Art Exhibitions', 'Event Space', 'Wheelchair Accessible'],
  2,
  true,
  false
),
(
  'Unity Wellness Center',
  'Holistic wellness center offering yoga, meditation, and therapy services with a focus on LGBTQ+ mental health and wellbeing.',
  '321 Harmony Boulevard',
  'Portland',
  'OR',
  'US',
  'Wellness',
  '+1-503-555-0321',
  'https://unitywellness.com',
  'wellness@unitywellness.com',
  ARRAY['LGBTQ+ Friendly', 'Wellness', 'Yoga', 'Mental Health'],
  ARRAY['Yoga Studio', 'Meditation Room', 'Therapy Rooms', 'Parking'],
  2,
  true,
  false
),
(
  'Queer Cuts Hair Salon',
  'Full-service hair salon specializing in gender-affirming cuts and styles. Our stylists understand the importance of feeling authentic.',
  '654 Style Street',
  'Austin',
  'TX',
  'US',
  'Salon',
  '+1-512-555-0654',
  'https://queercuts.com',
  'book@queercuts.com',
  ARRAY['LGBTQ+ Friendly', 'Hair Salon', 'Gender Affirming', 'Beauty'],
  ARRAY['Hair Cutting', 'Hair Coloring', 'Styling', 'Consultation'],
  2,
  true,
  false
),
(
  'The Phoenix Dance Club',
  'High-energy dance club with multiple floors, themed nights, and the best DJs in the city. Where the queer community comes to dance.',
  '987 Beat Avenue',
  'Miami',
  'FL',
  'US',
  'Nightclub',
  '+1-305-555-0987',
  'https://phoenixdanceclub.com',
  'party@phoenixdanceclub.com',
  ARRAY['LGBTQ+ Friendly', 'Dancing', 'Nightlife', 'Electronic Music'],
  ARRAY['Multiple Dance Floors', 'Full Bar', 'VIP Area', 'Coat Check'],
  3,
  true,
  true
);