-- Insert kink activity tags
INSERT INTO public.tags (name, category, description) 
SELECT name, category, description FROM (VALUES
  ('Age Play', 'kink-activities', 'Role-playing with age differences'),
  ('Age Regression', 'kink-activities', 'Acting younger than chronological age'),
  ('Analytikink', 'kink-activities', 'Analytical approach to kink'),
  ('Ass Worship', 'kink-activities', 'Worshipping buttocks'),
  ('Ball Busting', 'kink-activities', 'Impact play on testicles'),
  ('Bastinado', 'kink-activities', 'Foot or sole beating'),
  ('BDSM', 'kink-activities', 'Bondage, Discipline, Dominance, Submission, Sadism, Masochism'),
  ('Belly Stuffing', 'kink-activities', 'Filling belly with food or objects'),
  ('Blood Play', 'kink-activities', 'Activities involving blood'),
  ('Body Modification', 'kink-activities', 'Altering body appearance'),
  ('Bondage', 'kink-activities', 'Restraining with ropes, cuffs, or other items'),
  ('Breeding Play', 'kink-activities', 'Role-playing reproductive scenarios'),
  ('Castration Play', 'kink-activities', 'Fantasy or role-play of castration'),
  ('Cattle Play', 'kink-activities', 'Role-playing as livestock'),
  ('Chastity', 'kink-activities', 'Preventing sexual release'),
  ('Clit and Pussy Torture (CPT)', 'kink-activities', 'Pain play on female genitals'),
  ('Co-Topping', 'kink-activities', 'Multiple dominants working together'),
  ('Cock & Ball Torture (CBT)', 'kink-activities', 'Pain play on male genitals'),
  ('Collaring', 'kink-activities', 'Wearing collar as symbol of ownership'),
  ('Consensual Non-Consent (CNC)', 'kink-activities', 'Consensual resistance or force scenarios'),
  ('Creampie Gangbang', 'kink-activities', 'Multiple partners finishing inside'),
  ('Cuckolding', 'kink-activities', 'Partner having sex with others while watched'),
  ('Cunt Busting', 'kink-activities', 'Impact play on vulva'),
  ('Degradation', 'kink-activities', 'Verbal or physical humiliation'),
  ('Denim Play', 'kink-activities', 'Fetish involving denim clothing'),
  ('Discipline', 'kink-activities', 'Training through punishment and reward'),
  ('Disobedience Play', 'kink-activities', 'Deliberately breaking rules'),
  ('Dominance', 'kink-activities', 'Taking control in power exchange'),
  ('Dollification', 'kink-activities', 'Treating person as doll or object'),
  ('Dronification', 'kink-activities', 'Dehumanization into drone role'),
  ('Edgeplay', 'kink-activities', 'High-risk kink activities'),
  ('Electricity Play', 'kink-activities', 'Using electrical stimulation'),
  ('Energy Play', 'kink-activities', 'Manipulation of personal energy'),
  ('Exhibitionism', 'kink-activities', 'Exposing oneself to others'),
  ('Facesitting', 'kink-activities', 'Sitting on someone''s face'),
  ('Fear Play', 'kink-activities', 'Using fear for arousal'),
  ('Feminization', 'kink-activities', 'Making someone more feminine'),
  ('Financial Domination', 'kink-activities', 'Control through money'),
  ('Fire Play', 'kink-activities', 'Using fire for sensation'),
  ('Foot Fetish Play', 'kink-activities', 'Activities involving feet'),
  ('Gaping', 'kink-activities', 'Stretching body openings'),
  ('Hair Removal', 'kink-activities', 'Removing body hair'),
  ('Humiliation', 'kink-activities', 'Causing shame or embarrassment'),
  ('Hypnosis', 'kink-activities', 'Altered state of consciousness'),
  ('Incest Play', 'kink-activities', 'Role-playing family relationships'),
  ('Impact Play', 'kink-activities', 'Striking the body for sensation'),
  ('Knife Play', 'kink-activities', 'Using knives for sensation or fear'),
  ('Maid Roleplay', 'kink-activities', 'Role-playing as domestic servant'),
  ('Maid Service', 'kink-activities', 'Performing domestic tasks'),
  ('Maintenance Spanking', 'kink-activities', 'Regular spanking for behavior'),
  ('Masochism', 'kink-activities', 'Deriving pleasure from pain'),
  ('Medical Play', 'kink-activities', 'Role-playing medical scenarios'),
  ('Needle Play', 'kink-activities', 'Using needles for sensation'),
  ('Neotantra', 'kink-activities', 'Modern tantric practices'),
  ('Objectification', 'kink-activities', 'Treating person as object'),
  ('Omorashi', 'kink-activities', 'Bladder control and desperation'),
  ('One-sided Nudity', 'kink-activities', 'Only one person naked'),
  ('Pain Play', 'kink-activities', 'Consensual infliction of pain'),
  ('Panty Sniffing', 'kink-activities', 'Smelling used underwear'),
  ('Penis Shrinking', 'kink-activities', 'Making penis appear smaller'),
  ('Pet Play', 'kink-activities', 'Role-playing as animals'),
  ('Play Fighting', 'kink-activities', 'Wrestling or mock combat'),
  ('Post Orgasm Torture', 'kink-activities', 'Stimulation after orgasm'),
  ('Power Exchange', 'kink-activities', 'Transfer of control between partners'),
  ('Race Play', 'kink-activities', 'Role-playing racial stereotypes'),
  ('Role Play', 'kink-activities', 'Acting out scenarios or characters'),
  ('Rough Body Play', 'kink-activities', 'Intense physical activities'),
  ('Ruined Orgasm', 'kink-activities', 'Interrupting or diminishing climax'),
  ('Sadism', 'kink-activities', 'Deriving pleasure from causing pain'),
  ('Sadomasochism', 'kink-activities', 'Combining sadism and masochism'),
  ('Scene', 'kink-activities', 'Planned kink activity or session'),
  ('Sacred Play', 'kink-activities', 'Spiritual or ritualistic activities'),
  ('Sensory Play', 'kink-activities', 'Stimulating the senses'),
  ('Serve on Tiptoe', 'kink-activities', 'Serving while standing on toes'),
  ('Shame', 'kink-activities', 'Using feelings of shame'),
  ('Shaving', 'kink-activities', 'Removing body hair with razor'),
  ('Sissy Maid Service', 'kink-activities', 'Feminized domestic service'),
  ('Slave Training', 'kink-activities', 'Teaching submission and service'),
  ('Spanking', 'kink-activities', 'Striking buttocks with hand or implement'),
  ('Splosh', 'kink-activities', 'Wet and messy play'),
  ('Stagging', 'kink-activities', 'Male partner sharing female partner'),
  ('Submission', 'kink-activities', 'Giving up control in power exchange'),
  ('Tickling', 'kink-activities', 'Light touching to cause laughter'),
  ('Total Power Exchange', 'kink-activities', 'Complete transfer of control'),
  ('Trampling', 'kink-activities', 'Walking or standing on someone'),
  ('Urine Play', 'kink-activities', 'Activities involving urine'),
  ('Voyeurism', 'kink-activities', 'Watching others without participation'),
  ('Wax Play', 'kink-activities', 'Using hot wax for sensation'),
  ('Shoe Stealing', 'kink-activities', 'Taking someone''s footwear'),
  ('Lactation Play', 'kink-activities', 'Activities involving breast milk'),
  ('Pussy Worship', 'kink-activities', 'Worshipping female genitals'),
  ('Affectionate Domination', 'kink-activities', 'Loving dominance style'),
  ('Public Play', 'kink-activities', 'Kink activities in public spaces'),
  ('Obedience Training', 'kink-activities', 'Teaching compliance and submission'),
  ('Sensory Deprivation', 'kink-activities', 'Removing or limiting senses'),
  ('Orgasm Denial', 'kink-activities', 'Preventing sexual climax'),
  ('Rough Sex', 'kink-activities', 'Intense physical sexual activity'),
  ('Cell Popping', 'kink-activities', 'Breaking or popping small objects')
) AS new_tags(name, category, description)
WHERE NOT EXISTS (
  SELECT 1 FROM public.tags WHERE tags.name = new_tags.name
);