-- Insert sample events
INSERT INTO public.events (
  title,
  description,
  event_type,
  start_date,
  end_date,
  city,
  country,
  address,
  venue_name,
  organizer_name,
  organizer_contact,
  price_min,
  price_max,
  is_free,
  tags,
  website,
  ticket_url,
  status,
  featured,
  max_attendees
) VALUES 
(
  'Summer Music Festival',
  'A three-day outdoor music festival featuring local and international artists across multiple genres.',
  'Music',
  '2024-08-15 18:00:00+00',
  '2024-08-17 23:59:00+00',
  'Austin',
  'US',
  '2100 Barton Springs Rd, Austin, TX 78746',
  'Zilker Park',
  'Austin Music Events',
  'info@austinmusicevents.com',
  85.00,
  250.00,
  false,
  ARRAY['music', 'festival', 'outdoor', 'live-music'],
  'https://summermusicfest.com',
  'https://tickets.summermusicfest.com',
  'active',
  true,
  50000
),
(
  'Tech Innovation Summit',
  'Join industry leaders and innovators for a day of inspiring talks about the future of technology.',
  'Technology',
  '2024-09-05 09:00:00+00',
  '2024-09-05 18:00:00+00',
  'San Francisco',
  'US',
  '747 Howard St, San Francisco, CA 94103',
  'Moscone Center',
  'TechForward Conference',
  'hello@techforward.io',
  150.00,
  300.00,
  false,
  ARRAY['technology', 'innovation', 'networking', 'conference'],
  'https://techinnovationsummit.com',
  'https://eventbrite.com/tech-summit',
  'active',
  true,
  2000
),
(
  'Community Farmers Market',
  'Fresh local produce, artisan goods, and live entertainment every Saturday morning.',
  'Community',
  '2024-07-20 08:00:00+00',
  '2024-07-20 14:00:00+00',
  'Portland',
  'US',
  '2134 SE Hawthorne Blvd, Portland, OR 97214',
  'Hawthorne District',
  'Portland Community Markets',
  'markets@portlandcommunity.org',
  null,
  null,
  true,
  ARRAY['farmers-market', 'local', 'community', 'food'],
  'https://portlandmarkets.org',
  null,
  'active',
  false,
  500
),
(
  'Art Gallery Opening Night',
  'Exclusive preview of "Contemporary Visions" featuring emerging local artists.',
  'Arts',
  '2024-08-30 19:00:00+00',
  '2024-08-30 22:00:00+00',
  'New York',
  'US',
  '529 W 20th St, New York, NY 10011',
  'Chelsea Art Gallery',
  'Modern Art Collective',
  'events@chelseaart.gallery',
  25.00,
  25.00,
  false,
  ARRAY['art', 'gallery', 'opening', 'contemporary'],
  'https://chelseaart.gallery',
  'https://chelseaart.gallery/tickets',
  'active',
  false,
  150
),
(
  'Startup Networking Mixer',
  'Connect with fellow entrepreneurs, investors, and innovators in the startup ecosystem.',
  'Business',
  '2024-08-22 18:30:00+00',
  '2024-08-22 21:00:00+00',
  'Denver',
  'US',
  '1701 Wynkoop St, Denver, CO 80202',
  'The Bindery',
  'Denver Startup Community',
  'networking@denverstartups.co',
  15.00,
  15.00,
  false,
  ARRAY['networking', 'startup', 'business', 'entrepreneurs'],
  'https://denverstartups.co',
  'https://eventbrite.com/startup-mixer',
  'active',
  false,
  100
),
(
  'Yoga in the Park',
  'Join us for a peaceful morning yoga session surrounded by nature. All levels welcome!',
  'Health',
  '2024-07-28 07:00:00+00',
  '2024-07-28 08:30:00+00',
  'Santa Monica',
  'US',
  '1640 Ocean Ave, Santa Monica, CA 90401',
  'Palisades Park',
  'Santa Monica Wellness',
  'info@smwellness.com',
  null,
  null,
  true,
  ARRAY['yoga', 'wellness', 'outdoor', 'meditation'],
  'https://smwellness.com',
  null,
  'active',
  false,
  50
);