-- Insert sample marketplace listings
INSERT INTO public.marketplace_listings (
  title,
  business_name,
  business_type,
  category,
  subcategory,
  description,
  price,
  price_type,
  currency,
  location,
  contact_email,
  contact_phone,
  website,
  tags,
  shipping_available,
  shipping_info,
  featured,
  status
) VALUES 
(
  'Custom Pride Flag Pins & Patches',
  'Rainbow Craft Co.',
  'Small Business',
  'Fashion & Accessories',
  'Jewelry & Pins',
  'Handcrafted enamel pins and embroidered patches featuring various pride flags. Perfect for showing your pride or supporting a friend. Custom designs available.',
  15.99,
  'fixed',
  'USD',
  'Seattle, WA',
  'orders@rainbowcraft.com',
  '+1-206-555-0111',
  'https://rainbowcraft.com',
  ARRAY['Pride', 'LGBTQ+', 'Handmade', 'Accessories', 'Custom'],
  true,
  'Ships worldwide. Standard shipping 5-7 business days, express 2-3 days.',
  true,
  'active'
),
(
  'Queer Literature Book Bundle',
  'Diverse Pages Bookstore',
  'Retail',
  'Books & Media',
  'Books',
  'Curated collection of 5 contemporary LGBTQ+ novels by diverse authors. Perfect for book clubs or personal reading. Titles rotate monthly.',
  89.99,
  'fixed',
  'USD',
  'Portland, OR',
  'books@diversepages.com',
  '+1-503-555-0222',
  'https://diversepages.com',
  ARRAY['Books', 'LGBTQ+', 'Literature', 'Bundle', 'Diverse Authors'],
  true,
  'Free shipping on orders over $50. Careful packaging guaranteed.',
  false,
  'active'
),
(
  'Gender-Affirming Chest Binder',
  'Affirm Apparel',
  'Health & Wellness',
  'Health & Beauty',
  'Personal Care',
  'High-quality, comfortable chest binder made from breathable materials. Available in multiple sizes and skin tones. Designed for all-day wear.',
  45.00,
  'fixed',
  'USD',
  'San Francisco, CA',
  'support@affirmapparel.com',
  '+1-415-555-0333',
  'https://affirmapparel.com',
  ARRAY['Gender Affirming', 'Transgender', 'Health', 'Comfort', 'Inclusive'],
  true,
  'Discreet packaging. Size exchange policy available.',
  true,
  'active'
),
(
  'Rainbow Wedding Planning Services',
  'Equality Events',
  'Service Provider',
  'Services',
  'Event Planning',
  'Full-service wedding planning specializing in LGBTQ+ ceremonies. From intimate elopements to grand celebrations, we make your dream day perfect.',
  2500.00,
  'starting_at',
  'USD',
  'Los Angeles, CA',
  'hello@equalityevents.com',
  '+1-323-555-0444',
  'https://equalityevents.com',
  ARRAY['Wedding Planning', 'LGBTQ+', 'Events', 'Ceremonies', 'Celebration'],
  false,
  'Services provided locally in LA area.',
  true,
  'active'
),
(
  'Handmade Pronoun Jewelry',
  'Identity Artisans',
  'Small Business',
  'Fashion & Accessories',
  'Jewelry',
  'Delicate necklaces and bracelets featuring pronoun charms. Sterling silver and gold-filled options. Custom pronouns available.',
  28.50,
  'fixed',
  'USD',
  'Austin, TX',
  'create@identityartisans.com',
  '+1-512-555-0555',
  'https://identityartisans.com',
  ARRAY['Pronouns', 'Jewelry', 'Identity', 'Handmade', 'Custom'],
  true,
  'Eco-friendly packaging. 30-day return policy.',
  false,
  'active'
),
(
  'LGBTQ+ Mental Health Counseling',
  'Safe Space Therapy',
  'Healthcare Provider',
  'Services',
  'Mental Health',
  'Specialized therapy services for LGBTQ+ individuals and couples. Experienced in gender identity, coming out, and relationship counseling.',
  120.00,
  'starting_at',
  'USD',
  'Chicago, IL',
  'appointments@safespacetherapy.com',
  '+1-312-555-0666',
  'https://safespacetherapy.com',
  ARRAY['Mental Health', 'Therapy', 'LGBTQ+', 'Counseling', 'Safe Space'],
  false,
  'In-person and virtual sessions available.',
  false,
  'active'
),
(
  'Pride Month Art Print Collection',
  'Spectrum Studios',
  'Creative Services',
  'Art & Crafts',
  'Prints & Posters',
  'Limited edition art prints celebrating LGBTQ+ history and culture. Created by queer artists. 20% of proceeds donated to LGBTQ+ youth organizations.',
  35.00,
  'fixed',
  'USD',
  'Denver, CO',
  'art@spectrumstudios.com',
  '+1-303-555-0777',
  'https://spectrumstudios.com',
  ARRAY['Art', 'Pride', 'Limited Edition', 'Charity', 'Queer Artists'],
  true,
  'Shipped in protective tubes. International shipping available.',
  true,
  'active'
),
(
  'Trans-Friendly Fitness Training',
  'Inclusive Fitness Co.',
  'Fitness & Sports',
  'Services',
  'Personal Training',
  'Personal training services with expertise in trans and non-binary fitness needs. Body-positive approach in a welcoming environment.',
  75.00,
  'starting_at',
  'USD',
  'Atlanta, GA',
  'train@inclusivefitness.com',
  '+1-404-555-0888',
  'https://inclusivefitness.com',
  ARRAY['Fitness', 'Trans Friendly', 'Personal Training', 'Body Positive', 'Inclusive'],
  false,
  'In-person training at our private studio.',
  false,
  'active'
);