-- Insert toys tags
INSERT INTO public.tags (name, category, description) VALUES
('Cock Box', 'toys', 'Toys tag'),
('Fuckbox', 'toys', 'Toys tag'),
('Hardpoint', 'toys', 'Toys tag'),
('Hashira', 'toys', 'Toys tag'),
('Inflatable Ball', 'toys', 'Toys tag'),
('Inflatable Sleep Sack', 'toys', 'Toys tag'),
('One Bar Prison', 'toys', 'Toys tag'),
('Pillory', 'toys', 'Toys tag'),
('Sex Swing', 'toys', 'Toys tag'),
('Soroban', 'toys', 'Toys tag'),
('Spanking Bench', 'toys', 'Toys tag'),
('St Andrew''s Cross', 'toys', 'Toys tag'),
('Suspension Frame', 'toys', 'Toys tag'),
('Vacuum Bed', 'toys', 'Toys tag'),
('Vacuum Cube', 'toys', 'Toys tag'),
('Sensation & Stimulation Devices', 'toys', 'Toys tag'),
('E-Stim Machine', 'toys', 'Toys tag'),
('Nipple Clamps', 'toys', 'Toys tag'),
('Pinwheel', 'toys', 'Toys tag'),
('Vacuum Pump', 'toys', 'Toys tag'),
('Vampire Gloves', 'toys', 'Toys tag'),
('Vibrator', 'toys', 'Toys tag'),
('Violet Wand', 'toys', 'Toys tag'),
('Restraints', 'toys', 'Toys tag'),
('Box Stocks', 'toys', 'Toys tag'),
('Chastity Belt', 'toys', 'Toys tag'),
('Chastity Cage', 'toys', 'Toys tag'),
('Chastity Plug', 'toys', 'Toys tag'),
('Cuffs', 'toys', 'Toys tag'),
('Heretic fork', 'toys', 'Toys tag'),
('Humbler', 'toys', 'Toys tag'),
('John Willie', 'toys', 'Toys tag'),
('Rigid Fiddle', 'toys', 'Toys tag'),
('Spreader Bar', 'toys', 'Toys tag'),
('Stocks', 'toys', 'Toys tag'),
('Straitjacket', 'toys', 'Toys tag'),
('Insertables', 'toys', 'Toys tag'),
('Buttplug', 'toys', 'Toys tag'),
('Dick on a Stick', 'toys', 'Toys tag'),
('Dilator', 'toys', 'Toys tag'),
('Dildo', 'toys', 'Toys tag'),
('Fucking Machine', 'toys', 'Toys tag'),
('Ovipositor', 'toys', 'Toys tag'),
('Prostate Massager', 'toys', 'Toys tag'),
('Speculum', 'toys', 'Toys tag'),
('Strap On', 'toys', 'Toys tag'),
('Strategically Placed Appendage', 'toys', 'Toys tag'),
('Strategically Placed Hole', 'toys', 'Toys tag'),
('Urethral Sound', 'toys', 'Toys tag'),
('Yoni Egg', 'toys', 'Toys tag'),
('Impact Tools', 'toys', 'Toys tag'),
('Paddles', 'toys', 'Toys tag'),
('floggers', 'toys', 'Toys tag'),
('Cane', 'toys', 'Toys tag'),
('crops', 'toys', 'Toys tag'),
('dragon tails', 'toys', 'Toys tag'),
('whip', 'toys', 'Toys tag'),
('Slappers', 'toys', 'Toys tag'),
('Bat', 'toys', 'Toys tag'),
('Curry Comb', 'toys', 'Toys tag'),
('Flogger', 'toys', 'Toys tag'),
('Hammer', 'toys', 'Toys tag'),
('Paddle', 'toys', 'Toys tag'),
('Slapper', 'toys', 'Toys tag'),
('Whip', 'toys', 'Toys tag'),
('gag', 'toys', 'Toys tag'),
('Collar', 'toys', 'Toys tag'),
('Fur Clothing', 'toys', 'Toys tag'),
('Key Jewellery', 'toys', 'Toys tag'),
('Latex Clothing', 'toys', 'Toys tag'),
('Leather Clothing', 'toys', 'Toys tag'),
('Looplok', 'toys', 'Toys tag'),
('Manties', 'toys', 'Toys tag'),
('Mask', 'toys', 'Toys tag'),
('Neoprene Clothing', 'toys', 'Toys tag'),
('Polyurethane Clothing', 'toys', 'Toys tag'),
('Posture Clothing', 'toys', 'Toys tag'),
('PVC Clothing', 'toys', 'Toys tag'),
('Pleather Clothing', 'toys', 'Toys tag'),
('Rubber Clothing', 'toys', 'Toys tag'),
('Shiny Clothing', 'toys', 'Toys tag'),
('Silicone Clothing', 'toys', 'Toys tag'),
('Spandex Clothing', 'toys', 'Toys tag'),
('Vinyl Clothing', 'toys', 'Toys tag');