-- Insert sample events
INSERT INTO public.events (
  title,
  description,
  start_date,
  end_date,
  event_type,
  city,
  state,
  country,
  address,
  venue_name,
  organizer_name,
  organizer_contact,
  website,
  ticket_url,
  is_free,
  price_min,
  price_max,
  max_attendees,
  age_restriction,
  tags,
  featured,
  status
) VALUES 
(
  'Pride Month Drag Show Extravaganza',
  'Join us for a spectacular drag show featuring local and visiting performers. An evening of glamour, entertainment, and celebration of our vibrant LGBTQ+ community.',
  '2025-06-15 20:00:00-07:00',
  '2025-06-15 23:00:00-07:00',
  'Entertainment',
  'San Francisco',
  'CA',
  'US',
  '456 Castro Avenue',
  'The Glitter Bar',
  'Rainbow Events Collective',
  'events@rainbowcollective.com',
  'https://rainbowcollective.com/pride-drag-show',
  'https://tickets.rainbowcollective.com/drag-show',
  false,
  25.00,
  45.00,
  150,
  '21+',
  ARRAY['Pride', 'Drag Show', 'LGBTQ+', 'Entertainment', 'Nightlife'],
  true,
  'active'
),
(
  'Trans Rights Workshop & Support Group',
  'Educational workshop covering trans rights, resources, and support. Open to all allies and community members. Followed by a support group session.',
  '2025-07-20 14:00:00-07:00',
  '2025-07-20 17:00:00-07:00',
  'Workshop',
  'Portland',
  'OR',
  'US',
  '321 Harmony Boulevard',
  'Unity Wellness Center',
  'Trans Justice Coalition',
  'info@transjustice.org',
  'https://transjustice.org/workshops',
  null,
  true,
  null,
  null,
  50,
  'All Ages',
  ARRAY['Trans Rights', 'Workshop', 'Support Group', 'Education', 'Community'],
  true,
  'active'
),
(
  'Queer Book Club Monthly Meeting',
  'Monthly discussion of LGBTQ+ literature. This month we''re reading "Red: A Crayon''s Story" and "Cemetery Boys". New members always welcome!',
  '2025-07-25 18:30:00-05:00',
  '2025-07-25 20:30:00-05:00',
  'Social',
  'Austin',
  'TX',
  'US',
  '789 Literary Lane',
  'Diversity Bookstore & Gallery',
  'Queer Readers Society',
  'books@queerreaders.org',
  'https://diversitybooks.com/book-club',
  null,
  true,
  null,
  null,
  25,
  'All Ages',
  ARRAY['Book Club', 'Literature', 'LGBTQ+', 'Reading', 'Community'],
  false,
  'active'
),
(
  'Rainbow Wedding Fair',
  'Showcase of LGBTQ+ friendly wedding vendors, venues, and services. Meet photographers, planners, caterers, and more who celebrate love in all its forms.',
  '2025-08-10 10:00:00-05:00',
  '2025-08-10 16:00:00-05:00',
  'Fair',
  'Chicago',
  'IL',
  'US',
  '400 Convention Center Drive',
  'Chicago Pride Convention Center',
  'Equality Events',
  'hello@equalityevents.com',
  'https://equalityevents.com/wedding-fair',
  'https://tickets.equalityevents.com/wedding-fair',
  false,
  15.00,
  15.00,
  500,
  'All Ages',
  ARRAY['Wedding', 'Fair', 'LGBTQ+', 'Vendors', 'Planning'],
  true,
  'active'
),
(
  'Youth LGBTQ+ Art Workshop',
  'Creative art workshop for LGBTQ+ youth (ages 13-18). Explore self-expression through various art mediums. All supplies provided. Safe space guaranteed.',
  '2025-08-05 13:00:00-06:00',
  '2025-08-05 16:00:00-06:00',
  'Workshop',
  'Denver',
  'CO',
  'US',
  '555 Creative Avenue',
  'Spectrum Studios',
  'Youth Pride Arts',
  'youth@prideart.org',
  'https://prideart.org/youth-workshop',
  null,
  true,
  null,
  null,
  20,
  '13-18',
  ARRAY['Youth', 'Art', 'Workshop', 'Creative', 'Safe Space'],
  false,
  'active'
),
(
  'Lesbian Visibility Day Celebration',
  'Annual celebration of lesbian visibility with speakers, performances, and community networking. Celebrating lesbian culture, history, and achievements.',
  '2025-04-26 12:00:00-04:00',
  '2025-04-26 18:00:00-04:00',
  'Festival',
  'New York',
  'NY',
  'US',
  '100 Rainbow Plaza',
  'Central Park Bandshell',
  'Lesbian Visibility Coalition',
  'celebrate@lesbianvisibility.org',
  'https://lesbianvisibility.org/celebration',
  null,
  true,
  null,
  null,
  1000,
  'All Ages',
  ARRAY['Lesbian Visibility', 'Celebration', 'Community', 'Festival', 'Awareness'],
  true,
  'active'
),
(
  'Drag Queen Bingo Night',
  'Monthly bingo night hosted by fabulous drag queens! Win prizes, enjoy drinks, and have a blast. Proceeds benefit local LGBTQ+ youth programs.',
  '2025-07-30 19:00:00-04:00',
  '2025-07-30 22:00:00-04:00',
  'Fundraiser',
  'Miami',
  'FL',
  'US',
  '987 Beat Avenue',
  'The Phoenix Dance Club',
  'Miami Drag Collective',
  'bingo@miamidrag.com',
  'https://phoenixdanceclub.com/bingo',
  'https://tickets.phoenixdanceclub.com/bingo',
  false,
  20.00,
  20.00,
  100,
  '18+',
  ARRAY['Drag', 'Bingo', 'Fundraiser', 'Entertainment', 'Community'],
  false,
  'active'
),
(
  'Pride Fitness Bootcamp',
  'High-energy outdoor fitness class welcoming all bodies and fitness levels. Trans-friendly and body-positive environment. Bring water and a mat!',
  '2025-06-28 09:00:00-07:00',
  '2025-06-28 10:30:00-07:00',
  'Fitness',
  'Los Angeles',
  'CA',
  'US',
  '200 Fitness Park Drive',
  'West Hollywood Park',
  'Inclusive Fitness Co.',
  'classes@inclusivefitness.com',
  'https://inclusivefitness.com/bootcamp',
  'https://book.inclusivefitness.com/bootcamp',
  false,
  25.00,
  25.00,
  30,
  'All Ages',
  ARRAY['Fitness', 'Bootcamp', 'Inclusive', 'Outdoor', 'Body Positive'],
  false,
  'active'
);