-- Insert romantic orientation tags
INSERT INTO public.tags (name, category, description) VALUES
('Abroromantic', 'romantic-orientation', 'Romantic orientation that changes over time'),
('Aegoromantic', 'romantic-orientation', 'Aromantic who enjoys romantic content but not personal participation'),
('Aromantic', 'romantic-orientation', 'Little to no romantic attraction'),
('Apresromantic', 'romantic-orientation', 'Romantic attraction that develops after other forms of attraction'),
('Aroflux', 'romantic-orientation', 'Aromantic identity that fluctuates in intensity'),
('Autoromantic', 'romantic-orientation', 'Primary romantic attraction to oneself'),
('Benignoromantic', 'romantic-orientation', 'Romantic attraction without desire for romantic relationship'),
('Biromantic', 'romantic-orientation', 'Romantic attraction to two or more genders'),
('Cupioromantic', 'romantic-orientation', 'Aromantic who desires a romantic relationship'),
('Demiromantic', 'romantic-orientation', 'Romantic attraction only after strong emotional bond'),
('Desinoromantic', 'romantic-orientation', 'Romantic attraction that fades after getting to know someone'),
('Finromantic', 'romantic-orientation', 'Romantic attraction to feminine-in-nature people'),
('Frayromantic', 'romantic-orientation', 'Romantic attraction that fades as emotional connection grows'),
('Grayromantic', 'romantic-orientation', 'Experiencing romantic attraction rarely or weakly'),
('Gyneromantic', 'romantic-orientation', 'Romantic attraction to women or femininity'),
('Heteroromantic', 'romantic-orientation', 'Romantic attraction to opposite gender'),
('Homoromantic', 'romantic-orientation', 'Romantic attraction to same gender'),
('Minromantic', 'romantic-orientation', 'Minimal romantic attraction'),
('Monoromantic', 'romantic-orientation', 'Romantic attraction to one gender'),
('Nebularomantic', 'romantic-orientation', 'Romantic orientation that is unclear or hard to define'),
('Noetiromantic', 'romantic-orientation', 'Romantic attraction based on intelligence'),
('Omniromantic', 'romantic-orientation', 'Romantic attraction to all genders with preference differences'),
('Panromantic', 'romantic-orientation', 'Romantic attraction regardless of gender'),
('Polyromantic', 'romantic-orientation', 'Romantic attraction to multiple but not all genders'),
('Recipromantic', 'romantic-orientation', 'Romantic attraction only when attraction is mutual'),
('Romantically Fluid', 'romantic-orientation', 'Romantic orientation that changes over time'),
('Sapioromantic', 'romantic-orientation', 'Romantic attraction based on intelligence');