-- ============================================================================
-- normalize_news_tags() + backup table for a reversible news-tag cleanup
-- ----------------------------------------------------------------------------
-- news_articles.tags[] is an open topic vocabulary (9k distinct, mostly
-- legitimate specific topics) but the highest-frequency tags are duplicate
-- identity variants generated by the enrichment LLM: lgbtqia+ / lgbtqia /
-- lgbtq / lgbt (same concept), lgbtqia-rights / lgbtqia+-rights, trans /
-- transgender, trans-rights / transgender-rights. These surface as
-- inconsistent NewsCard chips + search facets.
--
-- This function does ONLY objective, high-confidence normalization — slugify,
-- dedupe, drop junk tokens, and collapse the unambiguous identity/rights
-- synonym clusters. It deliberately does NOT touch distinct topic facets
-- (lgbtqia-spaces/-politics/-representation) or the legitimate long tail.
-- Wired into pipeline-enrich-news so new articles stay clean; a one-time
-- reversible backfill (separate, batched) rewrites existing rows.
-- ============================================================================
create or replace function public.normalize_news_tags(p_tags text[])
returns text[]
language sql immutable as $$
  with norm as (
    select distinct case slug
        -- umbrella identity → lgbtqia+
        when 'lgbtqia' then 'lgbtqia+'
        when 'lgbtq'   then 'lgbtqia+'
        when 'lgbtq+'  then 'lgbtqia+'
        when 'lgbt'    then 'lgbtqia+'
        when 'lgbti'   then 'lgbtqia+'
        when 'lgbtqi'  then 'lgbtqia+'
        -- rights synonyms → lgbtqia-rights
        when 'lgbtqia+-rights' then 'lgbtqia-rights'
        when 'lgbtq-rights'    then 'lgbtqia-rights'
        when 'lgbtq+-rights'   then 'lgbtqia-rights'
        -- trans
        when 'trans'              then 'transgender'
        when 'transgender-rights' then 'trans-rights'
        else slug
      end as tag
    from (
      select trim(both '-' from regexp_replace(lower(trim(t)), '[^a-z0-9+]+', '-', 'g')) as slug
      from unnest(coalesce(p_tags, '{}')) as t
      where t is not null and trim(t) <> ''
    ) s
    where slug <> ''
      and slug not in ('null','undefined','general','rss-news','rss_news','news','uncategorized','none','n-a','-')
  )
  select coalesce(array_agg(tag order by tag), '{}')
  from norm;
$$;

alter function public.normalize_news_tags(text[]) owner to postgres;
grant execute on function public.normalize_news_tags(text[]) to service_role, authenticated;

create table if not exists public.news_tags_cleanup_backup_20260618 (
  article_id uuid primary key,
  prev_tags text[],
  backed_up_at timestamptz default now()
);
