-- ============================================================
-- trip_nudges: actionable cards surfaced to the trip owner for
-- events/news/timing that matter to this trip. Generated by the
-- `trip-nudges` edge function (cron-invoked); dismissed by the
-- user client-side via RLS update on `dismissed_at`.
--
-- Idempotency: the (trip_id, kind, dedupe_key) UNIQUE prevents
-- duplicate generation for the same condition (e.g. same event,
-- same news article). Edge function re-runs safely.
-- ============================================================

CREATE TABLE public.trip_nudges (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  trip_id UUID NOT NULL REFERENCES public.trips(id) ON DELETE CASCADE,
  kind TEXT NOT NULL CHECK (kind IN (
    'event_overlap',
    'news_alert',
    'document_expiry',
    'weather_warning',
    'booking_reminder'
  )),
  dedupe_key TEXT NOT NULL,
  title TEXT NOT NULL,
  body TEXT,
  action_label TEXT,
  action_url TEXT,
  severity TEXT NOT NULL DEFAULT 'info' CHECK (severity IN ('info','warning','critical')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  seen_at TIMESTAMPTZ,
  dismissed_at TIMESTAMPTZ
);

CREATE UNIQUE INDEX ux_trip_nudges_dedupe
  ON public.trip_nudges (trip_id, kind, dedupe_key);

CREATE INDEX idx_trip_nudges_active
  ON public.trip_nudges (trip_id, dismissed_at)
  WHERE dismissed_at IS NULL;

ALTER TABLE public.trip_nudges ENABLE ROW LEVEL SECURITY;

-- Select: trip owner + members
CREATE POLICY trip_nudges_select ON public.trip_nudges FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM public.trips t
    WHERE t.id = trip_nudges.trip_id
      AND (
        t.owner_id = (SELECT auth.uid())
        OR EXISTS (
          SELECT 1 FROM public.trip_members m
          WHERE m.trip_id = t.id AND m.user_id = (SELECT auth.uid())
        )
      )
  )
);

-- Update: dismiss / mark seen — only owner + editors
CREATE POLICY trip_nudges_update ON public.trip_nudges FOR UPDATE USING (
  EXISTS (
    SELECT 1 FROM public.trips t
    WHERE t.id = trip_nudges.trip_id
      AND (
        t.owner_id = (SELECT auth.uid())
        OR EXISTS (
          SELECT 1 FROM public.trip_members m
          WHERE m.trip_id = t.id AND m.user_id = (SELECT auth.uid())
                AND m.role IN ('owner','editor')
        )
      )
  )
);

-- Inserts done by service role only (edge function). No INSERT policy.
