-- Create 161 glossary terms that exist in the Kinktionary index and in no
-- row of `unified_tags` under any status.
--
-- GENERATED from scripts/data-quality/kinktionary-new-term-definitions.mjs by
-- scripts/data-quality/generate-new-term-migration.mjs. Edit the definitions
-- there and regenerate; do not hand-edit the VALUES below, or the two will
-- disagree about what was published.
--
-- 161 written from independently documented meaning, 0 inferred from the term's name.
--
-- NOTHING HERE IS PUBLISHED. Every row is created with seo_indexable=false,
-- human_reviewed=false and verification_status='unverified': usable for
-- tagging, browsing and site search, invisible to crawlers until a human
-- approves it. A machine-written definition of an identity or role term is a
-- draft, and this program spent its life retracting prose that reached
-- production as though it were not — 44 chimera pages, then five wrong-sense
-- revivals created while cleaning them up.
--
-- LICENCE. The Kinktionary is licensed NON-COMMERCIAL and queer.guide is
-- commercial, so NOT ONE WORD OF THEIR PROSE IS COPIED OR ADAPTED. Only their
-- TERM LIST was used, as a signal for which entries are absent. Every
-- definition below is original text. For the terms marked
-- `editorial:inferred-from-name`, the Kinktionary is the only place the term is
-- attested at all — so rather than reproduce their definition, the row records
-- that its meaning is a reasoned guess and waits for a human who knows the
-- vocabulary.
--
-- Provenance is written to `tag_sources` with is_public=false, so it is
-- available to reviewers and never rendered on the page.

set local statement_timeout = '600s';

select set_config('app.actor', 'migration:kinktionary-new-terms', true);

do $mig$
declare
  r        record;
  v_bad    int;
  v_made   int := 0;
  v_src    int := 0;
begin
  create temp table _new (
    slug text primary key, name text, cat text, kind text,
    adult boolean, sensitive boolean, sourced boolean,
    descr text, longd text
  ) on commit drop;

  insert into _new (slug, name, cat, kind, adult, sensitive, sourced, descr, longd) values
    ('demimasc', 'Demimasc', 'gender-identity', 'concept', false, false, true,
     'A gender identity in which a person is partially, but not wholly, masculine.',
     'Demimasc describes someone who identifies partly with masculinity and partly with something else — another gender, no gender, or a fluid mix. It sits in the same family as demiboy and demigirl, where the "demi-" prefix marks a partial rather than complete identification. Being demimasc says nothing about a person''s pronouns, presentation or assigned sex at birth.'),
    ('transbian', 'Transbian', 'sexual-orientation', 'concept', false, false, true,
     'A trans woman or transfeminine person who is a lesbian.',
     'Transbian is a self-descriptor combining "trans" and "lesbian", used by trans women and transfeminine people who are attracted to women. It is a term of community self-identification rather than a clinical category, and like most reclaimed vocabulary it is appropriate coming from people it describes.'),
    ('homocurious', 'Homocurious', 'questioning-labels', 'concept', false, false, true,
     'Someone who mainly identifies as straight but is curious about same-sex attraction or experience.',
     'Homocurious describes a person who generally considers themselves heterosexual while remaining open to, or actively exploring, attraction to the same gender. It parallels bi-curious and is usually a stage of self-description rather than a fixed identity; some people later adopt another label and some do not.'),
    ('pancurious', 'Pancurious', 'questioning-labels', 'concept', false, false, true,
     'Someone exploring whether pansexuality describes their attraction.',
     'Pancurious describes a person who is considering or exploring attraction that is not limited by gender, without yet claiming pansexual as an identity. As with other "-curious" terms it marks an open question rather than a settled answer.'),
    ('vegansexual', 'Vegansexual', 'sexual-orientation', 'concept', false, false, true,
     'A person who chooses sexual partners only among other vegans.',
     'Vegansexual describes someone whose choice of sexual partners is limited to other vegans, usually as an extension of an ethical commitment rather than a claim about attraction itself. The term was documented in New Zealand research in the mid-2000s and is a partner-selection preference rather than a sexual orientation in the usual sense.'),
    ('quoisexual', 'Quoisexual', 'sexual-orientation', 'concept', false, false, true,
     'A person for whom the distinction between sexual and other attraction does not apply or make sense.',
     'Quoisexual — from the French "quoi", meaning "what" — describes someone who cannot or does not separate sexual attraction from other kinds of attraction, or who finds the question itself unanswerable for them. It sits on the asexual spectrum and is the sexual counterpart of quoiromantic. It is a statement about the framework not fitting, rather than about the level of attraction.'),
    ('quoiromantic', 'Quoiromantic', 'sexual-orientation', 'concept', false, false, true,
     'A person for whom the distinction between romantic and platonic attraction does not apply or make sense.',
     'Quoiromantic, also called WTFromantic, describes someone who cannot distinguish romantic attraction from friendship or other closeness, or who finds that distinction meaningless for them. It sits on the aromantic spectrum. Like quoisexual, it describes a mismatch with the usual categories rather than an absence of feeling.'),
    ('aplatonic', 'Aplatonic', 'sexual-orientation', 'concept', false, false, true,
     'A person who experiences little or no platonic attraction — the pull toward friendship.',
     'Aplatonic people feel little or no desire to form friendships or close platonic bonds, in the same way an aromantic person feels little or no romantic attraction. It does not mean disliking people or being unable to maintain relationships; it describes the absence of a particular pull. The term comes from the aromantic and asexual communities, where attraction is routinely separated into distinct types.'),
    ('hijra', 'Hijra', 'gender-identity', 'concept', false, false, true,
     'A recognised third-gender community in South Asia, with centuries of documented history.',
     'Hijra refers to a third-gender community across India, Pakistan, Bangladesh and Nepal, generally comprising people assigned male at birth who live in a feminine gender role, alongside some intersex people. Hijra communities have their own kinship structures, and their presence is documented over centuries. India, Nepal, Pakistan and Bangladesh have each granted legal recognition to a third gender in recent decades. Hijra is a specific cultural identity, not a synonym for transgender, and should not be used as a general translation.'),
    ('polycule', 'Polycule', 'relationship-structures', 'concept', false, false, true,
     'The connected network of people linked by romantic or sexual relationships in a polyamorous group.',
     'A polycule is the whole web of people joined directly or indirectly by relationships — partners, partners'' partners, and so on. The word blends "poly" with "molecule", after the way such networks are drawn as diagrams. Polycules vary enormously: some function as a close unit, others are simply a map of who is connected to whom.'),
    ('consensual-non-monogamy', 'Consensual Non-Monogamy', 'relationship-structures', 'concept', false, false, true,
     'Any relationship structure where partners agree that more than one romantic or sexual relationship is permitted.',
     'Consensual non-monogamy, often shortened to CNM or ENM (ethical non-monogamy), is the umbrella for polyamory, open relationships, swinging, relationship anarchy and similar arrangements. The defining feature is informed agreement between everyone involved, which is what separates it from cheating. It describes a structure, not a level of commitment.'),
    ('new-relationship-energy-nre', 'New Relationship Energy (NRE)', 'relationship-structures', 'concept', false, false, true,
     'The intense excitement and preoccupation common in the early stage of a new relationship.',
     'New Relationship Energy describes the heightened attention, euphoria and urgency people often feel at the start of a relationship. The term is used widely in polyamorous communities because NRE with a new partner can unbalance existing relationships if it is not named and managed. It is generally understood as a temporary phase rather than a measure of how much a relationship matters.'),
    ('nesting-metamours', 'Nesting Metamours', 'relationship-structures', 'concept', false, false, true,
     'Metamours who share a home — partners of the same person who also live together.',
     'A metamour is your partner''s partner. Nesting metamours are metamours who also share a household, whether or not they are romantically involved with each other. The arrangement raises practical questions about space, finances and privacy that metamours living apart do not face.'),
    ('squish', 'Squish', 'relationship-structures', 'concept', false, false, true,
     'An intense desire for friendship with someone — the platonic counterpart of a crush.',
     'A squish is a strong pull toward friendship or close platonic connection with a particular person, without romantic or sexual desire. The term comes from the aromantic community, where separating types of attraction is standard, and gives a name to a feeling that English otherwise leaves to the vocabulary of romance.'),
    ('frottage', 'Frottage', 'practices-play', 'concept', true, true, true,
     'Sexual rubbing of the body against a partner, usually while clothed or without penetration.',
     'Frottage covers sexual activity in which people rub their bodies together for stimulation rather than engaging in penetration. Between men it is sometimes called frot. It carries a much lower risk of transmitting sexually transmitted infections than penetrative sex, which is one reason it appears in safer-sex guidance. The related term frotteurism describes non-consensual rubbing against another person and is a criminal act, not a practice.'),
    ('dry-humping', 'Dry Humping', 'practices-play', 'concept', true, true, true,
     'Rubbing the genitals against a partner or object while clothed.',
     'Dry humping is sexual rubbing that keeps clothing on. It is a common form of contact for people avoiding penetration, and carries a low risk of transmitting sexually transmitted infections while clothing remains a barrier.'),
    ('69-position', '69 Position', 'sex-positions', 'concept', true, true, true,
     'A position in which two people perform oral sex on each other at the same time.',
     'Named for the shape the numerals suggest, the 69 position has each partner oriented head-to-foot so both can give and receive oral sex simultaneously. It works with any combination of bodies, and comfort usually depends more on height difference and support than on anatomy.'),
    ('ear-licking', 'Ear Licking', 'practices-play', 'concept', true, true, true,
     'Oral stimulation of a partner''s ear.',
     'The outer ear and the skin around it are densely supplied with nerve endings, which is why licking, breathing on or lightly biting the ear is a common part of foreplay. Some people find it intensely pleasurable and others find it uncomfortable, so it is worth asking.'),
    ('hotdogging', 'Hotdogging', 'practices-play', 'concept', true, true, true,
     'Rubbing the penis between a partner''s buttocks without penetration.',
     'Hotdogging refers to sliding the penis between the buttocks or thighs rather than penetrating. Like other forms of frottage it carries substantially lower infection risk than penetrative sex.'),
    ('jilling-off', 'Jilling Off', 'practices-play', 'concept', true, true, true,
     'Female masturbation — the counterpart to "jacking off".',
     'Jilling off is informal slang for masturbation by women and people with vulvas, coined as a counterpart to the male-coded "jacking off". The term is playful rather than clinical.'),
    ('blumpkin', 'Blumpkin', 'practices-play', 'concept', true, true, true,
     'Receiving oral sex while sitting on a toilet and defecating.',
     'A blumpkin is a slang term for receiving fellatio while seated on a toilet using it. The term appears far more often in comedy and internet slang than as a described practice.'),
    ('rusty-trombone', 'Rusty Trombone', 'practices-play', 'concept', true, true, true,
     'Simultaneous anilingus and manual stimulation of the penis, performed from behind.',
     'The rusty trombone is a slang term for a combined act in which one partner performs anilingus while reaching around to stimulate the other''s penis by hand, the arm motion suggesting a trombone slide. As with any oral-anal contact, barriers substantially reduce the risk of transmitting gastrointestinal infections and hepatitis A.'),
    ('abasiophilia', 'Abasiophilia', 'fetishes-interests', 'concept', true, true, true,
     'Sexual attraction to people with impaired mobility, especially those using braces, casts or wheelchairs.',
     'Abasiophilia is attraction to people with limited mobility or to mobility aids such as leg braces, casts and wheelchairs. As with any attraction directed at a body or a device, the distinction that matters in practice is whether disabled people are treated as partners with their own agency or as objects of the interest.'),
    ('agoraphilia', 'Agoraphilia', 'fetishes-interests', 'concept', true, true, true,
     'Sexual arousal from sex in public or open spaces.',
     'Agoraphilia is arousal connected to having sex outdoors or in public places. The consent of everyone present is the governing issue: public sex where uninvolved people can see is illegal in most jurisdictions and is a consent violation regardless of the law, which is why the interest is usually practised at private outdoor locations or dedicated events.'),
    ('amychophilia', 'Amychophilia', 'fetishes-interests', 'concept', true, true, true,
     'Sexual arousal from being scratched, or from scratching a partner.',
     'Amychophilia is arousal from scratching — giving, receiving or the marks left behind. It overlaps with edge play and sensation play. Broken skin carries infection risk in both directions, so nails, hygiene and aftercare matter.'),
    ('emetophilia', 'Emetophilia', 'fetishes-interests', 'concept', true, true, true,
     'Sexual arousal from vomiting or from watching others vomit.',
     'Emetophilia, sometimes called Roman showers, is arousal connected to vomiting. It carries genuine physical risk: repeated induced vomiting damages tooth enamel and the oesophagus and can cause electrolyte disturbance, and vomit is an infection vector. It is also easily confused with, and can mask, an eating disorder.'),
    ('scopophilia', 'Scopophilia', 'fetishes-interests', 'concept', true, true, true,
     'Sexual pleasure derived from looking — the arousal of watching.',
     'Scopophilia is pleasure taken in looking, and appears both in psychoanalytic writing and in film theory, where Laura Mulvey used it in her account of the gaze. In a kink context it overlaps with voyeurism, with the same governing condition: the person being watched has agreed to it.'),
    ('martymachlia', 'Martymachlia', 'fetishes-interests', 'concept', true, true, true,
     'Sexual arousal from being watched by others during sex.',
     'Martymachlia is arousal from having an audience — the complement of voyeurism. It is a common reason people attend play parties and dedicated venues, where being watched is an agreed part of the setting rather than something imposed on bystanders.'),
    ('narratophilia', 'Narratophilia', 'fetishes-interests', 'concept', true, true, true,
     'Sexual arousal from hearing or telling erotic words and stories.',
     'Narratophilia is arousal driven by language — dirty talk, read or spoken erotica, or narrated fantasy. It is one of the interests that translates most easily to distance and text, and it underpins much of audio erotica.'),
    ('melolagnia', 'Melolagnia', 'fetishes-interests', 'concept', true, true, true,
     'Sexual arousal from music.',
     'Melolagnia is arousal produced by music itself, rather than by lyrics or associated imagery. It shades into the widely reported experience of music producing strong physical responses, sometimes called frisson.'),
    ('dormaphilia', 'Dormaphilia', 'fetishes-interests', 'concept', true, true, true,
     'Sexual arousal connected to a sleeping partner.',
     'Dormaphilia is arousal connected to sleep — a partner asleep, or the appearance of sleep. Consent is the whole of the matter here: a sleeping person cannot consent in the moment, so any practice in this area depends entirely on explicit agreement negotiated in advance while both people are awake, and on a clear means of withdrawing it.'),
    ('onychophilia', 'Onychophilia', 'fetishes-interests', 'concept', true, true, true,
     'Sexual attraction to fingernails or toenails.',
     'Onychophilia is attraction focused on nails — their length, shape, colour or the sensation of them. It frequently appears alongside hand and foot fetishism.'),
    ('pubephilia', 'Pubephilia', 'fetishes-interests', 'concept', true, true, true,
     'Sexual attraction to pubic hair.',
     'Pubephilia is attraction focused on pubic hair — its presence, quantity or styling. It sits alongside the broader trichophilia, which covers hair generally.'),
    ('armpit-fetish', 'Armpit Fetish', 'fetishes-interests', 'concept', true, true, true,
     'Sexual attraction to armpits, sometimes called maschalagnia.',
     'An armpit fetish is attraction focused on the underarm — its appearance, hair or scent. It overlaps with scent-based interests, and hygiene preferences vary widely between people who share it.'),
    ('belly-button-fetish', 'Belly Button Fetish', 'fetishes-interests', 'concept', true, true, true,
     'Sexual attraction to the navel, also called alvinolagnia.',
     'A belly button fetish is attraction focused on the navel and the surrounding stomach, whether through looking, touching or play directed there.'),
    ('ear-fetish', 'Ear Fetish', 'fetishes-interests', 'concept', true, true, true,
     'Sexual attraction to ears.',
     'An ear fetish is attraction focused on the ears — their shape, piercings, or stimulation of them. It often overlaps with interests in sound, whispering and breath.'),
    ('neck-fetish', 'Neck Fetish', 'fetishes-interests', 'concept', true, true, true,
     'Sexual attraction to the neck and throat.',
     'A neck fetish is attraction focused on the neck — its appearance, or kissing, biting and marking there. It is distinct from breath play or choking, which carry serious physical risk and are a separate practice with their own safety requirements.'),
    ('glasses-fetish', 'Glasses Fetish', 'fetishes-interests', 'concept', true, true, true,
     'Sexual attraction to people wearing glasses.',
     'A glasses fetish is attraction to eyewear and to partners wearing it. It sits with other clothing and accessory-based interests, where the object contributes to the appeal rather than being incidental.'),
    ('nylon-fetish', 'Nylon Fetish', 'fetishes-interests', 'concept', true, true, true,
     'Sexual attraction to nylon garments, especially hosiery.',
     'A nylon fetish is attraction to the material — tights, stockings and similar garments — for their texture, sheen and sound as much as their appearance. It is one of the longest-documented material fetishes.'),
    ('stockings-fetish', 'Stockings Fetish', 'fetishes-interests', 'concept', true, true, true,
     'Sexual attraction to stockings and the way they are worn.',
     'A stockings fetish is attraction focused on stockings, suspenders and hold-ups — how they look, how they feel, and often the ritual of putting them on or removing them.'),
    ('smoking-fetish', 'Smoking Fetish', 'fetishes-interests', 'concept', true, true, true,
     'Sexual attraction to the act or imagery of smoking, sometimes called capnolagnia.',
     'A smoking fetish is arousal connected to smoking — watching a partner smoke, the gestures involved, or the associated imagery. The health harms of tobacco apply regardless of context, and some people who share the interest keep it to imagery for that reason.'),
    ('balloon-fetish', 'Balloon Fetish', 'fetishes-interests', 'concept', true, true, true,
     'Sexual attraction to balloons, often called looning.',
     'A balloon fetish, known in its own community as looning, is arousal connected to balloons — inflating them, the texture and sound, and for some the anticipation or moment of popping. Participants generally divide into "poppers" and "non-poppers" by whether the burst is part of the appeal. Latex allergy is a practical consideration.'),
    ('cast-fetish', 'Cast Fetish', 'fetishes-interests', 'concept', true, true, true,
     'Sexual attraction to orthopaedic casts and braces.',
     'A cast fetish is attraction to plaster or fibreglass casts, braces and splints, whether worn by a partner or oneself. It overlaps with abasiophilia. Applying a real cast without medical need carries genuine risk of circulation and skin injury.'),
    ('robot-fetish', 'Robot Fetish', 'fetishes-interests', 'concept', true, true, true,
     'Sexual attraction to robots, androids or people acting mechanically.',
     'A robot fetish, sometimes called technosexuality or ASFR, covers attraction to robots and androids in fiction and imagery, and to partners who take on mechanical or programmed behaviour in roleplay. It overlaps with transformation and objectification interests.'),
    ('transformation-fetish', 'Transformation Fetish', 'fetishes-interests', 'concept', true, true, true,
     'Sexual attraction to the idea of a body or identity being changed into something else.',
     'A transformation fetish centres on change itself — a body, gender, species or role becoming something different. It is overwhelmingly a fantasy and fiction interest, expressed in writing and art, and it covers a wide range from gradual bodily change to instantaneous transformation.'),
    ('cum-fetish', 'Cum Fetish', 'fetishes-interests', 'concept', true, true, true,
     'Sexual attraction focused on semen.',
     'A cum fetish is arousal focused on semen — its appearance, taste, or where it ends up. Semen transmits HIV and several other sexually transmitted infections, so the usual risk-reduction questions about testing, PrEP and barriers apply.'),
    ('wetlook', 'Wetlook', 'fetishes-interests', 'concept', true, true, true,
     'Sexual attraction to people in wet clothing.',
     'Wetlook is arousal from seeing people fully clothed while soaked — in a pool, shower, rain or sea. The clothing staying on is the point; the interest is distinct from wet-and-messy play, which uses substances other than water.'),
    ('agonophilia', 'Agonophilia', 'fetishes-interests', 'concept', true, true, true,
     'Sexual arousal from a partner pretending to struggle or resist.',
     'Agonophilia is arousal from simulated struggle or resistance. In practice it is a form of consensual non-consent, which depends completely on negotiation done in advance, an agreed safeword or signal that works when speech is restricted, and aftercare. Without those it is not this practice.'),
    ('bimbofication', 'Bimbofication', 'fetishes-interests', 'concept', true, true, true,
     'A transformation fantasy of becoming, or making someone, exaggeratedly feminine and hypersexual.',
     'Bimbofication is a transformation kink in which a person is imagined or roleplayed as becoming stereotypically hyperfeminine and hypersexual. It is most often a fantasy and aesthetic, and it is practised both as something done to a submissive partner and as a self-directed identity that some people embrace on their own terms.'),
    ('power-top', 'Power Top', 'bdsm-power-exchange', 'concept', true, true, true,
     'Someone who tops with particular energy, stamina or forcefulness.',
     'A power top is a partner who takes the penetrative role assertively and vigorously. The term describes intensity and style rather than a distinct role, and it is used mainly in gay male contexts.'),
    ('total-top', 'Total Top', 'bdsm-power-exchange', 'concept', true, true, true,
     'Someone who only ever takes the penetrative role.',
     'A total top exclusively tops and does not bottom. The term marks the absence of versatility rather than any judgement about it.'),
    ('total-bottom', 'Total Bottom', 'bdsm-power-exchange', 'concept', true, true, true,
     'Someone who only ever takes the receptive role.',
     'A total bottom exclusively bottoms and does not top. As with total top, it describes a fixed preference rather than a hierarchy.'),
    ('vers-top', 'Vers Top', 'bdsm-power-exchange', 'concept', true, true, true,
     'A versatile partner who prefers topping.',
     'Vers top describes someone comfortable in both roles who leans toward topping. The term exists because "versatile" alone says nothing about which way a person leans, which matters when people are matching.'),
    ('vers-bottom', 'Vers Bottom', 'bdsm-power-exchange', 'concept', true, true, true,
     'A versatile partner who prefers bottoming.',
     'Vers bottom describes someone comfortable in both roles who leans toward bottoming — the counterpart of vers top.'),
    ('muscle-bear', 'Muscle Bear', 'subcultures', 'concept', false, false, true,
     'A muscular, typically hairy man within bear subculture.',
     'Muscle bear describes a man in bear culture who is muscular as well as hairy and solidly built. Bear subculture has a dense vocabulary of body types — bear, cub, otter, wolf, chub — and muscle bear marks the intersection of bear aesthetics with a built physique.'),
    ('twink-chaser', 'Twink Chaser', 'subcultures', 'concept', false, false, true,
     'Someone, usually an older man, who is specifically attracted to twinks.',
     'A twink chaser is a person attracted specifically to twinks — young-looking, slim, typically smooth men. "Chaser" is used across gay subcultures for directed attraction to a body type, and it carries a mildly loaded edge depending on who is using it.'),
    ('cub-chaser', 'Cub Chaser', 'subcultures', 'concept', false, false, true,
     'Someone attracted specifically to cubs — younger or smaller men in bear subculture.',
     'A cub chaser is attracted to cubs, meaning younger or smaller bear-identified men. It parallels the other "-chaser" terms in bear and gay subcultural vocabulary.'),
    ('otter-chaser', 'Otter Chaser', 'subcultures', 'concept', false, false, true,
     'Someone attracted specifically to otters — slim, hairy men.',
     'An otter chaser is attracted to otters, meaning lean and hairy men, a body type that sits between twink and bear in the subculture''s vocabulary.'),
    ('silver-fox-chaser', 'Silver Fox Chaser', 'subcultures', 'concept', false, false, true,
     'Someone attracted specifically to attractive older, grey-haired men.',
     'A silver fox chaser is attracted to older men with grey or silver hair. It overlaps with daddy-directed attraction, with the emphasis on age and appearance rather than on a dominant role.'),
    ('muscle-chaser', 'Muscle Chaser', 'subcultures', 'concept', false, false, true,
     'Someone attracted specifically to heavily muscular partners.',
     'A muscle chaser is attracted to visibly built, muscular bodies. It overlaps with muscle worship, which is the practice rather than the preference.'),
    ('daddy-chaser', 'Daddy Chaser', 'subcultures', 'concept', true, true, true,
     'Someone attracted specifically to daddies — older or dominant, typically masculine partners.',
     'A daddy chaser is drawn to partners who present as daddies, which may mean older, larger, more established or more dominant depending on the community. Unlike silver fox, the term usually carries a suggestion of role as well as appearance.'),
    ('pantyboy', 'Pantyboy', 'expression-presentation', 'concept', true, true, true,
     'A man or masculine person who wears women''s underwear, often as part of kink or self-expression.',
     'Pantyboy describes a man or masculine-presenting person who wears panties, whether privately, as part of a feminisation dynamic, or simply because he likes them. It is a self-descriptor as often as it is a role assigned in play, and it says nothing on its own about the wearer''s gender or orientation.'),
    ('boywife', 'Boywife', 'expression-presentation', 'concept', false, false, true,
     'A feminine or submissive masculine partner occupying a wife-like role.',
     'Boywife is an internet-native term for a masculine-presenting person, often young and queer, who takes a domestic or feminine partner role. It is used mostly as affectionate self-description and plays on the mismatch between "boy" and "wife" rather than asserting a gender identity.'),
    ('side-piece', 'Side Piece', 'relationship-structures', 'concept', false, false, true,
     'A secondary partner outside someone''s primary relationship.',
     'Side piece refers to a person someone is involved with alongside a main relationship. In common use it usually implies the primary partner does not know, which distinguishes it from the negotiated secondary partners of consensual non-monogamy. The term is informal and often dismissive.'),
    ('thot', 'Thot', 'slang-terminology', 'concept', false, true, true,
     'A derogatory slang term for a promiscuous woman, sometimes reclaimed.',
     'Thot originated in African American Vernacular English as an acronym for "that ho over there" and spread widely through internet culture as an insult aimed mainly at women perceived as promiscuous. Like several such terms it has been partly reclaimed and used self-referentially, but it remains pejorative in most contexts.'),
    ('littlespace', 'Littlespace', 'bdsm-power-exchange', 'concept', false, true, true,
     'The headspace a person enters when regressing to a childlike state in age play.',
     'Littlespace is the mental state someone occupies while in a "little" role — relaxed, dependent and childlike. It is not always sexual: many people use it for comfort, stress relief or as part of a caregiver dynamic. Entering and leaving littlespace can be disorienting, which is why aftercare and a reliable way to signal distress matter, and why the caregiver role carries real responsibility.'),
    ('middlespace', 'Middlespace', 'bdsm-power-exchange', 'concept', false, true, true,
     'A regressed headspace pitched at an older age than littlespace, roughly adolescent.',
     'Middlespace is the counterpart to littlespace for people who regress to a "middle" role — broadly adolescent rather than young child. Middles often want more independence and negotiation within the dynamic than littles do, and the same aftercare and signalling considerations apply.'),
    ('muir-cap', 'Muir Cap', 'gear-aesthetics', 'concept', false, false, true,
     'The peaked leather cap that became the defining headwear of leather subculture.',
     'The Muir cap is a stiff peaked leather cap, originally a motorcycle style made by the Muir company, that became the signature headwear of gay leather culture from the 1950s onward. In some traditional leather settings its wearing is governed by protocol and earned rather than simply bought.'),
    ('funishment', 'Funishment', 'bdsm-power-exchange', 'concept', true, true, true,
     'A "punishment" both partners enjoy, given for fun rather than correction.',
     'Funishment is a play punishment given because both people want it, not because a rule was broken. Naming it separately matters in disciplinary dynamics: treating enjoyable play as real correction undermines actual punishment, and treating real correction as funishment can leave a submissive confused about what is being asked of them.'),
    ('over-the-knee-otk-spanking', 'Over-the-Knee (OTK) Spanking', 'practices-play', 'concept', true, true, true,
     'Spanking with the receiving partner draped across the giver''s lap.',
     'Over-the-knee spanking is the classic position for hand spanking, with the receiver across the giver''s lap. The position offers close physical contact and control, and it keeps the strikes to the safest area — the fleshy part of the buttocks, away from the tailbone, kidneys and lower spine.'),
    ('chastity-key-holding', 'Chastity Key Holding', 'bdsm-power-exchange', 'concept', true, true, true,
     'Holding the key to a partner''s chastity device, controlling their access to release.',
     'A key holder keeps the key to a locked chastity device, which makes them responsible for when the wearer is released. The role carries real duties: devices must be removable promptly in an emergency, prolonged wear risks skin damage and circulation problems, and remote or long-distance arrangements need an agreed contingency if the holder becomes unreachable.'),
    ('inspection-play', 'Inspection Play', 'practices-play', 'concept', true, true, true,
     'Roleplay in which one partner formally examines another''s body.',
     'Inspection play is a scene in which a dominant partner examines a submissive''s body in a structured, often ritualised way. It overlaps with medical play and with military or institutional roleplay, and its charge usually comes from exposure and scrutiny rather than from sensation.'),
    ('group-worship', 'Group Worship', 'practices-play', 'concept', true, true, true,
     'A scene in which several people direct adoration at one person.',
     'Group worship is a scene where multiple participants focus attention and adoration on a single person — a body part, the whole body, or the person''s dominance. It scales up body worship, and the added participants make negotiation and a clear scene lead more important, not less.'),
    ('non-sexual-kink', 'Non-Sexual Kink', 'kink-community', 'concept', false, true, true,
     'Kink practised without sexual contact or intent.',
     'A great deal of kink is not sexual. Rope, impact, service, protocol and age play are all practised by people who take satisfaction, focus or connection from them without any sexual element. Assuming kink is always sexual misreads what many practitioners are doing and can make negotiation harder.'),
    ('soft-kink', 'Soft Kink', 'kink-community', 'concept', false, true, true,
     'Lower-intensity kink, often an entry point for newcomers.',
     'Soft kink is an informal label for lower-intensity practices — light restraint, blindfolds, gentle impact, teasing. The boundary is subjective and shifts with experience; what counts as soft for one person is not a fixed category.'),
    ('power-neutral', 'Power Neutral', 'bdsm-power-exchange', 'concept', false, true, true,
     'Kink practised without any power exchange between participants.',
     'Power neutral describes play where no one is dominant or submissive — partners engage in sensation, rope or other activity as equals. It gives a name to a position that the dominant/submissive/switch vocabulary otherwise leaves out.'),
    ('cowification', 'Cowification', 'fetishes-interests', 'concept', true, true, true,
     'A transformation kink centred on being turned into, or treated as, a cow.',
     'Cowification is a transformation and objectification fantasy in which a person is treated as livestock, usually involving milking imagery, and often overlapping with lactation and pet-play interests. It is generally roleplay and aesthetic rather than physical transformation.'),
    ('dumbification', 'Dumbification', 'fetishes-interests', 'concept', true, true, true,
     'An erotic fantasy of intelligence or awareness being reduced.',
     'Dumbification is a kink in which a person is imagined or roleplayed as becoming less able to think clearly. It overlaps with bimbofication and with hypnosis and mind-control fantasies, and it is almost entirely a matter of framing and language rather than anything physical.'),
    ('forcefem', 'Forcefem', 'fetishes-interests', 'concept', true, true, true,
     'Consensual roleplay of being compelled into a feminine presentation.',
     'Forcefem, short for forced feminisation, is a kink in which a partner is roleplayed as being compelled to present femininely. The "force" is a fiction agreed in advance. Worth separating from gender identity: some people who enjoy it are exploring gender and some are not, and it is not evidence either way about a partner being trans.'),
    ('forcemasc', 'Forcemasc', 'fetishes-interests', 'concept', true, true, true,
     'Consensual roleplay of being compelled into a masculine presentation.',
     'Forcemasc is the counterpart of forcefem: roleplay in which a partner is treated as being made to present masculinely. As with forcefem, the compulsion is agreed fiction, and it should not be read as a statement about the person''s gender.'),
    ('forced-gagging', 'Forced Gagging', 'practices-play', 'concept', true, true, true,
     'Consensual play involving the gag reflex, usually during deep oral sex.',
     'Forced gagging is play that deliberately triggers the gag reflex. It carries real risks — vomiting and aspiration among them — so it needs a non-verbal safe signal agreed in advance, since a gagging person cannot speak, and it is unwise on a full stomach.'),
    ('hot-tub-folliculitis', 'Hot Tub Folliculitis', 'health', 'concept', false, false, true,
     'An itchy rash caused by Pseudomonas bacteria in inadequately treated hot tubs.',
     'Hot tub folliculitis is a skin infection of the hair follicles caused by Pseudomonas aeruginosa, which survives in warm water that is not properly chlorinated. It appears a day or two after exposure as an itchy bumpy rash, typically worst where a swimsuit held water against the skin. It usually clears on its own within a week or two; persistent or spreading cases, or illness alongside it, warrant medical advice. It is relevant to venues with pools and hot tubs, where water treatment is the control.'),
    ('porn-induced-erectile-dysfunction-pied', 'Porn-Induced Erectile Dysfunction (PIED)', 'sexual-health', 'concept', false, true, true,
     'A contested claim that heavy pornography use causes erectile difficulty with partners.',
     'PIED is the proposal that frequent pornography use can lead to difficulty achieving erection with a partner. It is widely discussed online but remains scientifically contested: the evidence base is limited and largely self-reported, and it is not an established diagnosis. Erectile difficulty has well-documented physical causes — cardiovascular disease and diabetes among them — that are worth excluding first, since erectile dysfunction is sometimes the earliest sign of a serious condition.'),
    ('testicular-health-and-care', 'Testicular Health and Care', 'health', 'concept', false, false, true,
     'Routine care and self-examination of the testicles.',
     'Testicular self-examination means becoming familiar with the normal size, weight and texture of your testicles so that changes are noticeable. Testicular cancer is most common in men between roughly 15 and 45 and is highly treatable when found early, so a new painless lump, swelling or a change in firmness should be checked promptly. Sudden severe pain is different: it can indicate testicular torsion, which is a medical emergency requiring immediate attention.'),
    ('small-penis-positivity', 'Small Penis Positivity', 'sexual-health', 'concept', false, true, true,
     'Affirming that penis size does not determine worth, desirability or sexual capability.',
     'Small penis positivity pushes back on the widespread assumption that size determines sexual value. Measured average erect length is around 13 centimetres, well below what pornography and cultural messaging imply, and anxiety about size is a common source of genuine distress. It stands in direct contrast to small penis humiliation, which is a consensual kink built on the same cultural material — the difference being that one is a chosen scene and the other is an everyday message people do not consent to.'),
    ('venereophobia', 'Venereophobia', 'mental-health', 'concept', false, true, true,
     'Persistent, disproportionate fear of contracting a sexually transmitted infection.',
     'Venereophobia is anxiety about sexually transmitted infections severe enough to cause distress or interfere with life — repeated testing despite negative results, avoidance of intimacy, or checking behaviours. It is treatable, and it is distinct from the ordinary caution that leads people to test regularly and use protection. Where the fear persists after negative results, it is anxiety that needs addressing rather than more testing.'),
    ('doxxing', 'Doxxing', 'physical-digital-safety', 'concept', false, false, true,
     'Publishing someone''s private identifying information without consent, usually to enable harassment.',
     'Doxxing is the release of private information — legal name, address, workplace, family details — with the effect or intent of exposing someone to harassment. For LGBTQ+ people it frequently means involuntary outing, and can put jobs, housing, immigration status and physical safety at risk, especially in places where being queer is criminalised. Anyone using a scene name or separate profile should assume linkage between identities is the thing worth protecting.'),
    ('awareness-team', 'Awareness Team', 'safety-consent', 'concept', false, false, true,
     'Designated people at an event responsible for handling consent violations and safety concerns.',
     'An awareness team is a clearly identified group at a party, club or festival whom attendees can approach about a consent violation, harassment or feeling unsafe. Having named people with the authority to act — rather than leaving it to whoever is nearby — is one of the practical markers of an event that takes consent seriously. The term is most established in European party and kink scenes.'),
    ('cuddle-party', 'Cuddle Party', 'events-scene', 'concept', false, false, true,
     'A structured, explicitly non-sexual event for consensual platonic touch.',
     'A cuddle party is a facilitated gathering for non-sexual affectionate touch, run to a set of ground rules: clothes stay on, every touch is asked for and can be refused, and a "no" needs no justification. The format was formalised in New York in 2004 and has since spread widely. The rules are the point — it functions as much as consent practice as it does as an event.'),
    ('nudist-gathering', 'Nudist Gathering', 'events-scene', 'concept', false, true, true,
     'An organised event where participants are nude, typically non-sexual.',
     'A nudist or naturist gathering is an event where being unclothed is the norm — at a beach, resort, club or organised meet. Established naturist settings are explicitly non-sexual and usually have firm rules about photography and staring. Legal status varies sharply by country and even by beach, so local rules are worth checking before travelling.'),
    ('key-party', 'Key Party', 'events-scene', 'concept', true, true, true,
     'A partner-swapping party where pairings are decided at random by drawing keys.',
     'At a key party, attendees place their keys in a bowl and each draws one at random to determine who they go home with. Strongly associated with 1970s suburban swinging in the United States, it appears more often now as a cultural reference than as a common practice. As with any group setting, the arrangement only works where everyone has genuinely agreed in advance.'),
    ('420-day', '420 Day', 'events-scene', 'concept', false, true, true,
     'An annual cannabis observance held on 20 April.',
     '420 Day is marked on 20 April as a cannabis counterculture observance, with public gatherings in many cities. The number traces to a group of California students in the early 1970s who used "420" as a meeting time, and it spread through Grateful Dead fan networks. Cannabis remains illegal in many jurisdictions, and travellers should not assume tolerance at an event implies legality.'),
    ('international-fetish-day', 'International Fetish Day', 'events-scene', 'concept', false, true, true,
     'An annual day supporting fetish and BDSM communities, held in January.',
     'International Fetish Day is observed on the third Friday of January. It grew out of a UK campaign against the Criminal Justice and Immigration Act 2008, which criminalised possession of "extreme pornography", and was originally marked by wearing something fetish-related in public as a visibility action — the "Perverts Wear Purple" campaign.'),
    ('story-of-o', 'Story of O', 'art-literature-zines', 'concept', true, true, true,
     'The 1954 French erotic novel by Anne Desclos, foundational to modern BDSM literature.',
     'Histoire d''O was published in 1954 under the pen name Pauline Réage; the author was later revealed to be Anne Desclos. It follows a woman''s progressive submission and is among the most influential works in BDSM literature, both for its imagery and for the debates it provoked about consent, agency and whether it reads as liberation or its opposite. It was written by a woman, which was itself contested for decades.'),
    ('fifty-shades-of-grey', 'Fifty Shades of Grey', 'media-film-music', 'concept', false, true, true,
     'The 2011 E. L. James novel that brought BDSM imagery into mainstream culture.',
     'Fifty Shades of Grey began as Twilight fan fiction and became one of the best-selling novels of its decade, followed by sequels and films. Its cultural effect is genuine — it brought kink into ordinary conversation and sold a great many restraints — but it is widely criticised within kink communities for depicting a relationship that ignores negotiation and consent, and for presenting controlling behaviour as romance.'),
    ('the-omegaverse', 'The Omegaverse', 'art-literature-zines', 'concept', true, true, true,
     'A fan-fiction genre built on an alpha/beta/omega social and biological hierarchy.',
     'The Omegaverse, or A/B/O, is a fan-fiction setting in which people belong to secondary sexes — alpha, beta or omega — with associated dynamics such as heats, ruts, scent bonding and mating. It began in Supernatural fandom around 2010 and spread widely, particularly in male/male romance. It has since become a commercial genre in its own right.'),
    ('dark-romance', 'Dark Romance', 'art-literature-zines', 'concept', true, true, true,
     'A romance genre featuring morally compromised protagonists and coercive or violent themes.',
     'Dark romance is a romance subgenre whose relationships involve captivity, coercion, revenge or violence, usually with a possessive antihero. Readers generally treat it as fantasy explicitly separated from real relationship standards, and the genre relies heavily on content warnings for that reason.'),
    ('asmr', 'ASMR', 'media-film-music', 'concept', false, false, true,
     'A tingling sensation on the scalp and neck triggered by certain sounds or attention.',
     'Autonomous Sensory Meridian Response describes a pleasant tingling that begins on the scalp and travels down the neck and spine, commonly triggered by whispering, tapping, close personal attention or careful repetitive sounds. It supports a very large body of video and audio content. Most people who seek it out describe it as relaxing rather than sexual, though a minority experience it erotically, and the two uses coexist.'),
    ('bagpiping', 'Bagpiping', 'practices-play', 'concept', true, true, true,
     'Slang for rubbing a penis in a partner''s armpit.',
     'Bagpiping is slang for using the armpit for penetrative-style stimulation, the name coming from the arm position it requires. It frequently overlaps with armpit fetishism.'),
    ('omnigender', 'Omnigender', 'gender-identity', 'concept', false, false, true,
     'A gender identity encompassing all genders rather than one.',
     'Omnigender describes someone whose gender includes every gender rather than sitting at one point. It differs from pangender mainly by community usage rather than by definition, and both are distinct from agender, which is the absence of gender. Whether the genders are experienced simultaneously or in turn varies by person.'),
    ('maverick', 'Maverick', 'gender-identity', 'concept', false, false, true,
     'A nonbinary gender defined on its own terms rather than by reference to the binary.',
     'Maverick is a nonbinary identity for people whose gender cannot be described as partly male, partly female, or in between, because it does not use the binary as a reference frame at all. It was coined within autistic nonbinary communities, where the vocabulary of masculine and feminine often fails to describe anything a person recognises.'),
    ('faggot', 'Faggot', 'sexual-orientation', 'concept', true, true, true,
     'A slur for a gay man, reclaimed by some as a self-descriptor and as a kink role.',
     'Faggot is an English slur for gay men with a long history of use in violence and harassment. Some gay and queer people reclaim it as a defiant self-description, and in kink it also names a submissive role built around that reclamation. Reclamation is first-person only: it belongs to the people it is used against, and it is not a word for anyone else to apply to them.'),
    ('best-friend', 'Best Friend', 'relationship-structures', 'concept', false, false, true,
     'The closest person in someone''s life who is not a romantic or sexual partner.',
     'A best friend is the person someone is closest to outside a romantic or sexual relationship. For many queer people the role carries weight a partner-centred model does not account for: best friends are often the people who provide housing, care, emergency contact and continuity, particularly where family of origin has withdrawn. Some relationship structures name the role explicitly rather than treating it as secondary by default.'),
    ('ddlg-kink-dynamic', 'DDlg Kink Dynamic', 'bdsm-power-exchange', 'concept', true, true, true,
     'A daddy-dom and little-girl age-play power dynamic between consenting adults.',
     'DDlg pairs a caregiver role with a regressed or little role, mixing authority, nurture and structure. It is a dynamic between adults; the little role is a headspace, not a claim about age, and the vocabulary describes the feel of the relationship rather than its participants. Practitioners distinguish it sharply from anything involving actual minors, and communities police that line hard.'),
    ('homance', 'Homance', 'relationship-structures', 'concept', false, false, true,
     'An intense non-romantic bond between men, close to romance in everything but sex.',
     'Homance describes a friendship between men carrying the intimacy, exclusivity and emotional intensity usually reserved for romance, without being sexual. Where the joke word bromance keeps a defensive distance, homance is often used more sincerely, including by queer men naming a bond that a romantic label would misdescribe.'),
    ('in-service-to', 'In Service To', 'bdsm-power-exchange', 'concept', false, false, true,
     'The standard phrasing for a submissive''s committed service relationship to a specific person.',
     'To be in service to someone is to hold an ongoing, negotiated obligation to meet their needs, whether domestic, protocol, sexual or a mix, within a specific relationship rather than as a general disposition. The phrasing is deliberate: it names the person served, which is why service-oriented submissives use it in place of a bare role label.'),
    ('ommer', 'Ommer', 'relationships-family', 'concept', false, false, true,
     'A gender-neutral word for a parent''s sibling, in place of aunt or uncle.',
     'Ommer is a gender-neutral kinship term for a parent''s sibling, adapted from Scandinavian usage into English by nonbinary people and their families. English has no neutral word in that slot, and ommer fills it alongside coinages like pibling, with nibling covering the reciprocal relation.'),
    ('step-sister', 'Step-Sister', 'bdsm-power-exchange', 'concept', true, true, true,
     'A role-play framing borrowed from a pornography genre, played between adults.',
     'Step-sister is a role-play scenario drawn from a pornography genre built on non-blood family framing. It is played between consenting adults and its appeal is the transgression of a taboo without any of the substance of one, since the participants are unrelated. The framing is fiction the whole way down, which is what distinguishes it from anything it superficially resembles.'),
    ('affini', 'Affini', 'subcultures', 'concept', false, false, true,
     'The plant-based alien species of the Human Domestication Guide setting.',
     'The Affini are a species of sapient plant-like aliens in the Human Domestication Guide, a shared science-fiction setting popular in transgender and kink fandom. They take human companions, called florets, into affectionate but total care. The setting is used to explore surrender, transformation and being kept, and its vocabulary has spread beyond the stories themselves.'),
    ('floret-flort', 'Floret / Flort', 'subcultures', 'concept', false, false, true,
     'A human companion of an Affini in the Human Domestication Guide setting; flort is the neutral form.',
     'A floret is a human taken as a companion by an Affini in the Human Domestication Guide setting, cared for completely and no longer responsible for themselves. Floret is the feminine form and flort the gender-neutral one. Outside the fiction people use the words for a real dynamic of total care and surrender, which is why they appear in kink vocabulary at all.'),
    ('bunnygirl', 'Bunnygirl', 'bdsm-power-exchange', 'concept', true, false, true,
     'A feminine pet-play identity built on rabbit characteristics.',
     'Bunnygirl is a pet-play persona drawing on rabbit imagery: skittish, soft, easily startled, often paired with ears and a tail. It sits in the same family as kittengirl and puppygirl, and the persona is a headspace rather than a costume, though gear usually supports it. In some usage it also borrows from the cocktail-lounge bunny aesthetic.'),
    ('courtesan', 'Courtesan', 'bdsm-power-exchange', 'concept', true, false, true,
     'Historically a companion to wealthy patrons; used in kink for a cultivated, service-oriented role.',
     'A courtesan was historically a companion to wealthy or noble patrons, offering conversation, culture and social presence as much as sex, and often holding standing and independence unusual for women of the period. In kink the word names a role built on that model: refinement, hospitality and attentive service rather than obedience, closer to a companion than to a servant.'),
    ('cuddler', 'Cuddler', 'bdsm-power-exchange', 'concept', false, false, true,
     'Someone who gives affectionate non-sexual physical closeness.',
     'A cuddler is the holding side of a cuddling dynamic: warmth, weight and steady contact offered without sex being the destination. Professional cuddling exists as a service, and within kink the role is often part of aftercare or a standalone need in its own right. Non-sexual touch still requires consent and negotiation.'),
    ('cunnilinguist', 'Cunnilinguist', 'bdsm-power-exchange', 'concept', true, false, true,
     'A punning self-label for someone skilled at and devoted to oral sex on a vulva.',
     'Cunnilinguist puns on linguist to name someone who considers oral sex on a vulva a practised craft rather than an incidental act. It is a self-applied label expressing both enthusiasm and a claim to competence, and it says nothing about the person''s role in a power dynamic.'),
    ('dogboy', 'Dogboy', 'bdsm-power-exchange', 'concept', true, false, true,
     'A masculine pet-play identity built on canine behaviour and headspace.',
     'Dogboy is a pet-play persona in which someone takes on canine behaviour, posture and mindset: loyalty, eagerness, non-verbal communication and a handler to answer to. It overlaps with pup play, which has its own gear culture and a substantial gay-leather history; dogboy is used both inside and outside that tradition. The headspace is the point, and gear supports it rather than defining it.'),
    ('doggirl', 'Doggirl', 'bdsm-power-exchange', 'concept', true, false, true,
     'A feminine pet-play identity built on canine behaviour and headspace.',
     'Doggirl is the feminine counterpart to dogboy: a pet-play persona built on canine behaviour, devotion and non-verbal communication, usually paired with a handler or owner. As with all pet play the persona is a headspace between consenting adults and gear supports it rather than constituting it.'),
    ('fairy-gay-mother', 'Fairy Gay Mother', 'kink-community', 'concept', false, false, true,
     'An older queer person who guides someone newly out through queer life.',
     'A fairy gay mother is the queer version of the fairy godmother: the older or more experienced person who takes someone newly out in hand and shows them how any of it works, from the bars to the vocabulary to the relationships. The role is a real fixture of queer community life, filling the gap left where families of origin do not, and the joke in the name does not make the mentorship less serious.'),
    ('femdom', 'Femdom', 'bdsm-power-exchange', 'concept', true, false, true,
     'Female domination: a woman or feminine person in the dominant role.',
     'Femdom is the standard shorthand for female dominance, covering both the practice and the identity. It names the direction of the power rather than a style, so it spans everything from strict protocol to sadism to sensual control. It carries its own long-standing commercial and community history, including professional domination, and overlaps with but is not the same as matriarchy or female-led relationships.'),
    ('fluffer', 'Fluffer', 'bdsm-power-exchange', 'concept', true, false, true,
     'Someone whose job on a porn set is keeping a performer aroused between takes.',
     'A fluffer is a crew role from pornography production: the person who keeps a performer erect and ready during the long gaps between shots. The job is less common than its reputation suggests, having largely been displaced by erectile medication and by performers managing it themselves. The word has since been borrowed into kink for the same function in a group scene, and more loosely for anyone who warms someone up for someone else.'),
    ('gear-fetishist', 'Gear Fetishist', 'fetishes-interests', 'concept', true, false, true,
     'Someone whose fetish is the equipment itself rather than an act.',
     'A gear fetishist is aroused by kit — leather, rubber, harnesses, uniforms, boots, sports and industrial equipment — as the object of the fetish rather than as a prop for something else. Gear cultures carry their own codes and events, and for many people the material is what the scene is about, not the acts done while wearing it.'),
    ('gentle-dom-me', 'Gentle Dom(me)', 'bdsm-power-exchange', 'concept', false, false, true,
     'A dominant whose authority is expressed through warmth rather than harshness.',
     'A gentle dominant holds real authority but exercises it through praise, patience and care rather than through severity, degradation or pain. The style is not softer in the sense of less controlling — the control is total and the tone is kind. It is often what people mean when they say they want to submit but not to be hurt.'),
    ('gentle-femdom', 'Gentle Femdom', 'bdsm-power-exchange', 'concept', true, false, true,
     'Female domination in a warm, praising register rather than a strict one.',
     'Gentle femdom combines female dominance with a nurturing style: encouragement and praise instead of humiliation, guidance instead of orders barked. It emerged partly as a corrective to a commercial image of femdom fixed on severity, and it is one of the more widely used style labels in the vocabulary.'),
    ('grizzly-bear', 'Grizzly Bear', 'subcultures', 'concept', false, false, true,
     'A large, notably hairy and often greying bear within gay bear culture.',
     'Grizzly bear is one of the many descriptors gay bear culture uses for body and hair type: bigger, hairier and often older or grey, at the more imposing end of the bear spectrum. The vocabulary is affectionate and self-applied, and the categories are loose rather than policed.'),
    ('hippie', 'Hippie', 'subcultures', 'concept', false, false, true,
     'A counterculture identity of communal living, free love and anti-authoritarianism.',
     'Hippie names the 1960s counterculture and its descendants: communal living, environmentalism, psychedelics, pacifism and a rejection of sexual convention that fed directly into later open-relationship and polyamory practice. Within kink and poly communities the label is still used for people whose approach to sex and relationships comes from that lineage rather than from BDSM tradition.'),
    ('latex-mistress', 'Latex Mistress', 'bdsm-power-exchange', 'concept', true, false, true,
     'A female dominant whose practice and presentation centre on latex.',
     'Latex mistress names a female dominant for whom rubber is central: her own presentation, the gear she puts a submissive into, or both. Latex carries its own aesthetic tradition in fetish photography and clubwear, and the material itself is often the fetish rather than a costume for something else. Latex garments need dressing aids and care, and latex allergy is common enough to ask about.'),
    ('leather-mistress', 'Leather Mistress', 'bdsm-power-exchange', 'concept', true, false, true,
     'A female dominant working within the leather tradition.',
     'Leather mistress names a female dominant located in leather culture specifically — a tradition with its own history, protocols, titles and lineage growing out of post-war motorcycle clubs and gay leather bars, later joined by women''s and pansexual leather communities. The label carries more than a material preference: it places someone within that tradition and its expectations of mentorship and earned standing.'),
    ('matriarch', 'Matriarch', 'bdsm-power-exchange', 'concept', false, false, true,
     'A woman who heads a family or household and holds authority over it.',
     'A matriarch is the female head of a family or household, holding authority over its structure and decisions. In kink and chosen-family contexts the word names a woman who leads a leather family, household or polycule, which makes it broader than a scene role: the authority is standing, ongoing and social rather than something switched on for play.'),
    ('merman', 'Merman', 'subcultures', 'concept', false, false, true,
     'The male counterpart of a mermaid; also a swimming and performance subculture.',
     'A merman is the male form of the mermaid, and beyond the folklore the word names a real subculture of people who swim in monofins and tails, perform, and build an identity around it. It carries particular resonance in queer communities, where the mermaid figure has long been claimed as an image of transformation and of a body remade to suit its element.'),
    ('minx', 'Minx', 'bdsm-power-exchange', 'concept', false, false, true,
     'A flirtatious, mischievous and knowingly provoking feminine role.',
     'Minx is an old English word for a bold, flirtatious woman, historically used to disapprove and now used mostly with affection. In kink it names a role built on teasing and mischief: provoking a partner for the pleasure of the response, close to bratting but lighter and more flirtatious than defiant.'),
    ('monsterfucker', 'Monsterfucker', 'fetishes-interests', 'concept', true, false, true,
     'Someone attracted to monsters and non-human creatures in fiction.',
     'Monsterfucker is a self-applied fandom label for people drawn to monsters, beasts and other non-human figures in fiction and art. It is a substantial current in fan writing and illustration, and it is generally worn with humour. The attraction is to the fictional creature and the strangeness it represents, which is what separates it from teratophilia framed as a clinical category.'),
    ('muva', 'Muva', 'bdsm-power-exchange', 'concept', false, false, true,
     'A stylised spelling of mother used as a title of admiration in ballroom and drag culture.',
     'Muva is a stylised form of mother drawn from Black queer ballroom and drag vernacular, where a house mother leads and protects a chosen family. Used as an address it is a compliment of the highest order, marking someone as the one others look up to. It has since spread far beyond ballroom, which is worth naming: the word carries a specific Black queer history with it.'),
    ('mxstress', 'Mxstress', 'bdsm-power-exchange', 'concept', false, false, true,
     'A gender-neutral honorific for a dominant, built from Mx and mistress.',
     'Mxstress adapts mistress using the gender-neutral honorific Mx, giving nonbinary dominants a title that fits. Honorifics matter in kink because they encode both the dynamic and the person''s gender, and the standard set offered only master and mistress; mxstress, along with forms like maestress and Sir used neutrally, fills the gap.'),
    ('papa-bear', 'Papa Bear', 'subcultures', 'concept', false, false, true,
     'An older, protective bear who takes a paternal role in the community.',
     'Papa bear names an older man in gay bear culture who takes a caring, paternal role toward younger men — mentorship and protection rather than authority. It sits alongside the daddy vocabulary but is warmer and less explicitly about dominance, and it belongs to bear culture''s particular affection for size, hair and age.'),
    ('priestex', 'Priestex', 'bdsm-power-exchange', 'concept', false, false, true,
     'A gender-neutral form of priest or priestess.',
     'Priestex applies the gender-neutral -ex ending, as in latinx, to priest and priestess, giving nonbinary people a term for a religious or ritual role. In kink it appears where ritual and devotional framing is used, and the coinage exists for the same reason mxstress does: the standard vocabulary offers only a gendered pair.'),
    ('sadistic-dom-me', 'Sadistic Dom(me)', 'bdsm-power-exchange', 'concept', true, true, true,
     'A dominant whose authority is expressed through inflicting pain.',
     'A sadistic dominant combines two things that are often confused and are not the same: dominance is about control, sadism is about pain. Someone who is both directs a submissive and takes pleasure in hurting them, which is a narrower proposition than either alone. The distinction matters in negotiation, because a submissive who wants to obey does not necessarily want to be hurt.'),
    ('service-dom-me', 'Service Dom(me)', 'bdsm-power-exchange', 'concept', false, false, true,
     'A dominant who directs a scene in order to give the submissive what they need.',
     'A service dominant holds the controlling role but orients the whole scene around the submissive''s desires: they decide, direct and take responsibility, and what they choose is what the bottom wants. It is not the same as topping from the bottom, where the submissive is actually steering. The distinction is who holds authority, not who benefits.'),
    ('soft-boy', 'Soft Boy', 'expression-presentation', 'concept', false, false, true,
     'A masculine presentation built on gentleness and emotional openness.',
     'Soft boy describes a way of being masculine that is gentle, sensitive and emotionally available rather than stoic or dominant. It began as internet vernacular, was for a while used sceptically of men who performed sensitivity without practising it, and has settled into a broadly sincere self-description — particularly among queer and trans men for whom the available models of masculinity did not fit.'),
    ('submissive-sadist', 'Submissive Sadist', 'bdsm-power-exchange', 'concept', true, true, true,
     'Someone who submits and who takes pleasure in inflicting pain.',
     'A submissive sadist holds two things usually assumed to belong on opposite sides: they yield control and they enjoy hurting. In practice that means inflicting pain at a dominant''s direction or on someone their dominant provides. It exists because dominance and sadism are separate axes, and the label makes a combination visible that the standard vocabulary hides.'),
    ('submissive-top', 'Submissive Top', 'bdsm-power-exchange', 'concept', true, false, true,
     'Someone who does the physical topping while holding the submissive role.',
     'A submissive top performs the acts — striking, tying, penetrating — while the authority stays with the other person. It is the mirror of the service dominant and the reason kink separates top and bottom from dominant and submissive at all: one pair describes who does what, the other who decides.'),
    ('teddy-bear', 'Teddy Bear', 'subcultures', 'concept', false, false, true,
     'A soft, cuddly and notably gentle bear within gay bear culture.',
     'Teddy bear is one of gay bear culture''s body-and-manner descriptors: hairy and heavy-set like other bears, but soft, warm and approachable rather than gruff. As with the rest of that vocabulary the categories are affectionate and self-applied, and the word is also used more generally for anyone comforting to be held by.'),
    ('themdom', 'Themdom', 'bdsm-power-exchange', 'concept', true, false, true,
     'Domination by a nonbinary person, on the model of femdom and maledom.',
     'Themdom names domination by someone who uses they/them pronouns, built on femdom and maledom by substituting the pronoun. It exists because the established pair encodes a binary that leaves nonbinary dominants unnamed, the same gap that produced mxstress. The word describes who holds the power, not the style in which it is held.'),
    ('voyeur', 'Voyeur', 'fetishes-interests', 'concept', true, false, true,
     'Someone who is aroused by watching others being sexual.',
     'A voyeur is aroused by watching rather than participating. In kink and at play parties this is a consensual arrangement: the people being watched know and have agreed, which is the entire difference between voyeurism as a practice and voyeurism as an offence. Watching people who have not consented is a crime in most jurisdictions and is not what the community means by the word.'),
    ('robot', 'Robot', 'bdsm-power-exchange', 'concept', true, false, true,
     'An objectification role in which someone is a programmed machine.',
     'Robot play recasts a person as a machine: obeying commands literally, moving mechanically, and being switched on, reprogrammed or shut down. It draws on the same appeal as hypnosis and mind-control play — the surrender of will rather than of body — and overlaps with the doll and android aesthetics in gear-heavy scenes. The person is a person throughout, which is what aftercare exists to re-establish.'),
    ('patriarch', 'Patriarch', 'bdsm-power-exchange', 'concept', false, false, true,
     'A man who heads a family or household and holds authority over it.',
     'A patriarch is the male head of a family or household. In leather families, kink households and chosen families the word names a man who leads the group — standing that is ongoing and social rather than a scene role. The term carries the weight of patriarchy as a system, which is part of why it is used deliberately in communities that reorganise family structures on their own terms.'),
    ('domestic-service-sub', 'Domestic Service Sub', 'bdsm-power-exchange', 'concept', false, false, true,
     'A submissive whose service is household work.',
     'A domestic service submissive expresses submission through running a household: cleaning, cooking, laundry and maintenance done to a standard set by the dominant. It is one of the most common forms of service and one of the least sexual in its content, which is exactly the appeal for many people who hold the role. Because the work is real labour, sustainable arrangements set out expectations and reciprocity explicitly.'),
    ('sir-boy', 'Sir / boy', 'bdsm-power-exchange', 'concept', true, false, true,
     'A leather dynamic pairing an authority figure with a devoted subordinate.',
     'Sir and boy is one of the oldest dynamics in gay leather culture: Sir holds authority, mentors and trains, while boy serves and learns. Boy is a title of standing rather than a statement of age, and it is earned; the capitalisation convention, Sir capitalised and boy not, is itself part of the protocol. The relationship is traditionally about lineage and mentorship as much as about service.'),
    ('ballooning', 'Ballooning', 'fetishes-interests', 'concept', true, false, true,
     'A fetish for balloons, whether intact, inflated or burst.',
     'Ballooning, or looning, is a fetish for balloons. Practitioners generally split into those who love inflating and handling them intact and those for whom the burst is the point, and the fear-versus-anticipation tension of an over-inflated balloon does much of the work. Latex allergy is the practical caveat.'),
    ('call-and-response', 'Call and Response', 'bdsm-power-exchange', 'concept', false, false, true,
     'A ritual verbal exchange where a fixed prompt gets a fixed reply.',
     'Call and response is a protocol device: the dominant says a set phrase and the submissive answers with a set reply, every time. It has deep roots in Black musical and worship traditions, and in kink it is used to mark the start of a scene, confirm a headspace or reinforce a dynamic through repetition. The value is in the fixity — the exchange is the same whatever the mood.'),
    ('cumflation', 'Cumflation', 'fetishes-interests', 'concept', true, false, true,
     'A fantasy kink of a belly visibly swelling with semen.',
     'Cumflation is a fantasy kink, mostly expressed in art and fiction, in which someone''s belly visibly distends from the volume of semen inside them. It belongs to the inflation family alongside belly and body inflation, and it is understood as impossible by the people who enjoy it: the appeal is the image of being filled beyond capacity, not a belief that it happens.'),
    ('ownership-kink', 'Ownership Kink', 'bdsm-power-exchange', 'concept', true, false, true,
     'Eroticising belonging to someone, or having someone belong to you.',
     'Ownership kink is arousal from the fact of possession itself rather than from any act it leads to: being owned, or owning. It underlies master and slave dynamics, collaring and total power exchange, and it is often marked with a collar, a contract or a title. Ownership in this sense is a negotiated relationship between adults with limits and an exit, however absolute the language is; no jurisdiction recognises a person as property, and communities treat any claim otherwise as abuse rather than as kink.'),
    ('sports-kink', 'Sports Kink', 'fetishes-interests', 'concept', true, false, true,
     'Eroticising athletics, sportswear, locker rooms and competition.',
     'Sports kink covers arousal around athletic contexts: kit and gear, jockstraps and singlets, locker rooms, coaching dynamics, sweat and competition. It has a long history in gay male culture in particular, where the locker room is one of the oldest scenarios in the repertoire, and it overlaps heavily with gear fetishism and with muscle worship.'),
    ('body-count', 'Body Count', 'slang-terminology', 'concept', true, false, true,
     'The number of people someone has had sex with.',
     'Body count is slang for how many sexual partners a person has had. The phrase circulates mostly as a way of judging people, women especially, and has become a fixture of online discourse about sexual history. Sex-positive and queer communities generally reject it as a measure of anything, and the number carries no health information — testing does.'),
    ('grool', 'Grool', 'slang-terminology', 'concept', true, false, true,
     'Slang for vaginal wetness, blending girl and drool.',
     'Grool is internet slang for vaginal lubrication, a portmanteau of girl and drool. It comes out of online erotica and fandom writing rather than clinical vocabulary, and it is used for the visible, copious kind. Wetness varies enormously between people and across a cycle and is not a reliable measure of arousal.'),
    ('hat-trick', 'Hat Trick', 'slang-terminology', 'concept', true, false, true,
     'Sex with three different people in a short span; borrowed from sport.',
     'A hat trick is three scores by one player in a single game, from cricket by way of hockey and football. Applied to sex it means three partners in quick succession, generally in a single night or event, and it is used with the same jokey competitiveness as the sporting original.'),
    ('helicockter', 'Helicockter', 'slang-terminology', 'concept', true, false, true,
     'Joke slang for swinging a penis in circles.',
     'Helicockter is a joke coinage for rotating the hips so the penis swings in a circle, named for the rotor it resembles. It belongs firmly to comedy rather than to technique, and appears in locker-room and party contexts rather than in sex.'),
    ('sexercise', 'Sexercise', 'slang-terminology', 'concept', false, false, true,
     'Sex framed as physical exercise, or exercise framed erotically.',
     'Sexercise blends sex and exercise, covering both the observation that sex is physical activity and the framing of workouts as erotic. Sex does burn calories, though considerably fewer than the popular claims suggest, and the word is mostly used lightly. It overlaps with sports kink where the gym setting is the appeal.'),
    ('trans-new-world-order-tnwo', 'Trans New World Order (TNWO)', 'slang-terminology', 'concept', false, true, true,
     'An ironic in-joke among trans people, inverting a conspiracy theory about them.',
     'Trans New World Order is an in-joke: trans people adopting the language of the conspiracy theories told about them, claiming a global agenda in mock-sinister terms precisely because the accusation is absurd. The humour is defensive, of a piece with the transgender agenda joke, and it is community vocabulary used from the inside. Read straight it is exactly the rhetoric it is mocking, which is why context matters.'),
    ('mmd-r18', 'MMD R18', 'art-literature-zines', 'concept', true, false, true,
     'Adult animation made with MikuMikuDance, a free Japanese 3D tool.',
     'MikuMikuDance is free Japanese software, originally released for Vocaloid music videos, that lets people animate 3D character models without a studio pipeline. R18 is the Japanese adults-only rating, so MMD R18 denotes the explicit body of work made with it. It is a substantial amateur genre with its own model and motion-sharing culture, and it sits alongside SFM as a form of adult animation made largely by hobbyists.'),
    ('mosh', 'Mosh', 'events-scene', 'concept', false, false, true,
     'Deliberate slam dancing in a crowd at a loud show.',
     'Moshing is the practice of slamming into other people in a pit at punk, hardcore and metal shows. It runs on a strong etiquette that outsiders miss: you pick people up when they fall, you do not swing at anyone outside the pit, and you get out if you are done. Queer and femme-organised pits have made a point of enforcing that etiquette rather than abandoning it. It appears in kink vocabulary as a reference point for consensual roughness in a crowd.'),
    ('boundary', 'Boundary', 'safety-consent', 'concept', false, false, true,
     'A limit someone sets on what they will do, accept or be part of.',
     'A boundary is a statement about what a person will and will not accept. It differs from a rule in a dynamic: a rule tells someone else what to do, a boundary describes what you will do in response. Boundaries can be physical, sexual, emotional or about time and attention, and they can change — but only by the person whose boundary it is. In kink this is the layer underneath negotiation, and someone repeatedly testing a boundary is a warning sign rather than a compatibility problem.'),
    ('flow-state', 'Flow State', 'mental-health', 'concept', false, false, true,
     'Complete absorption in an activity, where effort and self-awareness fall away.',
     'Flow is the psychological state, named by Mihaly Csikszentmihalyi, of being fully absorbed in something difficult enough to demand everything and matched closely enough to skill to be possible: time distorts and self-consciousness disappears. It is the frame often used for what a rope top or a bottom deep in a scene is experiencing, and it is related to but distinct from subspace, which involves an endorphin response as well.');

  -- Every category must resolve. A typo would otherwise create an uncategorized
  -- row, which tag_hygiene_stats counts and nothing else would explain.
  select count(*) into v_bad from _new n
   where not exists (select 1 from public.tag_categories c where c.slug = n.cat);
  if v_bad > 0 then
    raise exception 'new terms: % row(s) name a category that does not exist', v_bad;
  end if;

  -- Refuse to create anything that already exists under any status. A term that
  -- is merely deprecated needs REVIVING, not a duplicate concept alongside it.
  select count(*) into v_bad from _new n
   where exists (select 1 from public.unified_tags t where t.slug = n.slug);
  if v_bad > 0 then
    raise exception 'new terms: % slug(s) already exist — revive them instead of creating duplicates', v_bad;
  end if;

  for r in select * from _new order by slug loop
    insert into public.unified_tags (
      name, slug, description, long_description,
      category_id, category, entity_kind,
      is_adult, is_sensitive,
      status, seo_indexable, human_reviewed, verification_status
    )
    select r.name, r.slug, r.descr, r.longd,
           c.id, c.name, r.kind::tag_entity_kind,
           r.adult, r.sensitive,
           'active', false, false, 'unverified'
      from public.tag_categories c where c.slug = r.cat;
    v_made := v_made + 1;

    insert into public.tag_sources (tag_id, source_type, claim_summary, is_public)
    select t.id,
           case when r.sourced then 'editorial:general-knowledge'
                else 'editorial:inferred-from-name' end,
           case when r.sourced
                then 'Definition written from independently documented meaning. Not derived from the Kinktionary, whose licence is non-commercial.'
                else 'Term is attested only in the FetLife Kinktionary. This definition is INFERRED from the term name and its section, and is a reasoned guess pending review by someone who knows the vocabulary.'
           end,
           false
      from public.unified_tags t where t.slug = r.slug;
    v_src := v_src + 1;
  end loop;

  ------------------------------------------------------------------ assertions
  select count(*) into v_bad from _new n
   where not exists (select 1 from public.unified_tags t where t.slug = n.slug);
  if v_bad > 0 then
    raise exception 'new terms: % row(s) were not created', v_bad;
  end if;

  -- Not one of them may be publishable. This is the whole safety property.
  select count(*) into v_bad from _new n
    join public.unified_tags t on t.slug = n.slug
   where t.seo_indexable or coalesce(t.human_reviewed, false) or t.verification_status <> 'unverified';
  if v_bad > 0 then
    raise exception 'new terms: % row(s) are publishable — they must be created unreviewed and unindexed', v_bad;
  end if;

  -- Every row carries a provenance record saying where its prose came from.
  select count(*) into v_bad from _new n
    join public.unified_tags t on t.slug = n.slug
   where not exists (select 1 from public.tag_sources s
                      where s.tag_id = t.id and s.source_type like 'editorial:%');
  if v_bad > 0 then
    raise exception 'new terms: % row(s) have no provenance record', v_bad;
  end if;

  -- The CI zero-invariant, corpus-wide.
  select count(*) into v_bad from public.unified_tags
   where status = 'active' and seo_indexable
     and coalesce(nullif(btrim(description), ''), short_description) is null;
  if v_bad > 0 then
    raise exception 'new terms: % indexable row(s) corpus-wide have no description', v_bad;
  end if;

  raise notice 'new terms: % created, % provenance row(s)', v_made, v_src;
end
$mig$;
