-- ============================================================
-- trip_safety_briefings: cache for the AI narrative safety summary
-- generated by the trip-safety-narrative edge function. Keyed on
-- trip_id (one cached briefing per trip). Contents are regenerated
-- when stale (>7 days) or when the caller passes refresh=true.
-- ============================================================

CREATE TABLE public.trip_safety_briefings (
  trip_id UUID PRIMARY KEY REFERENCES public.trips(id) ON DELETE CASCADE,
  narrative TEXT NOT NULL,
  country_ids UUID[] NOT NULL DEFAULT '{}',
  article_count INTEGER NOT NULL DEFAULT 0,
  risk_level TEXT CHECK (risk_level IN ('low','moderate','high','critical')),
  generated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.trip_safety_briefings ENABLE ROW LEVEL SECURITY;

-- SELECT: trip owner, members, or anyone if trip is public
CREATE POLICY trip_safety_briefings_select ON public.trip_safety_briefings FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM public.trips t
    WHERE t.id = trip_safety_briefings.trip_id
      AND (
        t.is_public = true
        OR t.owner_id = (SELECT auth.uid())
        OR EXISTS (
          SELECT 1 FROM public.trip_members m
          WHERE m.trip_id = t.id AND m.user_id = (SELECT auth.uid())
        )
      )
  )
);

-- Writes are done by the edge function via service role, so no
-- INSERT/UPDATE policy is needed for end users. (RLS blocks client
-- writes by default.)
