-- Deindex the remaining 131 pages carrying verbatim Kinktionary text, closing
-- the measurement 20261007160100 could only take to 71%.
--
-- WHAT CHANGED SINCE THAT MIGRATION
--
-- 20261007160100 deindexed 304 pages and said so honestly: FetLife had started
-- answering 403 partway through the sweep, 429 of 1,487 tags came back
-- UNREACHABLE (alphabetically contiguous, `protecting`..`zucchini`), and 304 was
-- therefore stated as A FLOOR, NOT A TOTAL, with ~120 more predicted at the
-- observed rate.
--
-- The block was transient and specific to unauthenticated requests: a plain
-- curl still returns 403, but the logged-in browser profile the script uses
-- returns 200 with full content. Re-running with resume (measure only slugs
-- lacking a numeric result, merge the rest) completed the tail:
--
--   examined      1,487        unreachable  0
--   clean            1,017
--   8-19 words          35     (short enough to be coincidence)
--   20+ words          435     (not coincidence)
--   at the 60-word cap 103     (true run unknown, at least 60)
--
-- 435 total, 304 already deindexed, so 131 remain. The prediction was ~120.
--
-- THE SUMMARY LINE IN THE RESULT FILE IS WRONG AND IS NOT WHAT THIS USES.
-- `run_20_plus_and_indexable` reads 435 because the resumed rows carry the
-- `seo_indexable` value captured on the FIRST run, before 304 of them were
-- deindexed. A merged prior result is stale for every column except the one it
-- was kept for. The live count comes from the database, not the artifact.
--
-- WHY DEINDEX RATHER THAN DELETE — unchanged from 20261007160100. Direction of
-- copying is not something a word-run measurement can establish, so some of this
-- may be OUR text that the Kinktionary took. Deindexing is reversible, deletes
-- nothing, and is better than the status quo under either answer.
--
-- THIS LISTS ALL 435, NOT JUST THE 131. The migration is then idempotent and the
-- list matches the artifact it was generated from exactly, so re-running or
-- re-deriving it cannot drift. The 304 already at false are simply not updated.
--
-- LICENCE, restated as kinktionaryLicence.test.ts requires of every migration in
-- this program: the Kinktionary is NON-COMMERCIAL only and queer.guide is
-- commercial, so NOT ONE WORD OF THEIR PROSE IS COPIED OR ADAPTED here — only
-- their term list and section headings were ever used, as a signal for which of
-- OUR rows to examine. This migration writes no prose at all; it changes one
-- boolean. The overlapping text was copied by an EARLIER import, and this
-- reduces its exposure rather than adding any.
--
-- run_tag_thin_page_reindex will not undo this: its re-index half only restores
-- rows it deindexed for having no description, and it skips is_sensitive /
-- is_adult rows, which most of these are.
--
-- Slug list generated from out/kinktionary-prose-overlap.json, committed
-- alongside, so the selection is reproducible rather than asserted.

set local statement_timeout = '600s';

select set_config('app.actor', 'migration:kinktionary-overlap-deindex-complete', true);

do $mig$
declare
  r      record;
  v_bad  int;
  v_done int := 0;
begin
  create temp table _overlap (slug text primary key) on commit drop;
  insert into _overlap (slug) values
    ('8-panel-sti-test'),
    ('abrasion-play'),
    ('abseiling'),
    ('accomplice'),
    ('acrotomophillia'),
    ('adult-baby-diaper-lover-abdl'),
    ('aesthetic-fetishist'),
    ('agalmatophilia'),
    ('age-dreaming'),
    ('age-regressor'),
    ('ahegao'),
    ('alliteration'),
    ('alpha-slave'),
    ('alterous-attraction'),
    ('amatonormativity'),
    ('anal-angel'),
    ('anal-august'),
    ('anal-bate'),
    ('anal-master'),
    ('anal-only-d-s'),
    ('anal-princess'),
    ('anasyrma'),
    ('androx'),
    ('anguisette'),
    ('aphephilia'),
    ('aposexual'),
    ('ass-job'),
    ('ass-master'),
    ('asswhore'),
    ('attunement-play'),
    ('autofellatio'),
    ('bacchanalia'),
    ('backshot'),
    ('bacterial-vaginosis'),
    ('ball-kicking'),
    ('ball-stretching'),
    ('basorexic'),
    ('bdsm-oriented'),
    ('belly-play'),
    ('bellyriding'),
    ('berrisexual'),
    ('bi-friendly'),
    ('bi-situational'),
    ('bird'),
    ('biter'),
    ('book-daddy'),
    ('boot-blacking'),
    ('boot-kink'),
    ('boot-licking'),
    ('boot-worship'),
    ('boston-marriage'),
    ('bottom-bitch'),
    ('boyflux'),
    ('brat-king'),
    ('brat-queen'),
    ('bratty-bottom'),
    ('bratty-dom-bratty-domme'),
    ('bratty-princess'),
    ('bratty-sub'),
    ('bratty-top'),
    ('breeder'),
    ('bunfuck'),
    ('bussy'),
    ('cake-and-cunnilingus-day'),
    ('cake-sitting'),
    ('capitalization-in-kink'),
    ('captain'),
    ('cardiophilia'),
    ('cassexual'),
    ('catfish'),
    ('cenobite'),
    ('cervical-orgasm'),
    ('chaos-top'),
    ('cheirophilia'),
    ('circumsexual'),
    ('clit-and-pussy-torture-cpt'),
    ('clit-pumping'),
    ('cock-milking'),
    ('cock-slut'),
    ('cock-socket'),
    ('compersion'),
    ('consensual-non-consent-cnc'),
    ('core-bdsm'),
    ('cosbied'),
    ('coterie'),
    ('crossdresser-transvestite'),
    ('crucifixion-fetish'),
    ('crumbs'),
    ('crurophilia'),
    ('cuckette'),
    ('cuddle-top'),
    ('cum-eating'),
    ('cum-factory'),
    ('cum-on-command-coc'),
    ('cum-princess'),
    ('cumdrunk'),
    ('cunnilingus-slave'),
    ('cyborg'),
    ('dark-age-play'),
    ('defilement'),
    ('demdom'),
    ('demian'),
    ('demon-mommy'),
    ('destroy-dick-december'),
    ('devil'),
    ('devourer'),
    ('diaperfur'),
    ('dilf'),
    ('dining-at-the-y-daty'),
    ('doctor'),
    ('dom-me-tamer'),
    ('domestic-discipline-dd'),
    ('dominance-and-submission-d-s'),
    ('dominant-little'),
    ('dominant-sadist'),
    ('domspace'),
    ('doraphilia'),
    ('double-blowjob'),
    ('double-glazing'),
    ('duminant'),
    ('dungeon-master-dm'),
    ('ecosexual'),
    ('emotional-support-human-esh'),
    ('empath'),
    ('eudaimonist'),
    ('event-safety'),
    ('exit-strategy'),
    ('eye-fucking'),
    ('face-farting'),
    ('fallen-angel'),
    ('faunetflux'),
    ('febfem'),
    ('felching'),
    ('fembot'),
    ('feral-muse'),
    ('fetish'),
    ('fetish-party'),
    ('fictoromantic'),
    ('fictosexual'),
    ('fidget-toy'),
    ('findom-me'),
    ('fingering'),
    ('flirtationship'),
    ('florasexual'),
    ('fluffing'),
    ('foot-play'),
    ('foot-worship'),
    ('formicophilia'),
    ('forniphilia'),
    ('free-spirit'),
    ('fuckit-list'),
    ('futanari'),
    ('futch'),
    ('fweeb'),
    ('gags'),
    ('gainer'),
    ('gangbang-party'),
    ('gender-nullification'),
    ('gerontophilia'),
    ('girl-next-door'),
    ('girlboss'),
    ('girlflux'),
    ('glove-fetish'),
    ('gokkun'),
    ('golden-retriever'),
    ('gooning'),
    ('graygender'),
    ('grounding'),
    ('group-masturbation'),
    ('group-sex'),
    ('guard-dog'),
    ('guinea-pig'),
    ('guru'),
    ('gynx'),
    ('hairjob'),
    ('hand-feeding'),
    ('hard-dom-me'),
    ('hard-masochist'),
    ('harlot'),
    ('hellkitten'),
    ('hentai'),
    ('hermit'),
    ('hierophilia'),
    ('high-protocol'),
    ('hinge-partner'),
    ('hobosexual'),
    ('hole-dozer'),
    ('homiesexual'),
    ('honorifics'),
    ('horny-net-geek-hng'),
    ('hot-aunty'),
    ('housewife'),
    ('human-ashtray'),
    ('human-fleshlight'),
    ('humiliatrix'),
    ('hunter'),
    ('huntress'),
    ('hussy'),
    ('impact-partner'),
    ('inflatee'),
    ('inflation-kink'),
    ('inflator'),
    ('inner-thigh-spanking'),
    ('international-fisting-day'),
    ('intimate-partner-abuse'),
    ('it-s-complicated'),
    ('jester'),
    ('kink'),
    ('kink-dispenser'),
    ('kinktober'),
    ('kinky-fuckery'),
    ('kinkycule'),
    ('kitsune'),
    ('lap-pet'),
    ('latex-princess'),
    ('leather-fetish'),
    ('leather-gloves-fetish'),
    ('leather-lover'),
    ('leather-pet'),
    ('level-party'),
    ('lifestyle-kink'),
    ('lingam-massage'),
    ('little-bear'),
    ('locktober'),
    ('lone-wolf'),
    ('lovedrug'),
    ('lover-girl'),
    ('luna'),
    ('lycampire'),
    ('lycan'),
    ('mademoiselle'),
    ('malewife'),
    ('mama-bear'),
    ('mancunt'),
    ('mare-cunt'),
    ('masculinization'),
    ('masturbation-party'),
    ('meat'),
    ('meat-puppet'),
    ('menorrhagia-heavy-periods'),
    ('merosexual'),
    ('mommy-dom-me'),
    ('monsieur'),
    ('morosexual'),
    ('mullerian'),
    ('multitool'),
    ('muscle-mommy'),
    ('mushroom-stamp'),
    ('mx'),
    ('mysophilia'),
    ('nala'),
    ('nantaimori'),
    ('netorare-ntr'),
    ('neurodivergence'),
    ('ninromantic'),
    ('ninsexual'),
    ('nipple-torture'),
    ('nipplegasm'),
    ('no-nut-november'),
    ('odaxelagnia'),
    ('olfactophilia'),
    ('outdoor-sex'),
    ('padded'),
    ('pain-bringer'),
    ('pain-princess'),
    ('panther'),
    ('panther-girl'),
    ('paraboy'),
    ('partialism'),
    ('patient'),
    ('patron-saint'),
    ('pay-for-play'),
    ('peer-rope'),
    ('pelvic-organ-prolapse'),
    ('percussion-play'),
    ('personal-responsibility-informed-consensual-kink-prick'),
    ('pervertables'),
    ('pet-owner'),
    ('phallophilia'),
    ('pharaoh'),
    ('philosopher'),
    ('pillow-prince'),
    ('plapgasm'),
    ('platonic-crush'),
    ('play-party'),
    ('play-room'),
    ('play-styles'),
    ('playtoy'),
    ('pleasure-masochist'),
    ('pleasure-slave'),
    ('pleasure-switch'),
    ('plushie'),
    ('polyplatonic'),
    ('polysaturation'),
    ('pomosexual'),
    ('pony-play'),
    ('poop-desperation'),
    ('post-nut-clarity'),
    ('praise-kink'),
    ('primal-play'),
    ('primal-prey'),
    ('primal-princess'),
    ('proclivities-sexual'),
    ('prostate-milking'),
    ('psychological-masochist'),
    ('psychrocism'),
    ('public-reminder'),
    ('pussy-spanking'),
    ('queefing'),
    ('queer-femme'),
    ('queer-for-queer-q4q'),
    ('queerplatonic-partner'),
    ('rat'),
    ('rearrange-guts'),
    ('relationship-boundaries-desires-sex-meaning-aftercare-rbdsma'),
    ('research-slut'),
    ('risk-aware-virus-exposure-rave'),
    ('road-head'),
    ('role-reversal'),
    ('rope-coven'),
    ('rope-eel'),
    ('rope-jam'),
    ('rope-social'),
    ('rope-toy'),
    ('ropetober'),
    ('rule-34'),
    ('sacred-sexuality'),
    ('safe-sane-and-consensual-ssc'),
    ('safer'),
    ('salirophilia'),
    ('salmacian'),
    ('salon'),
    ('saturnian'),
    ('sea-queen'),
    ('self-harm'),
    ('self-spanker'),
    ('semen-retention'),
    ('sensation-slut'),
    ('sensual-bdsm'),
    ('sensual-dominant'),
    ('sensual-sadist'),
    ('sensual-submissive'),
    ('sensual-switch'),
    ('service-daddy'),
    ('service-rigger'),
    ('sex-favorable'),
    ('sex-geek'),
    ('sex-party'),
    ('sex-positive'),
    ('sexuationship'),
    ('shallowing'),
    ('shemale'),
    ('skoliosexual-ceterosexual'),
    ('slutface'),
    ('slutty-princess'),
    ('small-penis-humiliation-sph'),
    ('smegma-fetish'),
    ('smoothie'),
    ('snack'),
    ('snugglefuck'),
    ('social-swinger'),
    ('sock-puppet'),
    ('soft-dom-me'),
    ('soft-limits'),
    ('sologamous'),
    ('solosexual'),
    ('soundtrix'),
    ('spaghetti-straight'),
    ('spectrophilia-phasmophilia'),
    ('spitting'),
    ('split-attraction-model-sam'),
    ('spotter'),
    ('spucking'),
    ('squat-cobbler'),
    ('st4t'),
    ('steak-and-a-blowjob-day'),
    ('step-brother'),
    ('stigmatophilia'),
    ('strap-on-domme'),
    ('stretch-marks-fetish'),
    ('subby-buddy'),
    ('submissive-mommy'),
    ('superhero'),
    ('supplicant'),
    ('swimsuit-fetish'),
    ('swingers-party'),
    ('switchtress'),
    ('sword-play'),
    ('taskmaster'),
    ('teacher-s-pet'),
    ('tease-and-denial'),
    ('tempter-temptress'),
    ('the-hanky-code'),
    ('throat-slayer'),
    ('tickle-toy'),
    ('timophilia'),
    ('tongue-fucking'),
    ('tongue-sucking'),
    ('toric'),
    ('transage'),
    ('transamorous'),
    ('transine'),
    ('tribbing'),
    ('trichophilia'),
    ('trixic'),
    ('unconference'),
    ('under-consideration'),
    ('uranic'),
    ('urethral-fuck'),
    ('ussy'),
    ('vaginal-atrophy'),
    ('vaginismus'),
    ('vajazzle'),
    ('vampire-dom'),
    ('vampire-sub'),
    ('vassal'),
    ('versandrogyne'),
    ('victorian-pornography'),
    ('vivisector'),
    ('voidboy'),
    ('voidgirl'),
    ('vorarephilia'),
    ('vulturing'),
    ('warlock'),
    ('warrior-princess'),
    ('water-bondage'),
    ('wet-and-messy-wam'),
    ('wet-walk'),
    ('whump'),
    ('widow-er'),
    ('world-bdsm-day'),
    ('xylophilia'),
    ('yandere'),
    ('zentai'),
    ('zucchini');

  for r in select o.slug, t.id from _overlap o
             join public.unified_tags t on t.slug = o.slug
            where t.seo_indexable loop
    update public.unified_tags
       set seo_indexable = false, updated_at = now()
     where id = r.id;
    v_done := v_done + 1;
  end loop;

  ------------------------------------------------------------------ assertions
  -- Absolute floor, so an empty set fails instead of passing silently.
  if (select count(*) from _overlap) < 400 then
    raise exception 'overlap deindex: only % slug(s) listed; expected 435', (select count(*) from _overlap);
  end if;

  select count(*) into v_bad from _overlap o
    join public.unified_tags t on t.slug = o.slug
   where t.seo_indexable;
  if v_bad > 0 then
    raise exception 'overlap deindex: % row(s) are still indexable', v_bad;
  end if;

  -- Visibility only. If a description went missing here, something else ran.
  select count(*) into v_bad from _overlap o
    join public.unified_tags t on t.slug = o.slug
   where coalesce(nullif(btrim(t.description), ''), t.short_description) is null;
  if v_bad > 0 then
    raise exception 'overlap deindex: % row(s) lost their description', v_bad;
  end if;

  raise notice 'overlap deindex: % newly deindexed of % listed', v_done, (select count(*) from _overlap);
end
$mig$;
