-- ============================================================================
-- INCIDENT REPAIR (step 2/2): give the surviving queues their msg_id back
-- ----------------------------------------------------------------------------
-- Step 1 (20260727153051) restored the pgmq extension. The three queues P3b
-- kept still cannot be used, because the same CASCADE also dropped the
-- extension-owned `msg_id` identity column from each q_* table:
--
--   q_pipeline_steps / q_dead_letter / q_enrichment_queue
--     -> read_ct, enqueued_at, vt, message, headers        (msg_id GONE)
--   a_* archive tables are intact (msg_id + pkey present).
--
-- Without msg_id, pgmq.read()/archive()/delete() cannot address a message, so
-- pipeline-executor's enqueueStep -> pgmq_send -> advance loop is dead.
--
-- This repair is deliberately ADDITIVE: no table is renamed, recreated or
-- dropped, and no row is moved. The alternative (rebuild via pgmq.create() and
-- copy 113k archived rows back) touches in-flight messages for no extra
-- benefit. Consequence: the q_* tables stay non-members of the extension —
-- the pre-existing "detached tables" state that made drop_queue fail in the
-- first place. That trap is now documented in the P3b migration and in
-- pipeline_hygiene_stats' comment rather than being silently re-armed.
--
-- msg_id assignment: existing rows are numbered ABOVE the archive high-water
-- mark, and the identity sequence starts above that again. A live id can
-- therefore never collide with an already-archived id (a_* has a PK on
-- msg_id, so a collision would break archiving later, not now).
-- ============================================================================

DO $$
DECLARE
  v_q       text;
  v_qtab    text;
  v_atab    text;
  v_base    bigint;
  v_next    bigint;
BEGIN
  FOREACH v_q IN ARRAY ARRAY['pipeline_steps', 'dead_letter', 'enrichment_queue']
  LOOP
    v_qtab := 'q_' || v_q;
    v_atab := 'a_' || v_q;

    CONTINUE WHEN NOT EXISTS (
      SELECT 1 FROM information_schema.tables
      WHERE table_schema = 'pgmq' AND table_name = v_qtab
    );

    -- Already healthy (e.g. partial re-run): skip.
    CONTINUE WHEN EXISTS (
      SELECT 1 FROM information_schema.columns
      WHERE table_schema = 'pgmq' AND table_name = v_qtab AND column_name = 'msg_id'
    );

    EXECUTE format('SELECT COALESCE(max(msg_id), 0) FROM pgmq.%I', v_atab) INTO v_base;

    EXECUTE format('ALTER TABLE pgmq.%I ADD COLUMN msg_id bigint', v_qtab);

    -- ctid is a safe row handle here: the table has no primary key yet.
    EXECUTE format($f$
      UPDATE pgmq.%I q
         SET msg_id = %s + s.rn
        FROM (SELECT ctid AS cid, row_number() OVER (ORDER BY enqueued_at) AS rn
                FROM pgmq.%I) s
       WHERE q.ctid = s.cid
    $f$, v_qtab, v_base, v_qtab);

    EXECUTE format('ALTER TABLE pgmq.%I ALTER COLUMN msg_id SET NOT NULL', v_qtab);
    EXECUTE format('ALTER TABLE pgmq.%I ADD CONSTRAINT %I PRIMARY KEY (msg_id)',
                   v_qtab, v_qtab || '_pkey');

    EXECUTE format('SELECT COALESCE(max(msg_id), %s) + 1 FROM pgmq.%I', v_base, v_qtab)
      INTO v_next;
    EXECUTE format(
      'ALTER TABLE pgmq.%I ALTER COLUMN msg_id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH %s)',
      v_qtab, v_next);
  END LOOP;
END $$;

-- pgmq.meta lost its rows with the extension. list_queues()/metrics() and the
-- admin Health tab read it; send/read/archive do not, so this is bookkeeping.
INSERT INTO pgmq.meta (queue_name, is_partitioned, is_unlogged, created_at)
VALUES ('pipeline_steps', false, false, now()),
       ('dead_letter', false, false, now()),
       ('enrichment_queue', false, false, now())
ON CONFLICT (queue_name) DO NOTHING;

-- pgmq 1.5.1's read() signature is (queue, vt, qty, conditional jsonb). The
-- 3-arg call the wrapper inherited from 1.4.x raises
-- "function pgmq.read(text, integer, integer) does not exist".
CREATE OR REPLACE FUNCTION "public"."pgmq_read"("p_queue" "text", "p_vt" integer, "p_qty" integer)
RETURNS TABLE("msg_id" bigint, "read_ct" integer, "enqueued_at" timestamp with time zone,
              "vt" timestamp with time zone, "message" "jsonb")
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
BEGIN
  IF p_queue NOT IN ('dead_letter','enrichment_queue','pipeline_steps') THEN
    RAISE EXCEPTION 'Invalid queue name: % (workflow queues were retired in P3)', p_queue;
  END IF;
  RETURN QUERY
    SELECT r.msg_id, r.read_ct, r.enqueued_at, r.vt, r.message
    FROM pgmq.read(p_queue, p_vt, p_qty, '{}'::jsonb) r;
END; $$;
