-- ============================================================
-- trip_recaps: post-trip Memory-phase auto-generated recap.
-- One row per trip (PK = trip_id). Generated by the `trip-recap` edge
-- function after end_date passes; rewritable when user requests a
-- refresh (e.g., after uploading photos or adding notes).
--
-- `summary`    — short narrative paragraph (2–4 sentences)
-- `highlights` — structured JSON: top places, favourite day, stats
-- `generated_at` lets the client show a "Regenerate" affordance when
-- the underlying trip has been modified since last recap.
-- ============================================================

CREATE TABLE public.trip_recaps (
  trip_id UUID PRIMARY KEY REFERENCES public.trips(id) ON DELETE CASCADE,
  summary TEXT NOT NULL,
  highlights JSONB NOT NULL DEFAULT '{}'::jsonb,
  generated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  generated_by UUID REFERENCES auth.users(id) ON DELETE SET NULL
);

ALTER TABLE public.trip_recaps ENABLE ROW LEVEL SECURITY;

-- Trip members (any role) or anonymous viewers of public trips can read.
CREATE POLICY trip_recaps_select ON public.trip_recaps FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM public.trips t
    WHERE t.id = trip_recaps.trip_id
      AND (
        t.is_public = true
        OR t.owner_id = (SELECT auth.uid())
        OR EXISTS (
          SELECT 1 FROM public.trip_members m
          WHERE m.trip_id = t.id AND m.user_id = (SELECT auth.uid())
        )
      )
  )
);

-- Only owner/editor can upsert (edge function uses service role so this
-- gate is for client-side safety; in practice inserts flow through the fn).
CREATE POLICY trip_recaps_upsert ON public.trip_recaps FOR INSERT WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.trips t
    WHERE t.id = trip_recaps.trip_id
      AND (t.owner_id = (SELECT auth.uid())
           OR EXISTS (
             SELECT 1 FROM public.trip_members m
             WHERE m.trip_id = t.id AND m.user_id = (SELECT auth.uid())
                   AND m.role IN ('owner','editor')
           ))
  )
);

CREATE POLICY trip_recaps_update ON public.trip_recaps FOR UPDATE USING (
  EXISTS (
    SELECT 1 FROM public.trips t
    WHERE t.id = trip_recaps.trip_id
      AND (t.owner_id = (SELECT auth.uid())
           OR EXISTS (
             SELECT 1 FROM public.trip_members m
             WHERE m.trip_id = t.id AND m.user_id = (SELECT auth.uid())
                   AND m.role IN ('owner','editor')
           ))
  )
);
