-- Phase 2: SECURITY DEFINER hardening + unused indexes + n8n/umami FK indexes.
--
-- Skipped: most SECURITY DEFINER public RPCs (intentional public reads that
-- need DEFINER to bypass RLS on inner joins). Per-function INVOKER review
-- is the right way to clear those — too risky to bulk-flip.

------------------------------------------------------------
-- 1. SECURITY DEFINER: revoke EXECUTE from anon/authenticated
--    on admin/maintenance functions; revoke from anon on
--    user-data RPCs.
------------------------------------------------------------

-- Admin/maintenance: refresh matviews + diagnostic listings.
-- Only service_role / dashboard should call these.
REVOKE EXECUTE ON FUNCTION public.event_guides_refresh_pick_count()  FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.venue_guides_refresh_pick_count()  FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.get_broken_marketplace_ids()       FROM anon, authenticated;

-- User-scoped data: take a user_id and read that user's records.
-- No anonymous use case — require sign-in.
REVOKE EXECUTE ON FUNCTION public.news_reading_streak(uuid)                FROM anon;
REVOKE EXECUTE ON FUNCTION public.venue_guide_reading_streak(uuid)         FROM anon;
REVOKE EXECUTE ON FUNCTION public.marketplace_guide_reading_streak(uuid)   FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_personalized_marketplace_listings(uuid, integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.user_local_supporter_cities(uuid)        FROM anon;
REVOKE EXECUTE ON FUNCTION public.footprint_public_stats(uuid)             FROM anon;
REVOKE EXECUTE ON FUNCTION public.local_supporter_score(uuid, uuid)        FROM anon;

------------------------------------------------------------
-- 2. n8n / umami foreign key indexes (third-party schemas).
------------------------------------------------------------
CREATE INDEX IF NOT EXISTS executions_workflow_id_idx          ON n8n.executions (workflow_id);
CREATE INDEX IF NOT EXISTS workflow_statistics_workflow_id_idx ON n8n.workflow_statistics (workflow_id);
CREATE INDEX IF NOT EXISTS workflow_tags_tag_id_idx            ON n8n.workflow_tags (tag_id);
CREATE INDEX IF NOT EXISTS session_website_id_idx              ON umami.session (website_id);
CREATE INDEX IF NOT EXISTS website_user_id_idx                 ON umami.website (user_id);
CREATE INDEX IF NOT EXISTS website_event_session_id_idx        ON umami.website_event (session_id);
CREATE INDEX IF NOT EXISTS website_event_website_id_idx        ON umami.website_event (website_id);

------------------------------------------------------------
-- 3. Drop 342 unused indexes. The 12 FK-covering indexes added
--    in 20260527100000_supabase_linter_cleanup.sql are kept —
--    they fix the higher-priority unindexed_foreign_keys lint
--    even though pg_stat_user_indexes hasn't seen them used yet.
------------------------------------------------------------
DROP INDEX IF EXISTS public.idx_admin_automation_runs_automation_id;
DROP INDEX IF EXISTS public.idx_event_attendees_user_id;
DROP INDEX IF EXISTS public.idx_events_festival_id;
DROP INDEX IF EXISTS public.idx_feedback_retest_runs_routine_run_id;
DROP INDEX IF EXISTS public.idx_feedback_votes_user_id;
DROP INDEX IF EXISTS public.idx_hotels_country_id;
DROP INDEX IF EXISTS public.idx_marketplace_reviews_user_id;
DROP INDEX IF EXISTS public.idx_message_reactions_user_id;
DROP INDEX IF EXISTS public.idx_pipeline_health_alerts_escalated_submission_id;
DROP INDEX IF EXISTS public.idx_topic_cluster_tags_tag_id;
DROP INDEX IF EXISTS public.idx_topic_clusters_parent_cluster_id;
DROP INDEX IF EXISTS public.idx_trip_collection_items_trip_id;
DROP INDEX IF EXISTS public.idx_trip_places_reservation_id;
DROP INDEX IF EXISTS public.idx_user_place_marks_trip_id;
DROP INDEX IF EXISTS public.idx_venue_reviews_user_id;
DROP INDEX IF EXISTS public.idx_wishlist_items_listing_id;
DROP INDEX IF EXISTS public.news_stories_country_gin_idx;
DROP INDEX IF EXISTS public.news_articles_is_premium_idx;
DROP INDEX IF EXISTS public.trips_staff_pick_public_idx;
DROP INDEX IF EXISTS public.news_stories_embedding_idx;
DROP INDEX IF EXISTS public.marketplace_guides_status_idx;
DROP INDEX IF EXISTS public.marketplace_guides_city_idx;
DROP INDEX IF EXISTS public.marketplace_guides_category_idx;
DROP INDEX IF EXISTS public.marketplace_guides_audience_tags_idx;
DROP INDEX IF EXISTS public.marketplace_guides_review_due_idx;
DROP INDEX IF EXISTS public.trips_vibe_tags_gin;
DROP INDEX IF EXISTS public.intimate_profiles_opted_in_idx;
DROP INDEX IF EXISTS public.intimate_profiles_city_idx;
DROP INDEX IF EXISTS public.intimate_profiles_role_idx;
DROP INDEX IF EXISTS public.intimate_profiles_into_idx;
DROP INDEX IF EXISTS public.intimate_reports_status_idx;
DROP INDEX IF EXISTS public.idx_alert_integrations_created_by;
DROP INDEX IF EXISTS public.idx_admin_api_keys_created_by;
DROP INDEX IF EXISTS public.idx_admin_automations_created_by;
DROP INDEX IF EXISTS public.idx_admin_edit_log_editor_id;
DROP INDEX IF EXISTS public.idx_ai_suggestions_reviewer_id;
DROP INDEX IF EXISTS public.idx_audio_files_created_by;
DROP INDEX IF EXISTS public.idx_audio_processing_jobs_audio_id;
DROP INDEX IF EXISTS public.idx_audio_renditions_audio_id;
DROP INDEX IF EXISTS public.idx_automation_modules_workflow_definition_id;
DROP INDEX IF EXISTS public.idx_automation_run_log_module_id;
DROP INDEX IF EXISTS public.idx_automation_run_log_workflow_run_id;
DROP INDEX IF EXISTS public.idx_captcha_verifications_user_id;
DROP INDEX IF EXISTS public.idx_cms_audit_log_actor_id;
DROP INDEX IF EXISTS public.idx_cms_content_deleted_by;
DROP INDEX IF EXISTS public.idx_cms_audit_log_content_id;
DROP INDEX IF EXISTS public.idx_cms_content_created_by;
DROP INDEX IF EXISTS public.idx_cms_content_published_by;
DROP INDEX IF EXISTS public.idx_cms_content_updated_by;
DROP INDEX IF EXISTS public.idx_cms_content_media_media_id;
DROP INDEX IF EXISTS public.idx_cms_content_metadata_last_edited_by;
DROP INDEX IF EXISTS public.idx_cms_content_metadata_locked_by;
DROP INDEX IF EXISTS public.idx_cms_content_metadata_published_by;
DROP INDEX IF EXISTS public.idx_cms_content_relationships_created_by;
DROP INDEX IF EXISTS public.idx_cms_content_relationships_to_content_id;
DROP INDEX IF EXISTS public.idx_cms_content_revisions_created_by;
DROP INDEX IF EXISTS public.idx_cms_duplicate_candidates_content_id_2;
DROP INDEX IF EXISTS public.idx_cms_duplicate_candidates_reviewed_by;
DROP INDEX IF EXISTS public.idx_cms_media_uploaded_by;
DROP INDEX IF EXISTS public.idx_cms_media_attachments_created_by;
DROP INDEX IF EXISTS public.idx_cms_media_attachments_media_id;
DROP INDEX IF EXISTS public.idx_cms_pages_author_id;
DROP INDEX IF EXISTS public.idx_cms_pages_created_by;
DROP INDEX IF EXISTS public.idx_cms_pages_published_by;
DROP INDEX IF EXISTS public.idx_cms_pages_updated_by;
DROP INDEX IF EXISTS public.idx_cms_review_comments_created_by;
DROP INDEX IF EXISTS public.idx_cms_review_comments_parent_comment_id;
DROP INDEX IF EXISTS public.idx_cms_review_comments_resolved_by;
DROP INDEX IF EXISTS public.idx_cms_review_comments_revision_id;
DROP INDEX IF EXISTS public.idx_cms_review_queue_assigned_to;
DROP INDEX IF EXISTS public.idx_cms_review_queue_resolved_by;
DROP INDEX IF EXISTS public.idx_cms_revisions_created_by;
DROP INDEX IF EXISTS public.idx_cms_scheduled_publish_created_by;
DROP INDEX IF EXISTS public.idx_cms_sync_jobs_connector_id;
DROP INDEX IF EXISTS public.idx_comment_likes_user_id;
DROP INDEX IF EXISTS public.idx_community_posts_user_id;
DROP INDEX IF EXISTS public.idx_community_submissions_assignee_id;
DROP INDEX IF EXISTS public.idx_content_changes_workflow_run_id;
DROP INDEX IF EXISTS public.idx_community_submissions_duplicate_of;
DROP INDEX IF EXISTS public.idx_community_submissions_flyer_scan_id;
DROP INDEX IF EXISTS public.idx_community_submissions_reviewed_by;
DROP INDEX IF EXISTS public.idx_community_submissions_audit_actor_id;
DROP INDEX IF EXISTS public.idx_content_changes_reviewed_by;
DROP INDEX IF EXISTS public.idx_content_flags_reviewed_by;
DROP INDEX IF EXISTS public.idx_content_metadata_last_edited_by;
DROP INDEX IF EXISTS public.idx_content_metadata_locked_by;
DROP INDEX IF EXISTS public.idx_content_metadata_published_by;
DROP INDEX IF EXISTS public.idx_content_threads_created_by;
DROP INDEX IF EXISTS public.idx_content_threads_parent_comment_id;
DROP INDEX IF EXISTS public.idx_content_threads_resolved_by;
DROP INDEX IF EXISTS public.idx_content_translations_translated_by;
DROP INDEX IF EXISTS public.idx_contributor_recognitions_created_by;
DROP INDEX IF EXISTS public.idx_conversation_participants_user_id;
DROP INDEX IF EXISTS public.idx_conversations_last_message_id;
DROP INDEX IF EXISTS public.idx_data_ops_alerts_acked_by;
DROP INDEX IF EXISTS public.idx_dedup_decisions_feedback_candidate_venue_id;
DROP INDEX IF EXISTS public.idx_dedup_decisions_feedback_decided_by;
DROP INDEX IF EXISTS public.idx_dedup_decisions_feedback_staging_id;
DROP INDEX IF EXISTS public.idx_donations_user_id;
DROP INDEX IF EXISTS public.idx_editorial_drafts_reviewer_id;
DROP INDEX IF EXISTS public.idx_editorial_rails_cluster_id;
DROP INDEX IF EXISTS public.idx_email_templates_created_by;
DROP INDEX IF EXISTS public.idx_email_templates_updated_by;
DROP INDEX IF EXISTS public.idx_enrichment_audit_pipeline_run_id;
DROP INDEX IF EXISTS public.idx_feedback_stories_approved_by;
DROP INDEX IF EXISTS public.idx_feedback_stories_archived_by;
DROP INDEX IF EXISTS public.idx_entity_link_review_article_id;
DROP INDEX IF EXISTS public.idx_entity_link_review_resolved_by;
DROP INDEX IF EXISTS public.idx_event_sources_event_id;
DROP INDEX IF EXISTS public.idx_events_venue_id;
DROP INDEX IF EXISTS public.idx_feedback_reviewed_by;
DROP INDEX IF EXISTS public.idx_feedback_submitted_by;
DROP INDEX IF EXISTS public.idx_feedback_duplicate_suggestions_dismissed_by;
DROP INDEX IF EXISTS public.idx_feedback_retest_runs_created_by;
DROP INDEX IF EXISTS public.idx_feedback_routine_runs_created_by;
DROP INDEX IF EXISTS public.idx_feedback_stories_assignee_id;
DROP INDEX IF EXISTS public.idx_feedback_stories_created_by;
DROP INDEX IF EXISTS public.idx_feedback_story_events_actor_id;
DROP INDEX IF EXISTS public.idx_feedback_story_events_retest_run_id;
DROP INDEX IF EXISTS public.idx_feedback_story_events_routine_run_id;
DROP INDEX IF EXISTS public.idx_feedback_story_members_added_by;
DROP INDEX IF EXISTS public.idx_feedback_story_suggestions_dismissed_by;
DROP INDEX IF EXISTS public.idx_festivals_city_id;
DROP INDEX IF EXISTS public.idx_festivals_country_id;
DROP INDEX IF EXISTS public.idx_festivals_created_by;
DROP INDEX IF EXISTS public.idx_festivals_updated_by;
DROP INDEX IF EXISTS public.idx_festivals_venue_id;
DROP INDEX IF EXISTS public.idx_flyer_scans_duplicate_event_id;
DROP INDEX IF EXISTS public.idx_flyer_scans_matched_city_id;
DROP INDEX IF EXISTS public.idx_flyer_scans_matched_country_id;
DROP INDEX IF EXISTS public.idx_flyer_scans_matched_venue_id;
DROP INDEX IF EXISTS public.idx_flyer_scans_user_id;
DROP INDEX IF EXISTS public.idx_geo_sources_city_id;
DROP INDEX IF EXISTS public.idx_geo_sources_country_id;
DROP INDEX IF EXISTS public.idx_group_comment_likes_user_id;
DROP INDEX IF EXISTS public.idx_group_join_requests_decided_by;
DROP INDEX IF EXISTS public.idx_group_notifications_group_id;
DROP INDEX IF EXISTS public.idx_group_notifications_related_comment_id;
DROP INDEX IF EXISTS public.idx_group_notifications_related_post_id;
DROP INDEX IF EXISTS public.idx_group_notifications_triggered_by_user_id;
DROP INDEX IF EXISTS public.idx_group_notifications_user_id;
DROP INDEX IF EXISTS public.idx_group_poll_votes_user_id;
DROP INDEX IF EXISTS public.idx_group_post_comments_parent_comment_id;
DROP INDEX IF EXISTS public.idx_group_post_comments_post_id;
DROP INDEX IF EXISTS public.idx_group_post_comments_user_id;
DROP INDEX IF EXISTS public.idx_group_post_likes_user_id;
DROP INDEX IF EXISTS public.idx_group_posts_group_id;
DROP INDEX IF EXISTS public.idx_group_posts_user_id;
DROP INDEX IF EXISTS public.idx_hotels_created_by;
DROP INDEX IF EXISTS public.idx_hotels_updated_by;
DROP INDEX IF EXISTS public.idx_hotline_reports_resolved_by;
DROP INDEX IF EXISTS public.idx_image_asset_links_added_by;
DROP INDEX IF EXISTS public.idx_import_audit_log_import_job_id;
DROP INDEX IF EXISTS public.idx_import_jobs_enhanced_source_id;
DROP INDEX IF EXISTS public.idx_import_validation_results_import_job_id;
DROP INDEX IF EXISTS public.idx_ingestion_dlq_staging_id;
DROP INDEX IF EXISTS public.idx_ingestion_events_city_id;
DROP INDEX IF EXISTS public.idx_intimate_reports_reporter_id;
DROP INDEX IF EXISTS public.idx_knowledge_base_created_by;
DROP INDEX IF EXISTS public.idx_mailbox_emails_in_reply_to_email_id;
DROP INDEX IF EXISTS public.idx_mailbox_emails_owner_id;
DROP INDEX IF EXISTS public.idx_ingestion_events_country_id;
DROP INDEX IF EXISTS public.idx_ingestion_rule_hits_rule_id;
DROP INDEX IF EXISTS public.idx_ingestion_rule_hits_submission_id;
DROP INDEX IF EXISTS public.idx_ingestion_rules_created_by;
DROP INDEX IF EXISTS public.idx_marketplace_categories_parent_id;
DROP INDEX IF EXISTS public.idx_marketplace_collection_items_listing_id;
DROP INDEX IF EXISTS public.idx_marketplace_favorites_user_id;
DROP INDEX IF EXISTS public.idx_marketplace_guide_reads_guide_id;
DROP INDEX IF EXISTS public.idx_marketplace_guides_author_id;
DROP INDEX IF EXISTS public.idx_marketplace_listing_sources_listing_id;
DROP INDEX IF EXISTS public.idx_marketplace_listings_created_by;
DROP INDEX IF EXISTS public.idx_marketplace_listings_merchant_id;
DROP INDEX IF EXISTS public.idx_marketplace_merchants_affiliate_partner_id;
DROP INDEX IF EXISTS public.idx_messages_conversation_id;
DROP INDEX IF EXISTS public.idx_messages_reply_to_id;
DROP INDEX IF EXISTS public.idx_messages_sender_id;
DROP INDEX IF EXISTS public.idx_moderation_flags_reporter_user_id;
DROP INDEX IF EXISTS public.idx_moderation_flags_resolved_by;
DROP INDEX IF EXISTS public.idx_news_article_cities_city_id;
DROP INDEX IF EXISTS public.idx_news_article_countries_country_id;
DROP INDEX IF EXISTS public.idx_news_articles_duplicate_of_id;
DROP INDEX IF EXISTS public.idx_news_categories_parent_category_id;
DROP INDEX IF EXISTS public.idx_news_dedup_audit_matched_article_id;
DROP INDEX IF EXISTS public.idx_news_dedup_audit_pipeline_run_id;
DROP INDEX IF EXISTS public.idx_news_dedup_audit_source_id;
DROP INDEX IF EXISTS public.idx_news_quality_settings_updated_by;
DROP INDEX IF EXISTS public.idx_news_stories_hero_article_id;
DROP INDEX IF EXISTS public.idx_personality_internal_notes_updated_by;
DROP INDEX IF EXISTS public.idx_packing_suggestion_cache_user_id;
DROP INDEX IF EXISTS public.idx_passkey_challenges_user_id;
DROP INDEX IF EXISTS public.idx_personalities_city_id;
DROP INDEX IF EXISTS public.idx_personality_sources_personality_id;
DROP INDEX IF EXISTS public.idx_pipeline_definition_versions_saved_by;
DROP INDEX IF EXISTS public.idx_pipeline_definitions_created_by;
DROP INDEX IF EXISTS public.idx_pipeline_node_templates_created_by;
DROP INDEX IF EXISTS public.idx_pipeline_permissions_granted_by;
DROP INDEX IF EXISTS public.idx_pipeline_permissions_user_id;
DROP INDEX IF EXISTS public.idx_placeholder_images_created_by;
DROP INDEX IF EXISTS public.idx_post_comments_parent_comment_id;
DROP INDEX IF EXISTS public.idx_post_comments_post_id;
DROP INDEX IF EXISTS public.idx_post_comments_user_id;
DROP INDEX IF EXISTS public.idx_post_likes_user_id;
DROP INDEX IF EXISTS public.idx_quality_backfill_jobs_article_id;
DROP INDEX IF EXISTS public.idx_queer_villages_created_by;
DROP INDEX IF EXISTS public.idx_queer_villages_updated_by;
DROP INDEX IF EXISTS public.idx_quests_created_by;
DROP INDEX IF EXISTS public.idx_quests_recap_article_id;
DROP INDEX IF EXISTS public.idx_rag_conversations_user_id;
DROP INDEX IF EXISTS public.idx_redirect_events_redirect_id;
DROP INDEX IF EXISTS public.idx_redirects_created_by;
DROP INDEX IF EXISTS public.idx_regions_continent_id;
DROP INDEX IF EXISTS public.idx_reservations_city_id;
DROP INDEX IF EXISTS public.idx_reservations_country_id;
DROP INDEX IF EXISTS public.idx_reservations_trip_day_id;
DROP INDEX IF EXISTS public.idx_reservations_trip_id;
DROP INDEX IF EXISTS public.idx_review_queue_resolved_by;
DROP INDEX IF EXISTS public.idx_scrape_runs_job_id;
DROP INDEX IF EXISTS public.idx_scrape_runs_source_id;
DROP INDEX IF EXISTS public.idx_scraper_dedupe_decisions_pipeline_run_id;
DROP INDEX IF EXISTS public.idx_search_synonyms_approved_by;
DROP INDEX IF EXISTS public.idx_scraper_dedupe_decisions_staging_id;
DROP INDEX IF EXISTS public.idx_search_reindex_jobs_triggered_by;
DROP INDEX IF EXISTS public.idx_search_synonyms_created_by;
DROP INDEX IF EXISTS public.idx_signup_funnel_events_user_id;
DROP INDEX IF EXISTS public.idx_search_settings_versions_created_by;
DROP INDEX IF EXISTS public.idx_source_coverage_targets_city_id;
DROP INDEX IF EXISTS public.idx_tag_categories_parent_id;
DROP INDEX IF EXISTS public.idx_tag_relations_target_tag_id;
DROP INDEX IF EXISTS public.idx_tag_relationship_exclusions_created_by;
DROP INDEX IF EXISTS public.idx_tag_relationship_exclusions_tag2_id;
DROP INDEX IF EXISTS public.idx_tag_slug_redirects_tag_id;
DROP INDEX IF EXISTS public.idx_tag_sources_tag_id;
DROP INDEX IF EXISTS public.idx_topic_cluster_tags_added_by;
DROP INDEX IF EXISTS public.idx_topic_clusters_curator_user_id;
DROP INDEX IF EXISTS public.idx_trip_booking_clicks_trip_id;
DROP INDEX IF EXISTS public.idx_trip_booking_clicks_trip_place_id;
DROP INDEX IF EXISTS public.idx_trip_booking_clicks_user_id;
DROP INDEX IF EXISTS public.idx_trip_concierge_messages_created_by;
DROP INDEX IF EXISTS public.idx_trip_concierge_messages_trip_id;
DROP INDEX IF EXISTS public.idx_trip_documents_country_id;
DROP INDEX IF EXISTS public.idx_trip_budget_items_paid_by;
DROP INDEX IF EXISTS public.idx_trip_budget_items_place_id;
DROP INDEX IF EXISTS public.idx_trip_budget_items_trip_id;
DROP INDEX IF EXISTS public.idx_trip_documents_user_id;
DROP INDEX IF EXISTS public.idx_trip_geo_review_queue_resolved_by;
DROP INDEX IF EXISTS public.idx_trip_geo_review_queue_resolved_city_id;
DROP INDEX IF EXISTS public.idx_trip_geo_review_queue_resolved_country_id;
DROP INDEX IF EXISTS public.idx_trip_inbox_items_slotted_reservation_id;
DROP INDEX IF EXISTS public.idx_trip_inboxes_created_by;
DROP INDEX IF EXISTS public.idx_trip_messages_reply_to;
DROP INDEX IF EXISTS public.idx_trip_messages_sender_id;
DROP INDEX IF EXISTS public.idx_trip_messages_trip_id;
DROP INDEX IF EXISTS public.idx_trip_notes_author_id;
DROP INDEX IF EXISTS public.idx_trip_notes_trip_id;
DROP INDEX IF EXISTS public.idx_trip_packing_items_marketplace_listing_id;
DROP INDEX IF EXISTS public.idx_trip_packing_items_trip_id;
DROP INDEX IF EXISTS public.idx_trip_packing_items_user_id;
DROP INDEX IF EXISTS public.idx_trip_places_city_id;
DROP INDEX IF EXISTS public.idx_trip_places_country_id;
DROP INDEX IF EXISTS public.idx_trip_places_created_by;
DROP INDEX IF EXISTS public.idx_trip_places_day_id;
DROP INDEX IF EXISTS public.idx_trip_places_venue_id;
DROP INDEX IF EXISTS public.idx_trip_polls_author_id;
DROP INDEX IF EXISTS public.idx_trip_places_event_id;
DROP INDEX IF EXISTS public.idx_trip_places_hotel_id;
DROP INDEX IF EXISTS public.idx_trip_places_trip_id;
DROP INDEX IF EXISTS public.idx_trip_polls_trip_id;
DROP INDEX IF EXISTS public.idx_trip_recaps_generated_by;
DROP INDEX IF EXISTS public.idx_trip_share_comments_place_id;
DROP INDEX IF EXISTS public.idx_trip_share_comments_trip_id;
DROP INDEX IF EXISTS public.idx_trip_share_comments_viewer_id;
DROP INDEX IF EXISTS public.idx_trip_share_reactions_trip_id;
DROP INDEX IF EXISTS public.idx_trip_shares_created_by;
DROP INDEX IF EXISTS public.idx_trip_shares_trip_id;
DROP INDEX IF EXISTS public.idx_trip_share_reactions_viewer_id;
DROP INDEX IF EXISTS public.idx_trip_share_views_share_id;
DROP INDEX IF EXISTS public.idx_trip_share_views_trip_id;
DROP INDEX IF EXISTS public.idx_trip_share_views_viewer_user_id;
DROP INDEX IF EXISTS public.idx_trip_suggestion_impressions_listing_id;
DROP INDEX IF EXISTS public.idx_trip_suggestion_impressions_partner_id;
DROP INDEX IF EXISTS public.idx_trip_suggestion_impressions_trip_id;
DROP INDEX IF EXISTS public.idx_trip_suggestion_impressions_user_id;
DROP INDEX IF EXISTS public.idx_trips_owner_id;
DROP INDEX IF EXISTS public.idx_trips_primary_city_id;
DROP INDEX IF EXISTS public.idx_trips_primary_country_id;
DROP INDEX IF EXISTS public.idx_venue_closed_audit_reverted_by;
DROP INDEX IF EXISTS public.idx_user_achievements_achievement_slug;
DROP INDEX IF EXISTS public.idx_user_endorsements_endorsee_id;
DROP INDEX IF EXISTS public.idx_user_events_user_id;
DROP INDEX IF EXISTS public.idx_user_follows_following_id;
DROP INDEX IF EXISTS public.idx_user_passkeys_user_id;
DROP INDEX IF EXISTS public.idx_user_place_marks_city_id;
DROP INDEX IF EXISTS public.idx_user_relationships_target_user_id;
DROP INDEX IF EXISTS public.idx_user_travel_preferences_home_city_id;
DROP INDEX IF EXISTS public.idx_user_travel_preferences_home_country_id;
DROP INDEX IF EXISTS public.idx_user_trust_overrides_set_by;
DROP INDEX IF EXISTS public.idx_venue_checkins_venue_id;
DROP INDEX IF EXISTS public.idx_venue_closed_audit_venue_id;
DROP INDEX IF EXISTS public.idx_venue_field_conflicts_venue_id;
DROP INDEX IF EXISTS public.idx_venue_personal_visits_venue_id;
DROP INDEX IF EXISTS public.idx_venue_safety_signals_question_id;
DROP INDEX IF EXISTS public.idx_video_processing_jobs_video_id;
DROP INDEX IF EXISTS public.idx_video_renditions_video_id;
DROP INDEX IF EXISTS public.idx_wishlists_cover_listing_id;
DROP INDEX IF EXISTS public.idx_workflow_runs_definition_id;
DROP INDEX IF EXISTS public.idx_user_news_reads_user_day;
DROP INDEX IF EXISTS public.user_activity_events_user_created_idx;
DROP INDEX IF EXISTS public.user_activity_events_domain_type_idx;
DROP INDEX IF EXISTS public.user_community_score_weekly_idx;
DROP INDEX IF EXISTS public.profiles_travel_mode_city_idx;
DROP INDEX IF EXISTS public.profiles_presence_dot_idx;
DROP INDEX IF EXISTS public.venues_seo_noindex_idx;
DROP INDEX IF EXISTS public.cities_seo_noindex_idx;
DROP INDEX IF EXISTS public.countries_seo_noindex_idx;
DROP INDEX IF EXISTS public.events_seo_noindex_idx;
DROP INDEX IF EXISTS public.news_articles_seo_noindex_idx;
DROP INDEX IF EXISTS public.personalities_seo_noindex_idx;
DROP INDEX IF EXISTS public.hotels_seo_noindex_idx;
DROP INDEX IF EXISTS public.queer_villages_seo_noindex_idx;
DROP INDEX IF EXISTS public.unified_tags_seo_noindex_idx;
DROP INDEX IF EXISTS public.intimate_likes_target_idx;
DROP INDEX IF EXISTS public.intimate_passes_actor_idx;
DROP INDEX IF EXISTS public.group_chat_messages_group_created_idx;
DROP INDEX IF EXISTS public.group_chat_messages_sender_idx;
DROP INDEX IF EXISTS public.group_collections_group_idx;
DROP INDEX IF EXISTS public.group_collection_items_collection_idx;
DROP INDEX IF EXISTS public.trip_group_links_group_idx;
DROP INDEX IF EXISTS public.venue_guides_status_idx;
DROP INDEX IF EXISTS public.venue_guides_city_idx;
DROP INDEX IF EXISTS public.venue_guides_category_idx;
DROP INDEX IF EXISTS public.venue_guides_audience_tags_idx;
DROP INDEX IF EXISTS public.venue_guides_review_due_idx;
DROP INDEX IF EXISTS public.venue_guide_reads_user_completed_idx;
DROP INDEX IF EXISTS public.event_guides_status_idx;
DROP INDEX IF EXISTS public.event_guides_city_idx;
DROP INDEX IF EXISTS public.event_guides_event_type_idx;
DROP INDEX IF EXISTS public.event_guides_audience_tags_idx;
DROP INDEX IF EXISTS public.event_guide_picks_event_idx;
DROP INDEX IF EXISTS public.quests_status_idx;
DROP INDEX IF EXISTS public.quest_contributions_submission_idx;
DROP INDEX IF EXISTS public.community_submissions_quest_idx;
