-- The TripSit interaction matrix: 421 pairs.
--
-- PROVENANCE. Every row is TripSit's work — both the rating and, where present,
-- the explanatory note. Imported from
-- https://github.com/TripSit/drugs (combos.json), which is the machine-readable
-- source behind https://combo.tripsit.me/ and the poster most people have seen.
-- `source` and `source_url` are on every row and the UI credits them on every
-- surface that renders one.
--
-- WHY NOT THE POSTER. The obvious way to build this is to read the PNG. That was
-- rejected: 300+ cells transcribed by eye, on a page where a wrong cell is a
-- person taking a combination we told them was fine. The repo is also current
-- where the poster is not — v4.0 of the image is from 2019 and charts 25
-- substances; combos.json charts 31, adding AMT, PCP, lithium, pregabalin,
-- diphenhydramine and mephedrone.
--
-- SYMMETRY WAS VERIFIED, NOT ASSUMED. The upstream file stores both directions.
-- Before collapsing to one row per pair, all 841 directed entries were compared:
-- 421 unordered pairs, ZERO status disagreements, one pair present in a single
-- direction only (amphetamines->lithium). Where only one direction carried a
-- note, that note is kept.
--
-- MAPPING. Upstream keys are their vocabulary, ours are slugs; `source_pair`
-- records the original so a re-import can be diffed. Two are worth naming:
-- `mushrooms` -> `psilocybin` (we file the compound, not the fungus) and `dox`
-- -> `dom-doi-dob-doc`. `2c-x` maps to `2c-b`, which already answers to "2C-x"
-- as an alias — the upstream row is for the family and 2C-B is its archetype.
--
-- REFRESHING. Re-run the generator against combos.json and replace this file
-- wholesale; the insert is idempotent on (tag_a_id, tag_b_id). When you do,
-- re-read the substance descriptions too — 20260909171500 documents two that
-- contradicted this data and had to be corrected before launch.

insert into public.substance_interactions (tag_a_id, tag_b_id, status, note, source, source_url, source_pair)
select least(ta.id, tb.id), greatest(ta.id, tb.id), v.status, nullif(v.note,''),
       'tripsit', 'https://combo.tripsit.me/', v.pair
from (values
  ('2c-t-x','2c-b','caution','','2c-t-x|2c-x'),
  ('2c-t-x','5-meo-xxt','caution','Both classes of compounds can be unpredictable alone','2c-t-x|5-meo-xxt'),
  ('2c-t-x','alcohol','low_risk_decrease','Both these classes of compound can interact unpredictably. Caution should be exercised.','2c-t-x|alcohol'),
  ('2c-t-x','amphetamine','unsafe','Stimulants increase anxiety levels and the risk of thought loops which can lead to negative experiences. In extreme cases, they can result in severe vasoconstriction, tachycardia, hypertension, and heart failure.','2c-t-x|amphetamines'),
  ('2c-t-x','amt','dangerous','','2c-t-x|amt'),
  ('2c-t-x','benzodiazepines','low_risk_decrease','','2c-t-x|benzodiazepines'),
  ('2c-t-x','caffeine','low_risk_no_synergy','High doses of caffeine may cause anxiety which is less manageable when tripping, and since both are stimulating the combination may cause some physical discomfort.','2c-t-x|caffeine'),
  ('2c-t-x','cannabis','caution','Cannabis has an unexpectedly strong and somewhat unpredictable synergy with psychedelics.','2c-t-x|cannabis'),
  ('2c-t-x','cocaine','unsafe','Cocaine and 2c-t-x both provide considerable stimulation. When combined they can result in severe vasoconstriction, tachycardia, hypertension, and in extreme cases heart failure.','2c-t-x|cocaine'),
  ('2c-t-x','dextromethorphan','unsafe','','2c-t-x|dextromethorphan'),
  ('2c-t-x','dmt','low_risk_synergy','','2c-t-x|dmt'),
  ('2c-t-x','dom-doi-dob-doc','caution','','2c-t-x|dox'),
  ('2c-t-x','ghb','low_risk_decrease','','2c-t-x|ghb/gbl'),
  ('2c-t-x','ketamine','low_risk_synergy','','2c-t-x|ketamine'),
  ('2c-t-x','lithium','dangerous','There are a large number of reports indicating a high seizure and psychosis risk from this combination.','2c-t-x|lithium'),
  ('2c-t-x','lsd','low_risk_synergy','','2c-t-x|lsd'),
  ('2c-t-x','maois','caution','MAO-B inhibitors can increase the potency and duration of phenethylamines unpredictably, which could be dangerous given the unpredictability of the 2C-T-x series','2c-t-x|maois'),
  ('2c-t-x','mdma','caution','','2c-t-x|mdma'),
  ('2c-t-x','mescaline','caution','','2c-t-x|mescaline'),
  ('2c-t-x','psilocybin','low_risk_synergy','','2c-t-x|mushrooms'),
  ('2c-t-x','mxe','caution','','2c-t-x|mxe'),
  ('2c-t-x','nbomes','caution','','2c-t-x|nbomes'),
  ('2c-t-x','nitrous-oxide','low_risk_synergy','','2c-t-x|nitrous'),
  ('2c-t-x','opioids','low_risk_no_synergy','No expected interactions, some opioids have serotonin action, and could lead to Serotonin Syndrome or a seizure. These are pretty much only to Pentazocine, Methadone, Tramadol, Tapenatdol.','2c-t-x|opioids'),
  ('2c-t-x','pcp','dangerous','','2c-t-x|pcp'),
  ('2c-t-x','ssris','low_risk_decrease','','2c-t-x|ssris'),
  ('2c-t-x','tramadol','unsafe','','2c-t-x|tramadol'),
  ('2c-b','5-meo-xxt','caution','The 5-MeO psychedelics can interact unpredictably to potentiate other psychedelics','2c-x|5-meo-xxt'),
  ('2c-b','alcohol','low_risk_decrease','','2c-x|alcohol'),
  ('2c-b','amphetamine','caution','The anxiogenic and focusing effects of stimulants increase the chance of unpleasant thought loops. The combination is generally unnecessary because of the stimulating effects of psychedelics. Combination of the stimulating effects may be uncomfortable.','2c-x|amphetamines'),
  ('2c-b','amt','dangerous','','2c-x|amt'),
  ('2c-b','benzodiazepines','low_risk_decrease','','2c-x|benzodiazepines'),
  ('2c-b','caffeine','low_risk_no_synergy','High doses of caffeine may cause anxiety which is less manageable when tripping, and since both are stimulating the combination may cause some physical discomfort.','2c-x|caffeine'),
  ('2c-b','cannabis','caution','Cannabis has an unexpectedly strong and somewhat unpredictable synergy with psychedelics.','2c-x|cannabis'),
  ('2c-b','cocaine','caution','The anxiogenic and focusing effects of stimulants increase the chance of unpleasant thought loops. The combination is generally unnecessary because of the stimulating effects of psychedelics. Combination of the stimulating effects may be uncomfortable.','2c-x|cocaine'),
  ('2c-b','dextromethorphan','low_risk_synergy','','2c-x|dextromethorphan'),
  ('2c-b','dmt','low_risk_synergy','','2c-x|dmt'),
  ('2c-b','dom-doi-dob-doc','caution','','2c-x|dox'),
  ('2c-b','ghb','low_risk_decrease','','2c-x|ghb/gbl'),
  ('2c-b','ketamine','low_risk_synergy','','2c-x|ketamine'),
  ('2c-b','lithium','dangerous','There are a large number of reports indicating a high seizure and psychosis risk from this combination.','2c-x|lithium'),
  ('2c-b','lsd','low_risk_synergy','','2c-x|lsd'),
  ('2c-b','maois','caution','MAO-B inhibitors can increase the potency and duration of phenethylamines unpredictably','2c-x|maois'),
  ('2c-b','mdma','low_risk_synergy','','2c-x|mdma'),
  ('2c-b','mescaline','caution','','2c-x|mescaline'),
  ('2c-b','psilocybin','low_risk_synergy','','2c-x|mushrooms'),
  ('2c-b','mxe','low_risk_synergy','','2c-x|mxe'),
  ('2c-b','nbomes','caution','','2c-x|nbomes'),
  ('2c-b','nitrous-oxide','low_risk_synergy','','2c-x|nitrous'),
  ('2c-b','opioids','low_risk_no_synergy','','2c-x|opioids'),
  ('2c-b','pcp','low_risk_synergy','','2c-x|pcp'),
  ('2c-b','pregabalin','low_risk_synergy','Pregabalin may reduce the anxiety and other possible side effects of 2C-X drugs. Additionally, the combination may increase inhibition, dizziness, and risk of injury.','2c-x|pregabalin'),
  ('2c-b','ssris','low_risk_decrease','','2c-x|ssris'),
  ('2c-b','tramadol','unsafe','Tramadol is well known to lower seizure threshold and psychedelics raise the risk of seizures.','2c-x|tramadol'),
  ('5-meo-xxt','alcohol','low_risk_decrease','','5-meo-xxt|alcohol'),
  ('5-meo-xxt','amphetamine','unsafe','The anxiogenic and focusing effects of stimulants increase the chance of unpleasant thought loops. The combination is generally unnecessary because of the stimulating effects of psychedelics.','5-meo-xxt|amphetamines'),
  ('5-meo-xxt','amt','dangerous','','5-meo-xxt|amt'),
  ('5-meo-xxt','benzodiazepines','low_risk_decrease','','5-meo-xxt|benzodiazepines'),
  ('5-meo-xxt','caffeine','low_risk_no_synergy','High doses of caffeine may cause anxiety which is less manageable when tripping, and since both are stimulating the combination may cause some physical discomfort.','5-meo-xxt|caffeine'),
  ('5-meo-xxt','cannabis','caution','Cannabis has an unexpectedly strong and somewhat unpredictable synergy with psychedelics.','5-meo-xxt|cannabis'),
  ('5-meo-xxt','cocaine','unsafe','The anxiogenic and focusing effects of stimulants increase the chance of unpleasant thought loops. The combination is generally unnecessary because of the stimulating effects of psychedelics.','5-meo-xxt|cocaine'),
  ('5-meo-xxt','dextromethorphan','unsafe','Little information exists about this combination.','5-meo-xxt|dextromethorphan'),
  ('5-meo-xxt','dmt','low_risk_synergy','','5-meo-xxt|dmt'),
  ('5-meo-xxt','dom-doi-dob-doc','caution','The 5-MeO class of tryptamines can be unpredictable in their interactions, particularly increasing the risk of unpleasant physical side effects.','5-meo-xxt|dox'),
  ('5-meo-xxt','ghb','low_risk_decrease','','5-meo-xxt|ghb/gbl'),
  ('5-meo-xxt','ketamine','low_risk_synergy','','5-meo-xxt|ketamine'),
  ('5-meo-xxt','lsd','low_risk_synergy','','5-meo-xxt|lsd'),
  ('5-meo-xxt','maois','dangerous','','5-meo-xxt|maois'),
  ('5-meo-xxt','mdma','caution','Some of the 5-MeO tryptamines are a bit unpredictable and should be mixed with MDMA with care','5-meo-xxt|mdma'),
  ('5-meo-xxt','mescaline','caution','The 5-MeO class of tryptamines can be unpredictable in their interactions','5-meo-xxt|mescaline'),
  ('5-meo-xxt','psilocybin','low_risk_synergy','','5-meo-xxt|mushrooms'),
  ('5-meo-xxt','mxe','low_risk_synergy','Little information exists about this combination.','5-meo-xxt|mxe'),
  ('5-meo-xxt','nbomes','caution','The 5-MeO class of tryptamines can be unpredictable in their interactions and the NBOMes are known to be unpredictable even alone. This combination is best avoided','5-meo-xxt|nbomes'),
  ('5-meo-xxt','nitrous-oxide','low_risk_synergy','','5-meo-xxt|nitrous'),
  ('5-meo-xxt','opioids','low_risk_no_synergy','','5-meo-xxt|opioids'),
  ('5-meo-xxt','pcp','dangerous','','5-meo-xxt|pcp'),
  ('5-meo-xxt','pregabalin','caution','Caution should be given due to 5-MeO-xxT drugs stimulating effects and pregabalin’s seizure concerns at higher dosages. Pregabalin may reduce the vasoconstriction, anxiety, and other side effects of 5-MeO-xxT drugs. Additionally, Pregabalin may increase 5-MeO-xxT drugs inhibition and risk of injury.','5-meo-xxt|pregabalin'),
  ('5-meo-xxt','ssris','low_risk_decrease','','5-meo-xxt|ssris'),
  ('5-meo-xxt','tramadol','unsafe','','5-meo-xxt|tramadol'),
  ('alcohol','amphetamine','caution','Drinking on stimulants is risky because the sedative effects of the alcohol are reduced, and these are what the body uses to gauge drunkenness. This typically leads to excessive drinking with greatly reduced inhibitions, high risk of liver damage and increased dehydration. They will also allow you to drink past a point where you might normally pass out, increasing the risk. If you do decide to do this then you should set a limit of how much you will drink each hour and stick to it, bearing in mind that you will feel the alcohol and the stimulant less. Extended release formulations may severely impede sleep, further worsening the hangover.','alcohol|amphetamines'),
  ('alcohol','amt','caution','aMT has a broad mechanism of action in the brain and so does alcohol so the combination can be unpredictable','alcohol|amt'),
  ('alcohol','benzodiazepines','dangerous','Ethanol ingestion may potentiate the CNS effects of many benzodiazepines. The two substances potentiate each other strongly and unpredictably, very rapidly leading to unconsciousness. While unconscious, vomit aspiration is a risk if not placed in the recovery position. Blacking out and memory loss is almost certain.','alcohol|benzodiazepines'),
  ('alcohol','caffeine','low_risk_no_synergy','','alcohol|caffeine'),
  ('alcohol','cannabis','low_risk_synergy','In excess, this combination can cause nausea.','alcohol|cannabis'),
  ('alcohol','cocaine','unsafe','Cocaine can decrease some of the intoxicating effects of alcohol, causing some people to drink more than they otherwise would, which leads to greater behavioral and physical health risks. There is also some debate about cocaethylene, a metabolite produced when combining alcohol and cocaine, with some researchers positing that it is more cardiotoxic than cocaine on its own. Use moderation when combining these substances.','alcohol|cocaine'),
  ('alcohol','dextromethorphan','dangerous','Both substances potentiate the ataxia and sedation caused by the other and can lead to unexpected loss of consciousness at high doses. Place the affected individual in the recovery position to prevent vomit aspiration from excess. Additionally, CNS depression can lead to difficulty breathing. Avoid on anything higher than 1st plateau.','alcohol|dextromethorphan'),
  ('alcohol','diphenhydramine','dangerous','The two substances potentiate each other strongly and unpredictably, and may rapidly lead to unconsciousness. They both increase each other''s side effects such as ataxia, sedation, and CNS depression. Blackouts and memory loss are significantly increased. If the user falls unconscious while under the influence there is a severe risk of vomit aspiration if they are not placed in the recovery position. Alcohol may also increase the deliriant effects of diphenhydramine. It should also be noted if the individual consuming alcohol typically has a flushing response to alcohol, diphenhydramine may reduce the reaction and mask some of the effects of the alcohol.','alcohol|diphenhydramine'),
  ('alcohol','dmt','low_risk_decrease','','alcohol|dmt'),
  ('alcohol','dom-doi-dob-doc','low_risk_decrease','Drinking on stimulants is risky because the sedative effects of the alcohol are reduced, and these are what the body uses to gauge drunkenness. This typically leads to excessive drinking with greatly reduced inhibitions, high risk of liver damage and increased dehydration. They will also  allow you to drink past a point where you might normally pass out, increasing the risk.','alcohol|dox'),
  ('alcohol','ghb','dangerous','Even in very low doses this combination rapidly leads to memory loss, severe ataxia and unconsciousness. There is a high risk of vomit aspiration while unconscious.','alcohol|ghb/gbl'),
  ('alcohol','ketamine','dangerous','Both substances cause ataxia and bring a very high risk of vomiting and unconsciousness. If the user falls unconscious while under the influence there is a severe risk of vomit aspiration if they are not placed in the recovery position.','alcohol|ketamine'),
  ('alcohol','lsd','low_risk_decrease','','alcohol|lsd'),
  ('alcohol','maois','unsafe','Tyramine found in many alcoholic beverages can have dangerous reactions with MAOIs, causing an increase in blood pressure.','alcohol|maois'),
  ('alcohol','mdma','caution','The combination of MDMA and alcohol may increase strain on the cardiovascular system and lead to increased alcohol consumption. MDMA may also impair one''s ability to recognize their level of drunkenness, leading to increased alcohol consumption and poor decision-making. Alcohol may also increase the risk of dehydration and hyperthermia (increased body temperature) when combined with MDMA.','alcohol|mdma'),
  ('alcohol','mescaline','low_risk_decrease','','alcohol|mescaline'),
  ('alcohol','psilocybin','low_risk_decrease','','alcohol|mushrooms'),
  ('alcohol','mxe','dangerous','There is a high risk of memory loss, vomiting and severe ataxia from this combination.','alcohol|mxe'),
  ('alcohol','nbomes','low_risk_decrease','','alcohol|nbomes'),
  ('alcohol','nitrous-oxide','caution','Both substances potentiate the ataxia and sedation caused by the other and can lead to unexpected loss of consciousness at high doses. While unconscious, vomit aspiration is a risk if not placed in the recovery position. Memory blackouts are likely.','alcohol|nitrous'),
  ('alcohol','opioids','dangerous','Both substances potentiate the ataxia and sedation caused by the other and can lead to unexpected loss of consciousness at high doses. Place the affected individual in the recovery position to prevent vomit aspiration from excess. Memory blackouts are likely','alcohol|opioids'),
  ('alcohol','pcp','unsafe','Details of this combination are not well understood but PCP generally interacts in an unpredictable manner.','alcohol|pcp'),
  ('alcohol','ssris','caution','Alcohol may potentiate some of the pharmacologic effects of CNS-active agents. Use in combination may result in additive central nervous system depression and/or impairment of judgment, thinking, and  psychomotor skills.','alcohol|ssris'),
  ('alcohol','tramadol','dangerous','Heavy CNS depressants, risk of seizures. Both substances potentiate the ataxia and sedation caused by the other and can lead to unexpected loss of consciousness at high doses. Place the affected individual in the recovery position to prevent vomit aspiration from excess. Memory blackouts are likely.','alcohol|tramadol'),
  ('amphetamine','amt','dangerous','','amphetamines|amt'),
  ('amphetamine','benzodiazepines','low_risk_decrease','Both can dull each other''s effects, so if one wears off before the other it''s possible to overdose due to the lack of counteraction','amphetamines|benzodiazepines'),
  ('amphetamine','caffeine','caution','This combination of stimulants is not generally necessary and may increase strain on the heart, as well as potentially causing anxiety and greater physical discomfort.','amphetamines|caffeine'),
  ('amphetamine','cannabis','caution','Stimulants increase anxiety levels and the risk of thought loops which can lead to negative experiences','amphetamines|cannabis'),
  ('amphetamine','cocaine','caution','This combination of stimulants will increase strain on the heart. It is not generally worth it as cocaine has a mild blocking effect on dopamine releasers like amphetamine','amphetamines|cocaine'),
  ('amphetamine','dextromethorphan','unsafe','Both substances raise heart rate, in extreme cases, panic attacks caused by these drugs have led to more serious heart issues.','amphetamines|dextromethorphan'),
  ('amphetamine','diphenhydramine','caution','Amphetamines as a stimulant may mask some of the negative side effects of DPH, leading to delusions of sobriety which has additional concern in states of delirium. The combination of stimulants will increase strain on the heart and may cause some physical discomfort, and has the chance to cause life-threatening cardiovascular issues. The combination may also increase each other''s neurotoxicity at higher dosages. The combination may increase anxiety levels and risks of thought loops on higher dosages, in addition to increasing each others negative side effects. Medical and common dosages of each substances are reported to not be a concern. Additionally, it is suggested that DPH potentiates amphetamine psychomotor activation, in addition to other interactions such as potentiation through inhibition of CYP2D6 and histamine H1 and H2 receptors, among other alterations.','amphetamines|diphenhydramine'),
  ('amphetamine','dmt','caution','Stimulants increase anxiety levels and the risk of thought loops which can lead to negative experiences','amphetamines|dmt'),
  ('amphetamine','dom-doi-dob-doc','unsafe','The combined stimulating effects of the two can lead to an uncomfortable body-load, while the focusing effects of amphetamine can easily lead to thought loops. Coming down from amphetamines while the DOx is still active can be quite anxiogenic.','amphetamines|dox'),
  ('amphetamine','ghb','caution','Stimulants increase respiration rate allowing for a higher dose of sedatives than normal. If the stimulant wears off first the opiate may overcome the individual and cause respiratory arrest.','amphetamines|ghb/gbl'),
  ('amphetamine','ketamine','caution','No unexpected interactions, though likely to increase blood pressure but not an issue with sensible doses. Moving around on high doses of this combination may be ill advised due to risk of physical injury.','amphetamines|ketamine'),
  ('amphetamine','lithium','low_risk_no_synergy','Lithium may be neuroprotective when taken with amphetamines and lithium may decrease the hyperactive and euphoric effects of amphetamines. Lithium may also decrease some negative side effects of amphetamines. Studies indicate this combination is safe.','amphetamines|lithium'),
  ('amphetamine','lsd','caution','Stimulants increase anxiety levels and the risk of thought loops which can lead to negative experiences','amphetamines|lsd'),
  ('amphetamine','maois','dangerous','MAO-B inhibitors can increase the potency and duration of phenethylamines unpredictably. MAO-A inhibitors with amphetamine can lead to hypertensive crises.','amphetamines|maois'),
  ('amphetamine','mdma','caution','This combination of stimulants will increase strain on the heart, may cause some physical discomfort, and has the chance to cause cardiovascular issues. The anxiogenic and focusing effects of stimulants can increase the chance of unpleasant thought loops and make the experience more uncomfortable, this combination raises these chances. Amphetamines will increase the neurotoxic effects of MDMA, in addition to causing further concerns of hyperthermia due to the inherent nature of the combination. It will also raise one''s body temperature, also likely making the combination more neurotoxic.','amphetamines|mdma'),
  ('amphetamine','mescaline','caution','The focus and anxiety caused by stimulants is magnified by psychedelics and results in an increased risk of thought loops','amphetamines|mescaline'),
  ('amphetamine','psilocybin','caution','Stimulants increase anxiety levels and the risk of thought loops which can lead to negative experiences','amphetamines|mushrooms'),
  ('amphetamine','mxe','caution','Risk of tachycardia, hypertension, and manic states','amphetamines|mxe'),
  ('amphetamine','nbomes','unsafe','Amphetamines and NBOMes both provide considerable stimulation. When combined they can result in tachycardia, hypertension, vasoconstriction and in extreme cases heart failure. The anxiogenic and focusing effects of stimulants are also not good in combination with psychedelics as they can lead to unpleasant thought loops. NBOMes are known to cause seizures and stimulants can increase this risk.','amphetamines|nbomes'),
  ('amphetamine','nitrous-oxide','low_risk_synergy','','amphetamines|nitrous'),
  ('amphetamine','opioids','caution','Stimulants increase respiration rate, which can allow for a higher dose of opiates normal . If the stimulant wears off first then the opiate may overcome the individual and cause respiratory arrest.','amphetamines|opioids'),
  ('amphetamine','pcp','unsafe','This combination can easily lead to hypermanic states','amphetamines|pcp'),
  ('amphetamine','pregabalin','unsafe','There is a significant risk of seizures from this combination. Amphetamines increase respiration rate allowing for a higher dose of sedatives than normal. If amphetamines wears off first, recreational dosages of pregabalin may overcome the individual and cause respiratory arrest. Both substances at recreational dosages cause strain of the heart and may lead to further dangerous heart complications.','amphetamines|pregabalin'),
  ('amphetamine','ssris','low_risk_no_synergy','','amphetamines|ssris'),
  ('amphetamine','tramadol','dangerous','Tramadol and stimulants both increase the risk of seizures.','amphetamines|tramadol'),
  ('amt','benzodiazepines','low_risk_decrease','','amt|benzodiazepines'),
  ('amt','caffeine','caution','High doses of caffeine may cause anxiety which is less manageable when tripping, and since both are stimulating the combination may cause some physical discomfort.','amt|caffeine'),
  ('amt','cannabis','caution','Cannabis has an unexpectedly strong and somewhat unpredictable synergy with psychedelics. Small amounts can reduce nausea with aMT but take care.','amt|cannabis'),
  ('amt','cocaine','dangerous','','amt|cocaine'),
  ('amt','dextromethorphan','dangerous','','amt|dextromethorphan'),
  ('amt','dmt','low_risk_synergy','','amt|dmt'),
  ('amt','dom-doi-dob-doc','dangerous','','amt|dox'),
  ('amt','ghb','low_risk_decrease','','amt|ghb/gbl'),
  ('amt','ketamine','low_risk_synergy','','amt|ketamine'),
  ('amt','lsd','low_risk_synergy','','amt|lsd'),
  ('amt','maois','dangerous','aMT is an MAOI on its own. Using enzyme inhibitors can greatly reduce predictability of effects.','amt|maois'),
  ('amt','mdma','dangerous','','amt|mdma'),
  ('amt','mescaline','dangerous','','amt|mescaline'),
  ('amt','psilocybin','low_risk_synergy','','amt|mushrooms'),
  ('amt','mxe','dangerous','','amt|mxe'),
  ('amt','nbomes','dangerous','','amt|nbomes'),
  ('amt','nitrous-oxide','low_risk_synergy','','amt|nitrous'),
  ('amt','opioids','low_risk_no_synergy','No unexpected interactions','amt|opioids'),
  ('amt','pcp','dangerous','','amt|pcp'),
  ('amt','ssris','dangerous','','amt|ssris'),
  ('amt','tramadol','dangerous','','amt|tramadol'),
  ('benzodiazepines','caffeine','low_risk_decrease','','benzodiazepines|caffeine'),
  ('benzodiazepines','cannabis','low_risk_decrease','','benzodiazepines|cannabis'),
  ('benzodiazepines','cocaine','low_risk_decrease','','benzodiazepines|cocaine'),
  ('benzodiazepines','dextromethorphan','caution','Small doses of benzos can end a bad trip, but both substances potentiate the ataxia and sedation caused by the other and this can lead to unexpected loss of consciousness at high doses. While unconscious, vomit aspiration is a risk if not placed in the recovery position.','benzodiazepines|dextromethorphan'),
  ('benzodiazepines','diphenhydramine','unsafe','Both substances potentiate the ataxia and sedation caused by the other and can lead to unexpected loss of consciousness at high doses. While unconscious, vomit aspiration is a risk if not placed in the recovery position. Memory blackouts are likely. Low medical doses are unlikely to be of concern.','benzodiazepines|diphenhydramine'),
  ('benzodiazepines','dmt','low_risk_decrease','','benzodiazepines|dmt'),
  ('benzodiazepines','dom-doi-dob-doc','low_risk_decrease','','benzodiazepines|dox'),
  ('benzodiazepines','ghb','dangerous','The two substances potentiate each other strongly and unpredictably, very rapidly leading to unconsciousness. While unconscious, vomit aspiration is a risk if not placed in the recovery position.','benzodiazepines|ghb/gbl'),
  ('benzodiazepines','ketamine','caution','Both substances potentiate the ataxia and sedation caused by the other and can lead to unexpected loss of consciousness at high doses. While unconscious, vomit aspiration is a risk if not placed in the recovery position.','benzodiazepines|ketamine'),
  ('benzodiazepines','lsd','low_risk_decrease','','benzodiazepines|lsd'),
  ('benzodiazepines','maois','low_risk_synergy','','benzodiazepines|maois'),
  ('benzodiazepines','mdma','low_risk_decrease','','benzodiazepines|mdma'),
  ('benzodiazepines','mescaline','low_risk_decrease','','benzodiazepines|mescaline'),
  ('benzodiazepines','psilocybin','low_risk_decrease','','benzodiazepines|mushrooms'),
  ('benzodiazepines','mxe','caution','Both substances potentiate the ataxia and sedation caused by the other and can lead to unexpected loss of consciousness at high doses. Place the affected individual in the recovery position to prevent vomit aspiration from excess.','benzodiazepines|mxe'),
  ('benzodiazepines','nbomes','low_risk_decrease','','benzodiazepines|nbomes'),
  ('benzodiazepines','nitrous-oxide','low_risk_decrease','','benzodiazepines|nitrous'),
  ('benzodiazepines','opioids','dangerous','Central nervous system and/or respiratory-depressant effects may be additively or synergistically present. The two substances potentiate each other strongly and unpredictably, very rapidly leading to unconsciousness. While unconscious, vomit aspiration is a risk if not placed in the recovery position Blackouts/memory loss likely','benzodiazepines|opioids'),
  ('benzodiazepines','pcp','unsafe','Both substances potentiate the ataxia and sedation caused by the other and can lead to unexpected loss of consciousness at high doses. While unconscious, vomit aspiration is a risk if not placed in the recovery position. Memory blackouts are likely','benzodiazepines|pcp'),
  ('benzodiazepines','ssris','low_risk_no_synergy','','benzodiazepines|ssris'),
  ('benzodiazepines','tramadol','dangerous','Central nervous system- and/or respiratory-depressant effects may be additively or synergistically present. Vomit aspiration is a risk when passed out, lay down in recovery position if ingested.','benzodiazepines|tramadol'),
  ('caffeine','cannabis','low_risk_no_synergy','','caffeine|cannabis'),
  ('caffeine','cocaine','caution','Both stimulants, risk of tachycardia, hypertension, and in extreme cases heart failure.','caffeine|cocaine'),
  ('caffeine','dextromethorphan','caution','High doses of caffeine can potentially exacerbate anxiety, especially during a dissociative experience, due to its stimulating effects. This combination might also lead to physical discomfort. However, individual responses to caffeine can vary significantly, often influenced by factors like habitual versus occasional usage.','caffeine|dextromethorphan'),
  ('caffeine','diphenhydramine','caution','Caffeine as a stimulant may mask some negative side effects of DPH, leading to delusions of sobriety, which has additional concerns in states of delirium. The combination of stimulants will increase strain on the heart and may cause some physical discomfort, and has the chance to cause cardiovascular issues such as complex tachycardia. The combination may increase anxiety levels and risks of thought loops at higher dosages, in addition to increasing each other''s negative side effects. Medical dosages are reported to not be a concern.','caffeine|diphenhydramine'),
  ('caffeine','dmt','low_risk_no_synergy','','caffeine|dmt'),
  ('caffeine','dom-doi-dob-doc','caution','High doses of caffeine may cause anxiety which is less manageable when tripping, and since both are stimulating it may cause some physical discomfort.','caffeine|dox'),
  ('caffeine','ghb','low_risk_no_synergy','','caffeine|ghb/gbl'),
  ('caffeine','ketamine','low_risk_no_synergy','No unexpected interactions.','caffeine|ketamine'),
  ('caffeine','lsd','low_risk_no_synergy','','caffeine|lsd'),
  ('caffeine','maois','low_risk_no_synergy','','caffeine|maois'),
  ('caffeine','mdma','caution','Caffeine is not really necessary with MDMA and increases any neurotoxic effects from MDMA','caffeine|mdma'),
  ('caffeine','mephedrone','caution','This combination of stimulants is not generally necessary and may increase strain on the heart, as well as potentially causing anxiety and great physical discomfort. However, individual responses to caffeine can vary significantly, often influenced by factors like habitual versus occasional usage.','caffeine|mephedrone'),
  ('caffeine','mescaline','low_risk_no_synergy','High doses of caffeine are uncomfortable and this will be magnified by psychedelics','caffeine|mescaline'),
  ('caffeine','psilocybin','low_risk_no_synergy','','caffeine|mushrooms'),
  ('caffeine','mxe','low_risk_no_synergy','No likely interactions','caffeine|mxe'),
  ('caffeine','nbomes','caution','Caffeine can bring out the natural stimulation from psychedelic drugs to make it uncomfortable. High doses can cause anxiety which is hard to handle while tripping','caffeine|nbomes'),
  ('caffeine','nitrous-oxide','low_risk_no_synergy','','caffeine|nitrous'),
  ('caffeine','opioids','low_risk_no_synergy','','caffeine|opioids'),
  ('caffeine','pcp','caution','Details of this combination are not well understood but PCP generally interacts in an unpredictable manner.','caffeine|pcp'),
  ('caffeine','pregabalin','unsafe','There is a risk of seizures from this combination, especially at higher dosages. Caffeine additionally reduces pregabalin’s anticonvulsant effects found in lower dosages. Caffeine increases respiration rate allowing for a higher dose of sedatives than normal. If amphetamines wears off first, recreational dosages of pregabalin may overcome the individual and cause respiratory arrest. Both substances at recreational dosages cause strain of the heart and may lead to further dangerous heart complications. Medical dosages are unlikely to be of concern.','caffeine|pregabalin'),
  ('caffeine','ssris','low_risk_no_synergy','','caffeine|ssris'),
  ('caffeine','tramadol','low_risk_no_synergy','','caffeine|tramadol'),
  ('cannabis','cocaine','caution','Stimulants increase anxiety levels and the risk of thought loops which can lead to negative experiences','cannabis|cocaine'),
  ('cannabis','dextromethorphan','low_risk_synergy','','cannabis|dextromethorphan'),
  ('cannabis','dmt','caution','Cannabis has an unexpectedly strong and somewhat unpredictable synergy with psychedelics.','cannabis|dmt'),
  ('cannabis','dom-doi-dob-doc','caution','Cannabis has an unexpectedly strong and somewhat unpredictable synergy with psychedelics.','cannabis|dox'),
  ('cannabis','ghb','low_risk_synergy','','cannabis|ghb/gbl'),
  ('cannabis','ketamine','low_risk_synergy','','cannabis|ketamine'),
  ('cannabis','lsd','caution','Cannabis has an unexpectedly strong and somewhat unpredictable synergy with psychedelics.','cannabis|lsd'),
  ('cannabis','maois','low_risk_synergy','','cannabis|maois'),
  ('cannabis','mdma','low_risk_synergy','Large amounts of cannabis may cause strong and somewhat unpredictable experiences in combination with MDMA. Cannabis should be saved for towards the end of the experience if possible.','cannabis|mdma'),
  ('cannabis','mescaline','caution','Cannabis has an unexpectedly strong and somewhat unpredictable synergy with psychedelics.','cannabis|mescaline'),
  ('cannabis','psilocybin','caution','Cannabis has an unexpectedly strong and somewhat unpredictable synergy with psychedelics.','cannabis|mushrooms'),
  ('cannabis','mxe','low_risk_synergy','','cannabis|mxe'),
  ('cannabis','nbomes','caution','Cannabis has an unexpectedly strong and somewhat unpredictable synergy with psychedelics.','cannabis|nbomes'),
  ('cannabis','nitrous-oxide','low_risk_synergy','','cannabis|nitrous'),
  ('cannabis','opioids','low_risk_synergy','','cannabis|opioids'),
  ('cannabis','pcp','low_risk_synergy','','cannabis|pcp'),
  ('cannabis','pregabalin','low_risk_synergy','Both substances may increase each other''s side effects, such as sedation, lowered blood pressure, and raised heart rate.','cannabis|pregabalin'),
  ('cannabis','ssris','low_risk_no_synergy','','cannabis|ssris'),
  ('cannabis','tramadol','low_risk_synergy','','cannabis|tramadol'),
  ('cocaine','dextromethorphan','unsafe','Both substances raise heart rate, in extreme cases, panic attacks caused by these drugs have led to more serious heart issues','cocaine|dextromethorphan'),
  ('cocaine','diphenhydramine','caution','Stimulants increase respiration rate allowing for a higher dose of sedatives than normal. If cocaine wears off first, recreational dosages of DPH may overcome the individual and cause respiratory arrest. Both substances at recreational dosages strain the heart and may lead to further dangerous heart complications. When taken together, both substances can potentially be more reinforcing and have greater risk of methemoglobinemia when higher dosages of DPH are combined with cocaine.','cocaine|diphenhydramine'),
  ('cocaine','dmt','caution','Stimulants increase anxiety levels and the risk of thought loops which can lead to negative experiences','cocaine|dmt'),
  ('cocaine','dom-doi-dob-doc','unsafe','The combined stimulating effects of the two can lead to an uncomfortable body-load, while the focusing effects of cocaine can easily lead to thought loops. Coming down from cocaine while the DOx is still active can be quite anxiogenic','cocaine|dox'),
  ('cocaine','ghb','caution','Stimulants increase respiration rate allowing for a higher dose of sedatives than normal. If the stimulant wears off first the opiate may overcome the individual and cause respiratory arrest. Likewise the ghb/gbl can wear off and leave a dangerous concentration of cocaine behind','cocaine|ghb/gbl'),
  ('cocaine','ketamine','caution','No unexpected interactions, though likely to increase blood pressure but not an issue with sensible doses. Moving around on high doses of this combination may be ill advised due to risk of physical injury.','cocaine|ketamine'),
  ('cocaine','lithium','low_risk_decrease','Lithium may inhibit some of the recreational effects of cocaine.','cocaine|lithium'),
  ('cocaine','lsd','caution','Stimulants increase anxiety levels and the risk of thought loops which can lead to negative experiences','cocaine|lsd'),
  ('cocaine','maois','dangerous','This combination is poorly explored','cocaine|maois'),
  ('cocaine','mdma','caution','Cocaine blocks some of the desirable effects of MDMA while increasing the risk of heart attack.','cocaine|mdma'),
  ('cocaine','mescaline','caution','The focus and anxiety caused by stimulants is magnified by psychedelics and results in an increased risk of thought loops','cocaine|mescaline'),
  ('cocaine','psilocybin','caution','Stimulants increase anxiety levels and the risk of thought loops which can lead to negative experiences','cocaine|mushrooms'),
  ('cocaine','mxe','caution','Stimulants taken with MXE can lead to hypermanic states much more easily, especially if sleep is avoided.','cocaine|mxe'),
  ('cocaine','nbomes','unsafe','Cocaine and NBOMes both provide considerable stimulation. When combined they can result in severe vasoconstriction, tachycardia, hypertension, and in extreme cases heart failure.','cocaine|nbomes'),
  ('cocaine','nitrous-oxide','low_risk_synergy','','cocaine|nitrous'),
  ('cocaine','opioids','dangerous','Stimulants increase respiration rate allowing for a higher dose of opiates than normal. If the stimulant wears off first then the opiate may overcome the individual and cause respiratory arrest.','cocaine|opioids'),
  ('cocaine','pcp','unsafe','This combination can easily lead to hypermanic states','cocaine|pcp'),
  ('cocaine','pregabalin','unsafe','There is a significant risk of seizures from this combination. Stimulants increase respiration rate, allowing for a higher dose of sedatives than normal. If cocaine wears off first, recreational dosages of pregabalin may overcome the individual and cause respiratory arrest. Both substances at recreational dosages strain the heart and may lead to further dangerous heart complications. The combination has a greater risk of methemoglobinemia when higher dosages are combined.','cocaine|pregabalin'),
  ('cocaine','ssris','low_risk_no_synergy','May reduce each others'' effectiveness. Cocaine can reduce mental stability and therefore exacerbate conditions which SSRIs are used to treat.','cocaine|ssris'),
  ('cocaine','tramadol','dangerous','Tramadol and stimulants both increase the risk of seizures.','cocaine|tramadol'),
  ('dextromethorphan','diphenhydramine','unsafe','The combination is reported to reduce the side effects of each drug and potentiate many of the recreational effects. There is a significant risk of serotonin syndrome, increased delirium, CNS depression, cognitive inhibition, risk of physical injury, hyperthermia, mania, paranoia, and psychosis, especially at higher dosages. There is an additional concern of tachycardia, hypertension, and in extreme cases, heart failure. Diphenhydramine is reported to inhibit the CYP2D6 enzyme which can increase levels of DXM. Medical dosages are not reported to be a concern. Caution is strongly recommended with this combination.','dextromethorphan|diphenhydramine'),
  ('dextromethorphan','dmt','low_risk_synergy','','dextromethorphan|dmt'),
  ('dextromethorphan','dom-doi-dob-doc','unsafe','The DOx class as psychedelic stimulants have the potential to mask the effects of DXM and could lead to redosing to an unsafe level. DXM can also potentiate DOx resulting in an unpleasantly intense experience.','dextromethorphan|dox'),
  ('dextromethorphan','ghb','dangerous','Both substances cause ataxia and bring a risk of vomiting and unconsciousness. If the individual falls unconscious while under the influence there is a severe risk of vomit aspiration if they are not placed in the recovery position. This combination is hard to predict','dextromethorphan|ghb/gbl'),
  ('dextromethorphan','ketamine','low_risk_synergy','Both substances primarily exert their effects through NMDA antagonism. Currently, there is no evidence regarding mechanisms that might reduce these effects.','dextromethorphan|ketamine'),
  ('dextromethorphan','lithium','dangerous','There is a risk of serotonin syndrome when combining Lithium with DXM.','dextromethorphan|lithium'),
  ('dextromethorphan','lsd','low_risk_synergy','','dextromethorphan|lsd'),
  ('dextromethorphan','maois','dangerous','High risk of serotonin syndrome','dextromethorphan|maois'),
  ('dextromethorphan','mdma','dangerous','','dextromethorphan|mdma'),
  ('dextromethorphan','mephedrone','dangerous','Risk of serotonin syndrome as both drugs raise serotonin levels. In addition to concerns of high blood pressure and unnecessary strain on the heart. As well as potentially causing anxiety and greater physical discomfort due to the combination.','dextromethorphan|mephedrone'),
  ('dextromethorphan','mescaline','low_risk_synergy','','dextromethorphan|mescaline'),
  ('dextromethorphan','psilocybin','low_risk_synergy','','dextromethorphan|mushrooms'),
  ('dextromethorphan','mxe','unsafe','There is a risk of serotonin syndrome when combining DXM with MXE, due to DXM and MXE both being SRI’s. MXE and DXM having notable affinities for the serotonin transporter.','dextromethorphan|mxe'),
  ('dextromethorphan','nbomes','unsafe','','dextromethorphan|nbomes'),
  ('dextromethorphan','nitrous-oxide','low_risk_synergy','','dextromethorphan|nitrous'),
  ('dextromethorphan','opioids','dangerous','CNS depression, difficult breathing, heart issues, hepatoxic, just very unsafe combination all around. Additionally if one takes DXM, their tolerance of opiates goes down slightly, thus causing additional synergistic effects.','dextromethorphan|opioids'),
  ('dextromethorphan','pcp','dangerous','','dextromethorphan|pcp'),
  ('dextromethorphan','pregabalin','unsafe','Pregabalin and DXM may increase each other’s effects such as inhibition, dizziness, sedation. At higher doses this can lead to unexpected loss of consciousness. Both drugs have seizure concerns which is greatly increased in combination.','dextromethorphan|pregabalin'),
  ('dextromethorphan','ssris','dangerous','High risk of serotonin syndrome.','dextromethorphan|ssris'),
  ('dextromethorphan','tramadol','dangerous','','dextromethorphan|tramadol'),
  ('diphenhydramine','dmt','caution','At 25-50mg, DPH may assist with side effects of the DMT such as nausea and anxiety. At higher dosages, the combination of a deliriant (DPH) and DMT is cautioned against. DMT is likely to increase the deliriant and negative effects of DPH, in addition to increasing the risk of severe injury and mental trauma.','diphenhydramine|dmt'),
  ('diphenhydramine','dom-doi-dob-doc','caution','At 25-50mg, DPH may assist with side effects of DOx drugs such as nausea and anxiety. At higher dosages, the combination of a deliriant (DPH) and DOx drugs is cautioned against. DOx drugs are likely to increase the deliriant and negative effects of DPH, in addition to increasing the risk of severe injury and mental trauma. DOx drugs and DPH at recreational dosages have additional cardiac concerns such as vasoconstriction, tachycardia, hypertension, which in combination may be exacerbated.','diphenhydramine|dox'),
  ('diphenhydramine','ghb','dangerous','Both substances are CNS depressants, potentiating each other strongly and unpredictably, raising the chances of memory loss, severe ataxia, and unconsciousness. The interaction will cause greater inhibition and risk of injury. If the user falls unconscious it is strongly recommended to put them into the recovery position and monitor breathing.','diphenhydramine|ghb/gbl'),
  ('diphenhydramine','ketamine','dangerous','Both substances potentiate the ataxia and sedation caused by the other and can lead to unexpected loss of consciousness at high doses. While unconscious, vomit aspiration is a risk if not placed in the recovery position. Ketamine has a high likelihood of increasing DPH''s deliriant effects at higher dosages and can greatly increase the risk of injury, mania, and psychosis. Medical dosages of both substances are unlikely to cause concern.','diphenhydramine|ketamine'),
  ('diphenhydramine','lithium','caution','There is a concern of serotonin syndrome at higher dosages of this combination. Caution is recommended in restricting diphenhydramine to medical dosages (25-50mg). Lithium and diphenhydramine both have concerns of QT prolongation which may be increased when taken in combination; risks increase due to a variety of factors such as the health of the user and drug dosages. Additionally, the combination may increase each drug''s side effects, such as dizziness and loss of consciousness.','diphenhydramine|lithium'),
  ('diphenhydramine','lsd','caution','At 25-50mg, DPH may assist with side effects of the LSD such as nausea and anxiety. At higher dosages, the combination of a deliriant (DPH) and LSD is cautioned against. LSD is likely to increase the deliriant and negative effects of DPH, in addition to increasing the risk of severe injury and mental trauma. LSD and DPH at recreational dosages have additional cardiac concerns such as vasoconstriction, tachycardia, hypertension, which in combination may be exacerbated.','diphenhydramine|lsd'),
  ('diphenhydramine','maois','unsafe','There is a significant risk of serotonin syndrome with this combination. Monoamine oxidase A inhibitors may extend and increase the anticholinergic effects of DPH. The combination increases each other’s side effects, such as drowsiness, dizziness, dry mouth, and headaches. Medical dosages are not reported to be of concern.','diphenhydramine|maois'),
  ('diphenhydramine','mephedrone','dangerous','There is a high risk of serotonin syndrome at recreational dosages. Both can dull each other''s effects, so if one wears off before the other it''s possible to overdose due to the lack of counteraction. Medical dosages are reported not to be a concern for the general population. Both substances affect the heart and may lead to further dangerous heart complications at higher dosages. The combination may increase each other''s side effects, such as dizziness and drowsiness. At higher dosages, the combination may increase each other''s side effects, such as delirium, mania, and psychosis.','diphenhydramine|mephedrone'),
  ('diphenhydramine','mescaline','caution','At 25-50mg, DPH may assist with side effects of the mescaline such as nausea and anxiety. At higher dosages, the combination of a deliriant (DPH) and mescaline is cautioned against. Mescaline is likely to increase the deliriant and negative effects of DPH, in addition to increasing the risk of severe injury and mental trauma.','diphenhydramine|mescaline'),
  ('diphenhydramine','psilocybin','caution','At 25-50mg, DPH may assist with side effects of the psilocybin such as nausea and anxiety. At higher dosages, the combination of a deliriant (DPH) and psilocybin is cautioned against. Psilocybin is likely to increase the deliriant and negative effects of DPH, in addition to increasing the risk of severe injury and mental trauma.','diphenhydramine|mushrooms'),
  ('diphenhydramine','mxe','dangerous','There is a high risk of serotonin syndrome from this combination. Both substances potentiate the ataxia and sedation caused by the other and can lead to unexpected loss of consciousness at high doses. While unconscious, vomit aspiration is a risk if not placed in the recovery position. MXE has a high likelihood of increasing DPH''s deliriant effects at higher dosages and can greatly increase the risk of injury, mania, and psychosis. Medical dosages are unlikely to be of concern.','diphenhydramine|mxe'),
  ('diphenhydramine','nbomes','caution','At 25-50mg, DPH may assist with side effects of the NBOMe drugs such as nausea and anxiety. At higher dosages, the combination of a deliriant (DPH) and NBOMe drugs is cautioned against. NBOMes are likely to increase the deliriant and negative effects of DPH, in addition to increasing the risk of severe injury and mental trauma. NBOMes and DPH at recreational dosages have additional cardiac concerns such as vasoconstriction, tachycardia, hypertension, which in combination may be exacerbated.','diphenhydramine|nbomes'),
  ('diphenhydramine','opioids','unsafe','Both substances are CNS depressants, potentiating each other strongly and unpredictably, raising the chances of memory loss, severe ataxia, and unconsciousness. The interaction will cause greater inhibition and risk of injury. DPH reduces histamine release by opioids, which reduces the itching side effect from opioids. DPH may reduce the nausea caused by opioids. DPH inhibits CYP2D6 activity which can lead to a reduction of effects in some opioids and potentiation of effects in others.','diphenhydramine|opioids'),
  ('diphenhydramine','pregabalin','unsafe','There is a significant risk of seizures from this combination. The combination is likely to increase each other’s negative side effects, such as nausea, dizziness, and loss of consciousness. At higher dosages, pregabalin is likely to increase diphenhydramine’s deliriant effects, inhibition, and risk of injury. Medical dosages are not reported to be a concern.','diphenhydramine|pregabalin'),
  ('diphenhydramine','ssris','dangerous','There is a high risk of serotonin syndrome at recreational dosages. Medical dosages are reported not to be a concern for the general population. The combination may increase each other''s side effects, such as dizziness and drowsiness.','diphenhydramine|ssris'),
  ('diphenhydramine','tramadol','dangerous','Both drugs increase the risk of serotonin syndrome. While at medical dosages, this is unlikely to be of concern, recreational doses should be avoided. Diphenhydramine may increase tramadol’s seizure risk.','diphenhydramine|tramadol'),
  ('dmt','dom-doi-dob-doc','low_risk_synergy','','dmt|dox'),
  ('dmt','ghb','low_risk_decrease','','dmt|ghb/gbl'),
  ('dmt','ketamine','low_risk_synergy','','dmt|ketamine'),
  ('dmt','lithium','dangerous','There are a large number of reports indicating a high seizure and psychosis risk from this combination.','dmt|lithium'),
  ('dmt','lsd','low_risk_synergy','','dmt|lsd'),
  ('dmt','maois','low_risk_synergy','','dmt|maois'),
  ('dmt','mdma','low_risk_synergy','','dmt|mdma'),
  ('dmt','mephedrone','low_risk_synergy','Stimulants increase anxiety levels and the risk of thought loops which can lead to negative experiences','dmt|mephedrone'),
  ('dmt','mescaline','low_risk_synergy','','dmt|mescaline'),
  ('dmt','psilocybin','low_risk_synergy','','dmt|mushrooms'),
  ('dmt','mxe','low_risk_synergy','','dmt|mxe'),
  ('dmt','nbomes','low_risk_synergy','','dmt|nbomes'),
  ('dmt','nitrous-oxide','low_risk_synergy','','dmt|nitrous'),
  ('dmt','opioids','low_risk_no_synergy','','dmt|opioids'),
  ('dmt','pcp','low_risk_synergy','','dmt|pcp'),
  ('dmt','pregabalin','low_risk_synergy','Pregabalin may reduce the anxiety and other possible side effects of DMT. Additionally, the combination may increase inhibition, dizziness, and risk of injury.','dmt|pregabalin'),
  ('dmt','ssris','low_risk_decrease','','dmt|ssris'),
  ('dmt','tramadol','unsafe','Tramadol is well known to lower seizure threshold and psychedelics also cause occasional seizures.','dmt|tramadol'),
  ('dom-doi-dob-doc','ghb','low_risk_decrease','','dox|ghb/gbl'),
  ('dom-doi-dob-doc','ketamine','low_risk_synergy','Ketamine and psychedelics tend to potentiate each other - go slowly.','dox|ketamine'),
  ('dom-doi-dob-doc','lithium','dangerous','There are a large number of reports indicating a high seizure and psychosis risk from this combination.','dox|lithium'),
  ('dom-doi-dob-doc','lsd','low_risk_synergy','','dox|lsd'),
  ('dom-doi-dob-doc','maois','caution','MAO-B inhibitors can increase the potency and duration of phenethylamines unpredictably','dox|maois'),
  ('dom-doi-dob-doc','mdma','caution','The combined stimulating effects of the two can be uncomfortable. Coming down on the MDMA while the DOx is still active can be quite anxiogenic.','dox|mdma'),
  ('dom-doi-dob-doc','mephedrone','caution','The anxiogenic and focusing effects of stimulants increase the chance of unpleasant thought loops, in addition to the possible negative side effects of coming down from said stimulant while on a psychedelic. In extreme cases, stimulants, especially in combination can result in severe vasoconstriction, tachycardia, hypertension, and heart failure.','dox|mephedrone'),
  ('dom-doi-dob-doc','mescaline','caution','','dox|mescaline'),
  ('dom-doi-dob-doc','psilocybin','low_risk_synergy','','dox|mushrooms'),
  ('dom-doi-dob-doc','mxe','caution','As an NMDA antagonist MXE potentiates DOx which can be unpleasantly intense','dox|mxe'),
  ('dom-doi-dob-doc','nbomes','caution','','dox|nbomes'),
  ('dom-doi-dob-doc','nitrous-oxide','low_risk_synergy','','dox|nitrous'),
  ('dom-doi-dob-doc','opioids','low_risk_no_synergy','No unexpected interactions.','dox|opioids'),
  ('dom-doi-dob-doc','pcp','unsafe','Details of this combination are not well understood but PCP generally interacts in an unpredictable manner.','dox|pcp'),
  ('dom-doi-dob-doc','pregabalin','caution','Caution should be given due to DOx drugs stimulating effects and pregabalin’s seizure concerns at higher dosages. Pregabalin may reduce the vasoconstriction, anxiety, and other side effects of DOx drugs. Additionally, Pregabalin may increase DOx drugs inhibition and risk of injury.','dox|pregabalin'),
  ('dom-doi-dob-doc','ssris','low_risk_decrease','','dox|ssris'),
  ('dom-doi-dob-doc','tramadol','unsafe','Tramadol is well known to lower seizure threshold and psychedelics also cause occasional seizures.','dox|tramadol'),
  ('ghb','ketamine','dangerous','Both substances cause ataxia and bring a risk of vomiting and unconsciousness. If the user falls unconscious while under the influence there is a severe risk of vomit aspiration if they are not placed in the recovery position.','ghb/gbl|ketamine'),
  ('ghb','lsd','low_risk_decrease','','ghb/gbl|lsd'),
  ('ghb','maois','low_risk_synergy','','ghb/gbl|maois'),
  ('ghb','mdma','caution','Large amounts of GHB/GBL may overwhelm the effects of MDMA on the comedown.','ghb/gbl|mdma'),
  ('ghb','mephedrone','caution','Both can dull each other''s effects, so if one wears off before the other it''s possible to overdose due to the lack of counteraction. Both substances affect the heart and may lead to further dangerous heart complications at higher dosages. Additionally, the combination may increase the negative side effects of each other.','ghb/gbl|mephedrone'),
  ('ghb','mescaline','low_risk_decrease','','ghb/gbl|mescaline'),
  ('ghb','psilocybin','low_risk_decrease','','ghb/gbl|mushrooms'),
  ('ghb','mxe','dangerous','Both substances cause ataxia and bring a risk of vomiting and unconsciousness. If the individual falls unconscious while under the influence there is a severe risk of vomit aspiration if they are not placed in the recovery position.','ghb/gbl|mxe'),
  ('ghb','nbomes','low_risk_decrease','','ghb/gbl|nbomes'),
  ('ghb','nitrous-oxide','caution','Both substances potentiate the ataxia and sedation caused by the other and can lead to unexpected loss of consciousness at high doses. While unconscious, vomit aspiration is a risk if not placed in the recovery position. Memory blackouts are likely.','ghb/gbl|nitrous'),
  ('ghb','opioids','dangerous','The two substances potentiate each other strongly and unpredictably, very rapidly leading to unconsciousness. While unconscious, vomit aspiration is a risk if not placed in the recovery position','ghb/gbl|opioids'),
  ('ghb','pcp','dangerous','Details of this combination are not well understood but PCP generally interacts in an unpredictable manner.','ghb/gbl|pcp'),
  ('ghb','pregabalin','dangerous','The two substances potentiate each other strongly and unpredictably, and may rapidly lead to unconsciousness. They both increase each other''s side effects such as ataxia, sedation, and CNS depression. Blackout and memory loss risk is significantly increased. If the user falls unconscious while under the influence there is a severe risk of vomit aspiration if they are not placed in the recovery position. There is an increased risk of seizures from this combination.','ghb/gbl|pregabalin'),
  ('ghb','ssris','low_risk_no_synergy','','ghb/gbl|ssris'),
  ('ghb','tramadol','dangerous','The sedative effects of this combination can lead to dangerous respiratory depression.','ghb/gbl|tramadol'),
  ('ketamine','lithium','low_risk_no_synergy','Lithium may enhance and prolong the antidepressant effects of ketamine.','ketamine|lithium'),
  ('ketamine','lsd','low_risk_synergy','','ketamine|lsd'),
  ('ketamine','maois','caution','MAO-B inhibitors appear to increase the potency of Ketamine. MAO-A inhbitors have some negative reports associated with the combination but there isn''t much information available','ketamine|maois'),
  ('ketamine','mdma','low_risk_synergy','No unexpected interactions, though likely to increase blood pressure but not an issue with sensible doses. Moving around on high doses of  this combination may be ill advised due to risk of physical injury.','ketamine|mdma'),
  ('ketamine','mescaline','low_risk_synergy','','ketamine|mescaline'),
  ('ketamine','psilocybin','low_risk_synergy','','ketamine|mushrooms'),
  ('ketamine','mxe','low_risk_synergy','','ketamine|mxe'),
  ('ketamine','nbomes','low_risk_synergy','','ketamine|nbomes'),
  ('ketamine','nitrous-oxide','low_risk_synergy','','ketamine|nitrous'),
  ('ketamine','opioids','dangerous','Both substances bring a risk of vomiting and unconsciousness. If the user falls unconscious while under the influence there is a severe risk of vomit aspiration if they are not placed in the recovery position.','ketamine|opioids'),
  ('ketamine','pcp','low_risk_synergy','','ketamine|pcp'),
  ('ketamine','pregabalin','caution','Pregabalin and ketamine may synergize and increase each other''s negative side effects such as nausea, dizziness, and loss of consciousness. Caution is advised for beyond medical dosages due to seizure concerns, and medical dosages for individuals with higher risk seizure profiles and or behavior.','ketamine|pregabalin'),
  ('ketamine','ssris','low_risk_no_synergy','','ketamine|ssris'),
  ('ketamine','tramadol','dangerous','','ketamine|tramadol'),
  ('lithium','lsd','dangerous','There are a large number of reports indicating a high seizure and psychosis risk from this combination.','lithium|lsd'),
  ('lithium','mdma','dangerous','High risk of serotonin syndrome','lithium|mdma'),
  ('lithium','mescaline','dangerous','There are a large number of reports indicating a high seizure and psychosis risk from this combination.','lithium|mescaline'),
  ('lithium','psilocybin','dangerous','There are a large number of reports indicating a high seizure and psychosis risk from this combination.','lithium|mushrooms'),
  ('lithium','mxe','dangerous','There is a risk of serotonin syndrome when combining Lithium with MXE, as Lithium can induce serotonin syndrome in conjunction with other serotonergic drugs, and MXE has shown a notable affinity for the serotonin transporter.','lithium|mxe'),
  ('lithium','nbomes','dangerous','There are a large number of reports indicating a high seizure and psychosis risk from this combination.','lithium|nbomes'),
  ('lithium','nitrous-oxide','low_risk_no_synergy','We are unable to find a report of concerns for CNS depression caused by Lithium.','lithium|nitrous'),
  ('lithium','ssris','low_risk_no_synergy','This interaction is used in medical settings without reported issues. If this combination is taken, caution would be recommended if any other drugs are planned to be taken on top of these that may have serotonergic activity.','lithium|ssris'),
  ('lithium','tramadol','dangerous','Tramadol and Lithium both increase the risk of seizures and serotonin syndrome.','lithium|tramadol'),
  ('lsd','maois','low_risk_decrease','','lsd|maois'),
  ('lsd','mdma','low_risk_synergy','','lsd|mdma'),
  ('lsd','mephedrone','caution','The anxiogenic and focusing effects of stimulants increase the chance of unpleasant thought loops, in addition to the possible negative side effects of coming down from said stimulant while on a psychedelic. In extreme cases, stimulants, especially in combination can result in severe vasoconstriction, tachycardia, hypertension, and heart failure.','lsd|mephedrone'),
  ('lsd','mescaline','low_risk_synergy','','lsd|mescaline'),
  ('lsd','psilocybin','low_risk_synergy','','lsd|mushrooms'),
  ('lsd','mxe','low_risk_synergy','','lsd|mxe'),
  ('lsd','nbomes','low_risk_synergy','','lsd|nbomes'),
  ('lsd','nitrous-oxide','low_risk_synergy','','lsd|nitrous'),
  ('lsd','opioids','low_risk_no_synergy','','lsd|opioids'),
  ('lsd','pcp','low_risk_synergy','','lsd|pcp'),
  ('lsd','pregabalin','caution','Caution should be given due to LSD’s stimulating effects and pregabalin’s seizure concerns at higher dosages. Pregabalin may reduce the vasoconstriction, anxiety, and other side effects of LSD. Additionally, Pregabalin may increase LSD’s inhibition and risk of injury.','lsd|pregabalin'),
  ('lsd','ssris','low_risk_decrease','','lsd|ssris'),
  ('lsd','tramadol','unsafe','Tramadol is well known to lower seizure threshold and psychedelics also cause occasional seizures.','lsd|tramadol'),
  ('maois','mdma','dangerous','MAO-B inhibitors can increase the potency and duration of phenethylamines unpredictably. MAO-A inhibitors with MDMA will lead to hypertensive crises.','maois|mdma'),
  ('maois','mescaline','caution','','maois|mescaline'),
  ('maois','psilocybin','low_risk_synergy','','maois|mushrooms'),
  ('maois','mxe','unsafe','MAO-B inhibitors appear to increase the potency of MXE. MAO-A inhbitors have some negative reports associated with the combination but there isn''t much information available','maois|mxe'),
  ('maois','nbomes','caution','MAO-B inhibitors can increase the potency and duration of phenethylamines unpredictably','maois|nbomes'),
  ('maois','nitrous-oxide','low_risk_no_synergy','','maois|nitrous'),
  ('maois','opioids','caution','Coadministration of monoamine oxidase inhibitors (MAOIs) with certain opioids has been associated with rare reports of severe and fatal adverse reactions. There appear to be two types of interaction, an excitatory and a depressive one. Symptoms of the excitatory reaction may include agitation, headache, diaphoresis, hyperpyrexia, flushing, shivering, myoclonus, rigidity, tremor, diarrhea, hypertension, tachycardia, seizures, and coma. Death has occurred in some cases.','maois|opioids'),
  ('maois','pcp','dangerous','This combination is very poorly explored','maois|pcp'),
  ('maois','ssris','dangerous','','maois|ssris'),
  ('maois','tramadol','dangerous','','maois|tramadol'),
  ('mdma','mephedrone','dangerous','Risk of serotonin syndrome as both drugs raise serotonin levels. Stimulants also increase the neurotoxic effects of MDMA, in addition to concerns of high blood pressure and unnecessary strain on the heart. As well as potentially causing anxiety and greater physical discomfort due to the combination.','mdma|mephedrone'),
  ('mdma','mescaline','low_risk_synergy','','mdma|mescaline'),
  ('mdma','psilocybin','low_risk_synergy','','mdma|mushrooms'),
  ('mdma','mxe','caution','There have been reports of risky serotonergic interactions when the two are taken at the same time, but MXE taken to the end of an MDMA experience does not appear to cause the same issues.','mdma|mxe'),
  ('mdma','nbomes','caution','','mdma|nbomes'),
  ('mdma','nitrous-oxide','low_risk_synergy','','mdma|nitrous'),
  ('mdma','opioids','low_risk_no_synergy','','mdma|opioids'),
  ('mdma','pcp','unsafe','This combination can easily lead to hypermanic states','mdma|pcp'),
  ('mdma','pregabalin','unsafe','There is a significant risk of seizures from this combination. Amphetamines increase respiration rate allowing for a higher dose of sedatives than normal. If amphetamines wears off first, recreational dosages of pregabalin may overcome the individual and cause respiratory arrest. Both substances at recreational dosages cause strain of the heart and may lead to further dangerous heart complications. Medical dosages are not reported to be a concern','mdma|pregabalin'),
  ('mdma','ssris','low_risk_decrease','','mdma|ssris'),
  ('mdma','tramadol','dangerous','Tramadol and stimulants both increase the risk of seizures.','mdma|tramadol'),
  ('mephedrone','psilocybin','low_risk_synergy','Stimulants increase anxiety levels and the risk of thought loops which can lead to negative experiences','mephedrone|mushrooms'),
  ('mephedrone','opioids','caution','Stimulants increase respiration rate allowing a higher dose of opiates. If the stimulant wears off first then the opiate may overcome the patient and cause respiratory arrest.','mephedrone|opioids'),
  ('mephedrone','pregabalin','unsafe','There is a significant risk of seizures from this combination. Mephedrone increases respiration rate allowing for a higher dose of sedatives than normal. If mephedrone wears off first, recreational dosages of pregabalin may overcome the individual and cause respiratory arrest. Both substances at recreational dosages cause strain of the heart and may lead to further dangerous heart complications.','mephedrone|pregabalin'),
  ('mephedrone','tramadol','dangerous','There is a high risk of serotonin syndrome and seizures at recreational dosages. Both substances affect the heart and may lead to further dangerous heart complications at higher dosages. Both can dull each other''s effects, so if one wears off before the other it''s possible to overdose due to the lack of counteraction. The combination may increase each other''s side effects, such as dizziness and drowsiness. At higher dosages, the combination may increase each other’s side effects, such as delirium, mania, and psychosis.','mephedrone|tramadol'),
  ('mescaline','psilocybin','low_risk_synergy','','mescaline|mushrooms'),
  ('mescaline','mxe','low_risk_synergy','','mescaline|mxe'),
  ('mescaline','nbomes','caution','','mescaline|nbomes'),
  ('mescaline','nitrous-oxide','low_risk_synergy','','mescaline|nitrous'),
  ('mescaline','opioids','low_risk_no_synergy','','mescaline|opioids'),
  ('mescaline','pcp','low_risk_synergy','','mescaline|pcp'),
  ('mescaline','pregabalin','caution','Caution should be given due to mescaline’s stimulating effects and pregabalin’s seizure concerns at higher dosages. Pregabalin may reduce the vasoconstriction, anxiety, and other side effects of mescaline. Additionally, Pregabalin may increase mescaline’s inhibition and risk of injury.','mescaline|pregabalin'),
  ('mescaline','ssris','low_risk_decrease','','mescaline|ssris'),
  ('mescaline','tramadol','unsafe','This combination can cause seizures due to the lowering of the threshold by tramadol and the potential of mescaline to cause seziures.','mescaline|tramadol'),
  ('psilocybin','mxe','low_risk_synergy','','mushrooms|mxe'),
  ('psilocybin','nbomes','low_risk_synergy','','mushrooms|nbomes'),
  ('psilocybin','nitrous-oxide','low_risk_synergy','','mushrooms|nitrous'),
  ('psilocybin','opioids','low_risk_no_synergy','','mushrooms|opioids'),
  ('psilocybin','pcp','low_risk_synergy','','mushrooms|pcp'),
  ('psilocybin','pregabalin','low_risk_synergy','Pregabalin may reduce the anxiety and other possible side effects of Psilocybin Mushrooms. Additionally, the combination may increase inhibition, dizziness, and risk of injury.','mushrooms|pregabalin'),
  ('psilocybin','ssris','low_risk_decrease','','mushrooms|ssris'),
  ('psilocybin','tramadol','unsafe','Tramadol is well known to lower seizure threshold and psychedelics also cause occasional seizures.','mushrooms|tramadol'),
  ('mxe','nbomes','caution','As an NMDA antagonist MXE potentiates NBOMes which can be unpleasantly intense','mxe|nbomes'),
  ('mxe','nitrous-oxide','low_risk_synergy','','mxe|nitrous'),
  ('mxe','opioids','dangerous','This combination can potentiate the effects of the opioid','mxe|opioids'),
  ('mxe','pcp','caution','There are no reports available about this combination','mxe|pcp'),
  ('mxe','pregabalin','caution','Pregabalin and MXE may synergize and increase each other’s negative side effects such as nausea, dizziness, and loss of consciousness. Caution is advised for anything above low dosages due to seizure concerns, and all dosages for individuals with higher risk seizure profiles and or behavior.','mxe|pregabalin'),
  ('mxe','ssris','caution','Depending on the SSRI this combination can be unpredictable','mxe|ssris'),
  ('mxe','tramadol','dangerous','','mxe|tramadol'),
  ('nbomes','nitrous-oxide','low_risk_synergy','','nbomes|nitrous'),
  ('nbomes','opioids','low_risk_no_synergy','','nbomes|opioids'),
  ('nbomes','pcp','low_risk_synergy','','nbomes|pcp'),
  ('nbomes','pregabalin','dangerous','NBOMes and pregabalin are reported to have significant seizure concerns that are likely to increase in combination. Therapeutic dosages of pregabalin are unlikely to be of concern and may decrease NBOMes side effects such as vasoconstriction and anxiety.','nbomes|pregabalin'),
  ('nbomes','ssris','low_risk_decrease','','nbomes|ssris'),
  ('nbomes','tramadol','unsafe','Tramadol is well known to lower seizure threshold and NBOMes have also shown a tendency to cause severe seizures','nbomes|tramadol'),
  ('nitrous-oxide','opioids','caution','Both substances potentiate the ataxia and sedation caused by the other and can lead to unexpected loss of consciousness at high doses. While unconscious, vomit aspiration is a risk if not placed in the recovery position. Memory blackouts are likely.','nitrous|opioids'),
  ('nitrous-oxide','pcp','low_risk_synergy','','nitrous|pcp'),
  ('nitrous-oxide','pregabalin','caution','Both substances potentiate the ataxia and sedation caused by the other, and may increase the risk of loss of consciousness at higher dosages. While unconscious, vomit aspiration is a risk if not placed in the recovery position. The combination may increase inhibition and risk of injury. Additionally, abuse of nitrous while under the influence of pregabalin may increase the risk of seizures. Medical dosages are unlikely to be a concern.','nitrous|pregabalin'),
  ('nitrous-oxide','ssris','low_risk_no_synergy','','nitrous|ssris'),
  ('nitrous-oxide','tramadol','caution','Both substances potentiate the ataxia and sedation caused by the other and can lead to unexpected loss of consciousness at high doses. While unconscious, vomit aspiration is a risk if not placed in the recovery position. Memory blackouts are likely.','nitrous|tramadol'),
  ('opioids','pcp','caution','PCP can reduce opioid tolerance, increasing the risk of overdose','opioids|pcp'),
  ('opioids','pregabalin','dangerous','','opioids|pregabalin'),
  ('opioids','ssris','low_risk_no_synergy','There have been some case reports of serotonin syndrome in individuals who were given a combination of opioids and SSRIs. Other research has indicated a small increase in overdose risk for people who are prescribed CYP2D6-inhibiting SSRIs (e.g. fluoxetine and paroxetine) with oxycodone. Overall, risk is low with this combination but, as always, be mindful of your consumption.','opioids|ssris'),
  ('opioids','tramadol','dangerous','Concomitant use of tramadol increases the seizure risk in individuals taking other opioids. These agents are often individually epileptogenic and may have additive effects on seizure threshold during coadministration. Central nervous system- and/or respiratory-depressant effects may be additively or synergistically present','opioids|tramadol'),
  ('pcp','ssris','unsafe','Details of this combination are not well understood but PCP generally interacts in an unpredictable manner.','pcp|ssris'),
  ('pcp','tramadol','dangerous','','pcp|tramadol'),
  ('pregabalin','tramadol','unsafe','There is a significant risk of seizures. Both substances are CNS depressants, potentiating each other strongly and unpredictably, raising the chances of memory loss, severe ataxia, and unconsciousness. The interaction will cause greater inhibition and risk of injury. If the user falls unconscious it is strongly recommended to put them into the recovery position and monitor breathing. Medical dosages are not reported to be a concern.','pregabalin|tramadol'),
  ('ssris','tramadol','dangerous','','ssris|tramadol')
) as v(a,b,status,note,pair)
join public.unified_tags ta on ta.slug = v.a
join public.unified_tags tb on tb.slug = v.b
where ta.id <> tb.id
on conflict (tag_a_id, tag_b_id) do update
  set status = excluded.status, note = excluded.note,
      source = excluded.source, source_url = excluded.source_url,
      source_pair = excluded.source_pair, updated_at = now();

do $verify$
declare v_n int; v_d int; v_notes int; v_bad int; v_digest text;
begin
  select count(*), count(*) filter (where status='dangerous'), count(note)
    into v_n, v_d, v_notes from public.substance_interactions;
  if v_n <> 421 then raise exception 'interactions: expected 421 pairs, got %', v_n; end if;
  if v_d  <> 82  then raise exception 'interactions: expected 82 dangerous, got %', v_d; end if;
  if v_notes <> 221 then raise exception 'interactions: expected 221 notes, got %', v_notes; end if;

  -- Spot-check two cells where being wrong is fatal, by SLUG rather than by
  -- position, so a remapping cannot quietly satisfy the count checks above.
  if not exists (select 1 from public.substance_interactions i
      join public.unified_tags a on a.id=i.tag_a_id join public.unified_tags b on b.id=i.tag_b_id
     where i.status='dangerous' and array['ghb','opioids'] <@ array[a.slug,b.slug]) then
    raise exception 'interactions: GHB + opioids is not dangerous - mapping is wrong'; end if;
  if not exists (select 1 from public.substance_interactions i
      join public.unified_tags a on a.id=i.tag_a_id join public.unified_tags b on b.id=i.tag_b_id
     where i.status='dangerous' and array['mdma','maois'] <@ array[a.slug,b.slug]) then
    raise exception 'interactions: MDMA + MAOIs is not dangerous - mapping is wrong'; end if;

  select count(*) into v_bad from public.substance_interactions
   where source is null or source_url is null or source = '';
  if v_bad > 0 then raise exception 'interactions: % rows without attribution', v_bad; end if;

  -- Content fingerprint. Counts and spot-checks can all pass while a single
  -- note or status is wrong; this cannot. Byte order (collate "C") is required
  -- so the digest matches the generator, which sorts by Unicode code point.
  select encode(sha256(convert_to(string_agg(line, chr(30) order by line collate "C"),'UTF8')),'hex')
    into v_digest
    from (select least(a.slug,b.slug)||chr(31)||greatest(a.slug,b.slug)||chr(31)
                 ||i.status||chr(31)||coalesce(i.note,'') as line
            from public.substance_interactions i
            join public.unified_tags a on a.id=i.tag_a_id
            join public.unified_tags b on b.id=i.tag_b_id) s;
  if v_digest <> '3b6768cc649dc2868c3451dee07b202c043cdad4d64b7ad22c101f9805fb5142' then
    raise exception 'interactions: content digest % does not match the imported snapshot', v_digest;
  end if;
end
$verify$;
