-- Phone numbers: one stored format, +<calling code><national number> (E.164).
--
-- WHY A TRIGGER. venues.phone had ~20 writers (source-* fns, the patroc /
-- testfinder / aids-ch parsers, the CSV import, venue-contact-enrich,
-- venue-accessibility-osm, commit_venue_staging_item, the CMS editor) and none
-- of them normalised. Measured 2026-10-01 over 7,965 live venues with a phone:
-- ~1,250 national or human-formatted ("(415) 551-2500", "020 7452 3000"), and
-- of the 5,623 that LOOKED like E.164, 235 were wrong — the national trunk
-- prefix carried over behind the calling code ("+66 0 26370507",
-- "+32 0 25035918", "+86 0 1082863879"). organizations: 827 phones, 22 E.164.
-- Patching each writer leaves the next one open, so the format is enforced
-- where every write lands: a BEFORE trigger on venues, organizations, hotels.
--
-- WHY GENERATED RULES. Turning a national number into E.164 needs per-country
-- facts a hand list gets wrong: the trunk prefix is "0" in most of Europe but
-- "1" in NANP, "8" in Russia, "06" in Hungary, and Italy KEEPS its 0 after
-- +39. phone_country_rules is a projection of libphonenumber's metadata, made
-- by scripts/data-quality/generate-phone-rules.mjs — regenerate, never edit.
--
-- VALIDATED AGAINST libphonenumber, not by reading. The same algorithm was run
-- in JS beside libphonenumber-js over all 8,344 venue + organization phones
-- readable through the anon API: of the 8,045 both accept, 8,040 come out
-- byte-identical, and the 5 that differ are US numbers ("773-743-5772") on
-- venues whose country_id is wrong, which libphonenumber reads as German /
-- Finnish / Indian / British. The pattern used here is the per-country
-- general number pattern, a little looser than libphonenumber's per-type
-- check, so ~60 numbers in old national plans (pre-2021 Colombia, pre-ninth-
-- digit Brazil) are accepted rather than discarded — the FORMAT is still
-- uniform, which is what this file promises; dialability is not re-verified.
--
-- WHAT IS NOT CONVERTIBLE IS NOT GUESSED. ~260 venue numbers fail (wrong digit
-- count, two numbers concatenated, a calling code that does not exist). The
-- column is cleared — so it only ever holds the one format — and the original
-- value is kept on the row at enrichment_status.phone_rejected {raw, reason,
-- country, at}, so nothing is lost and a human can repair it.
-- needs_attention is deliberately NOT raised: that flag gates visibility on
-- some entities, and a bad phone number is no reason to unpublish a venue.

-- ─── 1. Rules ────────────────────────────────────────────────────────────────

create table if not exists public.phone_country_rules (
  country_code      text primary key,
  calling_code      text not null,
  national_prefixes text[] not null default '{}',
  nsn_pattern       text not null,
  nsn_lengths       int[] not null,
  is_main_country   boolean not null
);

comment on table public.phone_country_rules is
  'Per-country phone numbering rules (calling code, trunk prefixes, national number pattern), generated from libphonenumber metadata by scripts/data-quality/generate-phone-rules.mjs. Read by canonicalize_phone(). Regenerate; do not edit by hand.';

create index if not exists phone_country_rules_calling_code_idx
  on public.phone_country_rules (calling_code);

alter table public.phone_country_rules enable row level security;
drop policy if exists phone_country_rules_read on public.phone_country_rules;
create policy phone_country_rules_read on public.phone_country_rules
  for select using (true);
grant select on public.phone_country_rules to anon, authenticated, service_role;

-- Generated by scripts/data-quality/generate-phone-rules.mjs from libphonenumber-js 1.13.14 metadata.max.json.
-- 245 countries. Do not edit by hand; regenerate.
insert into public.phone_country_rules (country_code, calling_code, national_prefixes, nsn_pattern, nsn_lengths, is_main_country) values
  ('AC', '247', '{}', '(?:[01589]\d|[2-467])\d{4}', '{5,6}', true),
  ('AD', '376', '{}', '(?:1|6\d)\d{7}|[135-9]\d{5}', '{6,8,9}', true),
  ('AE', '971', '{0}', '(?:[4-7]\d|9[0-689])\d{7}|800\d{2,9}|[2-4679]\d{7}', '{5,6,7,8,9,10,11,12}', true),
  ('AF', '93', '{0}', '[2-7]\d{8}', '{9}', true),
  ('AG', '1', '{1}', '(?:268|[58]\d\d|900)\d{7}', '{10}', false),
  ('AI', '1', '{1}', '(?:264|[58]\d\d|900)\d{7}', '{10}', false),
  ('AL', '355', '{0}', '(?:700\d\d|900)\d{3}|8\d{5,7}|(?:[2-5]|6\d)\d{7}', '{6,7,8,9}', true),
  ('AM', '374', '{0}', '(?:[1-489]\d|55|60|77)\d{6}', '{8}', true),
  ('AO', '244', '{}', '[29]\d{8}', '{9}', true),
  ('AR', '54', '{0}', '(?:11|[89]\d\d)\d{8}|[2368]\d{9}', '{10,11}', true),
  ('AS', '1', '{1}', '(?:[58]\d\d|684|900)\d{7}', '{10}', false),
  ('AT', '43', '{0}', '1\d{3,12}|2\d{6,12}|43(?:(?:0\d|5[02-9])\d{3,9}|2\d{4,5}|[3467]\d{4}|8\d{4,6}|9\d{4,7})|5\d{4,12}|8\d{7,12}|9\d{8,12}|(?:[367]\d|4[0-24-9])\d{4,11}', '{4,5,6,7,8,9,10,11,12,13}', true),
  ('AU', '61', '{0}', '1(?:[0-79]\d{7}(?:\d(?:\d{2})?)?|8[0-24-9]\d{7})|[2-478]\d{8}|1\d{4,7}', '{5,6,7,8,9,10,12}', true),
  ('AW', '297', '{}', '(?:[25-79]\d\d|800)\d{4}', '{7}', true),
  ('AX', '358', '{0}', '2\d{4,9}|35\d{4,5}|(?:60\d\d|800)\d{4,6}|7\d{5,11}|(?:[14]\d|3[0-46-9]|50)\d{4,8}', '{5,6,7,8,9,10,11,12}', false),
  ('AZ', '994', '{0}', '365\d{6}|(?:[124579]\d|60|88)\d{7}', '{9}', true),
  ('BA', '387', '{0}', '6\d{8}|(?:[35689]\d|49|70)\d{6}', '{8,9}', true),
  ('BB', '1', '{1}', '(?:246|[58]\d\d|900)\d{7}', '{10}', false),
  ('BD', '880', '{0}', '[1-469]\d{9}|8[0-79]\d{7,8}|[2-79]\d{8}|[2-9]\d{7}|[3-9]\d{6}|[57-9]\d{5}', '{6,7,8,9,10}', true),
  ('BE', '32', '{0}', '4\d{8}|[1-9]\d{7}', '{8,9}', true),
  ('BF', '226', '{}', '[024-7]\d{7}', '{8}', true),
  ('BG', '359', '{0}', '00800\d{7}|[2-7]\d{6,7}|[89]\d{6,8}|2\d{5}', '{6,7,8,9,12}', true),
  ('BH', '973', '{}', '[136-9]\d{7}', '{8}', true),
  ('BI', '257', '{}', '(?:[267]\d|31)\d{6}', '{8}', true),
  ('BJ', '229', '{}', '(?:01\d|8)\d{7}', '{8,10}', true),
  ('BL', '590', '{0}', '7090\d{5}|(?:[56]9|[89]\d)\d{7}', '{9}', false),
  ('BM', '1', '{1}', '(?:441|[58]\d\d|900)\d{7}', '{10}', false),
  ('BN', '673', '{}', '[2-578]\d{6}', '{7}', true),
  ('BO', '591', '{0}', '(?:[2-7]\d\d|8001)\d{5}', '{8,9}', true),
  ('BQ', '599', '{}', '(?:[34]1|7\d)\d{5}', '{7}', false),
  ('BR', '55', '{0}', '[1-467]\d{9,10}|55[0-46-9]\d{8}|[34]\d{7}|55\d{7,8}|(?:5[0-46-9]|[89]\d)\d{7,9}', '{8,9,10,11}', true),
  ('BS', '1', '{1}', '(?:242|[58]\d\d|900)\d{7}', '{10}', false),
  ('BT', '975', '{}', '[178]\d{7}|[2-8]\d{6}', '{7,8}', true),
  ('BW', '267', '{}', '(?:0800|(?:[37]|800)\d)\d{6}|(?:[2-6]\d|90)\d{5}', '{7,8,10}', true),
  ('BY', '375', '{80,8,0}', '(?:[12]\d|33|44|902)\d{7}|8(?:0[0-79]\d{5,7}|[1-7]\d{9})|8(?:1[0-489]|[5-79]\d)\d{7}|8[1-79]\d{6,7}|8[0-79]\d{5}|8\d{5}', '{6,7,8,9,10,11}', true),
  ('BZ', '501', '{}', '(?:0800\d|[2-8])\d{6}', '{7,11}', true),
  ('CA', '1', '{1}', '[2-9]\d{9}|3\d{6}', '{7,10}', false),
  ('CC', '61', '{0}', '1(?:[0-79]\d{8}(?:\d{2})?|8[0-24-9]\d{7})|[148]\d{8}|1\d{5,7}', '{6,7,8,9,10,12}', false),
  ('CD', '243', '{0}', '(?:(?:[189]|5\d)\d|2)\d{7}|[1-68]\d{6}', '{7,8,9,10}', true),
  ('CF', '236', '{}', '8776\d{4}|(?:[27]\d|61)\d{6}', '{8}', true),
  ('CG', '242', '{}', '222\d{6}|(?:0\d|80)\d{7}', '{9}', true),
  ('CH', '41', '{0}', '8\d{11}|[2-9]\d{8}', '{9,12}', true),
  ('CI', '225', '{}', '[02]\d{9}', '{10}', true),
  ('CK', '682', '{}', '[2-578]\d{4}', '{5}', true),
  ('CL', '56', '{}', '12300\d{6}|6\d{9,10}|[2-9]\d{8}', '{9,10,11}', true),
  ('CM', '237', '{}', '[26]\d{8}|88\d{6,7}', '{8,9}', true),
  ('CN', '86', '{0}', '(?:(?:1[03-689]|2\d)\d\d|6)\d{8}|1\d{10}|[126]\d{6}(?:\d(?:\d{2})?)?|86\d{5,6}|(?:[3-579]\d|8[0-57-9])\d{5,9}', '{7,8,9,10,11,12}', true),
  ('CO', '57', '{0}', '(?:46|60\d\d)\d{6}|(?:1\d|[39])\d{9}', '{8,10,11}', true),
  ('CR', '506', '{}', '(?:8\d|90)\d{8}|(?:[24-8]\d{3}|3005)\d{4}', '{8,10}', true),
  ('CU', '53', '{0}', '(?:[2-7]|8\d\d)\d{7}|[2-47]\d{6}|[34]\d{5}', '{6,7,8,10}', true),
  ('CV', '238', '{}', '(?:[2-59]\d\d|800)\d{4}', '{7}', true),
  ('CW', '599', '{}', '(?:[34]1|60|(?:7|9\d)\d)\d{5}', '{7,8}', true),
  ('CX', '61', '{0}', '1(?:[0-79]\d{8}(?:\d{2})?|8[0-24-9]\d{7})|[148]\d{8}|1\d{5,7}', '{6,7,8,9,10,12}', false),
  ('CY', '357', '{}', '(?:[279]\d|[58]0)\d{6}', '{8}', true),
  ('CZ', '420', '{}', '(?:[2-578]\d|60)\d{7}|9\d{8,11}', '{9,10,11,12}', true),
  ('DE', '49', '{0}', '[2579]\d{5,14}|49(?:[34]0|69|8\d)\d\d?|49(?:37|49|60|7[089]|9\d)\d{1,3}|49(?:2[024-9]|3[2-689]|7[1-7])\d{1,8}|(?:1|[368]\d|4[0-8])\d{3,13}|49(?:[015]\d|2[13]|31|[46][1-8])\d{1,9}', '{4,5,6,7,8,9,10,11,12,13,14,15}', true),
  ('DJ', '253', '{}', '(?:2\d|77)\d{6}', '{8}', true),
  ('DK', '45', '{}', '[2-9]\d{7}', '{8}', true),
  ('DM', '1', '{1}', '(?:[58]\d\d|767|900)\d{7}', '{10}', false),
  ('DO', '1', '{1}', '(?:[58]\d\d|900)\d{7}', '{10}', false),
  ('DZ', '213', '{0}', '(?:[1-4]|[5-79]\d|80)\d{7}', '{8,9}', true),
  ('EC', '593', '{0}', '1\d{9,10}|(?:[2-7]|9\d)\d{7}', '{8,9,10,11}', true),
  ('EE', '372', '{}', '8\d{9}|[4578]\d{7}|(?:[3-8]\d|90)\d{5}', '{7,8,10}', true),
  ('EG', '20', '{0}', '[189]\d{8,9}|[24-6]\d{8}|[135]\d{7}', '{8,9,10}', true),
  ('EH', '212', '{0}', '[5-8]\d{8}', '{9}', false),
  ('ER', '291', '{0}', '[178]\d{6}', '{7}', true),
  ('ES', '34', '{}', '(?:400|[5-9]\d\d)\d{6}', '{9}', true),
  ('ET', '251', '{0}', '(?:11|[2-57-9]\d)\d{7}', '{9}', true),
  ('FI', '358', '{0}', '[1-35689]\d{4}|7\d{10,11}|(?:[124-7]\d|3[0-46-9])\d{8}|[1-9]\d{5,8}', '{5,6,7,8,9,10,11,12}', true),
  ('FJ', '679', '{}', '45\d{5}|(?:0800\d|[235-9])\d{6}', '{7,11}', true),
  ('FK', '500', '{}', '[2-7]\d{4}', '{5}', true),
  ('FM', '691', '{}', '(?:[39]\d\d|820)\d{4}', '{7}', true),
  ('FO', '298', '{}', '[2-9]\d{5}', '{6}', true),
  ('FR', '33', '{0}', '[1-9]\d{8}', '{9}', true),
  ('GA', '241', '{}', '(?:[067]\d|11)\d{6}|[2-7]\d{6}', '{7,8}', true),
  ('GB', '44', '{180020,0}', '[1-357-9]\d{9}|[18]\d{8}|8\d{6}', '{7,9,10}', true),
  ('GD', '1', '{1}', '(?:473|[58]\d\d|900)\d{7}', '{10}', false),
  ('GE', '995', '{0}', '(?:[3-57]\d\d|800)\d{6}', '{9}', true),
  ('GF', '594', '{0}', '(?:694\d|7093)\d{5}|(?:59|[89]\d)\d{7}', '{9}', true),
  ('GG', '44', '{0}', '(?:1481|[357-9]\d{3})\d{6}|8\d{6}(?:\d{2})?', '{7,9,10}', false),
  ('GH', '233', '{0}', '[235]\d{8}|800\d{5,6}', '{8,9}', true),
  ('GI', '350', '{}', '(?:[25]\d|60)\d{6}', '{8}', true),
  ('GL', '299', '{}', '(?:19|[2-689]\d|70)\d{4}', '{6}', true),
  ('GM', '220', '{}', '[48]\d{8}|[2-9]\d{6}', '{7,9}', true),
  ('GN', '224', '{}', '722\d{6}|(?:3|6\d)\d{7}', '{8,9}', true),
  ('GP', '590', '{0}', '7090\d{5}|(?:[56]9|[89]\d)\d{7}', '{9}', true),
  ('GQ', '240', '{}', '222\d{6}|(?:3\d|55|[89]0)\d{7}', '{9}', true),
  ('GR', '30', '{}', '5005000\d{3}|8\d{9,11}|(?:[269]\d|70)\d{8}', '{10,11,12}', true),
  ('GT', '502', '{}', '80\d{6}|(?:1\d{3}|[2-7])\d{7}', '{8,11}', true),
  ('GU', '1', '{1}', '(?:[58]\d\d|671|900)\d{7}', '{10}', false),
  ('GW', '245', '{}', '[49]\d{8}|4\d{6}', '{7,9}', true),
  ('GY', '592', '{}', '(?:[2-8]\d{3}|9008)\d{3}', '{7}', true),
  ('HK', '852', '{}', '8[0-46-9]\d{6,7}|9\d{4,7}|(?:[2-7]|9\d{3})\d{7}', '{5,6,7,8,9,11}', true),
  ('HN', '504', '{}', '8\d{10}|[237-9]\d{7}', '{8,11}', true),
  ('HR', '385', '{0}', '[2-69]\d{8}|80\d{5,7}|[1-79]\d{7}|6\d{6}', '{7,8,9}', true),
  ('HT', '509', '{}', '[2-589]\d{7}', '{8}', true),
  ('HU', '36', '{06}', '[235-7]\d{8}|[1-9]\d{7}', '{8,9}', true),
  ('ID', '62', '{0}', '00[1-9]\d{9,14}|(?:[1-36]|8\d{5})\d{6}|00\d{9}|[1-9]\d{8,10}|[2-9]\d{7}', '{7,8,9,10,11,12,13,14,15,16,17}', true),
  ('IE', '353', '{0}', '(?:1\d|[2569])\d{6,8}|4\d{6,9}|7\d{8}|8\d{8,9}', '{7,8,9,10}', true),
  ('IL', '972', '{0}', '1\d{6}(?:\d{3,5})?|[57]\d{8}|[1-489]\d{7}', '{7,8,9,10,11,12}', true),
  ('IM', '44', '{0}', '1624\d{6}|(?:[3578]\d|90)\d{8}', '{10}', false),
  ('IN', '91', '{0}', '(?:000800|[2-9]\d\d)\d{7}|1\d{7,12}', '{8,9,10,11,12,13}', true),
  ('IO', '246', '{}', '3\d{6}', '{7}', true),
  ('IQ', '964', '{0}', '(?:1|7\d\d)\d{7}|[2-6]\d{7,8}', '{8,9,10}', true),
  ('IR', '98', '{0}', '[1-9]\d{9}|(?:[1-8]\d\d|9)\d{3,4}', '{4,5,6,7,10}', true),
  ('IS', '354', '{}', '(?:38\d|[4-9])\d{6}', '{7,9}', true),
  ('IT', '39', '{}', '0\d{5,11}|1\d{8,10}|3(?:[0-8]\d{7,10}|9\d{7,8})|(?:43|55|70)\d{8}|8\d{5}(?:\d{2,4})?', '{6,7,8,9,10,11,12}', true),
  ('JE', '44', '{0}', '1534\d{6}|(?:[3578]\d|90)\d{8}', '{10}', false),
  ('JM', '1', '{1}', '(?:[58]\d\d|658|900)\d{7}', '{10}', false),
  ('JO', '962', '{0}', '(?:(?:[2689]|7\d)\d|32|427|53)\d{6}', '{8,9}', true),
  ('JP', '81', '{0}', '00[1-9]\d{6,14}|[25-9]\d{9}|(?:00|[1-9]\d\d)\d{6}', '{8,9,10,11,12,13,14,15,16,17}', true),
  ('KE', '254', '{0}', '(?:[17]\d\d|900)\d{6}|(?:2|80)0\d{6,7}|[4-6]\d{6,8}', '{7,8,9,10}', true),
  ('KG', '996', '{0}', '8\d{9}|[235-9]\d{8}', '{9,10}', true),
  ('KH', '855', '{0}', '1\d{9}|[1-9]\d{7,8}', '{8,9,10}', true),
  ('KI', '686', '{0}', '(?:[37]\d|6[0-79])\d{6}|(?:[2-48]\d|50)\d{3}', '{5,8}', true),
  ('KM', '269', '{}', '[3478]\d{6}', '{7}', true),
  ('KN', '1', '{1}', '(?:[58]\d\d|900)\d{7}', '{10}', false),
  ('KP', '850', '{0}', '85\d{6}|(?:19\d|[2-7])\d{7}', '{8,10}', true),
  ('KR', '82', '{0}', '00[1-9]\d{8,11}|(?:[12]|5\d{3})\d{7}|[13-6]\d{9}|(?:[1-6]\d|80)\d{7}|[3-6]\d{4,5}|(?:00|7)0\d{8}', '{5,6,8,9,10,11,12,13,14}', true),
  ('KW', '965', '{}', '18\d{5}|(?:[2569]\d|41)\d{6}', '{7,8}', true),
  ('KY', '1', '{1}', '(?:345|[58]\d\d|900)\d{7}', '{10}', false),
  ('KZ', '7', '{8}', '8\d{13}|[78]\d{9}', '{10,14}', false),
  ('LA', '856', '{0}', '[23]\d{9}|3\d{8}|(?:[235-8]\d|41)\d{6}', '{8,9,10}', true),
  ('LB', '961', '{0}', '[27-9]\d{7}|[13-9]\d{6}', '{7,8}', true),
  ('LC', '1', '{1}', '(?:[58]\d\d|758|900)\d{7}', '{10}', false),
  ('LI', '423', '{0}', '[68]\d{8}|(?:[2378]\d|90)\d{5}', '{7,9}', true),
  ('LK', '94', '{0}', '[1-9]\d{8}', '{9}', true),
  ('LR', '231', '{0}', '(?:[2457]\d|33|88)\d{7}|(?:2\d|[4-6])\d{6}', '{7,8,9}', true),
  ('LS', '266', '{}', '(?:[256]\d\d|800)\d{5}', '{8}', true),
  ('LT', '370', '{0,8}', '(?:[3469]\d|52|[78]0)\d{6}', '{8}', true),
  ('LU', '352', '{}', '35[013-9]\d{4,8}|6\d{8}|35\d{2,4}|(?:[2457-9]\d|3[0-46-9])\d{2,9}', '{4,5,6,7,8,9,10,11}', true),
  ('LV', '371', '{}', '(?:[268]\d|78|90)\d{6}', '{8}', true),
  ('LY', '218', '{0}', '[2-9]\d{8}', '{9}', true),
  ('MA', '212', '{0}', '[5-8]\d{8}', '{9}', true),
  ('MC', '377', '{0}', '(?:[3489]|[67]\d)\d{7}', '{8,9}', true),
  ('MD', '373', '{0}', '(?:[235-7]\d|[89]0)\d{6}', '{8}', true),
  ('ME', '382', '{0}', '(?:20|[3-79]\d)\d{6}|80\d{6,7}', '{8,9}', true),
  ('MF', '590', '{0}', '7090\d{5}|(?:[56]9|[89]\d)\d{7}', '{9}', false),
  ('MG', '261', '{0}', '[23]\d{8}', '{9}', true),
  ('MH', '692', '{1}', '329\d{4}|(?:[256]\d|45)\d{5}', '{7}', true),
  ('MK', '389', '{0}', '[2-578]\d{7}', '{8}', true),
  ('ML', '223', '{}', '[24-9]\d{7}', '{8}', true),
  ('MM', '95', '{0}', '1\d{5,7}|95\d{6}|(?:[4-7]|9[0-46-9])\d{6,8}|(?:2|8\d)\d{5,8}', '{6,7,8,9,10}', true),
  ('MN', '976', '{0}', '[12]\d{7,9}|[5-9]\d{7}', '{8,9,10}', true),
  ('MO', '853', '{}', '0800\d{3}|(?:28|[68]\d)\d{6}', '{7,8}', true),
  ('MP', '1', '{1}', '[58]\d{9}|(?:67|90)0\d{7}', '{10}', false),
  ('MQ', '596', '{0}', '7091\d{5}|(?:[56]9|[89]\d)\d{7}', '{9}', true),
  ('MR', '222', '{}', '(?:[2-4]\d\d|800)\d{5}', '{8}', true),
  ('MS', '1', '{1}', '(?:[58]\d\d|664|900)\d{7}', '{10}', false),
  ('MT', '356', '{}', '3550\d{4}|(?:[2579]\d\d|800)\d{5}', '{8}', true),
  ('MU', '230', '{}', '(?:[57]|8\d\d)\d{7}|[2-468]\d{6}', '{7,8,10}', true),
  ('MV', '960', '{}', '(?:800|9[0-57-9]\d)\d{7}|[34679]\d{6}', '{7,10}', true),
  ('MW', '265', '{0}', '(?:[1289]\d|31|77)\d{7}|1\d{6}', '{7,9}', true),
  ('MX', '52', '{}', '[2-9]\d{9}', '{10}', true),
  ('MY', '60', '{0}', '1\d{8,9}|(?:3\d|[4-9])\d{7}', '{8,9,10}', true),
  ('MZ', '258', '{}', '(?:2|8\d)\d{7}', '{8,9}', true),
  ('NA', '264', '{0}', '[68]\d{7,8}', '{8,9}', true),
  ('NC', '687', '{}', '(?:050|[2-57-9]\d\d)\d{3}', '{6}', true),
  ('NE', '227', '{}', '[027-9]\d{7}', '{8}', true),
  ('NF', '672', '{}', '[13]\d{5}', '{6}', true),
  ('NG', '234', '{0}', '(?:20|9\d)\d{8}|[78]\d{9,13}', '{10,11,12,13,14}', true),
  ('NI', '505', '{}', '(?:1800|[25-8]\d{3})\d{4}', '{8}', true),
  ('NL', '31', '{0}', '(?:[124-7]\d\d|3(?:[02-9]\d|1[0-8]))\d{6}|8\d{6,9}|9\d{6,10}|1\d{4,5}', '{5,6,7,8,9,10,11}', true),
  ('NO', '47', '{}', '(?:0|[2-9]\d{3})\d{4}', '{5,8}', true),
  ('NP', '977', '{0}', '(?:1\d|9)\d{9}|[1-9]\d{7}', '{8,10,11}', true),
  ('NR', '674', '{}', '(?:222|444|(?:55|8\d)\d|666|777|999)\d{4}', '{7}', true),
  ('NU', '683', '{}', '(?:[4-7]|888\d)\d{3}', '{4,7}', true),
  ('NZ', '64', '{0}', '[1289]\d{9}|50\d{5}(?:\d{2,3})?|[27-9]\d{7,8}|(?:[34]\d|6[0-35-9])\d{6}|8\d{4,6}', '{5,6,7,8,9,10}', true),
  ('OM', '968', '{}', '(?:1505|[279]\d{3}|500)\d{4}|800\d{5,6}', '{7,8,9}', true),
  ('PA', '507', '{}', '(?:00800|8\d{3})\d{6}|[68]\d{7}|[1-57-9]\d{6}', '{7,8,10,11}', true),
  ('PE', '51', '{0}', '(?:[14-8]|9\d)\d{7}', '{8,9}', true),
  ('PF', '689', '{}', '4\d{5}(?:\d{2})?|8\d{7,8}', '{6,8,9}', true),
  ('PG', '675', '{}', '(?:180|[78]\d{3})\d{4}|(?:[2-589]\d|64)\d{5}', '{7,8}', true),
  ('PH', '63', '{0}', '(?:[2-7]|9\d)\d{8}|2\d{5}|(?:1800|8)\d{7,9}', '{6,8,9,10,11,12,13}', true),
  ('PK', '92', '{0}', '122\d{6}|[24-8]\d{10,11}|9(?:[013-9]\d{8,10}|2(?:[01]\d\d|2(?:[06-8]\d|1[01]))\d{7})|(?:[2-8]\d{3}|92(?:[0-7]\d|8[1-9]))\d{6}|[24-9]\d{8}|[89]\d{7}', '{8,9,10,11,12}', true),
  ('PL', '48', '{}', '(?:6|8\d\d)\d{7}|[1-9]\d{6}(?:\d{2})?|[26]\d{5}', '{6,7,8,9,10}', true),
  ('PM', '508', '{0}', '[78]\d{8}|[2-9]\d{5}', '{6,9}', true),
  ('PR', '1', '{1}', '(?:[589]\d\d|787)\d{7}', '{10}', false),
  ('PS', '970', '{0}', '[2489]2\d{6}|(?:1\d|5)\d{8}', '{8,9,10}', true),
  ('PT', '351', '{}', '1693\d{5}|(?:[26-9]\d|30)\d{7}', '{9}', true),
  ('PW', '680', '{}', '(?:[24-8]\d\d|345|900)\d{4}', '{7}', true),
  ('PY', '595', '{0}', '[36-8]\d{5,8}|4\d{6,8}|59\d{6}|9\d{5,10}|(?:2\d|5[0-8])\d{6,7}', '{6,7,8,9,10,11}', true),
  ('QA', '974', '{}', '800\d{4}|(?:2|800)\d{6}|(?:0080|[3-7])\d{7}', '{7,8,9,11}', true),
  ('RE', '262', '{0}', '709\d{6}|(?:26|[689]\d)\d{7}', '{9}', true),
  ('RO', '40', '{0}', '(?:[236-8]\d|90)\d{7}|[23]\d{5}', '{6,9}', true),
  ('RS', '381', '{0}', '38[02-9]\d{6,9}|6\d{7,9}|90\d{4,8}|38\d{5,6}|(?:7\d\d|800)\d{3,9}|(?:[12]\d|3[0-79])\d{5,10}', '{6,7,8,9,10,11,12}', true),
  ('RU', '7', '{8}', '8\d{13}|[347-9]\d{9}', '{10,14}', true),
  ('RW', '250', '{0}', '(?:06|[27]\d\d|[89]00)\d{6}', '{8,9}', true),
  ('SA', '966', '{0}', '(?:[15]\d|800|92)\d{7}', '{9,10}', true),
  ('SB', '677', '{}', '[6-9]\d{6}|[1-6]\d{4}', '{5,7}', true),
  ('SC', '248', '{}', '(?:[2489]\d|64)\d{5}', '{7}', true),
  ('SD', '249', '{0}', '[19]\d{8}', '{9}', true),
  ('SE', '46', '{0}', '(?:[26]\d\d|9)\d{9}|[1-9]\d{8}|[1-689]\d{7}|[1-4689]\d{6}|2\d{5}', '{6,7,8,9,10,12}', true),
  ('SG', '65', '{}', '(?:(?:1\d|8)\d\d|7000)\d{7}|[3689]\d{7}', '{8,10,11}', true),
  ('SH', '290', '{}', '(?:[256]\d|8)\d{3}', '{4,5}', true),
  ('SI', '386', '{0}', '[1-7]\d{7}|8\d{4,7}|90\d{4,6}', '{5,6,7,8}', true),
  ('SJ', '47', '{}', '0\d{4}|(?:[489]\d|79)\d{6}', '{5,8}', false),
  ('SK', '421', '{0}', '[2-689]\d{8}|[2-59]\d{6}|[2-5]\d{5}', '{6,7,9}', true),
  ('SL', '232', '{0}', '(?:[237-9]\d|66)\d{6}', '{8}', true),
  ('SM', '378', '{}', '(?:0549|[5-7]\d)\d{6}', '{8,10}', true),
  ('SN', '221', '{}', '(?:[378]\d|93)\d{7}', '{9}', true),
  ('SO', '252', '{0}', '[346-9]\d{8}|[12679]\d{7}|[1-5]\d{6}|[1348]\d{5}', '{6,7,8,9}', true),
  ('SR', '597', '{}', '(?:[2-5]|[6-9]\d)\d{5}', '{6,7}', true),
  ('SS', '211', '{0}', '[19]\d{8}', '{9}', true),
  ('ST', '239', '{}', '(?:22|9\d)\d{5}', '{7}', true),
  ('SV', '503', '{}', '[25-7]\d{7}|(?:80\d|900)\d{4}(?:\d{4})?', '{7,8,11}', true),
  ('SX', '1', '{1}', '7215\d{6}|(?:[58]\d\d|900)\d{7}', '{10}', false),
  ('SY', '963', '{0}', '[1-359]\d{8}|[1-5]\d{7}', '{8,9}', true),
  ('SZ', '268', '{}', '0800\d{4}|(?:[237]\d|900)\d{6}', '{8,9}', true),
  ('TA', '290', '{}', '8\d{3}', '{4}', false),
  ('TC', '1', '{1}', '(?:[58]\d\d|649|900)\d{7}', '{10}', false),
  ('TD', '235', '{}', '(?:22|[3689]\d|77)\d{6}', '{8}', true),
  ('TG', '228', '{}', '[279]\d{7}', '{8}', true),
  ('TH', '66', '{0}', '(?:001800|[2-57]|[689]\d)\d{7}|1\d{7,9}', '{8,9,10,13}', true),
  ('TJ', '992', '{}', '(?:[0-57-9]\d|66)\d{7}', '{9}', true),
  ('TK', '690', '{}', '[2-47]\d{3,6}', '{4,5,6,7}', true),
  ('TL', '670', '{}', '7\d{7}|(?:[2-47]\d|[89]0)\d{5}', '{7,8}', true),
  ('TM', '993', '{8}', '[1-7]\d{7}', '{8}', true),
  ('TN', '216', '{}', '[2-57-9]\d{7}', '{8}', true),
  ('TO', '676', '{}', '(?:0800|(?:[5-8]\d\d|999)\d)\d{3}|[2-8]\d{4}', '{5,7}', true),
  ('TR', '90', '{0}', '4\d{6}|8\d{11,12}|(?:[2-58]\d\d|900)\d{7}', '{7,10,12,13}', true),
  ('TT', '1', '{1}', '(?:[58]\d\d|900)\d{7}', '{10}', false),
  ('TV', '688', '{}', '(?:2|7\d\d|90)\d{4}', '{5,6,7}', true),
  ('TW', '886', '{0}', '[2-689]\d{8}|7\d{9,10}|[2-8]\d{7}|2\d{6}', '{7,8,9,10,11}', true),
  ('TZ', '255', '{0}', '(?:[25-8]\d|41|90)\d{7}', '{9}', true),
  ('UA', '380', '{0}', '[89]\d{9}|[3-9]\d{8}', '{9,10}', true),
  ('UG', '256', '{0}', '800\d{6}|(?:[29]0|[347]\d)\d{7}', '{9}', true),
  ('US', '1', '{1}', '[2-9]\d{9}|3\d{6}', '{10}', true),
  ('UY', '598', '{0}', '0004\d{2,9}|[1249]\d{7}|2\d{3,4}|(?:[49]\d|80)\d{5}', '{4,5,6,7,8,9,10,11,12,13}', true),
  ('UZ', '998', '{}', '(?:20|33|[5-9]\d)\d{7}', '{9}', true),
  ('VA', '39', '{}', '0\d{5,10}|3[0-8]\d{7,10}|55\d{8}|8\d{5}(?:\d{2,4})?|(?:1\d|39)\d{7,8}', '{6,7,8,9,10,11,12}', false),
  ('VC', '1', '{1}', '(?:[58]\d\d|784|900)\d{7}', '{10}', false),
  ('VE', '58', '{0}', '[68]00\d{7}|(?:[24]\d|[59]0)\d{8}', '{10}', true),
  ('VG', '1', '{1}', '(?:284|[58]\d\d|900)\d{7}', '{10}', false),
  ('VI', '1', '{1}', '[58]\d{9}|(?:34|90)0\d{7}', '{10}', false),
  ('VN', '84', '{0}', '[12]\d{9}|[135-9]\d{8}|[16]\d{6,7}|7\d{6}', '{7,8,9,10}', true),
  ('VU', '678', '{}', '[57-9]\d{6}|(?:[238]\d|48)\d{3}', '{5,7}', true),
  ('WF', '681', '{}', '(?:40|72|8\d{4})\d{4}|[89]\d{5}', '{6,9}', true),
  ('WS', '685', '{}', '(?:[2-6]|8\d{5})\d{4}|[78]\d{6}|[68]\d{5}', '{5,6,7,10}', true),
  ('XK', '383', '{0}', '2\d{7,8}|3\d{7,11}|(?:4\d\d|[89]00)\d{5}', '{8,9,10,11,12}', true),
  ('YE', '967', '{0}', '(?:1|7\d)\d{7}|[1-7]\d{6}', '{7,8,9}', true),
  ('YT', '262', '{0}', '(?:639\d|7093)\d{5}|(?:26|80|9\d)\d{7}', '{9}', false),
  ('ZA', '27', '{0}', '[1-79]\d{8}|8\d{4,9}', '{5,6,7,8,9,10}', true),
  ('ZM', '260', '{0}', '800\d{6}|(?:21|[579]\d|63)\d{7}', '{9}', true),
  ('ZW', '263', '{0}', '(?:13|8\d{4})\d{5}|[235-8]\d{8}|[23568]\d{6}', '{7,9,10}', true)
on conflict (country_code) do update set
  calling_code = excluded.calling_code,
  national_prefixes = excluded.national_prefixes,
  nsn_pattern = excluded.nsn_pattern,
  nsn_lengths = excluded.nsn_lengths,
  is_main_country = excluded.is_main_country;

-- ─── 2. canonicalize_phone ───────────────────────────────────────────────────
-- Returns {verdict:'ok', e164, country, reason} or {verdict:'unparseable',
-- reason}; NULL for an empty input. Pure function of (raw, country, rules).

create or replace function public.canonicalize_phone(p_raw text, p_country_code text default null)
returns jsonb
language plpgsql
stable
set search_path = public
as $fn$
declare
  s        text;
  d        text;
  intl     boolean;
  r        record;
  us       record;
  cc       text;
  nsn      text;
  np       text;
  i        int;
  v_cc     text := upper(nullif(btrim(p_country_code), ''));
begin
  if p_raw is null or btrim(p_raw) = '' then
    return null;
  end if;

  s := btrim(p_raw);
  -- URL-encoded whitespace copied out of an href ("830%E2%80%AF0840").
  s := btrim(regexp_replace(s, '(%[0-9A-Fa-f]{2})+', ' ', 'g'));
  -- A label or URI scheme in front of the number.
  s := regexp_replace(s, '^(tel|phone|telefon|telephone|tél|fon|ph)\s*[.:]?\s*', '', 'i');
  -- Several numbers in one field: the first is the main line.
  s := btrim(split_part(regexp_replace(s, '\s+(or|oder|ou|o|y|und|and)\s+|[;,|]', ';', 'gi'), ';', 1));
  -- A trailing extension, and a bracketed note ("(only WhatsApp!)", "(de)").
  s := regexp_replace(s, '\s*(ext\.?|extension|x|#|durchwahl|dw\.?)\s*\d{1,6}\s*$', '', 'i');
  s := btrim(regexp_replace(s, '\s*\([^)]*[[:alpha:]][^)]*\)', '', 'g'));

  if s ~ '[[:alpha:]]' then
    return jsonb_build_object('verdict', 'unparseable', 'reason', 'letters');
  end if;

  -- "+41 (0)31 …": the bracketed trunk prefix is never dialled from abroad.
  s := replace(s, '(0)', '');
  -- "(+44) 0207 …": the plus may sit behind an opening bracket.
  intl := s ~ '^[^0-9]*\+';
  d := regexp_replace(s, '\D', '', 'g');
  -- "0049 …" and the doubled "+0049 …" both mean international.
  if d ~ '^00' then
    intl := true;
    d := substr(d, 3);
  end if;

  if length(d) < 5 or length(d) > 17 then
    return jsonb_build_object('verdict', 'unparseable', 'reason', 'length');
  end if;

  if intl then
    -- ITU calling codes are prefix-free, so at most one length has rules.
    for i in 1..3 loop
      cc  := left(d, i);
      nsn := substr(d, i + 1);
      for r in
        select * from public.phone_country_rules
         where calling_code = cc
         order by (country_code = v_cc) desc, is_main_country desc, country_code
      loop
        if nsn ~ ('^(?:' || r.nsn_pattern || ')$') then
          return jsonb_build_object('verdict', 'ok', 'e164', '+' || cc || nsn,
                                    'country', r.country_code, 'reason', 'international');
        end if;
        -- "+66 0 26370507": the trunk prefix carried over behind the calling
        -- code. Stripped only when what remains is a valid national number.
        foreach np in array r.national_prefixes loop
          if left(nsn, length(np)) = np
             and substr(nsn, length(np) + 1) ~ ('^(?:' || r.nsn_pattern || ')$') then
            return jsonb_build_object('verdict', 'ok', 'e164', '+' || cc || substr(nsn, length(np) + 1),
                                      'country', r.country_code, 'reason', 'stripped_trunk_prefix');
          end if;
        end loop;
      end loop;
    end loop;
    return jsonb_build_object('verdict', 'unparseable', 'reason', 'invalid_for_calling_code');
  end if;

  -- National form: only the row's own country can say what it means.
  select * into r from public.phone_country_rules where country_code = v_cc;
  if not found then
    return jsonb_build_object('verdict', 'unparseable', 'reason', 'no_country');
  end if;

  -- "773-743-5772" on a row whose country is not the US: the North American
  -- layout is unambiguous, and read as a national number of the row's own
  -- country it parses into something wrong (+49 773…, +353 818…). Those rows
  -- carry a wrong country_id; that is a geo defect, and the number itself is
  -- still dialled as +1. Hyphen/dot separators only — a space-separated
  -- "333 123 4567" is an Italian mobile.
  if r.country_code <> 'US'
     and s ~ '^(\([2-9][0-9]{2}\) ?|[2-9][0-9]{2}[-.])[2-9][0-9]{2}[-.][0-9]{4}$' then
    select * into us from public.phone_country_rules where country_code = 'US';
    if d ~ ('^(?:' || us.nsn_pattern || ')$') then
      return jsonb_build_object('verdict', 'ok', 'e164', '+1' || d,
                                'country', 'US', 'reason', 'nanp_layout');
    end if;
  end if;

  foreach np in array r.national_prefixes loop
    if left(d, length(np)) = np
       and substr(d, length(np) + 1) ~ ('^(?:' || r.nsn_pattern || ')$') then
      return jsonb_build_object('verdict', 'ok', 'e164', '+' || r.calling_code || substr(d, length(np) + 1),
                                'country', r.country_code, 'reason', 'national');
    end if;
  end loop;
  if d ~ ('^(?:' || r.nsn_pattern || ')$') then
    return jsonb_build_object('verdict', 'ok', 'e164', '+' || r.calling_code || d,
                              'country', r.country_code, 'reason', 'national_no_prefix');
  end if;
  -- International form written without its "+".
  if left(d, length(r.calling_code)) = r.calling_code
     and substr(d, length(r.calling_code) + 1) ~ ('^(?:' || r.nsn_pattern || ')$') then
    return jsonb_build_object('verdict', 'ok', 'e164', '+' || d,
                              'country', r.country_code, 'reason', 'missing_plus');
  end if;

  return jsonb_build_object('verdict', 'unparseable', 'reason', 'invalid_national');
end;
$fn$;

comment on function public.canonicalize_phone(text, text) is
  'Canonicalises a phone number to E.164 (+<calling code><number>, no separators) using phone_country_rules. Returns {verdict, e164, country, reason}. p_country_code (ISO2) is used only for numbers written in national form.';

grant execute on function public.canonicalize_phone(text, text) to anon, authenticated, service_role;

-- ─── 3. The guard ────────────────────────────────────────────────────────────
-- UNSCOPED on purpose: country_id is often set by trg_*_geo_derive, which is
-- not in the UPDATE statement, and a column-scoped trigger fires on the
-- columns the STATEMENT names, not on what another BEFORE trigger wrote. The
-- name sorts after every geo-derivation and normalisation trigger on the three
-- tables (BEFORE triggers fire in name order), so it sees the final country.

create or replace function public.phone_canonical_guard()
returns trigger
language plpgsql
set search_path = public
as $fn$
declare
  v_cc  text;
  v_res jsonb;
begin
  -- Nothing to do when neither input moved — except under the backfill
  -- runner, which re-writes phone to itself precisely to come through here
  -- (a self-assignment changes no column, so without this flag every row it
  -- touches would return early and the backfill would report work it never
  -- did — exactly what the first prod dry run showed).
  if tg_op = 'UPDATE'
     and new.phone is not distinct from old.phone
     and new.country_id is not distinct from old.country_id
     and coalesce(current_setting('app.phone_recanonicalize', true), '') <> 'on' then
    return new;
  end if;

  if new.phone is null or btrim(new.phone) = '' then
    new.phone := null;
  else
    -- Always re-run, even on an E.164-shaped value: "+66026370507" has the
    -- right shape and a wrong trunk 0, and is exactly what this repairs.
    select code into v_cc from public.countries where id = new.country_id;
    v_res := public.canonicalize_phone(new.phone, v_cc);
    if v_res->>'verdict' = 'ok' then
      new.phone := v_res->>'e164';
    else
      new.enrichment_status := coalesce(new.enrichment_status, '{}'::jsonb)
        || jsonb_build_object('phone_rejected', jsonb_build_object(
             'raw', new.phone, 'reason', v_res->>'reason', 'country', v_cc, 'at', now()));
      new.phone := null;
    end if;
  end if;

  -- venues carries a second copy that trg_venues_normalized computed from the
  -- RAW value a moment earlier; keep the two in step.
  if tg_table_name = 'venues' then
    new.phone_e164 := new.phone;
  end if;
  return new;
end;
$fn$;

drop trigger if exists trg_venues_zz_phone_canonical on public.venues;
create trigger trg_venues_zz_phone_canonical
  before insert or update on public.venues
  for each row execute function public.phone_canonical_guard();

drop trigger if exists trg_organizations_zz_phone_canonical on public.organizations;
create trigger trg_organizations_zz_phone_canonical
  before insert or update on public.organizations
  for each row execute function public.phone_canonical_guard();

drop trigger if exists trg_hotels_zz_phone_canonical on public.hotels;
create trigger trg_hotels_zz_phone_canonical
  before insert or update on public.hotels
  for each row execute function public.phone_canonical_guard();

-- ─── 4. Backfill runner ──────────────────────────────────────────────────────
-- Keyset-paged over ids so it terminates and can resume: each call scans the
-- next p_batch rows with a phone after p_after and rewrites only those whose
-- stored value differs from its canonical form (a shape test alone would miss
-- the "+66 0 …" rows, which already look like E.164). Writing phone to itself
-- is enough — the guard does the work. Batched because a venues UPDATE runs
-- the spine/search chain per row.

create or replace function public.run_phone_canonical_backfill(
  p_table text, p_after uuid default null, p_batch int default 300)
returns jsonb
language plpgsql
security definer
set search_path = public
as $fn$
declare
  v_updated int;
  v_last    uuid;
begin
  if p_table not in ('venues', 'organizations', 'hotels') then
    raise exception 'unsupported table %', p_table using errcode = '22023';
  end if;

  execute format(
    'select max(id::text)::uuid from (
       select id from public.%I
        where phone is not null and ($1 is null or id > $1)
        order by id limit $2) w', p_table)
    into v_last using p_after, least(greatest(p_batch, 1), 1000);

  if v_last is null then
    return jsonb_build_object('table', p_table, 'updated', 0, 'next', null, 'done', true);
  end if;

  -- Transaction-local: read by phone_canonical_guard() only.
  perform set_config('app.phone_recanonicalize', 'on', true);

  execute format(
    'update public.%1$I t set phone = t.phone
       from (select w.id, c.code
               from public.%1$I w
               left join public.countries c on c.id = w.country_id
              where w.phone is not null
                and ($1 is null or w.id > $1) and w.id <= $2) s
      where t.id = s.id
        and t.phone is distinct from coalesce(public.canonicalize_phone(t.phone, s.code)->>''e164'', '''')', p_table)
    using p_after, v_last;
  get diagnostics v_updated = row_count;
  perform set_config('app.phone_recanonicalize', 'off', true);

  return jsonb_build_object('table', p_table, 'updated', v_updated, 'next', v_last, 'done', false);
end;
$fn$;

revoke all on function public.run_phone_canonical_backfill(text, uuid, int) from public, anon, authenticated;
grant execute on function public.run_phone_canonical_backfill(text, uuid, int) to service_role;

-- ─── 5. Sentinel ─────────────────────────────────────────────────────────────
-- trigger_attached is reported beside the count because an absent guard and a
-- clean table both read zero.

create or replace function public.phone_format_signals()
returns jsonb
language sql
stable
security definer
set search_path = public
as $fn$
  select jsonb_build_object(
    'probe_ok', true,
    'rules', (select count(*) from public.phone_country_rules),
    'tables', jsonb_build_object(
      'venues', jsonb_build_object(
        'with_phone', (select count(*) from public.venues where phone is not null),
        'non_e164',   (select count(*) from public.venues where phone is not null and phone !~ '^\+[1-9][0-9]{6,14}$'),
        'rejected',   (select count(*) from public.venues where enrichment_status ? 'phone_rejected' and phone is null),
        'trigger_attached', exists (select 1 from pg_trigger where tgrelid = 'public.venues'::regclass
                                      and tgname = 'trg_venues_zz_phone_canonical' and tgenabled <> 'D')),
      'organizations', jsonb_build_object(
        'with_phone', (select count(*) from public.organizations where phone is not null),
        'non_e164',   (select count(*) from public.organizations where phone is not null and phone !~ '^\+[1-9][0-9]{6,14}$'),
        'rejected',   (select count(*) from public.organizations where enrichment_status ? 'phone_rejected' and phone is null),
        'trigger_attached', exists (select 1 from pg_trigger where tgrelid = 'public.organizations'::regclass
                                      and tgname = 'trg_organizations_zz_phone_canonical' and tgenabled <> 'D')),
      'hotels', jsonb_build_object(
        'with_phone', (select count(*) from public.hotels where phone is not null),
        'non_e164',   (select count(*) from public.hotels where phone is not null and phone !~ '^\+[1-9][0-9]{6,14}$'),
        'rejected',   (select count(*) from public.hotels where enrichment_status ? 'phone_rejected' and phone is null),
        'trigger_attached', exists (select 1 from pg_trigger where tgrelid = 'public.hotels'::regclass
                                      and tgname = 'trg_hotels_zz_phone_canonical' and tgenabled <> 'D'))
    )
  );
$fn$;

revoke all on function public.phone_format_signals() from public, anon, authenticated;
grant execute on function public.phone_format_signals() to service_role;

-- ─── 6. Postconditions ───────────────────────────────────────────────────────
do $verify$
declare
  v text;
begin
  if (select count(*) from public.phone_country_rules) < 240 then
    raise exception 'phone_country_rules not seeded';
  end if;
  -- Every generated pattern must compile under Postgres ARE syntax.
  perform 1 from public.phone_country_rules where '0' ~ ('^(?:' || nsn_pattern || ')$');

  foreach v in array array[
    '+66026370507|TH|+6626370507',
    '+32025035918|BE|+3225035918',
    '(415) 551-2500|US|+14155512500',
    '020 7452 3000|GB|+442074523000',
    '02 805 8051|IT|+39028058051',
    '+390510075926|IT|+390510075926',
    '+41 (0)31 534 18 30|CH|+41315341830',
    '0049 30 4476789|DE|+49304476789',
    '030/4476789|DE|+49304476789',
    '773-743-5772|DE|+17737435772',
    '860880534|LT|+37060880534'
  ] loop
    if public.canonicalize_phone(split_part(v, '|', 1), split_part(v, '|', 2))->>'e164'
       is distinct from split_part(v, '|', 3) then
      raise exception 'canonicalize_phone(%,%) = %, expected %',
        split_part(v, '|', 1), split_part(v, '|', 2),
        public.canonicalize_phone(split_part(v, '|', 1), split_part(v, '|', 2))->>'e164',
        split_part(v, '|', 3);
    end if;
  end loop;

  if public.canonicalize_phone('+4202222511343', 'CZ')->>'verdict' <> 'unparseable' then
    raise exception 'an invalid number was accepted';
  end if;

  if (select count(*) from pg_trigger
       where tgname in ('trg_venues_zz_phone_canonical', 'trg_organizations_zz_phone_canonical',
                        'trg_hotels_zz_phone_canonical')) <> 3 then
    raise exception 'phone guard not attached to all three tables';
  end if;
end;
$verify$;
