import { describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

// Guards 99991790994947_geo_subdivisions_region_code.sql and its generator.
//
// What must not drift:
//   1. the seed is the generator's output (EXTRA_ALIASES reach the seed; every
//      parent link was resolved — dr5hn types id as a number and parent_id as
//      a string, and a first draft silently produced no hierarchy at all)
//   2. the resolver NEVER guesses: an arm that finds more than one first-level
//      unit returns NULL; FIPS numbers only match a digits-only input
//   3. Indonesian island groups ('geographical unit') are excluded in EVERY arm
//   4. the sync trigger sorts after trg_cities_aa_split_name and an explicit
//      region_code write wins over derivation
//   5. the backfill writes only rows that resolve, in batches
//   6. postconditions include negative controls, not just positive ones

const MIGRATION = '99991790994947_geo_subdivisions_region_code.sql';
const raw = readFileSync(join(process.cwd(), 'supabase/migrations', MIGRATION), 'utf8');
const generator = readFileSync(
  join(process.cwd(), 'scripts/data-quality/generate-geo-subdivisions.mjs'),
  'utf8',
);

/** Full-line comments removed, so prose cannot satisfy a guard. */
const statements = raw
  .split('\n')
  .filter((l) => !l.trimStart().startsWith('--'))
  .join('\n');

const seedRows = statements.split('\n').filter((l) => /^\('[A-Z]{2}-[A-Z0-9]{1,4}', '[A-Z]{2}',/.test(l));
const resolver = statements.slice(
  statements.indexOf('create or replace function public.resolve_region_code'),
  statements.indexOf('grant execute on function public.resolve_region_code'),
);
const trigger = statements.slice(
  statements.indexOf('create or replace function public.cities_sync_region_code'),
  statements.indexOf('create trigger trg_cities_ab_region_code'),
);
const backfill = statements.slice(statements.indexOf('do $backfill$'), statements.indexOf('$backfill$;'));
const verify = statements.slice(statements.indexOf('do $verify$'));

describe('spans', () => {
  it('found every block', () => {
    expect(seedRows.length).toBeGreaterThan(5000);
    expect(resolver.length).toBeGreaterThan(1500);
    expect(trigger.length).toBeGreaterThan(300);
    expect(backfill.length).toBeGreaterThan(300);
    expect(verify.length).toBeGreaterThan(1500);
  });
});

describe('seed', () => {
  it('carries the generator header and one row per code', () => {
    expect(raw).toContain('-- generated by scripts/data-quality/generate-geo-subdivisions.mjs');
    const codes = seedRows.map((r) => r.slice(2, r.indexOf("'", 2)));
    expect(new Set(codes).size).toBe(codes.length);
  });

  it('every EXTRA_ALIASES entry reached its row', () => {
    const block = generator.slice(generator.indexOf('const EXTRA_ALIASES'), generator.indexOf('}', generator.indexOf('const EXTRA_ALIASES')));
    const pairs = [...block.matchAll(/'([A-Z]{2}-[A-Z0-9]+)': \[([^\]]+)\]/g)];
    expect(pairs.length).toBeGreaterThan(40);
    for (const [, code, names] of pairs) {
      const row = seedRows.find((r) => r.startsWith(`('${code}',`));
      expect(row, code).toBeDefined();
      for (const n of names.match(/'([^']+)'/g) ?? []) expect(row, `${code} ${n}`).toContain(n.replace(/'/g, "''").slice(1, -1));
    }
  });

  it('builds the hierarchy (second-level units point at a parent)', () => {
    const withParent = seedRows.filter((r) => /^\('[^']+', '[A-Z]{2}', '(?:[^']|'')*', (?:'[^']*'|null), '[A-Z]{2}-/.test(r));
    expect(withParent.length).toBeGreaterThan(900);
    expect(seedRows.find((r) => r.startsWith("('BE-VAN',"))).toContain("'BE-VLG'");
    expect(generator).toContain('codeById.get(String(s.parent_id))');
  });
});

describe('resolver', () => {
  it('excludes geographical units in all four arms', () => {
    expect(resolver.match(/coalesce\(subdivision_type, ''\) <> 'geographical unit'/g)?.length).toBe(4);
  });

  it('returns NULL when an arm finds more than one unit', () => {
    expect(resolver.match(/if cardinality\(v_hits\) = 1 then return v_hits\[1\]; end if;/g)?.length).toBe(4);
    expect(resolver.match(/if cardinality\(v_hits\) > 1 then return null; end if;/g)?.length).toBe(2);
  });

  it('only matches FIPS numbers for a digits-only input, and stops there', () => {
    expect(resolver).toMatch(/if v_raw ~ '\^\[0-9\]\+\$' then[\s\S]*?fips_code = v_raw;[\s\S]*?return null;\s+end if;/);
  });

  it('climbs to the first-level unit', () => {
    expect(resolver.match(/array_agg\(distinct public\.geo_subdivision_root\(code\)\)/g)?.length).toBe(4);
  });
});

describe('sync trigger', () => {
  it('sorts after the name splitter', () => {
    expect('trg_cities_ab_region_code' > 'trg_cities_aa_split_name').toBe(true);
    expect('trg_cities_ab_region_code' < 'trg_cities_normalized').toBe(true);
    expect(statements).toMatch(/create trigger trg_cities_ab_region_code\s+before insert or update on public\.cities/);
  });

  it('lets an explicit region_code write win', () => {
    expect(trigger).toMatch(/if tg_op = 'UPDATE'\s+and new\.region_code is distinct from old\.region_code then\s+return new;/);
  });

  it('re-derives when region_name or country changes', () => {
    expect(trigger).toContain('new.region_name is distinct from old.region_name');
    expect(trigger).toContain('new.country_id is distinct from old.country_id');
  });
});

describe('backfill', () => {
  it('writes only rows that resolve, in batches of 500', () => {
    expect(backfill).toMatch(/select id, rc from todo where rc is not null limit 500/);
    expect(backfill).toMatch(/exit when v_n = 0;/);
  });

  it('runs with lock and statement timeouts', () => {
    expect(statements).toContain("set local lock_timeout = '30s';");
    expect(statements).toContain("set local statement_timeout = '5min';");
  });
});

describe('postconditions', () => {
  it('cover all six arms with positive AND negative controls', () => {
    for (const p of ['P1 failed', 'P2 failed', 'P3 failed', 'P4 failed', 'P5 failed', 'P6 failed']) expect(verify).toContain(p);
    expect(verify).toContain("resolve_region_code('GB', 'South Carolina') is not null");
    expect(verify).toContain("resolve_region_code('US', 'Nowhere Land') is not null");
    expect(verify).toContain("resolve_region_code('BE', 'Antwerp')");
    expect(verify).toMatch(/if v_n < 3000 then/);
  });

  it('has no neutered predicate', () => {
    expect(verify).not.toMatch(/where\s+false/i);
    expect(verify).not.toMatch(/if false then/i);
  });
});
